### ISSUE TITLE
Journal Subjects

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1000]
**Is your feature request related to a problem? Please describe.**
Journals could use a similar implementation as article keywords to declare subjects or disciplines.

We could then add filtering/searching functionality to the journals page, utilising these

**Comment by ajrbyers** [comment]
How is this different from sections?

**Comment by mauromsl** [comment]
I guess its the same, in which case we just need to add a filter/search box in the Journals page.

**Comment by mauromsl** [comment]
Issue #1000! :100: 0

**Comment by ajrbyers** [comment]
Not sure if that’s good or bad 😂

**Comment by mauromsl** [comment]
Can't be too bad, considering we have only 200 issues open :)

**Comment by ajrbyers** [comment]
Looks ok, but was it really supposed to replace the manual keywords section in submit_info? If so, we'll need to make this a setting as the majority of live journals will want to keep that.

**Comment by mauromsl** [comment]
It doesn't replace the manual keywords section in "submit_info" I just transformed that form element into a django form and re-used for both the article and the journal pages.

**Comment by ajrbyers** [comment]
> It doesn't replace the manual keywords section in "submit_info" I just transformed that form element into a django form and re-used for both the article and the journal pages.

Well duh. Nicely done!
