### ISSUE TITLE
ORCID - Authenticate and Display

### ISSUE THREAD

**Issue by amardesi** [BirkbeckCTP/janeway#1010]
First two steps of ORCID integration criteria outlined here: 
https://docs.google.com/document/d/1ZYMlmoYKGuiPnkoprVov62xL1m9OVtAVZivgjMRPzYQ/edit?usp=sharing

**Comment by amardesi** [comment]
Thanks @ajrbyers

**Comment by ajrbyers** [comment]
@amardesi does your package cover what @mauromsl suggested here:

https://github.com/BirkbeckCTP/janeway/issues/973

**Comment by amardesi** [comment]
**Additional Requirement:**
Provide a separate AUTHENTICATION_BACKEND so users logging in with ORCID are not required to enter a password. Python Social Auth: https://python-social-auth-docs.readthedocs.io/en/latest/index.html 

Email will still be required (and can be pre-populated if it's public in their ORCID record).

First time users authenticating via ORCID are not required to enter a password, but are welcome to. In this case, these users will have two methods of logging in going forward.

**Comment by amardesi** [comment]
@mauromsl and @ajrbyers :
Re: The ORCID field in the edit user, profile, and new author pages

- This will no longer be a modifiable form field fed into these pages. I am removing `orcid` field from the `account` model, as well as removing the `orcidtoken` model.
- The allauth app stores the orcid in its associated `socialaccount` table, instantiated in janeway through allauth. Going forward, the ORCID will retrieved fo a given user by a separate utility function and added to the context for these pages (unless you can suggest a better way).
- Of course a user can remove their ORCID from their account profile. I will be adding a button that gives the user the option to remove their ORCID.

I also plan to rename utils/orcid.py to utils/socialaccount.py to serve as a place to put similar functionality for any other social accounts that may be added in the future, if that's ever in the cards.
