### ISSUE TITLE
Add Editorial Board info to Issues

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1017]
Currently, the editorial board only displays current editors. Add option to list editors responsible for the issue on issue page to capture history of journal editors and acknowledge their work.

See bepress issue view, editorial board displays under issue cover image: https://lib.dr.iastate.edu/macnewsletter/vol45/iss3/ 

--Feature requested by JCTP editorial board.

**Comment by ajrbyers** [comment]
This feature sort of already exists. See “guest editor” feature when editing a lab issue. We can change the wording!
