### ISSUE TITLE
Avoid Signature as "None None" when adding users on admin

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1034]
**Is your feature request related to a problem? Please describe.**
Some users were confused as to why their signature came up automatically as None None in email templates.This was because they were created from the admin panel on the backend which first brings you here to fill out username (is that used?) and password
![image](https://user-images.githubusercontent.com/1020384/54838050-1efdbd00-4c9e-11e9-9a92-396c6617de23.png)

and then here:
![image](https://user-images.githubusercontent.com/1020384/54838059-2329da80-4c9e-11e9-804b-31ea515758b0.png)

None None is set to this persons name and so is the signature automatically. 
![image](https://user-images.githubusercontent.com/1020384/54838450-08a43100-4c9f-11e9-9718-f8bf034dc8fc.png)

"None" does not show up in the Firstname or Lastname fields but it is being rednered in the signature. So perhaps there's a `{{ fistname  | safe }} {{ lastname | safe}}` being issued on the signature field?
Users are still able to update their profile to have their signatures be whatever they want of course and this is a non-traditional use-case so that's why this is a feature request.

**Describe the solution you'd like**
Extend the fieldsets in the admin so that first name and last name are required on the first screen **OR** when adding a new user go to the second screen with more field automatically **OR** do not populate the signature field when adding from admin.

**Comment by ajrbyers** [comment]
I have a few ideas on this:

1. We don’t fill in signature at all
2. We fill it in only if fname and lname are present
3. We turn account.signature into a property that can return the text in a _signature attribute or the users full_name if they have one

I think 3 would be quite good...

**Comment by ajrbyers** [comment]
I've actually implemented `Extend the fieldsets in the admin so that first name and last name` and extended it to include email also which we use as our username so this makes the admin interface more useful overall.
