### ISSUE TITLE
Corporate Authors

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1037]
**Is your feature request related to a problem? Please describe.**
We have "articles" that are not attributed to individuals and would like to use an organizational name as the author.

**Describe the solution you'd like**
Be able to assign corporate authors to articles.

**Comment by mauromsl** [comment]
Hi @hinefuku,
Thanks for raising this. Can you explain your use case a bit further?:

Would articles from corporate authors follow the regular workflow (peer review, copy editing etc..)? If so, who would be receiving change requests and general correspondence regarding the article? 
If instead they were to be loaded in via back content plugin, would it be fine to just store corporate authors as part of the article's metadata without issuing accounts for them? (All regular authors are issued accounts in Janeway, even if these are never activated).

**Comment by hinefuku** [comment]
We mainly use corporate authors for our more new-sy publications, rather than scholarly. These generally do production outside of Janeway, so using the back content plugin works. However, if MAC Newsletter, for example, begins using Janeway to manage publishing workflow (people really like the workflow tools), then would need corporate authors for regular workflow. 

For example: https://macnewsletter.iastatedigitalpress.com/article/id/133/, is a press release from the Midwest Archives Conference, so MAC would be the corporate author. Correspondence can go to the editor.

**Comment by ajrbyers** [comment]
@mauromsl can you take a look at this one for 1.3.4? Not sure how easy/hard it will be.
