### ISSUE TITLE
Heading Ranks

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1042]
**Describe the bug**
Heading ranks do not appear to be used hierarchically (e.g., most important header at h1), which is important for accessibility.

**Janeway version**
OLH theme. Have not looked at other themes.

**To Reproduce**
Go to https://macnewsletter.iastatedigitalpress.com/issue/45/info/

The most important element, "Volume 46, Issue 4 (2019)" uses h3.
The second most important element, section titles, uses h4
The third most important element, article titles, use h2.

**Expected behavior**
I would expect headings to be nested by importance, e.g., Issue title/info using h2, section titles using h3, article titles using h4.

**Additional context**
This was raised by one of our college's web accessibility manager. Will also be of interest to our IT and Marketing departments.

**Comment by ajrbyers** [comment]
Seems to be an issue across the board. For some reason in Material and OLH themes the header tags for `h1` are massive so will need restyling.

**Comment by ajrbyers** [comment]
Hi! This will be updated in 1.3.6 :D
