### ISSUE TITLE
Link to Login via Orcid not using http*s* + not full link for journals

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1048]
**Describe the bug**
Links to ORCID via uri are not being generated properly. with `url_config = 'path'`

https://orcid.org/oauth/authorize?client_id=OUR_APP_ID&response_type=code&scope=/authenticate&redirect_uri=http://lps-staging.library.cmu.edu/login/orcid/
should have the param
redirect_uri=http**s**://lps-staging......

on the journal page

https://orcid.org/oauth/authorize?client_id=OUR_APP_ID&response_type=code&scope=/authenticate&redirect_uri=/login/orcid/
**Janeway version**
85dfef1cbd86f6e7c4b089fff2e5968971a6f6fa

The link resolves correctly if the redirect_uri param is changed to https is changed in the press and the full url is available in the redirect_uri  for the journal.

**To Reproduce**
1. Go to the login page on press or journal with https enabled and try to log in. or inspect element
you can go to our staging site to see:

**Expected behavior**
The link generated will be https

**Screenshots**
Result of trying to log in from journal with request_uri portion of url in view.
![image](https://user-images.githubusercontent.com/1020384/55007175-58dc0580-4fb5-11e9-89e7-abfb9423df0f.png)
__________________________
Result of changing request_uri to a full url with https
![image](https://user-images.githubusercontent.com/1020384/55007252-77da9780-4fb5-11e9-89c4-621fdcc8770d.png)

**Additional context**

Tracking this down
in the press:
### templates/core/login.html
```
<a href="{{ settings.ORCID_URL }}?client_id={{ settings.ORCID_CLIENT_ID }}&response_type=code&scope=/authenticate&redirect_uri={% if request.journal %}{{ request.journal.site_url }}{% else %}**{{ request.press_base_url }}**{% endif %}/login/orcid/" class="success button expanded">{% trans "Log in with ORCiD" %}</a>
```
### core/middleware.py
request.press_base_url = press.site_url()
### press/models.py
```
def press_url(request):
        return 'http{0}://{1}{2}{3}'.format('s' if request.is_secure()...
```
Not sure why it's not seeing a secure request here? should it be `request.journal.is_secure()`?

and as for the journal -- `request.journal_base_url`  seems to return blank.

# Possible solution: 
### utils/orcid.py
There's a line in this file:
`"redirect_uri": '%s/login/orcid/' % domain if domain else settings.ORCID_REDIRECT_URI,`

ORCID_REDIRECT_URI is not in the settings file but it can be. I think having this to build the links in the login templates and perhaps in the "search for author" portions would also solve all problems, right? Or will there be issues with path vs. domain based journals especially when dealing with the press?

**Comment by mauromsl** [comment]
The redirect URIs for the "Login with ORCID" feature are constructed in the templates. 
Unfortunately, they haven't been kept in sync and the links in the material and default themes are broken.

The OLH theme for the press seems to construct the `redirect_uri` just fine:
![image](https://user-images.githubusercontent.com/10760678/55022833-5bf5e680-4ff3-11e9-9e46-e7bebacd6116.png)

I'll move this bit of logic to the view instead

**Comment by amardesi** [comment]
Thank you @hachacha for writing this up and @mauromsl for addressing. I'm having a further issue on the journal side where request.journal.site_url is not being called properly in core views.user_login_orcid.

`> /Users/amardesi/dev/janeway-dev/src/core/views.py(133)user_login_orcid()
-> domain = request.journal.site_url if request.journal else request.press_base_url
(Pdb) n
(Pdb) p domain
<bound method Journal.site_url of <Journal: test1: www.example.com>>`

Changing it to `request.journal.site_url()` fixes that problem. Curious why you're not getting it on your end.
