### ISSUE TITLE
Sort topnav items by sequence

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1049]
**Is your feature request related to a problem? Please describe.**
The navigation items are not being sorted when entering sequence.

**Describe the solution you'd like**
When returning the navigation items from `context_processor` put `.order(sequence)`  on the filter that is returning these items. 
![image](https://user-images.githubusercontent.com/1020384/55025718-e03a7080-4fd7-11e9-9bdc-5e0c37489368.png)

**Additional context**
https://github.com/BirkbeckCTP/janeway/blob/master/src/core/context_processors.py#L74
I tried on my local adding `.order_by('sequence')` and it worked on my local. I can make a PR for this unless this may break something else or if it's not the correct way of going about this. Related: Is there any way to change the order of non-cms pages among these cms pages other than directly editing the template?

**Comment by ajrbyers** [comment]
@hachacha we are rebuilding the navigation system in 1.4:

https://github.com/BirkbeckCTP/janeway/issues/509

So you can have a completely custom nav mixing CMS items and what were previously fixed items as well as all previous fixed pages becoming customisable pages with elements in them,

Happy for you to put a PR in for this as its part of 509 but can you tag it as 509 and close this?

**Comment by hachacha** [comment]
sure thing #509 
(i think you tagged it as #509 in your comment but i'll do it again?)
