### ISSUE TITLE
Unassigning editor error bc no email setting found

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1053]
**Describe the bug**
Removing an editor makes a call to look for an email `unassign_editor` that does not exist. There is an email `unassigned_editor` :upside_down_face: 

**Janeway version**
fb20e9ccc58c27a48ba4a0cb8271169db413931c

**To Reproduce**
1. Start article submission
2. Assign an editor and move the article out of the submission page
3. Use article jump in top right to move article back to editor assignment
4. Remove an editor

**Expected behavior**
see email template for unassign_editor

**Additional context**
There is `unassinged_editor`
https://github.com/BirkbeckCTP/janeway/blob/master/src/utils/install/journal_defaults.json#L354
but it's looking for unassign_editor email
There's also no subject_unassign_editor setting. 
I added both these on our instance via the admin and it worked. Not exactly sure how you want to handle this fix for your journals.

**Comment by ajrbyers** [comment]
Updating the name and adding a subject setting will fix it automatically when synced.
