### ISSUE TITLE
Author Peer Reviewer Suggestions

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1079]
**Is your feature request related to a problem? Please describe.**
Some journals would like to request that the Authors of a paper submit potential referees during the submission process.

**Describe the solution you'd like**
An optional new submission section would request that the authors supply first name, last name and email address for as many referees as they can provide, these are then displayed in the review stage and if the suggested referee isn't in the database have an option to create an account and assign the reviewer role to them.

**Describe alternatives you've considered**
we could provide a free for text box but this is not as useful.

**Additional context**
This appears to be standard practice in various industries, which is odd.

**Comment by rhb123** [comment]
This would be very helpful for 1.4 - thanks

**Comment by ajrbyers** [comment]
I'm closing this - Editors who want to ask a question like this can use the additional submission fields system.
