### ISSUE TITLE
Some static resources not found when running apache

### ISSUE THREAD

**Issue by amardesi** [BirkbeckCTP/janeway#1083]
**Describe the bug**
Resources 
static/common/css/common.css
and
static/common/js/timezone-setter.js
are not being found when I run janeway on apache.

net::ERR_ABORTED 404 (Not Found)

Running janeway locally (w/o Apache) does not give me this problem

**Janeway version**
Any version 1.3.3 or later

**Comment by ajrbyers** [comment]
These are new assets. Have you run build_assets?

**Comment by amardesi** [comment]
Ah, thanks. I see I also need to run build_assets if any of these files change.
