### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1087]
**Describe the bug**
There are a few typos in Janeway:

1. Production page: have at “lease” one galley: please amend to 'at least'
2. Pre-pub checklist: please amend to Set A Publication date: ‘immediately’
3. Submission page: “If you have any competing or conflictof insterests in the publication of this article please state them here.” please amend to: “If you have any competing or conflicts of interest in the publication of this article please state them here.” 
4. When a Reviewer Declines to review an article: please amend to "Notify" not "nofity"

**Janeway version**
The version of Janeway under which the bug has been reproduced.
If running off of master, please, indicate the current HEAD of the Janeway installation

**To Reproduce**

**Expected behavior**

**Screenshots**

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rhb123** [comment]
This would be very helpful for 1.4 (if this hasn't yet been fixed already)- thanks
