### ISSUE TITLE
Author tasks rendering bug

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1096]
**Describe the bug**
The tasks section of the article page shows that "There are no active tasks" even when there are some.

**Janeway version**
1.3.4

**Screenshots**
![image](https://user-images.githubusercontent.com/10760678/56976738-8e9f7b80-6b6b-11e9-8eeb-aec28be06fcb.png)

**Comment by ajrbyers** [comment]
Will be dealt with in 1.3.8 as part of #197
