### ISSUE TITLE
Preprints

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#11]
Allow a site wide option for preprints and add option to submission process.

#### Front end/Display
- [x] Add a new is_preprint boolean to submission model
- [x] Set default submission objects manager to filter out non-preprints
- [x] Add a new boolean setting 'enable_preprints'
- [x] If preprints are enabled, add a nav item for preprints
- [x] Add a "preprints" area with info pages on preprints and a way to search preprints
- [x] Add a new preprint article display template
- [x] Add a preprint list page (paginated by 15)

#### Submission
- [x] If enabled, add a drop down to the submission nav item allowing selection of either a normal article or a preprint for submission
- [x] Add new preprint start submission page with its own content
- [x] Allow user to complete submission as normal
- [x] Limit submission to PDF files only (setting?)
- [x] Add Event to be fired on submission

#### Workflow
- [x] Add new interface to view all unaccepted preprints
- [x] Allow editor to view preprint metadata and make a decision
- [x] Editor should be able to email the decision to the author(s)
- [x] If accepted, it will appear in the preprint archive
- [x] If declined, it will not appear on the site

#### Comments
- [x] There should be a way for people to leave comments on the manuscript that are moderated... by the _author_ as to whether they appear in public
- [x] Add interface to view all comments moderated and un-moderated for a given article
- [x] Allow author to approve comments for public display
- [x] Allow Editors to see a list of comments, their status and allow Editors to make them public also

**Comment by ajrbyers** [comment]
Step 1 will be to set the Submission Manager to filter out all preprints from normal ops.

https://docs.djangoproject.com/en/1.11/topics/db/managers/#modifying-a-manager-s-initial-queryset

**Comment by Protohedgehog** [comment]
A way of tagging between pre- and post-prints would be useful perhaps? I would make ORCID a requirement for submission too. Any way of checking things against journal preprint policies too?
