### ISSUE TITLE
The OLH theme doesn't indicate the minumim length for the password

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1107]
**Describe the bug**
When trying to register on a journal under the OLH theme, if the registration fails due to the lenght of the password, the user can only see the word "length"

**Janeway version**
1.3.4

**Expected behavior**
The error message should show the min/max length. It should probably be indicated in the form label as well ahead of time.

**Screenshots**
![image](https://user-images.githubusercontent.com/10760678/57013768-f3f37b00-6c04-11e9-8396-89d1bc462059.png)

**Comment by MartinPaulEve** [comment]
This looks resolved to me on OLH theme:

"Your password should be at minimum 12 characters long. It does not need to contain specific characters but you should make it as long as possible. For more information read on password guide ."
