### ISSUE TITLE
Reviewers can't see the article abstract before accepting the review task

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1109]
**Describe the bug**
When a reviewer logs into the dashboard and has a pending decision to make on whether to review an article or not, they can't see any of the metadata about the article.

**Janeway version**
1.3.4

**Expected behavior**
There should be a link in the article card to the review page where they can make the decision.

**Screenshots**
![image](https://user-images.githubusercontent.com/10760678/57014456-1dfa6c80-6c08-11e9-8956-403e3933d514.png)

**Comment by ajrbyers** [comment]
Yes for review this should probably just be view task as the accept and decline buttons  are also on that page.

**Comment by mauromsl** [comment]
True, and the email links to that page correctly. We are just missing the navigation from the dashboard

**Comment by ajrbyers** [comment]
This should have been closed by https://github.com/BirkbeckCTP/janeway/pull/1219
