### ISSUE TITLE
fully support multilingual journals.

### ISSUE THREAD

**Issue by Beethro** [BirkbeckCTP/janeway#1110]
**Is your feature request related to a problem? Please describe.**

We are thinking of implementing Janeway but have the need to fully support multilingual journals. Frontend side we'd need to have e.g. section titles differ for each language, metadata side we would need title, abstract and keywords to be translatable.

**Describe alternatives you've considered**
Are additional metadata fields the way to go to solve (part of) the problem ?

Thank you for your efforts !

Best regards,
Oliver

**Comment by mauromsl** [comment]
Hi Oliver @Beethro,

Front-end wise, Janeway is fully translatable as we use [Django's translation engine](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/), but we don't have support for many languages as of yet (contributions are always welcome!).

In terms of dynamic fields, (such as some metadata, settings or emails), we use the library  [django-hvad](https://pypi.org/project/django-hvad/), which we could also use for fields such as the article title, abstract and keywords. 

Could you tell us a bit about the kind of workflow you were thinking of for translating the metadata? 
Would the author provide translations at submission? or perhaps it would be done at some point in the production workflow?

**Comment by Beethro** [comment]
Hi Mauro,

Thanks for the pointers, I shall have a look. Seems I was deterred by #1111

Ideally authors would have the option to add non-english abstracts etc. at submission time. Don't know how this would be best reflected in the forms, especially regarding keywords. Either you have a different set of keywords for each language one needs to be supported or one could think of having a explicit mapping for each single keyword (might be overkill)

**Comment by ajrbyers** [comment]
@Beethro could we invite you onto our Discord channel so we can discuss this further? We're keen to come up with a solution for this as supporting multi lang is something we think would be great.

**Comment by Beethro** [comment]
@ajrbyers 
Sure :) Please also invite @Mandrae She's the one "insisting" on Janeway in the first place.

**Comment by ajrbyers** [comment]
Cool, can you drop me an email: a.byers@bbk.ac.uk so I can email you an invite link?

**Comment by ajrbyers** [comment]
@Beethro see work in https://github.com/BirkbeckCTP/janeway/milestone/27
