### ISSUE TITLE
<img/> in rendered galleys should have alt attribute 

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1118]
**Describe the bug**
No alt attribute in rendered img elements

**Janeway version**
fd6a8f1a8df1d2061eccb213f743107b60372e86

**To Reproduce**
1. look at an article that has been published using pandoc + image upload
2. no alt attribute :<

**Screenshots**
![image](https://user-images.githubusercontent.com/1020384/57468078-c71d1480-7251-11e9-9f90-13ee850d190f.png)

**Additional context**
We were asked to do an audit for accessibility to the site. Most things can be changed within our own theme but the images are being rendered (as you see above) in the galley and without the alt text which is important for impaired users of websites who will be using screen readers. Using the same text as the label when rendering the image would be sufficient I think.
![image](https://user-images.githubusercontent.com/1020384/57469315-617e5780-7254-11e9-87c4-ef148c796b2a.png)

I tried to find where that code would be for a PR but got lost in the galleys. if you can direct me i will make that change.

**Comment by ajrbyers** [comment]
Hi @hachacha,

The core of janeway only handles uploading of the image files, the plugin generates the HTML where the alt text should be placed. If you want the core to edit the galley and place alt text based on the label of the uploaded image the place to start would be `production.views.edit_galley` and `production.logic.save_galley_image`.

**Comment by hachacha** [comment]
Ah, I see now. The [pandoc plugin](https://github.com/BirkbeckCTP/pandoc_plugin) can handle alt text so if that is added during document creation it will end up in the galley. There are no changes that should happen to core or the plugin.
