### ISSUE TITLE
issue galleys uploaded to wrong place

### ISSUE THREAD

**Issue by Beethro** [BirkbeckCTP/janeway#1119]
**Describe the bug**
When I try to upload an issue galley the (pdf)-files seem to end up in the wrong place,, i.e .../janeway/src/files instead of .. /janeway/src/files/issues/&lt;issueid&gt;/

**Janeway version**
origin/master

**To Reproduce**
1. Create an issue
2. Upload a galley file
3. Try to download the file

**Additional context**
I'm quite sure it's not a file permission issue.
The problem also happens after chown -R apache:apache and chmod -R 775 .../janeway/src/files

**Comment by Beethro** [comment]
*
instead of instead of .. /janeway/src/files/issues/&lt;issueid&gt;/

**Comment by ajrbyers** [comment]
Thanks for the report, I've added a PR for this.

**Comment by Beethro** [comment]
I can confirm it's fixed
