### ISSUE TITLE
Allow subheadings in References list in XML

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1135]
The Editors of EE would like the References list to be divided into subheadings in the XML, in order to reflect different kinds of sources (e.g. Literature, Archival Sources, Interviews, etc).

We support this on the PDF so could this be added to the XML so that they match.

**Comment by ajrbyers** [comment]
@hks25 we will look into this, but it may not be supported by JATS so please make the EE editors aware of this.
