### ISSUE TITLE
Edit Author window unexpectedly closes, angering BitNinja

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1142]
**Describe the bug**
When editing author information fro the Edit Article > Edit Author page, the pop up window closes suddenly when clicking in a text field. Doing this repeatedly causes BitNinja to block the IP address.

**Janeway version**
The version of Janeway under which the bug has been reproduced.
If running off of master, please, indicate the current HEAD of the Janeway installation

**To Reproduce**
1. Go to an Article (in itaa.iastatedigitalpress.com)
2. Click on 'Edit Article'
3. Click on 'Edit Metadata'
4. Click on 'Edit' for an author
5. Click or click and drag within a text field.

**Expected behavior**
Pop up stays open until I click close window.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Chrome
 - Version 74.0.3729.131

**Additional context**

**Comment by hinefuku** [comment]
It seems to happen most often when clicking and dragging within a text field.

**Comment by ajrbyers** [comment]
Can you get a screenshot?

**Comment by hinefuku** [comment]
![bitninja](https://user-images.githubusercontent.com/45498398/58200936-8b466e00-7c99-11e9-9798-7587f0a30b67.png)

**Comment by hinefuku** [comment]
Looks like a Reclaim thing: https://community.reclaimhosting.com/t/working-with-bitninja/910

**Comment by ajrbyers** [comment]
Yeah just saw this.

**Comment by ajrbyers** [comment]
@hinefuku we will soon be moving the install off of Reclaim which will make bitninja go away!
