### ISSUE TITLE
Getting "Couldn't match a resource for /" warning that disables Janeway

### ISSUE THREAD

**Issue by wernerkrampl** [BirkbeckCTP/janeway#1153]
**Describe the bug**
After installation of Janeway by the wiki I was unable to load "\<url\>/install" webpage as well as only "\<url\>" as loading these urls redirects me to "https://www.example.org" (or any site in "DEFAULT_HOST" in "janeway/src/core/settings.py" for that matter). The only log I'm getting from "janeway/logs/janeway.log" is "WARNING 2019-05-29 03:48:12,721 middleware P:23919 T:140662665213696 Couldn't match a resource for /, redirecting to https://www.example.org".

I tried to change access rights (even allowed full access for everyone at one point) but with no satisfactory results.

**Janeway version**
v1.3.4

**To Reproduce**
By "BirkbeckCTP/janeway" wiki including installation of apache2.

**Expected behavior**
Running Janeway webpage.

**Additional context**
Running on Ubuntu 18.04.2 LTS
Apache/2.4.29 (Ubuntu)
MySQL 14.14 Distrib 5.7.26

**Comment by mauromsl** [comment]
Hi @wernerkrampl ,
I suspect your installation `URL_CONFIG` is set to `"path"`.
Janeway can run in two URL routing modes:
 - Path mode: The press site can be accessed under the domain provided for the press during installation. The journal sites can be accessed under `http(s)://<press.domain>/<journal_code>`. For example, if the press domain is set to `localhost`, a journal with a code of `"journal"` would be accessible under `http://localhost/journal`. This mode is particularly useful when it is not possible (or not convenient) to configure the webserver running janeway.

 - Domain mode: The press site and each of the installed journals are accessible under their own domains. The domain field is unique across all journals.

Path mode is the more convenient option when running Janeway in development as it doesn't require redirecting all journal domains to your webserver, so this is the default option. You can change the value of `URL_CONFIG` on your `src/core/settings.py`  to either `"path"` or `"domain"`.

There is a section in the wiki devoted to this topic but we haven't taken the time to describe this in detail yet:
https://github.com/BirkbeckCTP/janeway/wiki/Settings#url-config

**Comment by wernerkrampl** [comment]
Thank you @mauromsl ,

Error was in the way I filled "Press domain:" input during installation. I filled the current domain of the press, not the domain where the Janeway will run.

**Comment by hardyoyo** [comment]
Gosh, thank you so much for asking the question, and for the concise answer. I've been trying to set up a local instance of Janeway, using a dump of the production database (to help in a bug hunt), and this error message was blocking me, because I usually have URL_CONFIG set to "path". One quick change, and presto! everything works. So, I wanted to say thanks for this.
