### ISSUE TITLE
Getting "hvad.models.DoesNotExist: SettingValueTranslation matching query does not exist." error

### ISSUE THREAD

**Issue by wernerkrampl** [BirkbeckCTP/janeway#1158]
**Describe the bug**
After installation of Janeway by the wiki and opening "\<domain\>/install" in browser, I logged in and as a first step I uploaded a logo of the Press. After upload (webpage was showing successfully uploaded logo) I clicked on the "Move to Next Step" button and I got "
Issue Server Error Sorry, there was a server error. Our team has been notified." error. Going back and clicking on "Journal" in Dashboard menu results in the same error.

In "/var/www/janeway/logs/janeway.log", I have:

`CRITICAL 2019-06-06 14:49:29,273 setting_handler P:29785 T:140312124856064 [press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press:press] Failed to load setting for context:`

`setting_name: journal_name,`
`journal: None,`
`fallback: True,`
`request language: en,`
`settings language: en,`

`ERROR 2019-06-06 14:49:29,273 exception P:29785 T:140312124856064 Internal Server Error: /install/journal/`
`Traceback (most recent call last):`
`  File "/var/www/.virtualenvs/janeway/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner`
`    response = get_response(request)`
`  File "/var/www/.virtualenvs/janeway/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response`
`    response = self._get_response(request)`
`  File "/var/www/.virtualenvs/janeway/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response`
`    response = self.process_exception_by_middleware(e, request)`
`  File "/var/www/.virtualenvs/janeway/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response`
`    response = wrapped_callback(request, *callback_args, **callback_kwargs)`
`  File "/var/www/.virtualenvs/janeway/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view`
`    return view_func(request, *args, **kwargs)`
`  File "/var/www/janeway/src/install/views.py", line 43, in journal`
`    initial_items = logic.get_initial_settings(request.journal, settings_to_get)`
`  File "/var/www/janeway/src/install/logic.py", line 11, in get_initial_settings`
`    got = setting_handler.get_setting('general', setting, journal).value`
`  File "/var/www/janeway/src/utils/setting_handler.py", line 74, in get_setting`
`    raise e`
`  File "/var/www/janeway/src/utils/setting_handler.py", line 60, in get_setting`
`    setting_group, setting, journal, lang, create, fallback, default)`
`  File "/var/www/janeway/src/utils/setting_handler.py", line 110, in _get_setting`
`    journal=journal,`
`  File "/var/www/.virtualenvs/janeway/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get`
`    self.model._meta.object_name`
`hvad.models.DoesNotExist: SettingValueTranslation matching query does not exist.`

**Janeway version**
v1.3.4

**To Reproduce**
By "BirkbeckCTP/janeway" wiki including installation of apache2.
Open <domain>/install, upload Press logo and click on "Move to Next Step" button.

**Expected behavior**
Opening Journal Dashboard webpage.

**Additional context**
Running on Ubuntu 18.04.2 LTS
Apache/2.4.29 (Ubuntu)
MySQL 14.14 Distrib 5.7.26
Python 3.6.7

**Comment by wernerkrampl** [comment]
Problem was based on using `CHARACTER SET = utf8` in database-creating command `CREATE DATABASE janeway CHARACTER SET = utf8 COLLATE = utf8_general_ci;` in MySQL as is currently written in Wiki page. As is also stated in Wiki page, for MySQL, the correct command is: `CREATE DATABASE janeway CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;`

As Wiki page clearly states the MySQL command, this should also be corrected there.

**Comment by mauromsl** [comment]
Thanks @wernerkrampl , I've corrected the command shown on the wiki page.
