### ISSUE TITLE
Text error in Competing Interests field

### ISSUE THREAD

**Issue by hlflanagan** [BirkbeckCTP/janeway#1163]
**Describe the bug**

**Janeway version**
The version of Janeway under which the bug has been reproduced.
If running off of master, please, indicate the current HEAD of the Janeway installation

**To Reproduce**

**Expected behavior**

**Screenshots**

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ajrbyers** [comment]
@hlflanagan can you update this issue, it seems to just have the default text.

**Comment by hlflanagan** [comment]
Well, that's embarassing. Not sure what happened there, and I don't have the uncorrected template available anymore to highlight what's wrong about the text. Might as well delete the issue.
