### ISSUE TITLE
Add a button for sorting articles in an issue/collection by date or alphanumerically

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1170]
There is currently a sort button which sorts articles in alphabetical descending order. We also need buttons for sorting by pub date both in ascending and descending order. This is helpful for sorting issues/collections with a large number of items.

Collections don't a button at all and drag and drop seems unresponsive

**Comment by ajrbyers** [comment]
Its worth noting that the sort/order buttons that are displayed on the Issue page shouldn't be there.

**Comment by ajrbyers** [comment]
Allow for multiple types of sorting (title, date, page numbers, article number)
