### ISSUE TITLE
Articles not sorting into Sections

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1179]
**Describe the bug**
In Issues and Collections, article are not grouped into sections properly.

**To Reproduce**
Collections: https://www.iastatedigitalpress.com/itaa/collections/77/
Issues: https://www.iastatedigitalpress.com/farmreports/issue/74/info/

**Expected behavior**
Articles should be listed and grouped by their section.

**Screenshots**
![articleorder1](https://user-images.githubusercontent.com/45498398/59523727-a884eb80-8e97-11e9-9675-a74c92eb8ef5.png)
![articleorder2](https://user-images.githubusercontent.com/45498398/59523728-aae74580-8e97-11e9-809a-d7bb2caf2171.png)

Articles/Sections all hammajang.

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Explorer

**Comment by ajrbyers** [comment]
@mauromsl was this fixed?

**Comment by mauromsl** [comment]
Confirmed fixed on 1.3.7
