### ISSUE TITLE
Title and subtitle fields on Janeway

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1182]
**Describe the bug**
Instructions for how to complete Title and Subtitle fields are unclear to authors ('subtitle of article display format, title'). Can this be removed/edited for clarity.

**Janeway version**
1.3.5

**Screenshots**
![Screenshot (60)](https://user-images.githubusercontent.com/48489285/59685042-2b2ce400-91d3-11e9-81c4-10ad1e2d6a6c.png)

**Comment by MartinPaulEve** [comment]
@hks25 - can you suggest some alternative wording here?

Perhaps we should standardize so that it is gives a preview of the full title?

**Comment by rhb123** [comment]
Thanks for this - a preview of the full title sounds good if this is possible.

In terms of alternative text, I would change 'Subtitle of the article display format; Title: Subtitle' to 'The article's full title will display as 'Title: Subtitle'

**Comment by joemull** [comment]
Recently an editor said they were also confused by the subtitle field, since it does not display on the published article. We should consider removing this field entirely from the Edit Metadata page and other metadata views if it is not being used in the published article.

**Comment by joemull** [comment]
Current status: the above commit should be ready for a PR that closes this issue once @ajrbyers has a chance to check that deprecating subtitle in `repository` is safe.
