### ISSUE TITLE
Notify all authors when a prepublication email is sent.

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1186]
**Describe the solution you'd like**
At the pre-publication checklist stage, there is the option to email the author, section editor and peer reviewers. It would be great if all listed co-authors could be informed of the imminent publication.

**Comment by rhb123** [comment]
This would be very helpful for 1.4 - thanks

**Comment by simifilm** [comment]
Also, it would be great if all listed co-authors could be informed of the imminent publication.

**Comment by MatthiasULB** [comment]
Additional idea: Option to send a mail to all involved authors of an issue when it is published so they're informed.

**Comment by ajrbyers** [comment]
We're writing up a new issue that will allow users to signup to be notified as articles move through the workflow, so are closing this in favour of https://github.com/BirkbeckCTP/janeway/issues/1674 which has a specific change to the existing feature.

**Comment by joemull** [comment]
See also https://github.com/BirkbeckCTP/janeway/issues/3357
