### ISSUE TITLE
Add option to view articles in table view in Kanban

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1196]
**Is your feature request related to a problem? Please describe.**
In the Review and Editing stages of the Janeway workflow, it is possible to view articles either in the kanban or in table view. For Production and Proofing this is not possible, though it would be ideal as it's easier to find articles that way, especially if there are lots of articles to search through.

**Describe the solution you'd like**
An option at all stages of the workflow to see articles either in kanban style (with tickets in columns) or in table view.

**Comment by ajrbyers** [comment]
This feature is covered in the Search Submissions interface.
