### ISSUE TITLE
Limit the number of revision requests

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1198]
**Is your feature request related to a problem? Please describe.**
A co-authored piece will potentially have multiple authors looking at it and requesting corrections at proofing stage.  

**Describe the solution you'd like**
There should be a limit at the 'Request Changes' stage, so that editors/PMs who are responsible for this can only send one lot of revisions back to the typesetters.

**Comment by ajrbyers** [comment]
The new workflow in typesetting already supports this.
