### ISSUE TITLE
Hypothesis Peer Review

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#12]
Add ability for people to use Hypothesis for Peer Review.

**Comment by adunning** [comment]
A great model of this from eLife and ORCID: <https://orcid.org/blog/2018/03/27/elife-users-can-now-register-orcid-annotate-scientific-content-online>.

**Comment by Vinnl** [comment]
Some more details on the technical implementation are here: https://mobile.twitter.com/Flockademic/status/961509331933061121

**Comment by ajrbyers** [comment]
Moved this to Milestone 1.4 - the public API is not yet ready for this process as we need the ability to keep reviews private to the Reviewer, Editor and Author and this isn't available, yet.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
This issue has been marked for possible future development but is now closed.

For more information see: https://github.com/BirkbeckCTP/roadmap/issues/13
