### ISSUE TITLE
Provide guidance on editorial timelines

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1212]
**Is your feature request related to a problem? Please describe.**
Some editors have unrealistic expectations of how long it can take to typeset and proof an article, leading perhaps to some frustration on their part.

**Describe the solution you'd like**
Please add a short note in the Actions box saying 'Please remember to allow sufficient time for typesetting and author proofing of this article prior to publication.'

**Comment by ajrbyers** [comment]
Cant this be added by using the editable action blocks feature?
