### ISSUE TITLE
Make abstract compulsory

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1213]
**Is your feature request related to a problem? Please describe.**
Some authors fail to submit an abstract with their work. This is especially a problem for book reviews.

**Describe the solution you'd like**
Please can we:
1. Ideally, add an asterisk at the point of submission to indicate that this is a compulsory field.
2. If this can't be done, please can we add a note at the point of submission clarifying that an abstract should be added.
3. Please can this note include the line 'All submissions require an abstract, including book reviews.'

**Comment by ajrbyers** [comment]
@hks25 might it be worth tying abstract being required with Section?
