### ISSUE TITLE
Notify editors if note added

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1214]
**Is your feature request related to a problem? Please describe.**
Notes can be left for editors and authors in the blank Notes field. However, at the moment there is no trigger to notify editors if someone leaves a note after the point of submission, even though the note might include something important.

**Describe the solution you'd like**
If a note is added, please can (i) the editors assigned to the article and (ii) the author be notified as required.

**Comment by ajrbyers** [comment]
I thought we agreed that https://github.com/BirkbeckCTP/janeway/issues/1173 would take precedent?

**Comment by hks25** [comment]
Good spot, Byers. Yes, please focus on 1173 instead.
