### ISSUE TITLE
Bug with saving keywords

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1215]
**Describe the bug**
Some articles do not let you save keywords

**Janeway version**
1.3.5 (I think?)

**To Reproduce**
1. Go to article's metadata (e.g. https://poetry.openlibhums.org/edit/article/754/metadata/?return=/publish/article/754/)
2. Click on Edit metadata
3. Scroll down to Keywords
4. Try to add 'place' and 'Peter Manson' as keywords

**Expected behavior**
'Place' and 'Peter Manson' should save as keywords and also be visible online immediately

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by ajrbyers** [comment]
@hks25 this isn't *technically* a bug with Janeway but with our database server ignore case sensitivities. 

Anyway, it should be working now.
