### ISSUE TITLE
Users Edit/Merge

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1234]
**Is your feature request related to a problem? Please describe.**
Sometimes needs to merge duplicate author accounts, or details in user record (corrections), especially when dealing with articles and authors that imported from bepress.

**Describe the solution you'd like**
Have a screen where we can view/search/sort all users, and check radio boxes for proflle merges, mass editing of a  user's profile. Should be limited to staff users.

**Additional context**
![rothschild](https://user-images.githubusercontent.com/45498398/62230438-68b28e80-b387-11e9-8804-2131e37829db.png)

**Comment by ajrbyers** [comment]
This has been done already! YAY!
