### ISSUE TITLE
Add a checkbox to confirm HTML proofed

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1275]
**Is your feature request related to a problem? Please describe.**
I suspect that some authors are not proofing both the PDF and the HTML files when they are invited to proof them, despite both files being sent as part of the task. This is leading to, occasionally, errors only being identified post-publication when the author actually reads their piece online. This is a problem as OLH incurs a cost to fix things post-publication.

**Describe the solution you'd like**
Please can we have a tickbox where the author must confirm that they have proofed both the PDF and the HTML. The proofing task cannot be completed without the author ticking both boxes to confirm.

**Describe alternatives you've considered**

**Additional context**
e.g. happened on https://orbit.openlibhums.org/article/id/1387/

**Comment by rhb123** [comment]
This would be very helpful for 1.4 - thanks

**Comment by mauromsl** [comment]
Fixed in typesetting plugin
