### ISSUE TITLE
Add Document ID to all tables

### ISSUE THREAD

**Issue by hks25** [BirkbeckCTP/janeway#1278]
**Is your feature request related to a problem? Please describe.**
Some editors might potentially put the wrong file into copyediting - this is especially a concern on JBIIP - and especially if lots of files have been uploaded prior to production/is an inexperienced guest editor.

**Describe the solution you'd like**
Please add Document ID to all tables to help editors pick the right ones. This is especially a concern at copyedit, (as editor needs to be looking at the revised file): add the ID in the table at Step 2.
https://poetry.openlibhums.org/copyediting/article/764/assignment/add/

**Comment by mauromsl** [comment]
closed in favour of #1343
