### ISSUE TITLE
Migrating Database Pending Trigger Events Error

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1282]
**Describe the bug**
We had been running on 1.3.4 until now. I'm now trying to update to 1.3.6 
When attempting to migrate our janeway instance running on psql to `223042f` :
```
Applying journal.0033_migrate_issue_types...Traceback (most recent call last):
  File "/home/jon/.virtualenvs/janeway/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: cannot ALTER TABLE "journal_issuetype" because it has pending trigger events
```
issuetype is a new table that did not exist previously since our last update. Do I need to put something in there and associate it with the current issues that are already available? 

`0033_migrate_issue_types` refers to a json file that is indeed available @ `utils/install/issue_type.json` but it doesn't seem to install when running ./.update.sh
Should I manually populate the issuetypes in and then associate the current issues with those IDs or would that upset migrations further down the road?

**Janeway version**
223042f @ master

**To Reproduce**
1. generate a couple issues with the archive plugin in version 1.3.4
2. try to update to 1.3.6

**Expected behavior**
a clean migration 

**Screenshots**

A search of all our current issues are shown here. 
![image](https://user-images.githubusercontent.com/1020384/64370991-8e1d6280-cfed-11e9-8080-85f93f30de82.png)

A search of our current issuetypes shown here:
![image](https://user-images.githubusercontent.com/1020384/64375988-3125aa80-cff5-11e9-9ce6-2af45ee37a0a.png)

** Additional info **
The issues that we have on the ETHOS instance of janeway are generated by the [archive plugin](https://github.com/cmu-lib/archive_plugin). If there is an issue that should be creating a type I will update the archive plugin accordingly.

**Comment by ajrbyers** [comment]
@hachacha interesting. I suspect this is a PGSQL issue as we've only ever run these migrations on MySQL/SQLITE. @mauromsl can you take a look at this tomorrow?

**Comment by hachacha** [comment]
Ah, I didn't realize you don't run tests with PGSQL. Is PGSQL not recommended?
After populating IssueType manually I was able to move forward with the migration and not have any other issues. Not sure if this is best practice. But if PGSQL is not offered under support then this issue could be disregarded and we'll move over to mysql.

**Comment by hachacha** [comment]
hi hi any further investigation into if this is a psql error or something else?

**Comment by mauromsl** [comment]
Hey @hachacha, can you give the `1282-Bugfix` branch a go? You would need to rollback the `journal 0032`migration first with `manage.py migrate journal 0031`

Let me know how it goes

**Comment by hachacha** [comment]
That seems to have done the trick. It migrated with no errors on the 1282-Bugfix branch
