### ISSUE TITLE
Display issue editors/guest editors details on the issue page

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1285]
**Is your feature request related to a problem? Please describe.**
PR #1046 added the editors and issue editors to the context on the issue view, however it seems the templates are not rendering them

- [x] Guest editors shown on issue page (#1673)
- [x] Guest editors shown on Current Issue homepage element (#1673)
- [ ] Guest editors Show on Article page (with an on/off toggle)

**Comment by mauromsl** [comment]
From simon @ ZFF: They'd like to also render the guest editor details on the article page. I imagine we'd only want to show the guest editors of the article's primary issue.

**Comment by ajrbyers** [comment]
> From simon @ ZFF: They'd like to also render the guest editor details on the article page. I imagine we'd only want to show the guest editors of the article's primary issue.

Definitely needs to be optional.

**Comment by mauromsl** [comment]
partially resolved in #1673
