### ISSUE TITLE
Download Issue (ZIP) does not include all articles

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1295]
**Describe the bug**
Download Issue (ZIP) does not include all articles from issue in ZIP file.

**To Reproduce**
1. Go to  https://www.iastatedigitalpress.com/jctp/issue/61/info/
2. Click on Download Issue (ZIP)
3. Open ZIP file
4. See error, Trans*Forming Authentic Leadership: A Conceptual Framework is not included

**Expected behavior**
All articles from issue should be included in ZIP file.

Missing articles from 3 most recent issues:
--Issue 8(1). Maybe They Are Just Kinesthetic Learners? Student Walkouts and the Purposes of Education
--Issue 7(2), Cultural Competency Training: How Do We Measure Outcomes?
--Issue 7(1), Who gets in? The Price of Acceptance in Canada
; “No more blackface!” How can we get people to change their minds about Zwarte Piet?; Who Belongs? Immigrants, Refugees, Migrants, and Actions Towards Justice: A Conversation With Tim Wise;

**Comment by hinefuku** [comment]
Editor notes it only seems to be an issue for their larger issues.

**Comment by ajrbyers** [comment]
As discussed with @hinefuku we will limit the display of this feature, I've opted for a limit of 30 articles.
