### ISSUE TITLE
Capture search metrics

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1296]
**Describe the solution you'd like**
When users make use of our search tool, we should keep track of which search terms are being introduced as well as present insights driven from this metrics on the reports view.

Additionally, we could track which content is been accessed through the results that come up from the search, which would be necessary for Counter reports as well.

**Comment by ajrbyers** [comment]
This issue has been marked for possible future development but is now closed.

For more information see: https://github.com/BirkbeckCTP/roadmap/issues/13
