### ISSUE TITLE
Email update

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#1297]
Hi Andy and Mauro, would it be possible to drop me a quick reply to any outstanding emails that I sent through to you since starting to let me know the status of these please (even if it's just a quick 'done' on items that have been actioned, so I've got this on file)? Thanks again for your help

**Comment by ajrbyers** [comment]
Hey Rose,

I think this is more suited to the support ticket system rather than GitHub Issues. You can email support@openlibhums.org or go to Https://support.janeway.systems
