### ISSUE TITLE
TypeError: overwrite_file() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1298]
**Describe the bug**
Calls to `core.files.overwrite_file`  from `core.logic.handle_article_thumb_image_file` are not passing the correct number of arguments and lead to a server error when replacing an article thumbnail

**Janeway version**
1.3.6

**Comment by simifilm** [comment]
There is still something odd here. When I try to replace an image, in most instances the change is not reflected in the articles image manager. The change seems to happen – although only later –, but this is not visible in the manager, i.e. the new image is displayed after upload.

**Comment by ajrbyers** [comment]
The process of updating the file perhaps does not clear the article cache which means it takes a few minutes before the update is live.
