### ISSUE TITLE
Google Scholar Meta Tags

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1312]
- `citation_pdf_url` meta tag
- Where tags are empty we should not display empty tags

Monica will supply us with additional tags

**Comment by mwestin-googlescholar** [comment]
Monica from Google Scholar here. 

- citation_pdf_url metatag is most important metatag missing from indexing setups currently
 -- format for citation_pdf_url metatag: <meta name="citation_pdf_url" content="http://www.example.com/content/271/20/11761.full.pdf">
 -- note that the PDF URL should be in the same subdomain as the article landing page/ abstract page/ HTML fulltext for anti-spam reasons (see 2H here: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing)

- Other useful metatags for journal publishing:
 -- <meta name="citation_publisher" content="Michigan Publishing">
 -- <meta name="citation_firstpage" content="61"> 
 -- <meta name="citation_lastpage" content="66">
