### ISSUE TITLE
Default large image for issues

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1329]
**Describe the solution you'd like**
Would like to be able to set a default large image by issue/collection

**Describe alternatives you've considered**
Could use the large image from the issue page as default for articles in the issue.

**Comment by ajrbyers** [comment]
This work should probably be done with #1081

**Comment by mauromsl** [comment]
Instead of adding another setting, we could use the issue large image as the default when there isn't a large image provided for the articles. This is what I did for many migrated issues and worked quite well.

The logic would be Article Image > Issue Image > journal default
