### ISSUE TITLE
submission fails if copyright notice not checked in submission fields config

### ISSUE THREAD

**Issue by Beethro** [BirkbeckCTP/janeway#1374]
**Janeway version**
1.3.7

**To Reproduce**
1. uncheck copyright notice in submission fields configuration
2. try to start a submission

**Additional context**
submission/forms.py

first
      if not journal.submissionconfiguration.copyright_notice:
            self.fields.pop('copyright_notice')
        else:
            self.fields['copyright_notice'].required = True
and later
     self.fields['copyright_notice'].label = copyright_label

results in a key error if copyright_notice is unchecked

**Comment by ajrbyers** [comment]
Thanks for this @Beethro we'll patch this tomorrow am.
