### ISSUE TITLE
More detail for Copyediting stage

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1411]
**Is your feature request related to a problem? Please describe.**
When viewing the Articles in Copyediting page (https://www.iastatedigitalpress.com/mmb/copyediting/) it's unclear what stage of copyediting articles are in without viewing each article.

**Describe the solution you'd like**
Would like the Stage column to have additional values than "Editor Copyediting." May include, "Unassigned" "In Copyediting" "Author Review", etc.

**Comment by ajrbyers** [comment]
I've noted this feedback against the copyediting rebuild issue here: https://github.com/BirkbeckCTP/janeway/issues/1420
