### ISSUE TITLE
Copyedit assignment author review message

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1412]
**Describe the bug**
This template is addressed to the wrong user, it currently has the name of the copyeditor and should have the name of the author.

**Janeway version**
1.3.7

**Comment by hinefuku** [comment]
The email template itself is correct, but the html rendering (?) is addressed to the copyeditor. I'll grab a screenshot the next time I send out an email.

**Comment by ajrbyers** [comment]
@hinefuku can you confirm if this is still an issue? It looks okay from here. May be a specific issue with the journal you saw this on?

**Comment by hinefuku** [comment]
<img width="752" alt="copyedit" src="https://user-images.githubusercontent.com/45498398/79942647-e6925a80-842c-11ea-9e7c-ed06eefafbed.png">

**Comment by hinefuku** [comment]
The email is to Wes Schilling, but in grey box, it is addressed to the Copyeditor
