### ISSUE TITLE
pandoc plugin fails on conversion to html due to encoding error in save_galley

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1425]
**Describe the bug**
The save_galley function in production/logic.py fails if the html document being saved has been converted by the pandoc plugin. I think this would be the case with other documents that are encoded in utf8 (most?). 
It fails at this line `html_contents = f.read()`
Here is the full stack trace:
```

Traceback:

File "~/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "~/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "~/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "~/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "~/janeway/src/plugins/pandoc_plugin/views.py" in convert
  99.             logic.save_galley(article, request, output_path, True, 'HTML', save_to_disk=False)

File "~/janeway/src/production/logic.py" in save_galley
  84.             f.seek(0)

File "~/.virtualenvs/janeway/lib/python3.5/encodings/ascii.py" in decode
  26.         return codecs.ascii_decode(input, self.errors)[0]

Exception Type: UnicodeDecodeError at /plugins/pandoc_plugin/convert/17/file/232/
Exception Value: 'ascii' codec can't decode byte 0xe2 in position 1700: ordinal not in range(128)
```

**Janeway version**
master a58d982 (1.3.7)

**To Reproduce**
1. on proofing/typesetting stage attempt to convert a docx to html using pandoc with the [pandoc plugin](https://github.com/BirkbeckCTP/pandoc_plugin)
2. see error 

**Expected behavior**
a converted html document would be rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/1020384/74196121-95930880-4c2a-11ea-9b9f-bcd0c9e698f9.png)

**Additional context**
I was able to get around this by setting the read to
`with open(new_file.self_article_path(), 'r+', encoding='utf8') as f:` on the line above.
If this is acceptable I can make the pull request to add it.

**Comment by mauromsl** [comment]
Thanks @hachacha,
Most calls to `open()` in Janeway implicitely expect the host locale to be set to UTF-8.

I thin we should always declare the encoding explicitly (like you did in this instance).
Sounds good @ajrbyers ?

@hachacha  In the interim and if at all possible, I'd recommend changing the host preferred locale to UTF-8, as you will otherwise find this exception in some other views.
