### ISSUE TITLE
Initial migration/install/setup fails on sqlite

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#1432]
**Describe the bug**
Running install_janeway management command fails with:

> Applying submission.0037_auto_20190808_1326...Traceback (most recent call last):
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
>     return self.cursor.execute(sql)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
>     return Database.Cursor.execute(self, query)
> sqlite3.OperationalError: table "submission_article_source_files" already exists
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "./manage.py", line 16, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/home/martin/Documents/Programming/janeway/src/utils/management/commands/install_janeway.py", line 45, in handle
>     call_command('migrate')
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
>     return command.execute(*args, **defaults)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
>     fake_initial=fake_initial,
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 311, in database_forwards
>     to_model._meta.get_field(self.new_name),
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 516, in alter_field
>     return self._alter_many_to_many(model, old_field, new_field, strict)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 282, in _alter_many_to_many
>     self.create_model(new_field.remote_field.through)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 319, in create_model
>     self.execute(sql, params or None)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 136, in execute
>     cursor.execute(sql, params)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
>     return super(CursorDebugWrapper, self).execute(sql, params)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
>     return self.cursor.execute(sql)
>   File "/home/martin/.virtualenvs/janeway2020/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
>     return Database.Cursor.execute(self, query)
> django.db.utils.OperationalError: table "submission_article_source_files" already exists
> 

**Janeway version**
commit c44d53a177633cc7d8ebf2ac15cd5a94db730304 (HEAD -> master, origin/master, origin/HEAD)

**To Reproduce**
1. Clone repo
2. Switch to SQLite
3. run manage.py install_janeway

**Expected behavior**
Janeway is installed.

**Additional context**
Andy can reproduce

**Comment by ajrbyers** [comment]
Closed by https://github.com/BirkbeckCTP/janeway/pull/1434
