### ISSUE TITLE
Support for EPS/SVG files

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1445]
Our typesetter for MMB currently produces EPS files for figures. Would like to have support for EPS files in Janeway. Have asked them to supply PNG in meantime.

**Comment by ajrbyers** [comment]
Just an FYI: this isn't a case of Janeway supporting EPS files, browsers do not currently support displaying them.

**Comment by hinefuku** [comment]
ah nm then!
