### ISSUE TITLE
Editor Task Dashboard

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1472]
This would be a place for Janeway to draw editors attention to things that are coming up, things that are nearly due and things that are overdue (eg. blocking progress on an article).

Items will be colour coded: 
- Green
- Amber/Yellow
- Red

Suggested columns are

Date due | Article | Task | Responsible Parties (Editor/Reviewer/Typesetter/Proofreader etc)

**Comment by joemull** [comment]
This is potentially an early iteration of this idea: https://github.com/BirkbeckCTP/janeway/issues/1380

**Comment by ajrbyers** [comment]
Agreed!
