### ISSUE TITLE
Disable elements on Submissions page

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1476]
The Submissions page has a number text blocks that can be edited by the editors. These can be "disabled" by leaving the blocks empty. However this is not good enough for some blocks such as the "About" block. Since leaving the block empty would also remove it from other pages (e.g. homepage element)

It should be possible to hide any block from displaying regardless of its content. Otherwise, it should be possible to do this for blocks whose content is shared across different pages (although this might lead to confusion from the point of view of the editor).

**Comment by ajrbyers** [comment]
Workaround for this specific situation would be to:

- Copy the HTML rendered by the About block into an HTML block
- Clear the about text so it doesn't show on the submission page

But yeah - this should be fixed by the new CMS where each of these blocks can be enabled/disabled right?
