### ISSUE TITLE
Add expected issue of publication feature

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#1477]
Posting for another editor who has requested this:

"would be possible to include on the dashboard for 'articles under review' a column in which we enter the expected issue of publication (if the article is accepted) - a value that we could change, if necessary. Having this information would be very helpful to use for visualizing which articles belong together, which need to prioritized etc. I find myself going back very frequently to our old overview system (in a dropbox) to find out this information, and so it seems like it's something that  
needs to be included on our platform."

**Comment by ajrbyers** [comment]
@rhb123 this has already been completed for 1.3.8 release :D
