### ISSUE TITLE
Auto-remove erroneous formatting for abstracts in metadata

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#1481]
**Describe the bug**
At present, even when using plain text editors to paste metadata into the abstract field, this leaves a lot of invisible code junk which messes up the formatting, meaning that it needs to be fixed by going into the code manually. This is particularly time consuming across an issue, at which this needs to be fixed individually for several articles.

**Expected behavior**
An auto-formatter would be good that strips out all surplus / weird formatting would be great as it would save a lot of time doing these individually.

Thanks for your help

**Comment by ajrbyers** [comment]
Clean paste available in new version of Django Summernote.

**Comment by joemull** [comment]
Provisionally added to 1.4.3 as a reminder to take care of the Summernote formatting issues that are a persistent frustration for many users

**Comment by ajrbyers** [comment]
Another option for this one: Bleach Field. It can be used with summernote.

**Comment by ajrbyers** [comment]
Sadly, this issue will need to wait until 1.5 as bleach, which I think is the best solution for this, doesn't work on django 1.11.

**Comment by joemull** [comment]
It will be important to retain italicization by default so that titles of works retain italics.

**Comment by ajrbyers** [comment]
> It will be important to retain italicization by default so that titles of works retain italics.

Using bleach will allow us to flexibly determine which elements are and which aren't allowed. They can bet set at the global level and then tweaked for individual fields that require different elements.

**Comment by mauromsl** [comment]
closed by #3983
