### ISSUE TITLE
CMYK images break on upload: 'cannot write mode CMYK as PNG'

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1482]
**Describe the bug**
When a user uploads a `jpg` image with `CMYK` color mode, a 500 error is raised.and the stored image file is corrupted
The error is raised during transformation in `core.logic.resize_and_crop` when saving the image as `png`

**Janeway version**
v1.3.7

**To Reproduce**
1. Go to edit an issue's large image
2. Upload a CMYK image
3. See error

**Expected behavior**
The image should be transformed correctly into PNG

```
File "/usr/local/lib/python3.5/site-packages/PIL/PngImagePlugin.py", line 802, in _save
    raise IOError("cannot write mode %s as PNG" % mode)
OSError: cannot write mode CMYK as PNG
```

**Comment by ajrbyers** [comment]
`img.convert('RGB').save(img_path, "png")` might do it.
