### ISSUE TITLE
Add support for embedded youtube videos on JATS XML galleys

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1484]
**Is your feature request related to a problem? Please describe.**
Render an embedded YouTube video player for JATS galleys declaring an embedded YouTube media link

**Describe the solution you'd like**
At the XSLT layer, we could detect media elements of `mimetype=video` and `show=embed`.
If we can match the `href` attribute with a YouTube URL (regex?) we should be able to include the YouTube snippet on the output HTML.

**Comment by ajrbyers** [comment]
Closed by #2470
