### ISSUE TITLE
Additional Metadata

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1495]
**Is your feature request related to a problem? Please describe.**
Editors may want to create their own fields.

**Describe the solution you'd like**
Extend the existing configuratior to work for repositories

**Comment by mauromsl** [comment]
It might make sense to have at share a common submission model for both preprints and articles, it seems the submission process is identical and they only divert from post-submission.

**Comment by mauromsl** [comment]
assuming a flow like this:
![image](https://user-images.githubusercontent.com/10760678/83130558-679cdb80-a0d6-11ea-9035-2a18bc969749.png)
We could have a common submission model that leads to a preprint/article based on the submission platform. That way they can both use all of the submission logic, configuration... avoiding the duplicity
