### ISSUE TITLE
Preprints Manager Role

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1500]
There is not currently a role in the system that would permit a user to manage preprints without otherwise having superuser permissions. There should be, at minimum, a new role created that would give a user access to the Preprints Dashboard + Preprints Manager screens, but not to other Press-level functions.

The role might also have access to other Preprints areas (Subjects, Licences, Additional Fields, Settings), or these functions might be reserved for a different role.

**Comment by ajrbyers** [comment]
@justingonder I think we have this covered with https://github.com/BirkbeckCTP/janeway/issues/1493

Repository Manager for each repository.

**Comment by justingonder** [comment]
oops, you're right! i promise we tried to find an issue before posting ;)
