### ISSUE TITLE
article.peer_review on acceptance

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1525]
**Is your feature request related to a problem? Please describe.**
Editors sometimes forget to mark an article as reviewed and are surprised so see messages on article pages that inform readers that articles have not been reviewed.

**Describe the solution you'd like**
On acceptance:
- [x] Check if the article has had any completed reviews
- [x] Mark the article as reviewed
- [x] Leave the checkbox editable
- [x] On prepub, warn editors if it has not been marked as reviewed

**Comment by rhb123** [comment]
^rather than just warning if it has _not_ been marked as reviewed, it would be good to get the notification either way, ie, even if this has been marked as peer-reviewed if possible - thanks
