### ISSUE TITLE
Search function for supporters

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#1530]
**Is your feature request related to a problem? Please describe.**
There is currently a long list of supporters at https://www.openlibhums.org/plugins/supporters/ but no way to search these quickly, or to enable authors/editors to check if their institutions are supporters.

**Describe the solution you'd like**
A search box at the top of the page with 'Check whether your institution is a supporting member here' that auto-fills / refines the list as you type, and if none is found, says 'Your institution doesn't currently support OLH - please {get in touch}' or similar

**Describe alternatives you've considered**
Manually scanning down the list on the page

**Additional context**
It would be great to get this in so that we can encourage authors/editors to check whether their institution is supporting and get them to contact us for help getting them on board if not. Thanks for your help

**Comment by ajrbyers** [comment]
See: https://github.com/BirkbeckCTP/consortial_billing/issues/19
