### ISSUE TITLE
Hide citation counts on OLH theme

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1531]
Right now, the OLH theme displays citation counts. Although a feature to include references in Crossref metadata will be in 1.3.8, it only works for publications with XML. Would like to hide citation counts on publications without XML, to avoid having 0 displayed for all articles.

**Comment by ajrbyers** [comment]
We should also review other settings that can be moved to the new Aritlce group.

**Comment by ajrbyers** [comment]
This was completed in 1.3.9
