### ISSUE TITLE
Show the number of accepted reviews on the reviews dashboard

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1537]
**Is your feature request related to a problem? Please describe.**
From Monique at EE:
> On the dashboard/grid overview of reviews (https://ee.openlibhums.org/review/), the "No. active reviews" is misleading, because it doesn't distinguish between those that have accepted and those that have never answered. Could you divide it into two columns: "No. of requested reviews" and "No. of accepted reviews" - or just change the one column into "No. of accepted reviews", because that's what we want to know at a glance: have our requests finally been accepted?

**Describe the solution you'd like**
The number should be displayed in  a separate column.

**Describe alternatives you've considered**
We could combine the two figures into a single column so the table doesn't spread far too wide:
```
accepted/active reviews
=======================
                    2/3
=======================
```

**Comment by joemull** [comment]
I think this has been completed now, with the more recent detailed status column

**Comment by ajrbyers** [comment]
Confirming @joemull's assesment.
