### ISSUE TITLE
Allow editors to add any arbitrary email addresses in copy on the email screens

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1542]
**Is your feature request related to a problem? Please describe.**
When an email is sent from the system, the editors might want to add additional people in CC

**Describe the solution you'd like**
An input box for the editor to add arbitrary email addresses. I believe we could use the tagging library used for keywords with a custom email validator to present the user a single input element.

Requested on behalf of JCMS editors.

**Comment by joemull** [comment]
Merging into https://github.com/BirkbeckCTP/janeway/issues/2086
