### ISSUE TITLE
Add support for page ranges of an article within an issue

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1564]
**Is your feature request related to a problem? Please describe.**
Editors would like to indicate the range of pages an article takes within a given issue.

**Describe the solution you'd like**
There is a field called `page_numbers` in the Article model, but it is an `IntegerField` which is not suitable for declaring a page range. We could use a string field, similar to how other platforms do. This would help with content migrated from other platforms (e.g. OJS)

**Describe any alternatives you have considered**
Add a second IntegerField and build the range at render time. There is a limitation to this though: Some publications use roman numerals, so we would need to add support for rendering ints as roman numerals, as well as as flag to indicate which publications require this. With a **CharField**, we can't validate the input data but the value is more flexible for this use case and others

**Comment by ajrbyers** [comment]
Just a heads up, Article.page_numbers is a CharField so you can represent page numbers like `20-25` withouth making any changes.

**Comment by mauromsl** [comment]
Ah, my bad, I thought this was an integer field
