### ISSUE TITLE
Preprints - Links to external supplementary files

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1590]
**Is your feature request related to a problem? Please describe.**
The preprint system should allow authors to add externaly hosted supplementary files (e.g.: Driad)

**Describe the solution you'd like**
An interface for adding a link to an external supplementary file that is then related to the submission

**Additional context**
Not sure if we would need versioning support here.

**Comment by tingletech** [comment]
I'll take a look at this one

**Comment by ajrbyers** [comment]
What remains on #1789 to finish this?

**Comment by tingletech** [comment]
`/repository/dashboard/1010/` pages 
`/repository/manager/1010/edit/` pages
