### ISSUE TITLE
Back Content Plugin: Missing authors and galley

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1631]
**Describe the bug**
When using the Back Content Plugin to upload publications:

- Authors are not saved when the content is published, although the main author is retained, but not listed as an author.
- Upload Galley function does not work, uploaded file does not appear in the submission

**Janeway version**
1.3.8

**To Reproduce**
1. Go to back content plugin
2. Complete the metadata
3. Upload a galley and submit (file does not appear in galley list after upload)
4. Publish content
5. Published content appears without authors or uploaded file

**Expected behavior**
Retain authors and uploaded file

**Screenshots**
<img width="948" alt="missingauthorsfile" src="https://user-images.githubusercontent.com/45498398/84837807-9aaffc00-affe-11ea-9cd1-f3f3744ed0c7.png">

**Comment by ajrbyers** [comment]
@hinefuku I've filed this on the plugin repo here: https://github.com/BirkbeckCTP/back_content/issues/19
