### ISSUE TITLE
Trouble setting up apache

### ISSUE THREAD

**Issue by mittinatten** [BirkbeckCTP/janeway#165]
Hi,
I have had some trouble getting a test installation off its feet.

I found no documentation for how to set up a webserver to serve Janeway, so I tried setting up apache with mod_wsgi pointing to `src/core/wsgi.py`. 

I have run `python3 manage.py install_janeway` and everything seems to be ok there. When I then try to open the app in a browser I get an automatic redirect (302) to the `DEFAULT_HOST` in `settings.py`. Since this is a test, I set up my press to have the path `myserver.com/janeway` and the journal `myserver.com/janeway/journalAbbrev`, and the paths `janeway/`, `janeway/journalAbbrev/` and `janeway/journalAbbrev/install` all give same redirect.

This is the first time I have ever set up a Django app, so might be doing some really basic errors (it would have helped if there was a guide for this, or a link to one, in the installation wiki). The only changes I did to the settings-file were `DEFAULT_HOST` and the database credentials, is there something else that's obligatory?

regards,
Simon Mitternacht

**Comment by ajrbyers** [comment]
Hey Simon,

Can you tell me what the URL_CONFIG variable in your settings.py is? Also: just for the record we have a piece of documentation on setting up Janeway with Apache and Mod WSGI.  

https://github.com/BirkbeckCTP/janeway/wiki/Janeway%2C-Apache-and-WSGI

**Comment by mittinatten** [comment]
Hi, 
Thanks for the link, didn't see that!

URL_CONFIG was set to 'domain'. I changed it to the domain of my server, and updated wsgi.py with the correct paths, but it didn't help. No errors are logged.

**Comment by ajrbyers** [comment]
Okay, so it sounds like you're trying to use path based multi-tenancy, docs on that are here:

https://github.com/BirkbeckCTP/janeway/wiki/Multi-Tenancy

So you need to set `URL_CONFIG = 'path'` and restart apache then you should hopefully find that the press is available at:

myserver.com/press

and the journal is available at

myserver.com/journal_abbrev

**Comment by ajrbyers** [comment]
@mittinatten btw, we have a slack channel that might be useful for us to discuss this issue and post up a resolution once we work it out. Drop me an email a.byers@bbk.ac.uk if you want an invite to the slack channel.

Andy

**Comment by ajrbyers** [comment]
Apache documentation has been updated to help avoid the issue @mittinatten experienced.
