### ISSUE TITLE
Article Stages and Logs

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1653]
**Is your feature request related to a problem? Please describe.**
The Article Stages and Logs drop down is super useful but not prominent enough.

**Describe the solution you'd like**
This should be converted into a gapless button group (see image 2) with a drop-down on the end for Logs, Document Management and Admin,

**Describe alternatives you've considered**
Leaving it as is.

**Additional context**
![image](https://user-images.githubusercontent.com/8321378/85755030-7ee6dd00-b705-11ea-9c59-c7196f5f8ddc.png)
![image](https://user-images.githubusercontent.com/8321378/85755238-ab025e00-b705-11ea-8940-2764bdfbded5.png)

**Comment by hlflanagan** [comment]
You've described this as a "jump" button. What about just changing the button name to "Jump to Article Stages & Logs"?
