### ISSUE TITLE
HTML headers are instinguishable between levels

### ISSUE THREAD

**Issue by hlflanagan** [BirkbeckCTP/janeway#1660]
**Describe the bug**
The header/font ratio in the HTML is such that h1, h2, h3, etc are indistinguishable from each other, both in the text and in the article ToC.

**Janeway version**
Hosted

**To Reproduce**
See: [https://bok.idpro.org/article/id/45/](https://bok.idpro.org/article/id/45/)
The levels are different in the HTML:
<h1 id="introduction">
   Introduction
  </h1>
  <p>
...
  </p>
  <h2 id="resources-need-stability">
   Resources need stability
  </h2>

**Expected behavior**
Indentation in the ToC to indicate subsections
Visually distinct header levels (e.g., font changes between h1 vs h2 vs h3, etc)

**Screenshots**
See attached screenshot; no changes between Intro, Resources Need Stability, etc
![Screenshot_2020-06-30 Introduction to Identity - Part 2 Access Management](https://user-images.githubusercontent.com/4659093/86181374-bd541180-bae2-11ea-8854-f3207136daf1.png)

**Comment by ajrbyers** [comment]
<img width="675" alt="Screenshot 2024-08-06 at 17 07 23" src="https://github.com/user-attachments/assets/0ff0c6fe-fd0c-40cd-a00a-5ddeea4cdb77">

h1 and h2 now use quite different sizes (2.5 and 2.0 REM) so I don't think this issue anymore. Please do let me know if you consider this an issue still @hlflanagan.
