### ISSUE TITLE
Homepage glitches with images

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#1663]
**Describe the bug**
Something odd appears to be happening with the image displays for the logos on the homepages https://poetry.openlibhums.org/ and https://19.bbk.ac.uk/ (see screenshots)

![image](https://user-images.githubusercontent.com/55796596/86264635-b26cb000-bbba-11ea-8c8a-0519de9939ae.png)

![image](https://user-images.githubusercontent.com/55796596/86264702-c44e5300-bbba-11ea-88e8-8286567e7c44.png)

**Desktop (please complete the following information):**
Windows 10, Chrome

Also flagged via Discord but adding here as well - thanks

**Comment by ajrbyers** [comment]
This is not a bug - just a config error on the server which has been fixed :)
