### ISSUE TITLE
Automatical email after publication of article

### ISSUE THREAD

**Issue by simifilm** [BirkbeckCTP/janeway#1674]
**Is your feature request related to a problem? Please describe.**
We have someone who is responsible for social media et al. but who is not an editor or otherwise involved in the publication process. Since he is responsible for promoting published articles, it would be cool if he could be automatically notified when a new article goes online. 

**Describe the solution you'd like**
Add to possibility to inform people in addition to author, reviewer and section editor if an article is published.

**Describe alternatives you've considered**
Write an email

**Comment by mauromsl** [comment]
Helen requested the exactly the same feature some time ago #1186

**Comment by ajrbyers** [comment]
Cool. @simifilm I'm closing this in favour of #1186 which looks the same.

**Comment by joemull** [comment]
FYI this was closed because we want to include this work in a more general feature that would make it possible to configure notifications to people in arbitrary roles when articles move between stages. See https://github.com/BirkbeckCTP/janeway/issues/3357
