### ISSUE TITLE
Bump Django Version

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1683]
- Bump Django version to 4.1 -> 4.2
- Make backwards incompatible changes
- Bump other dependencies
Closes #3198
Things to test:

- [x] Replace django-recaptcha2 with https://github.com/torchbox/django-recaptcha
- [x] #3223
- [x] Replace simple-math-captcha with https://pypi.org/project/django-simple-math-captcha/
- [x] mardown-duex isn't supported
- [x] Bug on funding submission page
- [x] django-foundation is broken, `[Django TypeError: render() got an unexpected keyword argument 'renderer'](https://stackoverflow.com/questions/52039654/django-typeerror-render-got-an-unexpected-keyword-argument-renderer)`

**Comment by hardyoyo** [comment]
A quibble: this ticket says 2.2 but the [Roadmap on Trello says 3.2](https://trello.com/c/an4Mrsea/4-v15-django-32-upgrade) I will assume the Road Map is correct.

**Comment by ajrbyers** [comment]
> 

Thanks. Updated. The ticket is ancient.

**Comment by cederom** [comment]
Hello world :-) This seems the most modern open-source publishing platform.. and I love Python + Django that I use myself.. however 1.11LTS has been outdated in 2017.. so this bump to a new and still supported LTS seem really important in terms of decision making :-)

**Comment by ajrbyers** [comment]
> Hello world :-) This seems the most modern open-source publishing platform.. and I love Python + Django that I use myself.. however 1.11LTS has been outdated in 2017.. so this bump to a new and still supported LTS seem really important in terms of decision making :-)

Hello! In our upcoming release we’ll be making the jump to 4.2.

**Comment by cederom** [comment]
Awsome! Thanks for the info @ajrbyers :-) When is the next major release planned with Django 4.2? :-)

**Comment by ajrbyers** [comment]
@cederom we will make the jump to 4.1 and then to 4.2 when its finalised.

**Comment by cederom** [comment]
Thank you @ajrbyers :-)

**Comment by ajrbyers** [comment]
> Thank you @ajrbyers :-)

I've also added a note to test against Python 3.10 once I get a stable build with Django 4.1.

**Comment by ajrbyers** [comment]
Dropped markdown-duex in favor of python-markdown and an inhouse template tag.

**Comment by cederom** [comment]
After successful install and some hours with `v.1.4.3-RC-4` I also find current WYSIWYG RichText editor amazignly confusing and unreliable.. it does not work smoothly, confuses blocks, several times copy-paste and edit operation resulted in truncated results required several agttempts with original always in the clipboard. I would be really disappointed using this editor as the core source of my text and then just see that 3/4 of what I wrote was gone :-)

World does not need fancy pancy msword in browser anymore, just reliable simple focus and goal oriented solutions.. personally I prefer MarkDown (as here) for simple formatting and scratchpad.. and LaTeX for serious works (articles, books, presentations). Having MarkDown editor like here on GitHub woud be really amazing.

In a perfect situation we would like to automate Issue generation.. I know and use LaTeX.. but there may be other tools to allow that in elegant way :-) Submission Fields + Simple universal formatting + Templates may be the way to go. Thank you! :-)

Here is my sandbox (in fact we just need the Journal part at the main URL):
1. Press: https://new.e-health.pl/
2. Journal: https://new.e-health.pl/advances/

**Comment by ajrbyers** [comment]
Closed by https://github.com/BirkbeckCTP/janeway/pull/3438
