### ISSUE TITLE
Preprints subject builder requires repository selection, field missing

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1700]
/repository/manager/subjects/ used to configure repository subjects requires the selection of a repository, but no repository field is in the UI. it is not possible to save a new subject without making a repository selection, and it is not possible to submit a preprint to the repository without configuring at least one subject.

<img width="1059" alt="2020-07-17_13-48-31" src="https://user-images.githubusercontent.com/29953714/87821024-be03dc00-c834-11ea-839f-b76bf7a32af4.png">

**Comment by ajrbyers** [comment]
Hey Justin - checkout https://github.com/BirkbeckCTP/janeway/milestone/21 if you can before adding these. This particular thing is known already - https://github.com/BirkbeckCTP/janeway/issues/1634

**Comment by ajrbyers** [comment]
BTW - you can work-around this by adding the subject in Admin.
