### ISSUE TITLE
Refactor core.views.edit_settings_group

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1708]
**Is your feature request related to a problem? Please describe.**
This view has a number of problems
 It serves 4 different purposes:

- Create a new journal from the press
- Edit a journal from the press manager
- Edit a journal from the journal manager
- Edit a setting group

**Describe the solution you'd like**
- Break the view into a single view for each use case
- Get rid of the mutation of the global state of `request.journal`

**Comment by ajrbyers** [comment]
@mauromsl as I am refactoring this for multi-lang should I include this in 1.4?
