### ISSUE TITLE
Cannot add authors during repository submission process

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1723]
**Describe the bug**
The mechanism an author would use to add authors manually to their submission is not working.

**Janeway version**
preprint-remodel

**To Reproduce**
1. Start a new submission
2. Make it to step 2, Authors (e.g. ~/repository/submit/4/authors/)
3. Click 'Add New Author' button
4. Enter required author information in resulting modal
5. Click 'Add New Author' at bottom of modal to save.
The modal will close, but no new author will have been added to the submission.

**Expected behavior**
Completing the new author form should result in the addition of an author to the submission, or the user should receive an error indicating why the author add failed.

**Additional context**
Currently, only the 'Add Self as Author' button is functional.

**Comment by ajrbyers** [comment]
I suspect this is because it is finding an existing author account and not handling it properly.

**Comment by ajrbyers** [comment]
Clsoed by d97e9bea
