### ISSUE TITLE
Uploading new version as author causes error "NoReverseMatch at /repository/dashboard/2/"

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1724]
**Describe the bug**
As an author, if I attempt to upload a new version of my manuscript file, I get the error "NoReverseMatch at /repository/dashboard/2/"

**Janeway version**
preprint-remodel

**To Reproduce**
1. Navigate to an existing submission. (Not sure if it matters, but in this case the submission had 0 files associated with it, since I had deleted the original file from the Editor view.)
2. Click the 'Upload New Version' button
3. Select any update type and upload a new file
4. See error upon clicking the Upload button. (Note I reproduced this multiple times - sometimes instead of the Django error, my browser gave me a 'Connection reset' error.)
5. The file does appear to successfully upload, despite the error.

**Expected behavior**
File upload should complete without error.

**Screenshot**

<img width="1201" alt="2020-07-23_16-21-10" src="https://user-images.githubusercontent.com/29953714/88339996-99aa7280-cd00-11ea-8e08-06f2c6328348.png">

**Comment by justingonder** [comment]
The same error occurs if you attempt to upload a new version as an Editor

**Comment by ajrbyers** [comment]
Closed by 883e3954
