### ISSUE TITLE
Upload of New Version file with long filename fails silently as Editor

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1725]
**Describe the bug**
As Editor, if you attempt to upload a file with a >100 character filename, the file upload fails silently. If you attempt to do the same as an Author, you get the error:

> Form errors:
>     File
>         Ensure this filename has at most 100 characters (it has 124).

**Janeway version**
preprint-remodel

**To Reproduce**
1. Go to Preprints Manager
2. Select any existing preprint
3. Scroll to the Files section
4. Click Upload File
5. Upload a file with >100 character filename
6. The upload fails silently.

Repeat the same steps, except instead of starting from Preprints Manager, start from Dashboard. Instead of the file upload failing silently, you will receive an error explaining the character limit.

**Expected behavior**
Editor should receive same feedback as author so that they know the file upload failed and why.

**Additional context**
Example file for reproducing attached.
[Simon Franchini Calibration of astigmatic particle tracking velocimetry based on generalized Gaussian feature extraction.pdf](https://github.com/BirkbeckCTP/janeway/files/4969012/Simon.Franchini.Calibration.of.astigmatic.particle.tracking.velocimetry.based.on.generalized.Gaussian.feature.extraction.pdf)

**Comment by ajrbyers** [comment]
Closed by 9a3db03b
