### ISSUE TITLE
Some values set in repository Setup Wizard are not reflected in repository Settings

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1729]
**Describe the bug**
The following fields that are initially configured via the repository Setup Wizard are not reflected when the same fields are viewed in that repository's own Settings screen.

- Preprints About
- Preprints Start
- Limit upload to PDF
- All email template text

**Janeway version**
preprint-remodel

**To Reproduce**
1. Complete any of the above fields via the Setup Wizard
2. In the same repository, navigate to Settings
3. Field values listed above will not match what was configured in the wizard.

**Expected behavior**
The values of these fields should always be the same in both the Wizard and Settings, and changes made in either place should have the expected effect on the repository (e.g. changes to the About text in either place should result in changes to the public-facing About page). Currently it seems that most public-facing pages are displaying whatever is entered in the wizard, and ignoring the same fields under Settings.

**Additional context**
Preprints Start doesn't seem to display anywhere in the deposit workflow, regardless of whether you enter text into that field from the wizard or settings.

**Comment by ajrbyers** [comment]
@justingonder I think for this part the Wizard will replace the settings screen which is from the old model which is why things won't be represented properly.

**Comment by ajrbyers** [comment]
Actions:

- Remove old settings page
- Replace link with that of the wizard
- Display start text on submit/start

@justingonder can you confirm that looks ok?

**Comment by justingonder** [comment]
@ajrbyers  perfect! but it's late Friday and you're not supposed to open these gems from me till tomorrow ;P

**Comment by ajrbyers** [comment]
![image](https://user-images.githubusercontent.com/8321378/88453796-4d774380-ce62-11ea-8640-f88a0fb28fb1.png)

Completed by fcf50114
