### ISSUE TITLE
Journal submission form crashes if no copyright notice

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1752]
**Describe the bug**
The journal submission form (step 1) leads to an error page if the copyright notice has been removed from the Submission Configurator

**Janeway version**
eschol_pilot (modified 1.3.7)

**To Reproduce**
1. Using the Submission Configurator, uncheck the Copyright Notice check-box
2. Attempt to start a new submission. You will reach an error page.
3. Return to Configurator and re-check the Copyright Notice box.
4. Submissions will work as expected again.

**Expected behavior**
If Copyright Notice is required for the page to work (which it probably should be) then a user should not be able to un-check the Copyright Notice box in the Configurator. Or, the submission process should not break if the box is unchecked in Configurator.

**Comment by ajrbyers** [comment]
@justingonder this has been fixed already, consider asking @hardyoyo if eschol_pilot can be bumped to v1.3.8-RC-9 or if you can wait a couple of days the finalised 1.3.8 we will be publishing shortly.
