### ISSUE TITLE
Allow custom text on the Upload Files page

### ISSUE THREAD

**Issue by blakistonr** [BirkbeckCTP/janeway#1754]
**Issue**
Because we ask authors for pitches (rather than full manuscripts) as their initial submission, we'd like to customize the text at the top of the "Upload files" page to explain, and link to a pitch template.

**Solution**
Make this text an editable field in the Submission Settings: "Submission guidelines: To upload a file, select it using one of the 'Choose file' buttons, then upload it with the 'Upload file' button next to it. You will then be asked for some additional information (label, description etc.)"

**Alternatives**
We know you're already working on customizing the label "Manuscript" so that we can change it to "Manuscript or pitch." This will help, but a place for some more contextual, custom instructions would be useful.

**Additional context**
A custom field will also allow us to do things like link to our style guide or our publishing guidelines at the point of need where authors are uploading their submission.

**Comment by ajrbyers** [comment]
Hi @blakistonr we're includin a setting to override the upload file title in our next release which is coming out in the next few days.

 Information on what file to upload can be included in the submission checklist for the time being and we can look at adding a contextual setting to the upload page in a future version.

**Comment by blakistonr** [comment]
Sounds like a plan, thanks so much for your quick response!
