### ISSUE TITLE
[Preprints] Article list template needs pagination

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1767]
**Is your feature request related to a problem? Please describe.**
/repository/list and search results page currently lack pagination, making it difficult for users to navigate a long list of objects
(note: on our current instance, this is also a problem on the homepage, but believe that is being fixed by capping the number of items shown on the homepage)

**Describe the solution you'd like**
Expect any page using the list template to show a maximum default number of results (e.g. 10) and have an interface for navigating additional pages of results, determining the number of results per page, etc.

**Comment by ajrbyers** [comment]
I believe there is a django paginator in the view. Will investigate why it's not working.

**Comment by ajrbyers** [comment]
The list view is already being paginated but the paginator is not displaying. PR added to fix.
