### ISSUE TITLE
[Preprints] Submit link from Repository Dashboard view broken

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1768]
**Describe the bug**
Submit link broken from Repository Dashboard

**Janeway version**
preprint-mvp

**To Reproduce**
1. Go to ~/repository/dashboard/
2. Select profile icon in upper right
3. Select 'submit'
You'll land at an error page. Appears that the underlying URL is missing /repository/

**Comment by ajrbyers** [comment]
@justingonder reports this is not fixed.

**Comment by ajrbyers** [comment]
@justingonder on local I get the following URL: http://localhost:8000/eartharxiv/repository/submit/start/
