### ISSUE TITLE
[Preprints] License on item page should provide details, link to license URL

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1784]
**Is your feature request related to a problem? Please describe.**
Currently the repository item page displays the value of the License Name field, but does not surface the license text or URL. e.g.: http://pub-janeway2-dev.escholarship.org/EA/repository/view/9/

**Describe the solution you'd like**
The license should at least link out using the license URL.

**Comment by ajrbyers** [comment]
Is that an actual abstract? My lord its long. We may need to truncate with a "View More" type thing.

**Comment by justingonder** [comment]
i was thinking of posting that, but picking my battles ;P

**Comment by ajrbyers** [comment]
> i was thinking of posting that, but picking my battles ;P

I could make the abstract text a bit smaller at the very least...
