### ISSUE TITLE
Author metadata edits during prepublication not retained

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#1796]
**Describe the bug**
Edits made to author metadata (e.g. name, institution) during prepublication are not retained when article is published.

**Janeway version**
1.3.8

**Screenshots**
<img width="643" alt="authormetadata" src="https://user-images.githubusercontent.com/45498398/91324109-4c9a4000-e787-11ea-91e9-b9a891902338.png">

During prepublication, the following edits were made and lost during publication:

- Perdue changed to Perdue Foods Inc.
- Hawkins changed to Hawkins Inc.
- Wes changed to M. Wes

**Comment by ajrbyers** [comment]
Fixed in 1.3.9 with an update to the snapsot command.
