### ISSUE TITLE
Hide Journal Name in Footer of Emails

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1836]
**Is your feature request related to a problem? Please describe.**
Some journals setup their signatures properly and so want to be able to hide the automatic addition of the journal name to the email.

**Describe the solution you'd like**
Add a boolean option to disable this feature.

**Comment by joemull** [comment]
We are going to implement something like this but a bit more comprehensive by creating a setting for standard information appended to all emails in https://github.com/BirkbeckCTP/janeway/issues/2137.
