### ISSUE TITLE
[Preprint] Improve Repository Manager page load time

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1842]
**Describe the bug**
Repository Manager page load times are a bit slow (up to 15 seconds) /repository/dashboard/ on our instance. AB suspects it may have to do with our 1,500+ preprint objects.

**Janeway version**
preprint-remodel

**To Reproduce**
1. Log in
2. go to /repository/dashboard/
3. wait
4. go to author dashboard to see example of normal page load time.

**Comment by ajrbyers** [comment]
Can you confirm this is on Dev AND live?

**Comment by justingonder** [comment]
just checked. it is hanging on prod as well, though not as long (presumably though our prod server is beefier)
