### ISSUE TITLE
[Preprints] Editors unable to edit metadata b/c of form error "Submission Agreement: This field is required"

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#1844]
**Describe the bug**
Since the introduction of the author agreement to the submission form, editors have lost the ability to make changes to items' metadata because the system returns the error "Submission Agreement: This field is required."

**Expected behavior**
Editors should be able to make metadata changes without re-affirming the submission agreement (which isn't available on the editor's edit metadata page anyway).

**Screenshots**
Attached
<img width="524" alt="2020-10-03_16-09-34" src="https://user-images.githubusercontent.com/29953714/95001814-15dbf480-0593-11eb-89b7-fc3600e88e3e.png">

**Comment by ajrbyers** [comment]
Looks like it's using the submission form, missed that. Should be a quick fix in place for tomorrow.
