### ISSUE TITLE
[Preprints] Manager becomes owner after editing metadata, no log of metadata edit or owner change

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#1893]
**Describe the bug**
When a Manager edits the metadata of a preprint -- pending or published -- the Owner of the preprint is updated to the Manager. 

**Janeway version**
Janeway preprints 

**To Reproduce**
1. Go to a pending or published preprint; note the preprint's **Owner**. 
2. Under Controls, click **Edit Metadata** 
3. Make an edit, eg to the title. 
4. Click **Save Metadata** and be returned to the edit page. 
5. Return to the Preprint Manager view for the preprint (eg by clicking the **title**). 
6. Note that the **Owner** has changed to the Manager's account. 
7. Under Controls, click **Log**. Note that there is no log of the metadata update or change of owner. 

**Expected behavior**
1. The preprint's Owner remains the submitter. 
2. The metadata change and the change of Owner are listed in the log. 
2. The Manager has a method to change the Owner. 

**Screenshots**
[Screenshot - change in Owner](https://user-images.githubusercontent.com/15632391/97338967-63791380-1858-11eb-93e2-110645faf22e.png)
[Screenshot - no metadata update or Owner change in item log](https://user-images.githubusercontent.com/15632391/97339250-bb177f00-1858-11eb-8d12-d2a37fdc3bd4.png)

**Comment by ajrbyers** [comment]
Thanks @alainna I've got a fix in for this, once reviewed the guys at CDL can get it deployed.

**Comment by alainna** [comment]
thanks @ajrbyers ! 

Is there possibility to add record of owner or metadata changes to the log (or a history file as mentioned in https://github.com/BirkbeckCTP/janeway/pull/1891 ) as well?

**Comment by ajrbyers** [comment]
@alainna once this bug is fixed the only way to change the owner will be via our admin system. That said I think a LogEntry would be okay for these changes rather than a Version.
