### ISSUE TITLE
Filtering preprints by sub-discipline

### ISSUE THREAD

**Issue by shicks-seismo** [BirkbeckCTP/janeway#1898]
**Is your feature request related to a problem? Please describe.**
On the old EarthArXiv website, we used to be able to browse preprints and filter them by discipline/tag, e.g. "Geophysics and Seismology". This was useful for quickly browsing new preprints most relevant to the user.

**Describe the solution you'd like**
Currently, a workaround is to search for the "geophysics and seismology" tag, which sort of works, but the search results cannot be sorted by date, so it is not easy to quickly browse the newest preprints which are most appropriate to you. The sub-discipline tickbox options on the old EarthArXiv website worked well, I think.

**Comment by ajrbyers** [comment]
Hey @shicks-seismo I've added a PR for this here: https://github.com/BirkbeckCTP/janeway/pull/1899

Once it is reviewed the folks over at CDL can put it up for you.

**Comment by shicks-seismo** [comment]
Nice - speedy work - thanks!
