### ISSUE TITLE
Text for Source Files to help typesetters know where to upload InDesign files

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#1902]
**Is your feature request related to a problem? Please describe.**
Previously typesetters have missed uploading InDesign files correctly in the system, either not uploading them altogether or uploading these to the wrong section.

**Describe the solution you'd like**
Would it be possible to add some reminder text to the 'Source Files' section to help signpost this for the typesetters more clearly, eg, under the Source Files header, add the text: 'This is where any source files used to create the typeset galley files should be uploaded (eg, InDesign files).' If no files are added under 'Source Files', I'd then also suggest adding a warning popup: 'Warning: no source files have been uploaded. Click continue to proceed or go back to return and upload source files.'

Thanks for your help

**Comment by joemull** [comment]
Fixed by https://github.com/BirkbeckCTP/typesetting/commit/0348886e
