### ISSUE TITLE
Editing email templates on new journal does not create new setting. overwrites default.

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1903]
**Describe the bug**
Editing email templates on new journal does not create new setting overwrites default. 

**Janeway version**
7f5ce75271b3a7e5882d04d55dea8b02e7ed2a77
1.3.8-hotfix-3 hosting our own press using URL_CONFIG = 'path'

**To Reproduce**
What I assume should be happening is when you edit a template in a journal a new setting is made for that journal as it states above the form on this /LDR/manager/templates/author_publication/
 _You can edit the override for this journal by filling this form:_

submitting a change to /LDR/manager/templates/author_publication/ does not create a new setting but overwrites the default:
![image](https://user-images.githubusercontent.com/1020384/98128419-e9fba980-1e85-11eb-9603-eeb7ea34b463.png)
^there is no LDR setting being set here
and then if you look at the default setting on the admin (or just refresh the page to see the above "default" change to what you just submitted)
![image](https://user-images.githubusercontent.com/1020384/98128924-83c35680-1e86-11eb-87ae-ac9eab71fffd.png)

**Expected behavior**
a new setting should be made so that we are not overwriting the default

**Additional context**
Looking at the `edit_email_template` function in core/views.py i see that it's returning the default setting while in the LDR journal from the `get_setting` function. Is this happening because when a new journal is made email templates are not created? I don't know if the best solution for this is to create a duplicate setting value for every journal on the journal's creation OR to alter this function so that a new setting is made whenever submitting this form.

**Comment by ajrbyers** [comment]
hey @hachacha 1.3.9-RC2 is out and has a fix for this https://github.com/BirkbeckCTP/janeway/tree/v1.3.9-RC-2

**Comment by ajrbyers** [comment]
(here is the PR incase you want to do some wizardry https://github.com/BirkbeckCTP/janeway/pull/1862)

**Comment by hachacha** [comment]
@ajrbyers thanks, boss!
