### ISSUE TITLE
Tweak repository.site_url to handle calls outside of a request context (like press.site_url)

### ISSUE THREAD

**Issue by hardyoyo** [BirkbeckCTP/janeway#1935]
**Is your feature request related to a problem? Please describe.**
I'm working on a management command to facilitate minting DOIs for accepted preprints, and need a way to generate a correct target_url to send to EZID/Crossref. Currently repository.site_url does not return a correct value when called outside of normal Django context (i.e. in a view).

**Describe the solution you'd like**
In a CLI context, it would be useful for repository.site_url to return a correct value, much the same as press.site_url does.

**Describe alternatives you've considered**
Many workarounds, but they all fall into the category of "kludge", this seems like the most elegant solution.

**Additional context**
This feature suggestion was originally made by @mauromsl in Discord

**Comment by ajrbyers** [comment]
In the interim the site_url output of the `Repository` model has been updated:

```
In [1]: from repository import models

In [2]: r = models.Repository.objects.first()

In [3]: r
Out[3]: <Repository: [live] ing.grid Preprint Repository>

In [4]: r.site_url()
Out[4]: 'https://preprints.inggrid.org'
```
