### ISSUE TITLE
[Preprints] Allow author to add published DOI during update

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1940]
**Is your feature request related to a problem? Please describe.**
We display a generic statement that papers are not peer reviewed, this is sometimes not true.

**Describe the solution you'd like**
When an author updates a preprint we should ask for the published version DOI and whether it has been peer reviewed to hide this statement.

**Comment by tingletech** [comment]
This language seems fine?

https://eartharxiv.org/repository/view/1734/
[
<img width="592" alt="Screen Shot 2021-05-06 at 9 55 35 AM" src="https://user-images.githubusercontent.com/227374/117336922-99bfcd00-ae51-11eb-9c55-e3dec4fc35fa.png">
](url)
(just a note to myself) https://github.com/BirkbeckCTP/janeway/blame/preprint-remodel/src/repository/models.py#L351-L365

The link does need to be made to work

```
themes/material/templates/repository/preprint.html
33:                    This is a {{ request.repository.object_name }} and has not been peer reviewed.{% if preprint.doi %} The published version of this {{ request.repository.object_name }} is available: <a href="{{ preprint.doi }}">{{ preprint.doi }}</a>.{% endif %} This is version {{ preprint.current_version.version }} of this {{ request.repository.object_name }}.
```

**Comment by alainna** [comment]
Adding envisaged screenshot: 
![image](https://user-images.githubusercontent.com/15632391/119535505-10b3fb80-bd56-11eb-842a-6565c43041cb.png)

**Comment by ajrbyers** [comment]
I’m not 100% sure what the field looks like atm but shouldn’t we capture just the DOI rather than the URL?

**Comment by tingletech** [comment]
Note for CDL: see also 
 *  (#PUBD-28) Authors can edit metadata to add published DOI

There was a proposal once to also add keywords to this PR, seems a little harder since it is a many-to-many
  * (#PUBD-125) Authors should be able to edit metadata to add/edit/remove keywords

**Comment by tingletech** [comment]
FWIW, the `help_text` on the model current seem to say to use the full URL https://github.com/BirkbeckCTP/janeway/blame/preprint-remodel/src/repository/models.py#L357

```
351     doi = models.CharField(
352         max_length=100,
353         blank=True,
354         null=True,
355         verbose_name='Published DOI',
356         help_text='You can add a DOI linking to this item\'s published version using this field. '
357                   'Please provide the full DOI ie. https://doi.org/10.1017/CBO9781316161012.'
358     )
359     preprint_doi = models.CharField(
360         max_length=100,
361         blank=True,
362         null=True,
363         verbose_name='Preprint DOI',
364         help_text='System supplied DOI. '
365     )
```

but, no one who has entered a DOI (I guess all the current values came in from the original ETL).

```
MySQL [janeway]> select doi, preprint_doi, id from repository_preprint where doi;
+-----------------------------+-----------------+------+
| doi                         | preprint_doi    | id   |
+-----------------------------+-----------------+------+
| 10.13140/RG.2.2.35973.78563 | 10.31223/X5759Q | 1734 |
| 10.1111/sed.12817           | 10.31223/X50W3H | 1878 |
| 1773/44712                  | NULL            | 1920 |
| 10.1093/gji/ggx375          | 10.31223/X5T30W | 1953 |
| 10.1093/gji/ggz041          | 10.31223/X5PC8F | 1954 |
+-----------------------------+-----------------+------+
5 rows in set, 743 warnings (0.00 sec)
```

I've started a branch and fixed the template so it supplies `https://doi.org/` in the href -- should it display `https://doi.org/` in the link text as well?

<img width="294" alt="Screen Shot 2021-05-27 at 7 54 05 AM" src="https://user-images.githubusercontent.com/227374/119848605-cc913a00-bec0-11eb-9bde-22ec50de8c14.png">

**Comment by alainna** [comment]
>I've started a branch and fixed the template so it supplies https://doi.org/ in the href -- should it display https://doi.org/ in the link text as well?

@tingletech Yes, please! "https://doi.org/" is compliant with the DOI display guidelines

**Comment by ajrbyers** [comment]
For clarification - do we want to capture the full URL or just the prefix/suffix?
