### ISSUE TITLE
[Preprints] Manager cannot add a registered author to a preprint 

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#1954]
**Describe the bug**
When a manager edits a submitted or published preprint's metadata to add a co-author then clicks "Save Author" or "Save Metadata", the system will return an error and not add the co-author if the co-author's email address is already registered in the system. 

**Janeway version**
janeway preprints 

**To Reproduce**
1. Navigate to preprint (ex: https://dev.eartharxiv.org/repository/manager/1720/ ) and click "Edit Metadata" under Controls: https://dev.eartharxiv.org/repository/manager/1720/edit/
2. Add an author whose email address is already in the system (ex: alainna.wrigley+1@ucop.edu ) 
3. Click "Save Author" and receive an error notice: 
> Form errors:
> Email address
> Author with this Email address already exists.
4. Because author data still appears to be in the form, scroll down and click "Save Metadata" 
5. The new author's data is not in the preprint metadata: https://dev.eartharxiv.org/repository/manager/1720/

**Expected behavior**
1. The new author's data is in the preprint metadata. 
2. There would be an option for the author / manager to search for existing authors by name or email address (similar to what is on the author's submission form): "Add an author already in the system" 

**Additional context**
This does not occur when a submitter adds authors on the initial submission form

**Comment by ajrbyers** [comment]
Noooo! I fixed this already. Will take a look tomorrow.

**Comment by tingletech** [comment]
seems like to fix this, we would need to have the "Add an author already in the system" from the author's submission form and change "➕More Author Forms" to "➕Add an author NOT already in the system"
  
<img width="1610" alt="Screen Shot 2021-02-11 at 7 14 58 AM" src="https://user-images.githubusercontent.com/227374/107656385-f50a6680-6c38-11eb-9271-e2972be00a71.png">

<img width="718" alt="Screen Shot 2021-02-11 at 7 20 39 AM" src="https://user-images.githubusercontent.com/227374/107657218-d22c8200-6c39-11eb-908b-302183118391.png">

**Comment by tingletech** [comment]
or, if there is an email match, then 1) ignore all the other fields and 2) use the info already associated with the author, and change the message to "Author with this Email address already exists -- using data from the author's record"?
