### ISSUE TITLE
[XSLT] Footnotes not linking properly when using ids with Upper case characters

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1956]
**Describe the bug**
When a footnote with upper case letters is present in a JATS XML file, our XSLT renders the ID in lower case but doesn't do that to the href. This means that the anchor in the text doesn't link to the footnote properly (N11 is now n11).

**Janeway version**
v1.3.8

**Expected behavior**
The XSLT shouldn't tamper with the footnote ids set by the typesetter

**Screenshots**
![image](https://user-images.githubusercontent.com/10760678/102490398-aee4bc80-4066-11eb-89f8-bb19856cde48.png)

**Comment by joemull** [comment]
This is a persistent issue with other kinds of cross-references too. Here's one reported by @pgoussy at Michigan recently:

JATS footnote number:
`<xref ref-type="fn" rid="fn001"><sup>1</sup></xref>`

JATS footnote
`<fn rid="fn001"><label>1.</label> <p>Post-retreat workshops have addressed pedagogical topics such as &#x201C;Applying Retreat Insights to Your Teaching&#x201D; and &#x201C;Teaching with TIME in Mind.&#x201D; In May 2020, we held our first &#x201C;alumni only&#x201D; weeklong retreat, and during the upcoming academic year, we will offer advanced workshops for retreat alumni, thus creating a scaffolded curriculum that further supports our integrative, insight-driven approach.</p></fn>`

HTML footnote number:
`<a class="xref-fn" href="#fn001" id="nm1"><sup><sup>1</sup></sup></a>`

HTML footnote:
`<li> <span class="footnotemarker" id="fn1"></span>Post-retreat workshops have addressed pedagogical topics such as “Applying Retreat Insights to Your Teaching” and “Teaching with TIME in Mind.” In May 2020, we held our first “alumni only” weeklong retreat, and during the upcoming academic year, we will offer advanced workshops for retreat alumni, thus creating a scaffolded curriculum that further supports our integrative, insight-driven approach.
        [<span class="footnotemarker" id="n1"><a href="#nm1"><sup>^</sup></a></span>]
    </li>`
