### ISSUE TITLE
[XSLT] Handle `mailto` on email tags

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1957]
**Is your feature request related to a problem? Please describe.**
When an <email> tag is found in the JATS XML, we should render a `mailto` link
<email xlink:href="mailto:username@some.com">username@some.com</email>

**Comment by ajrbyers** [comment]
JATS uses the <email> tag (not mailto) and @tbelc added support for it here: https://github.com/BirkbeckCTP/janeway/pull/4092

(@mauromsl if you think this should be re-opened go ahead and comment)
