### ISSUE TITLE
syntax error in merge_users in press prevents execution of logic

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1971]
**Describe the bug**
small bug!
return redirect(reverse('merge_users')) on line 272 in https://github.com/BirkbeckCTP/janeway/blob/master/src/press/views.py
prevents the try except and further logic from executing so merge does not occur
just throw a \t in front and it works.

**Janeway version**
1e3af4a18af0a6926afc85ee43bd533366d2aba5
but also current master

**To Reproduce**
1. try to merge users on press leve
2. it does not and does not return any sort of message.

**Expected behavior**
the users merge

**Comment by mauromsl** [comment]
Good catch @hachacha ! Thanks!

Feel free to put a PR together, otherwise we'll sort it out tomorrow.
