### ISSUE TITLE
[Preprints] When acct w/ existing preprints updates profile data, existing author record is not updated

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#1973]
**Describe the bug**
When an existing user updates their account data (e.g. name, affiliation, email address), the corresponding "author" record is not updated, resulting in potential errors when adding self as an author during submission: 

* When the account holder uses the "Add self" button to add self as author on a preprint, a new author entry is created with their current account details. 
* When the account holder uses the "Search by email" option to add self as author on a preprint, a new author entry is created with their current account details. 
* When the account holder uses the "Search by ORCID [iD]" option to add self as an author on a preprint, the old author entry with the outdated data is used -- *unless* the account holder has already created an author entry using either of the above methods, in which case an error returns (possibly due to there now being two author entries with the same ORCID iD). 

**Janeway version**
Janeway preprints

**To Reproduce**
1. Sign in using an existing account.  Add account's "self" as author using available options and submit the preprint. 
2. Update the account profile data using information visible in the author submission page. Recommended: Email address, name, institution. 
3. Start submission for new preprint. Use search ORCID iD to add author. 
4. See old account profile details. 
5. For convenience's sake, delete old profile author. Use "add self" or "search by email" to add self with new profile details. 
6. Delete new profile author. Use search ORCID iD to try to add self. 
7. See error. 

**Expected behavior**
1. An "author" and its corresponding "account" are linked so when an account holder updates their account's e.g.  email address, their "author" profile's email address is also updated. 
2. No option to "search by ORCID iD" -- this is rife with data entry error. (ask me sometime for examples of publications with my personal iD bc people copied my iD from email signature thinking it was theirs...) 
3. The system would expect multiple users to have the same ORCID iD. Ideally this would prompt for clarification ("Do you mean a. Bob Researcher bobresearcher@mailinator.com [ORCID iD verified] or b. Robert Researcher bobresearcher@institution.ac.uk [ORCID iD not verified]?"). Alternatively, users who try to connect their ORCID iD to the system in which an ORCID iD is already found in the author or account table would be asked to confirm whether they already exist in the system ("Is this you?") and, if the user affirms that they do not or if those identities are not theirs, that ORCID iD would be marked as unverified or old in the other account. 

**Screenshots**
To follow. 

[edit] Removed "additional context" -- I suspect this was due to the manager not following the expected steps.

**Comment by ajrbyers** [comment]
Can @hardyoyo or @tingletech look into this? I wont have time in the near future.

**Comment by ajrbyers** [comment]
Also: be careful about updating Author records - you dont necesarily want to change all attributes and things like Inst and Dept shoudl be locked as they were when the Preprint was submitted.

**Comment by tingletech** [comment]
@alainna trying to wrap my mind around this -- any screenshots would help

**Comment by ajrbyers** [comment]
We should probably have a chat to discuss this one @tingletech @alainna

**Comment by tingletech** [comment]
> Also: be careful about updating Author records - you dont necesarily want to change all attributes and things like Inst and Dept shoudl be locked as they were when the Preprint was submitted.

there is only one author record full stop though?  Or, is there an author record per preprint?
