### ISSUE TITLE
Adding text to help editors remove author names from file properties

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#1976]
On the 'Add Files' page where manuscripts are uploaded, it would be useful to add in some brief guide text on how to anonymise a manuscript in Word and on PDF to remove author properties - currently there is generic text on anonymising but the author properties are easily missed.

I've pasted the text used for this in OJS below to give you an idea (something shorter would be useful) - many thanks

*****
Ensuring a Blind Peer Review

To ensure the integrity of the blind peer-review for submission to this journal, every effort should be made to prevent the identities of the authors and reviewers from being known to each other. This involves the authors, editors, and reviewers (who upload documents as part of their review) checking to see if the following steps have been taken with regard to the text and the file properties:

    The authors of the document have deleted their names from the text, with "Author" and year used in the references and footnotes, instead of the authors' name, article title, etc.

    With Microsoft Office documents, author identification should also be removed from the properties for the file.

    For Microsoft 2003 and previous versions, and Macintosh versions of Word:
        Under the File menu select: Save As > Tools (or Options with a Mac) > Security > Remove personal information from file properties on save > Save.

    For MacIntosh Word 2008 (and future versions)
        Under the File menu select "Properties."
        Under the Summary tab remove all of the identifying information from all of the fields.
        Save the File.

    For Microsoft 2007 (Windows):
        Click on the office button in the upper-left hand corner of the office application
        Select "Prepare" from the menu options.
        Select "Properties" for the "Prepare" menu options.
        Delete all of the information in the document property fields that appear under the main menu options.
        Save the document and close the document property field section.

    For Microsoft 2010 (Windows):
        Under the File menu select "Prepare for sharing."
        Click on the "Check for issues" icon.
        click on "inspect document" icon.
        Uncheck all of the checkboxes except "Document Properties and Personal information".
        Run the document inspector, which will then do a search of the document properties and indicated if any document property fields contain any information.
        If the document inspector finds that some of the document properties contain information it will notify you and give you the option to "Remove all," which you will click to remove the document properties and personal information from the document.

    For PDF files:
        With PDFs, the authors' names should also be removed from Document Properties found under File on Adobe Acrobat's main menu.

**Comment by ajrbyers** [comment]
@rhb123 can you confirm for me this is the Add Files page on Submission?

Ta

**Comment by rhb123** [comment]
Thanks for this - yes, I think it would be useful on the Add Files page at the point of submission, and if possible also just before the editor checks and sends the submission to peer-review, so that the guidelines are given to both author and editor in case needed. Thanks again!
