### ISSUE TITLE
Warning message for if author hasn't added or amended files when resubmitting

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#1980]
When the author is completing their revisions in the system, a warning popup would be very useful for if they try to submit without amending any of the existing files, ie, 'Warning: you have not made changes to any of the existing files. Please click 'back' to upload your revised files, or click 'continue' to proceed without uploading files.'

This would stop the author accidentally forgetting to upload their revised manuscript, which the editor may not immediately realise if the previous file is still attached. Many thanks.

**Comment by ajrbyers** [comment]
A revision confirmation popup has been added already.
