### ISSUE TITLE
Add links to share in social media on Material theme

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1989]
**Is your feature request related to a problem? Please describe.**
The material theme doesn't render links for sharing articles on social media

**Describe the solution you'd like**
The article page should show links to share an article on facebook, twitter etc... as per OLH theme

**Comment by ajrbyers** [comment]
Yes it does, yay!

<img width="1280" alt="image" src="https://github.com/BirkbeckCTP/janeway/assets/8321378/4b226238-4e4f-41ce-b501-c8f01c396eb9">
