### ISSUE TITLE
Improve "decline to review" page

### ISSUE THREAD

**Issue by jfrome1** [BirkbeckCTP/janeway#2003]
**Is your feature request related to a problem? Please describe.**
The "Decline to Review" page currently requires users to click a button in order to be taken to a page that allows them to suggest reviewers. Although it seems like a small obstacle, I think this additional click will significantly reduce the number of people who will suggest alternate reviewers.

**Describe the solution you'd like**
On the "Decline to Review" page, automatically display a form to allow people to suggest additional reviewers without clicking a button. You might then add a button to the first page to give the options "Suggest reviewers" and "Decline without suggesting reviewers". The idea is to provide a small amount of guilt to those who will not offer alternate suggestions. :-)

**Describe alternatives you've considered**
Leave as is with current obstacle to suggesting reviewers.

**Comment by ajrbyers** [comment]
The current process was chosen to specifically avoid this - we must consider this from the Reciewers POV and not just the Editor, so won’t be considering this change.
