### ISSUE TITLE
Improve 'Review Assignment Updated' notification

### ISSUE THREAD

**Issue by jfrome1** [BirkbeckCTP/janeway#2006]
**Is your feature request related to a problem? Please describe.**
When potential peer reviewers respond to a review invite, the editor gets an email that reads like this: "This is a notification that the reviewer Jonathan Frome has responded to your review request for "Pakistani TV" in Global Storytelling. You can view more information on the journal site."

The problem is that the email doesn't tell me whether the invite was accepted or declined. I have to click the link to find out.

**Describe the solution you'd like**
The email should include the information about whether the invite was accepted or declined. Why keep me in suspense?

**Describe alternatives you've considered**
Leave as is, require a click to the site to find out the info the system already has.

**Comment by ajrbyers** [comment]
See https://github.com/BirkbeckCTP/janeway/issues/2102 which will be in 1.3.10.
