### ISSUE TITLE
Allow markdown editing of text fields

### ISSUE THREAD

**Issue by jfrome1** [BirkbeckCTP/janeway#2007]
**Is your feature request related to a problem? Please describe.**
Text fields are currently not markdown editable. This is suboptimal as many people want to edit these fields in editors such as plaintext or MS Word, and these formats don't copy/paste well into text boxes or HTML code.

**Describe the solution you'd like**
Allow markdown editing of appropriate text fields, such as Submission Page introductory text.

**Describe alternatives you've considered**
Leave as is.

**Additional context**
This is lower-priority for me than my other feature requests, but would be very useful for me, as I edit in markdown whenever available.

**Comment by ajrbyers** [comment]
This is not something we will be looking into in the short or medium term.
