### ISSUE TITLE
Improve Submission page customization

### ISSUE THREAD

**Issue by jfrome1** [BirkbeckCTP/janeway#2008]
**Is your feature request related to a problem? Please describe.**
I'll talk about submission page, but this really relates to any user-customizable public-facing page. It would be much easier for users to configure the submission page in one place rather than having to go to three places, settings, fields, and additional fields. The current system is hugely confusing and I currently can't figure out how to add a field and get it to appear, among several other issues.

**Describe the solution you'd like**
Make a new page where the entire submission page can be configured. It can be based on the current 'submission settings' page but would make some or all of these changes:
- Each section has a checkbox on the left side that includes/excludes the section. Move the default license/language/section settings to the submission settings main page. Now the 'fields' page is not needed.
- Rather than setting up the page on the assumption that users will want a default set of pre-defined sections, set it up with the assumption that users will want to be able to add or modify sections. Make each section name clickable and editable. (Is there any way to easily section titles? If I want to change "Publishing Fees" to "Submission and Publishing Fees", it should be easy to make this change.)
- Have a button at the bottom to allow users to add a section (not a 'field', this is confusing I think--sections have several fields, no?). When clicked, users can add a section based on a menu of section templates as you currently have on the 'additional fields' page. Now there is no need for a 3rd separate submission settings page.
- Ideally the sections can be moved via drag and drop, or by clicking up/down buttons. Currently, the 'additional sections' page asks me to order the sections by number. I have no idea what number order it should be, but I probably know whether I want my new field above or below "Submission Checklist".

**Describe alternatives you've considered**
Leave it as is? Better documentation would help but the workflow would still be very awkward, because it requires regular switching between pages.

**Comment by ajrbyers** [comment]
This is a duplicate issue - we already have this in the works.
