### ISSUE TITLE
Problems editing text fields

### ISSUE THREAD

**Issue by jfrome1** [BirkbeckCTP/janeway#2009]
**Describe the bug**
When editing text fields using Win 10 and Firefox, Control+arrow keys are not performing their typical function, which is to let me skip left and right by word instead of by character. Control+Shift+arrow is not working either. This works in all other programs and is making in very hard to edit text in the browser.

**Janeway version**
unsure

**To Reproduce**
Using Win 10 and Firefox, go to "Submission Settings", choose a text box, enter text, and try to move around using Control+arrow keys. The cursor will not move, but Control+right will indent the paragraph.

**Expected behavior**
The cursor should jump left and right by word.

**Screenshots**

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox
 - Version: 85

**Comment by ajrbyers** [comment]
We utilise JQTE and SUMMERNOTE for rich text fields. Although their operation may not match this expectation I don’t think it’s something that will cause issue for the vast majority of people.
