### ISSUE TITLE
Transform files for peer review

### ISSUE THREAD

**Issue by jfrome1** [BirkbeckCTP/janeway#2010]
**Is your feature request related to a problem? Please describe.**
When testing the peer review process, I downloaded a manuscript as a peer reviewer. The file was the the submitted .doc file with just the file name changed. Identifying information, such as the author's name, was still in the file metadata. There was also nothing marking it as a current journal submission that should not be shared. Finally, the manuscript did not include information that would be useful to the reviewer, such as the abstract or keywords.

One journal worked with uses manuscriptcentral.com for peer review and it has a very good system. Submissions are converted into .pdfs with metadata removed. A title page is automatically attached with relevant information included (e.g. abstract) and identifying information excluded. The whole submission has a "for peer review" watermark embedded to discourage sharing with others.

I know the authors and editors should check all submissions to remove identifying information, but this seems like an accident waiting to happen.

**Describe the solution you'd like**
I'd like Janeway to take author-submitted files, create pdf files with the features described above, and let peer reviewers download only those versions of the files.

**Describe alternatives you've considered**
Keep current system.

**Comment by ajrbyers** [comment]
We have work on stripping metadata from submitted documents underway. I’m closing this issue.

**Comment by jfrome1** [comment]
What about the issues other than metadata?
- include abstract and keywords for reviewers
- 'for peer review' watermark

**Comment by ajrbyers** [comment]
Why wouldn’t the Abstract and Keywords be in the document already? I don’t think adding a watermark is of much use.

**Comment by ajrbyers** [comment]
I don’t think the watermark is a useful feature. Could you add the abstract request from this to the other issue you opened? We can display that on the Review Form page quite easily along with keywords.

**Comment by jfrome1** [comment]
Sure, but which one? I opened many issues.

**Comment by jfrome1** [comment]
BTW, maybe it is field-specific, but abstracts and keywords are optional in many humanities journals so it is not the default to include them in the submission file.

**Comment by ajrbyers** [comment]
You opened one where you asked us to include the abstract when inviting a reviewer. It seems like this would fit with that issue, no?
