### ISSUE TITLE
[Preprints] Authors should be able to add published DOI when editing metadata

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2042]
**Is your feature request related to a problem? Please describe.**
As a preprint author, I want to update my preprint metadata to add the published  article DOI, so people reading my preprint can access the final version of my article. 

**Describe the solution you'd like**
When submitting metadata updates (per [improvements in issue 1873](https://github.com/BirkbeckCTP/janeway/issues/1873)), author should be able to add published DOI.

**Comment by tingletech** [comment]
add published article doi to `repository.models.VersionQueue`, `repository.forms.VersionForm`, `repository.models.PreprintFile`, `repository.views.repository_submit_update`

`src/templates/admin/elements/repository/version_detail.html` also would need to be updated

add a migration to update existing version queue objects
