### ISSUE TITLE
Installation didn't work properly

### ISSUE THREAD

**Issue by MarHerUMR** [BirkbeckCTP/janeway#205]
Hi,

I just wanted to install janeway but ran into several issues. I startet with the manual install. Everything was done on the latest stable Debian.

On point two of the manuel install at least the installation of pip3 is missing. The manual installation and the automatic setup are not installing the same things.

I allready had the latest mysql so followed the steps until step six. There I got the following error:

> :~/janeway/src$ python3 manage.py install_janeway
> Migrations for 'submission':
>   submission/migrations/0013_auto_20171012_1133.py
>     - Alter field meta_image on article
> Migrations for 'journal':
>   journal/migrations/0006_auto_20171012_1133.py
>     - Alter field cover_image on issue
>     - Alter field large_image on issue
>     - Alter field default_cover_image on journal
>     - Alter field default_large_image on journal
>     - Alter field favicon on journal
>     - Alter field header_image on journal
> Migrations for 'cron':
>   cron/migrations/0003_auto_20171012_1133.py
>     - Alter field template_name on reminder
> Migrations for 'review':
>   review/migrations/0003_auto_20171012_1133.py
>     - Alter field default_visibility on reviewformelement
> Migrations for 'utils':
>   utils/migrations/0003_auto_20171012_1133.py
>     - Alter field types on pluginsetting
> Migrations for 'core':
>   core/migrations/0011_auto_20171012_1133.py
>     - Alter field profile_image on account
> Migrations for 'press':
>   press/migrations/0006_auto_20171012_1133.py
>     - Alter field default_carousel_image on press
>     - Alter field favicon on press
> Operations to perform:
>   Apply all migrations: admin, auth, carousel, cms, comms, contenttypes, copyediting, core, cron, django_summernote, featured, identifiers, journal, metrics, preprint, press, production, proofing, review, sessions, sites, submission, utils
> Running migrations:
>   Applying core.0001_initial...Traceback (most recent call last):
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
>     return self.cursor.execute(sql)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
>     return self.cursor.execute(query, args)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
>     raise errorvalue
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
>     res = self._query(query)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
>     rowcount = self._do_query(q)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
>     db.query(q)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
>     _mysql.connection.query(self, query)
> _mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "manage.py", line 11, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/home/marher/janeway/src/utils/management/commands/install_janeway.py", line 25, in handle
>     call_command('migrate')
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 131, in call_command
>     return command.execute(*args, **defaults)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
>     fake_initial=fake_initial,
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
>     schema_editor.create_model(model)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 303, in create_model
>     self.execute(sql, params or None)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 120, in execute
>     cursor.execute(sql, params)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
>     return super(CursorDebugWrapper, self).execute(sql, params)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
>     return self.cursor.execute(sql, params)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
>     return self.cursor.execute(sql)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
>     return self.cursor.execute(query, args)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
>     raise errorvalue
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
>     res = self._query(query)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
>     rowcount = self._do_query(q)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
>     db.query(q)
>   File "/home/marher/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
>     _mysql.connection.query(self, query)
> django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

After that I tried to install with the automatic script. There I ended up with a different error:

> :~/janeway/src$ python3 manage.py install_janeway
> Traceback (most recent call last):
>   File "manage.py", line 11, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/home/marher/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
>     django.setup()
>   File "/home/marher/.local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "/home/marher/.local/lib/python3.5/site-packages/django/apps/config.py", line 94, in create
>     module = import_module(entry)
>   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
> ImportError: No module named 'dynamicsites'

I was testing the install with:
- Debian GNU/Linux 9
- Python 3.5.3
- mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Is there anything that I'm missing??

**Comment by ajrbyers** [comment]
Hey @MarHerUMR - I'm pulling a Debian image now to test this out. Will install MariaDB (we've only ever tested with MySQL) and run the installation program to see what happens.

**Comment by ajrbyers** [comment]
Can confirm that auto-installer is breaking for me because `libmysqlclient-dev` isn't available on Debian.

@MarHerUMR can I send you an invite to our Slack channel so we can chat about this?

**Comment by ajrbyers** [comment]
We are going to have to create a new auto-install script for deb 9 (the installer works perfectly on Ubuntu) that deals with mariadb stuff. That said, I think I know the problem you are hitting and its easy to solve, can you drop the janeway db and then create it again using:

`CREATE DATABASE janeway CHARACTER SET = utf8 COLLATE = utf8_general_ci;`

**Comment by ajrbyers** [comment]
See #206 for fixes in place on master. Let me know if you need any more assistance!
