### ISSUE TITLE
Review reminder link problem

### ISSUE THREAD

**Issue by cobblepot1** [BirkbeckCTP/janeway#2054]
**Describe the bug**
When a review reminder is sent, the auto-generated email doesn't have the link properly set like the initial review request email does. Instead, it shows the URL but adds a full stop at the end, so if someone cuts and pastes the URL into the browser, it won't work unless they edit it or are very careful in copying it properly.

e.g. `We would appreciate it if you could let us know your decision or decline to undertake the review: https://mpub.janewaysharedhosting.com/gs/review/requests/415/?access_code=1e2ccf15-838f-4859-a923-67927ee8b99f.`
(note - access code manually changed here)

**Janeway version**
No idea - where do I find this info?

**To Reproduce**
Sent a review reminder, look at the generated email.

**Expected behavior**
The email should have a proper link with display text that can be clicked to take you to the proper URL.

**Comment by ajrbyers** [comment]
Hello @cobblepot1 can you upload a screenshot of the email as received?

**Comment by ajrbyers** [comment]
@cobblepot1 we have fixed this in 1.3.9, coming soon!
