### ISSUE TITLE
[Preprints] Manager cannot make updates to the author list order

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2062]
**Describe the bug**
Manager's edits to the author list ordering are not saved. 

**Janeway version**
Preprints 

**To Reproduce**
1. Go to manager view for a preprint with multiple authors e.g. https://dev.eartharxiv.org/repository/manager/1675/ 
2. Scroll to the author list and click the "up down" icons to rearrange authors 
3. Visit the preprint and see that author list ordering has not been updated. 

(n.b. Cannot make ordering changes in Author List due to https://github.com/BirkbeckCTP/janeway/issues/1954 )

**Expected behavior**
When a manager drags and drops the authors in the correct/preferred order, either a) the author order will save immediately, or b) a box will appear asking the manager to confirm the changes to the author list order.

**Screenshots**
![image](https://user-images.githubusercontent.com/15632391/108901263-a5d51600-75e8-11eb-8ff1-41abf9b1d7ac.png)

**Comment by ajrbyers** [comment]
Hi @alainna I can confirm this is not a bug in Janeway. When attempting to change an author order the CDL server returns a 404. @tingletech may be able to look into this.

**Comment by ajrbyers** [comment]
`POST https://eartharxiv.org/repository/submit/296/authors/order/` <-- 404 is returned when posting to this, perhaps due to a rewrite?

**Comment by alainna** [comment]
Thanks @ajrbyers, i've added  this to  our list
