### ISSUE TITLE
Errror in the apache config

### ISSUE THREAD

**Issue by MarHerUMR** [BirkbeckCTP/janeway#207]
On the Janeway, Apache and WSGI page the following apache config is proposed:

> <Directory /path/to/janeway/src//src>
>     <Files wsgi.py>
>         Require all granted
>     </Files>
> </Directory>

In the Directory tag the `/src` at the end has to be removed to get it working.

**Comment by ajrbyers** [comment]
Thanks for this, instructions have been updated - presumably you got past the SQL error yesterday? :+1:

**Comment by MarHerUMR** [comment]
Yes. Worked fine this time.
