### ISSUE TITLE
Article metadata can't be edited during 'Unassigned' stage.

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2074]
**Describe the bug**
Editors can't edit article metadata from the Unassigned stage.

**To Reproduce**
1. Go to any article that is sitting on the unassigned stage
2. There is no link to edit metadata

**Expected behavior**
There should be a link to edit the metadata, similar to what we have in the following workflow elements.

**Comment by ajrbyers** [comment]
There is now!
<img width="902" alt="Screenshot 2024-08-06 at 17 10 22" src="https://github.com/user-attachments/assets/a0b3ed7d-9634-41e0-b3aa-4eb095f5e595">
