### ISSUE TITLE
[Preprints] Notifications: Declining submission results in error

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2075]
**Describe the bug**
When the Manager declines a submission and tries to send a notification to the author, the system displays an error message despite successfully sending the decline notification. 

**Janeway version**
Janeway Preprints

**To Reproduce**
1. Go to a new submission (ex: https://dev.eartharxiv.org/repository/manager/1753/ )
2. Click **Decline Preprint**
3. Insert a note to the author then click "Decline Preprint"
4. Be redirected to the "Notify the author page". Click **Send**
5. See the error page "**Sorry, there was a server error. Our team has been notified.**"
6. Open mailbox and confirm that the notification has been successfully received (this example uses the public mailbox bobresearcher@mailinator.com, use www.mailinator.com to access) 

**Expected behavior**
The Manager receives a notice that their notification has been successfully delivered.

**Comment by ajrbyers** [comment]
I’ll test this shortly to get the error message.

**Comment by hardyoyo** [comment]
Upon investigation in the logs, we've determined the `preprint_publication` hook script is being called erroneously, and thus causing the DOI minting process to start off, which is incorrect for a decline event. More investigation underway.
