### ISSUE TITLE
Add CC, BCC and Attachment field to all emails

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#2086]
It would be helpful to allow arbitrary CCs on all emails for those who want them.

- [ ]  All email views have a CC input

- [ ] All email views have a BCC input

- [ ] All email views have an attachment input

**Comment by severett89** [comment]
It would also be helpful and appreciated if BCC can also be added to email fields in Janeway, if possible.

**Comment by mauromsl** [comment]
see https://github.com/BirkbeckCTP/janeway/issues/1294 while doing this

**Comment by joemull** [comment]
Originally requested May 5, 2020: https://github.com/BirkbeckCTP/janeway/issues/1542

Mauro's note about a potential implementation: 'I believe we could use the tagging library used for keywords with a custom email validator to present the user a single input element.'
