### ISSUE TITLE
[Preprints] Preprints with 3+ authors should be shortened with "et al", modal display

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2090]
**Is your feature request related to a problem? Please describe.**
Preprints currently display *all* authors (be it 2 authors or 2000) on all pages the author list may appear: front page, repository list, search, preprint item page. This leads to poor display if the author list is very, very long. 

**Describe the solution you'd like**
* On front page, repository list, search: Author list should be condensed to Author1, Author2, Author3, et al 
* On preprint item page: Author list should be condensed to "Author1, Author2, Author3, et all **[display full author list]**" "Display full author list" should be a modal that when clicked displays the full author list. The modal should have the option to condense/collapse the list/close the modal box. 

**Screenshot of current display**
![image](https://user-images.githubusercontent.com/15632391/111501629-862e9a80-871b-11eb-895c-13aef145d322.png)

**Comment by tingletech** [comment]
some notes:
```
themes/material/templates/repository/elements/preprint_home_listing.html
12:                        <p class="authors card-text">{{ preprint.display_authors }}</p>

themes/material/templates/repository/elements/preprint_listing.html
11:            <p class="authors card-text">{{ preprint.display_authors }}</p>
```

**Comment by tingletech** [comment]
@alainna does this seem okay then for the preprint home page?

<img width="347" alt="Screen Shot 2021-05-26 at 10 24 15 AM" src="https://user-images.githubusercontent.com/227374/119704585-aad67b00-be0c-11eb-98ec-4536a1e0982e.png">

<img width="326" alt="Screen Shot 2021-05-26 at 10 24 27 AM" src="https://user-images.githubusercontent.com/227374/119704635-bc1f8780-be0c-11eb-8b5b-796f5ce97797.png">

**Comment by tingletech** [comment]
Here is an example listing

<img width="572" alt="Screen Shot 2021-05-26 at 10 40 13 AM" src="https://user-images.githubusercontent.com/227374/119706417-cb073980-be0e-11eb-9b48-58ea4ba3cdc8.png">

**Comment by alainna** [comment]
@tingletech This works well -- thank you!

**Comment by tingletech** [comment]
Okay; that is a lot more work

**Comment by ajrbyers** [comment]
What is left to be done with this one @tingletech @alainna
