### ISSUE TITLE
Hyperlinks inserted in news items are not rendered

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2123]
**Describe the bug**
Announcements added through the news manager are being rendered as text rather than HTML, so hyperlinks are stripped out

**Janeway version**
v1.3.9

**To Reproduce**
1. Go to the news manager
2. Add a news item with a hyper link in the body
3. Go to the news page

**Expected behavior**
Since the input is  a rich-text box, hyperlinks and other HTML tags should be rendered on the news page and home page.

**Comment by ajrbyers** [comment]
@mauromsl can I confirm that this is specifically talking about the preview of the article? If you remember the reason this is stripped is because you can have HTML tags that start before the cutoff leading to them never being closed.

**Comment by mauromsl** [comment]
> 
> 
> @mauromsl can I confirm that this is specifically talking about the preview of the article? If you remember the reason this is stripped is because you can have HTML tags that start before the cutoff leading to them never being closed.

We can https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#truncatechars-html
