### ISSUE TITLE
JATS front matter generator

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2125]
**Is your feature request related to a problem? Please describe.**
Some publications are not  typeset into JATS XML for a variety of reasons. For such publications, Janeway is unable to expose article metadata in JATS, which is often used by indexing servers to ingest publication metadata.

**Describe the solution you'd like**
Implement a mechanism to generate article metadata in JATS format using the metadata in the Janeway database as a source and expose it to users and indexing services

**Comment by ajrbyers** [comment]
This already exists on the Portico plugin so we could pull the generator into core and have the plugin use it.

https://github.com/BirkbeckCTP/portico/blob/83a204edce6c8294ff6f11fab918b1b1bc195c36/logic.py#L24

**Comment by mauromsl** [comment]
Closed by b775908b88f34b0f0b98df3e030d3834c949da92
