### ISSUE TITLE
Cannot Upload Images or Create New User Roles

### ISSUE THREAD

**Issue by StVicious** [BirkbeckCTP/janeway#213]
After finishing the installation of Janeway, I ran into some issues:

1. When I tried to upload a logo for the issue, the page refreshes, but the logo doesn't get added.
2. When I tried to add a new user, the page also refreshed, with all of the personal information gone. The new user was not added when I checked on the dashboard.
3. When I tried to upload a header image, it gave me a "Permission Error". 

It seems like these questions are related to some extent. Can you please help me out? Thanks!
![janeway_error_message](https://user-images.githubusercontent.com/4967666/31983567-a607bbbe-b912-11e7-86c4-d3d7f0dcad60.png)
![janeway_logo_upload_page](https://user-images.githubusercontent.com/4967666/31983568-a623ae46-b912-11e7-864e-bd7f2b5fe344.png)

**Comment by MartinPaulEve** [comment]
Hi StVicious,

1. This is a bug: at the moment, only SVG files are allowed. @ajrbyers: we should fix this or display a warning.

2. Not sure what's going on here. We will investigate.

3. This looks like a problem with the web server not being allowed to write to the file system, but I hope that @ajrbyers can help further.

Martin

**Comment by StVicious** [comment]
Hi Martin, Thank you for the prompt response! Looking forward to further advice on 2 and 3.

**Comment by ajrbyers** [comment]
I've created issues for the two bugs, the permission error is related to your server. If you are using apache you need to make sure that the www-data user has permission to write to the folder. This can be done by giving the www-data group ownership of the janeway folder (chown -R youruseranme:www-data). If you're willing, dropping into our Slack group to discuss this particular issue will be easier than a back and forth over github :)

**Comment by StVicious** [comment]
For Issue #2, I think the problem is that, on the "Add New User page", There is no "Add" button to click after I entered all the information. At the bottom right corner of the page, the button says "Update Profile". When click on it, it simply clears up all the information I just entered on the page. So, How can I add the new user once I entered all the information on this page? Screenshot attached. Thanks for your help!
![unable_to_add_new_iuser_upper_page](https://user-images.githubusercontent.com/4967666/32035061-73390e2c-b9cb-11e7-9cca-a7326784c142.png)
![unable_to_add_new_user_lower_page](https://user-images.githubusercontent.com/4967666/32035062-734f1c8a-b9cb-11e7-811c-4422601cb08e.png)

**Comment by ajrbyers** [comment]
The Update Profile button should still save the form content. There is a bug here and I'm investigating it today.

In the meantime, you can use the admin interface (/admin/ or select it from the drop down in the top right) to add new users.

![screenshot from 2017-10-26 08 48 23](https://user-images.githubusercontent.com/8321378/32040993-8649eb30-ba2a-11e7-9e17-79c59e52d7dc.png)

Under the Core heading you can select Add next to Accounts.

![screenshot from 2017-10-26 08 51 51](https://user-images.githubusercontent.com/8321378/32041135-f290efe6-ba2a-11e7-9f84-ca2cd09585dd.png)

**Comment by ajrbyers** [comment]
FYI: No. 2 has been fixed. See issue #215. You'll need to do a pull on master.
