### ISSUE TITLE
Title input when requesting reviewer

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#2143]
Would it be possible to have a section to input the reviewer's title (ie, Professor, Dr etc) when inputting a reviewer's details? I would always address a reviewer formally by their title when contacting them with a review request, but the system only has fields for first and last name at present, so if it might be possible to add this that would be very useful (or perhaps change the first name field to 'Title and first name' as a workaround if this isn't possible?)

Janeway version: 1.3.9

Thanks again folks!

**Comment by ajrbyers** [comment]
> Would it be possible to have a section to input the reviewer's title (ie, Professor, Dr etc) when inputting a reviewer's details? I would always address a reviewer formally by their title when contacting them with a review request, but the system only has fields for first and last name at present, so if it might be possible to add this that would be very useful (or perhaps change the first name field to 'Title and first name' as a workaround if this isn't possible?)
> 
> Janeway version: 1.3.9
> 
> Thanks again folks!

This is a quick add interface so we limit the options. If you want to add all the reviewers details do so via `Manager > Users` and then add them as a reviewer via `Manager > Roles > Reviewer`.

**Comment by rhb123** [comment]
Thanks for this - that's good to know, although this might be something to consider in future if possible so that there's a faster way of doing this as I'd need to do this workaround for every reviewer at present. Thanks again for taking a look though

**Comment by ajrbyers** [comment]
@rhb123 added a PR for this to include it in 1.3.10.
