### ISSUE TITLE
Ability to pull in abstract in peer-review template

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#2145]
It would be great to be able to automatically populate the end of the review request email with a copy of the abstract of the paper - currently the title of the paper is automatically pulled in but not the abstract, so a way to do this would be brilliant if possible.

Alternatively do let me know if the reviewer is able to see this upon clicking through the link before they accept or decline, and I can update the template to note that they will be able to preview the abstract on clicking through. Thanks again.

**Comment by ajrbyers** [comment]
We've included this in 1.3.10 improvements.
