### ISSUE TITLE
URL for Janeway frontend

### ISSUE THREAD

**Issue by StVicious** [BirkbeckCTP/janeway#217]
Hi, 

I installed Janeway and I am working with its backend from http://yourfirstjournal.com/install/ . 

A quick question: What is the URL for the front end where a visitor can view the journal content? 

It doesn't seem to be in the field of "Publisher URL" on the "Install - Journal" page as the attached screenshot shows. Speaking of which, what should I put in "Publisher URL"? Is it optional? 

Thank you.

**Comment by StVicious** [comment]
Sorry. Adding screenshot here.. 
![install_journal](https://user-images.githubusercontent.com/4967666/32028009-14c46686-b9a1-11e7-9d20-a21fa348e9e1.png)

**Comment by ajrbyers** [comment]
the base URL without /install/ in it will render the journal... see for example https://ijwwe.uwp.co.uk

Publisher URL should be a URL, it's optional though so you can clear the field. I'll update the default setting though as the current default makes no sense.
