### ISSUE TITLE
Prompt to run similarity check

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#2182]
**Describe the bug**
Currently for OLHJ there is the ability to run a similarity check, but this must be done manually for each submission. The ability to run this automatically at the point of submission would be great, so that it can be turned on/off for each journal accordingly so that the editor is able to review the similarity score prior to deciding to send the paper on for peer-review or not.

**Janeway version**
1.3.9

**Desktop (please complete the following information):**
- Windows 10

Thanks for your help!

**Comment by rhb123** [comment]
^ update - following discussion with the tech team re. vulnerabilities involved in doing this, would it be possible to add a warning message for editors so that when they move a paper to peer-review, the following (or similar) comes up at the top of the page before they add reviewers:
'This paper has not been auto-checked for plagiarism. If you would like to do so, {click here} to run an automatic plagiarism check and see a similarity report from iThenticate.'
Thanks for your help :)

**Comment by ajrbyers** [comment]
Woohoo! This is done already.
