### ISSUE TITLE
Keywords in Janeway should allow a set sort order

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2187]
**Is your feature request related to a problem? Please describe.**
As a submitting author or editor/manager, I expect that keywords will display per the sort order that I have assigned them. 

**Janeway version**
Janeway Preprints

### Steps to reproduce 

1. In manager view, find preprint with 3+ keywords 
2. Change display order of keywords e.g. KeywordB, KeyboardC, KeywordA
3. Save

### Expected
Keywords display as KeywordB, KeyboardC, KeywordA

### Actual 
Keywords display as KeywordA, KeywordB, KeyboardC

### Steps to reproduce 

1. In manager view, find preprint with 3+ keywords
2. Remove all keywords
3. Save 
4. Add keywords as: NewKeywordD, OldKeywordB, NewKeywordE, OldKeywordC
5. Save 

### Expected
Keywords display as NewKeywordD, OldKeywordB, NewKeywordE, OldKeywordC

### Actual 
Keywords display as OldKeywordB, OldKeywordC, NewKeywordD, NewKeywordE

![image](https://user-images.githubusercontent.com/15632391/117313967-59ae1980-ae54-11eb-91f0-c4b050784ed3.png)

**Comment by mauromsl** [comment]
Thanks for the report @alainna 

We implented this behaviour in Janeway 1.3.9 already: #2056
Once we update the `preprint-remodel` branch and mergeit  into master, all keywords should preserve the order they were inserted on.

I'll leave the issue open and test it once we are closer to the official release of Preprints (1.4.2)

**Comment by alainna** [comment]
Lovely, thanks @mauromsl ! I've added it to our local card so we can track it with the update

**Comment by mauromsl** [comment]
closed by #2056
