### ISSUE TITLE
Preprint DOI should be exposed in Moderator and Author Dashboard view

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2188]
**Is your feature request related to a problem? Please describe.**
As an author or moderator, I want to be able to easily find the DOI for an accepted and published preprint without needing to navigate directly to the preprint's page. 

**Describe the solution you'd like**
Add to the Dashboard view a field for Preprint DOI. Mockups attached.

**Additional context**
![image](https://user-images.githubusercontent.com/15632391/117317077-2e78f980-ae57-11eb-8d9b-6dc8619ade28.png)

**Comment by alainna** [comment]
@hardyoyo Not yet seeing this on the author's view. Could it be that the author view (e.g. at https://dev.eartharxiv.org/repository/dashboard/9/ ) uses a different template?

**Comment by hardyoyo** [comment]
The code in this PR: #2468 only displays a preprint.preprint_doi if one exists.

**Comment by hardyoyo** [comment]
See #2482 for an additional template revision
