### ISSUE TITLE
Author Revisions Interface

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2197]
**Is your feature request related to a problem? Please describe.**
This interface is not particularly easy for the Author to use. We should make it better.

**Describe the solution you'd like**
- Add a guide setting
- Make the upload button more prominent
- Add help text to covering letter field
- Allow authors to save the covering letter
- Add a finish button that is clearly defined

**Comment by SiobhanMcG** [comment]
One of our editors suggested/ requested: "rename ‘complete revisions’ button to ‘submit revisions’ – this is when authors respond to the revision requests. We had many instances when authors press this button before they are ready to submit their revisions. "

**Comment by ajrbyers** [comment]
Hi @SiobhanMcG yeah we've reworded this already to make things clearer.

**Comment by SiobhanMcG** [comment]
@ajrbyers Thank you :) I'll feedback to the editor.
