### ISSUE TITLE
Ability to add title to special collections page

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#2206]
**Describe the bug**
At present there is no way to add a title to the special collections page so it doesn't actually say what all the boxes represent at https://olh.openlibhums.org/collections/collection/ (unlike the other pages, ie, the Articles page starts with a header that says 'Articles'). Would it be possible to add the title 'Special Collections' at the top of the page please? Thanks for your help.

**Janeway version**
1.3.10

**Comment by ajrbyers** [comment]
No worries!
