### ISSUE TITLE
Error message page in typesetting when clicking 'Manage' next to proofreading task

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#2207]
**Describe the bug**
In typesetting, when I click 'Manage' next to the proofreading task this goes to an error page - see screenshot below for the link that triggers it:

![image](https://user-images.githubusercontent.com/55796596/117787448-59d85b80-b23e-11eb-8e57-e5b4ebf5e86e.png)

The corrected proofs for this article have just been returned from the typesetter, so I was clicking on this to try to access the request that was originally sent to the typesetter containing the proofreader's comments, in order to check that these had all been actioned. I figured out how to do this by clicking 'Admin' to access the comments, but just flagging the error message here (possibly occurring because the proofreading task is complete?) Thanks again

**Janeway version**
1.3.10

**Comment by mauromsl** [comment]
Thanks for the report  @rhb123,

I've moved this to the typesetting plugin repo, where this problem applies: https://github.com/BirkbeckCTP/typesetting/issues/131
