### ISSUE TITLE
Unable to sort by any variable in Article Document Management

### ISSUE THREAD

**Issue by SiobhanMcG** [BirkbeckCTP/janeway#2213]
Unable to sort by any of the variables when Article Document Management.

**Janeway version**
1.3.9 (is what it displays, though I thought we switched to 1.3.10?)

**To Reproduce**
Dash -> Back content -> Articles -> [Select article - I was on https://www.fieldsjournal.org.uk/manage/archive/article/803/] -> Article stages and logs -> Documents,

Then when attempting to sort by any variable, nothing happens.

*Windows 10 - Issue appears on both Chrome and Firefox

**Comment by ajrbyers** [comment]
I've tested this out and the columns in Document Management are sortable as expected (both on live and dev)

@S-Haime this is your old account? 😄

**Comment by S-Haime** [comment]
Haha yep - my back in 't day account. Must have been resolved in an earlier version :)
