### ISSUE TITLE
Add more customization options to the "Submissions" page template

### ISSUE THREAD

**Issue by christofs** [BirkbeckCTP/janeway#2217]
**Is your feature request related to a problem? Please describe.**
At the moment (in version 1.3 I suppose), there are a number of predefined sections in the "Submission Settings" page (...manager/settings/submission/), but the range of options is quite limited and does not exactly suit our needs. For example, we would like to include a short section on "manuscript preparation" and on "Data and code" here. 

**Describe the solution you'd like**
We believe the possibility to add custom sections (with freely defineable title plus a text field) would make this section a lot more flexible. In addition, it would be very useful to be able to re-order the sections on this page. For example, we would like to include a short section on "manuscript preparation" and on "Data and code" here.

**Describe alternatives you've considered**
One possible alternative, i.e. adding the additional information we would like to provide to authors in the uppermost field, does not work for us. One reason is that some of the information should not really be placed right at the top of the page, as this overly prioritizes it. The second reason is that subsections we add in the uppermost field do not appear in the table of contents column, which means it is harder to find and impossible to provide a direct link to it. 

**Additional context**
This issue may be related to, although it seems to me that it is distinct from, issues #969 and #122. 
If this or a similar feature is already planned for version 1.4, then please ignore the issue.

**Comment by mauromsl** [comment]
Hi @christofs 

Thanks for the feature request, we will discuss it when planning the next release of Janeway.
The fixed fields/sections under the 'Submission Settings' serve two purposes: The first is to display the content of those settings under the submissions page ('/submissions') as well as to the authors during the submission process. The second is to be able to deterministically share those settings as metadata with various  metadata harvesting services (e.g DOAJ).

In case you find it useful, an approach that other journals follow to further customise the submissions page is to link to a separate page using Janeway's built-in [CMS System](https://janeway.readthedocs.io/en/v1.3.10/manager/content/index.html). As an example, the [OLH Journal](https://olh.openlibhums.org/submissions/)  has a link to the 'Author Guidelines' from the Submission Checklist section.

**Comment by christofs** [comment]
Hi Mauro, thanks for the feedback and explanation, much appreciated. 

Yes, we have considered linking to another page for the "Author Guidelines" (but that kind of spreads relevant information into two places) or, in fact, considered linking to a PDF as well as a LaTeX template with further information from the "Submissions" page. Even in this scenario, however, it would be nice to have a section other than the "Submission Checklist" where we can summarize the essential points and add pointers to additional information. 

For additional issues, like our data and code policy, we feel like an additional dedicated section would be more suitable. It won't be a long text, so no need for an extra page, but it also doesn't really fit anywhere else.
