### ISSUE TITLE
New account creators are sent to Page Not Found

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2223]
**Describe the bug**
When someone logs in to JW for the first time using ORCID, they are sent back to /dashboard/ which triggers a 404 if they started from our main journals page, journals.publishing.umich.edu. Could they instead be sent back to journals.publishing.umich.edu?

**Janeway version**
1.3.10

**To Reproduce**
1. In private browser, check that you're logged out of Janeway and ORCID
2. Go to journals.publishing.umich.edu
3. Select Login
4. Select Log in with ORCID 
5. Follow ORCID's steps to authorize Janeway
6. Arrive back at journals.publishing.umich.edu/dashboard

**Expected behavior**
Back to journals.publishing.umich.edu

**Screenshots**
![Screen Shot 2021-05-19 at 4 49 09 PM](https://user-images.githubusercontent.com/47217308/118882425-2e024900-b8c2-11eb-94fb-1e9316e8b58c.png)

**Comment by ajrbyers** [comment]
Hey @joemull is this logging in on the press site?

**Comment by joemull** [comment]
Yes that's right. We are writing docs for people to create Janeway accounts and want to send them to journals.publishing.umich.edu rather than the individual journal websites, to keep things streamlined
