### ISSUE TITLE
Janeway and Windows!

### ISSUE THREAD

**Issue by Gitubert** [BirkbeckCTP/janeway#223]
Hi,

This project seems to be promising! I am impatient to test it on Windows as I am not so familiar with Linux, unfortunately!
So, my question is: would be there any Windows' version/compatibility or should one learn Linux?

Thank you,

**Comment by ajrbyers** [comment]
Hi,

Janeway runs on Python 3.5 so I would expect that it is possible to set it up on Windows, though I have not tried this myself. We are planning to build a Docker container for Janeway which would make the windows setup easier for people who want to test it out, would that be of interest?

Andy

**Comment by Gitubert** [comment]
Thank you, Andy, for your your response.
Yes, it would be of great interest, indeed, to make it easier to install on Windows. 
I have tried many times while checking the Internet but I am still struggling in vain!
So, it would be highly appreciable that one can install it easily whatever the OS.
PHP-based applications are relatively easy to install using WAMP server but Python-based apps seem to be "harder" though Python is relatively easier to handle.
Should you try it on Windows, I'd be grateful if you can tell me how to install it properly.
Thank you once again.

Gitubert

**Comment by Gitubert** [comment]
I was interested to try this software but I should give up. It is so complicated and not intuitive from the first glance to get installed, how then it should be after installation? 
If it is not easily installable, how easy it would be to work with?  
Worse than the installation problem, some web hosts claim that their shared servers do not support Python-Django applications, hence Janeway.
They say that only VDS/dedicated servers that support such applications made with Python-Django. Such servers are obviously more expensive than shared servers and more daunting to try and host a journal.
It is surprising, however, that only dedicated servers would support Python-Django applications but not shared servers. 
It is a pity that it is so complicated for non-experts/non-developers to get this software installed.
If I was able to install it locally, I'd probably made some suggestion/bugs reports to improve it but unfortunately I couldn't.

Gitubert

**Comment by ajrbyers** [comment]
The installation process has not yet been set for Windows (see our Wiki). The installation process for Linux is reasonably simple and a fair number of people have managed to get it running without issue. That said, we have been working on this for windows users, we intend to have a docker installer ready soon that will make installing in Windows easier. 

VPS services start from $5 (Digital Ocean, Linode, AWS) so I think your suggestion is a bit disingenuous, it’s not terribly more expensive. Shared hosts such as Reclaim certainly do support python applications and I’d say any shared host that doesn’t isn’t very good. 

Janeway is open source, made available for free,  and a brand new application. I’m sorry that you think we haven’t responded quickly enough but we are doing our best. 

Andy

**Comment by Gitubert** [comment]
Sorry, it was because of a disappointment not to be able to try Janeway. So, all my apologies for any inconvenience. 
Regarding the host "Digital Ocean, Linod, AWS" they do not tell much about the features included in their hosting plan except the memory (512M, Disq space and transfer; for Digital Ocean. Nothing for Linode and AWS). 
 From my side, I am telling what some host providers told me. I know they may exaggerate to make money but more than one said the same thing: Only VDS/dedicated servers would support Python-Django with a pricing plans starting from $50/mo for basic features and could reach up more than $500/mo.
It most likely that they were sale representatives but not technical experts so they would try to make new customers. 
Check for example these among others: 
arvixe.com
interserver.com
who they have live chat service where you can ask them and you will see. I simply asked if their shared servers would support Python-Django applications and they said NO.

Back to Janeway on Windows, it might be appear that Windows is for beginners, but it is extremely easy to use compared with Linux and Mac that many try to mislead people by claiming they are easier. I do not find this! Linux seems to be more difficult to work with than Windows, at least for me! 
Actually, Linux still works the way Windows has been working at its beginnings longtime ago! 
Windows has evolved from commands and typing-based tasks into visual-click-tasks while Linux still working by commands. Of course, this might be arguable on which is better but tasks are much easier on Windows than on Linux, however this is only my opinion.  
That being said, Windows is not a perfect system. In contrary, it is fraught of defects, bugs, vulnerability, shortcomings and so on, but it has the merit to be user-friendly. By the way, the majority of people using computers are PC users, not Linux or Mac, mainly because of its simplicity, intuitiveness and 'visuality' of its tasks.    
Regarding Janeway, I tried to watch some videos and read about Python and Django projects on the web, but to be frank, none of them helped to get Janeway installed, though many of them are relatively clear and simple to follow. 
I should say that I am lost between the instructions you provided and those in some videos I watched on how to install Django projects (see for eg. https://www.youtube.com/watch?v=uHCeLlD1le8).
Following this video, I tried to rename "janeway" to "test" and to literally follow in the instructions presented here and in other videos, but still unable to get Janeway installed. 
It is not clear whether one should install django each time to change the folder and why there are two folders with the same name after creating virtual environment or when we close the Shell and start it again! 
I am sure it would be easy to install for those who have experience with Python and Django but this is not the case of all people.
A clear and step-by-step guideline is missing in my opinion.  
Maybe a video of 5 min on how to install Janeway locally, or an illustrated step-by-step guide starting from downloading Janeway into getting it installed would be highly useful and appreciable. Otherwise, people like me might find it recalcitrant and give up to try it.

Thanks and sorry again for any inconvenience. I am still interested to try it if I find an easy way to get it installed if you can provide it.
