### ISSUE TITLE
Way to authorise draft decisions and skip author email

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#2238]
At present, there's no way to authorise a draft decision that is a straightforward reject to remove the paper from the system (in this case, because the author uploaded a second version of their paper in error). When this happens, the section editor needs to be able to simply reject the paper and skip the email to the author, which then comes through to the editor to approve, so if there could be a 'skip author email' function in draft decisions as well, so that the editor can then approve authorising the decision without an email notification, that would be great please.

**Comment by ajrbyers** [comment]
For my own clarity, in what instance would a paper make it the Peer Review stage and _then_be desk rejected without a notfication needed for the Author?

**Comment by rhb123** [comment]
So in this case, the author uploaded a new version of the paper and the SE moved it to the peer review stage, but on finding it was a duplication of the original paper advised the author to upload this in the correct place instead, and then needed to delete the duplicate version from the system. Thanks for taking a look.

**Comment by ajrbyers** [comment]
We have since added the Archive option which covers this requirement.
