### ISSUE TITLE
Bad line breaks inside hyperlinked text

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2240]
**Describe the bug**
Text inside hyperlinks gets wrapped without regard to word breaks, so there are often bad line breaks in the middle of words.

**Janeway version**
1.3.10

**To Reproduce**
1. Go to any preview galley with hyperlinks such as https://journals.publishing.umich.edu/weaveux/plugins/typesetting/preview_galley/article/217/galley/43/
2. Adjust the width of the browser until a piece of linked text wraps in the middle

**Expected behavior**
Lines should break on spaces only

**Screenshots**
![Screen Shot 2021-06-04 at 1 09 43 PM](https://user-images.githubusercontent.com/47217308/120839246-b295ce00-c536-11eb-8b45-d55bc1ff1caf.png)

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Firefox
 - Version 88.0.1

**Comment by joemull** [comment]
Oh and this journal has the material theme set.

**Comment by ajrbyers** [comment]
Breaking on space only could cause the text to apparat outside the reader block. I’m not sure which is worse.

**Comment by joemull** [comment]
Oh, you mean if the text is a URL, it might extend beyond the space visible to the user? Could you break on space if linked text contains a protocol like `https`, but otherwise break "aggressively"?

**Comment by ajrbyers** [comment]
I don’t think CSS can differentiate between the two

**Comment by joemull** [comment]
Huh. But surely this is something others have run into, right? I'm looking at an NYT article that breaks hyperlinked phrases at word breaks and nowhere else.
![Screen Shot 2021-06-04 at 1 52 38 PM](https://user-images.githubusercontent.com/47217308/120843577-46b66400-c53c-11eb-9164-b176732e4be5.png)
This is not an urgent issue, but surely there's a fix out there?

**Comment by ajrbyers** [comment]
Do they have an example of a long URL linked in the text? We do in a few places.

**Comment by ajrbyers** [comment]
I’m sure we can sort something @joemull ! :)

**Comment by joemull** [comment]
OK so this seemed to fix it for me for both hyperlinked phrases and long URLs:

**Comment by ajrbyers** [comment]
👏👏 want to make a PR? 😀

**Comment by joemull** [comment]
Haha sure let me figure out how to do that!

**Comment by joemull** [comment]
Credit: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

**Comment by joemull** [comment]
Recent example of a slightly different issue:

![Screenshot from 2022-10-18 11-03-55](https://user-images.githubusercontent.com/47217308/196400848-a1b9d06b-70a8-458b-84aa-1674790a4a92.png)

**Comment by mauromsl** [comment]
> Recent example of a slightly different issue on Chrome (but not Firefox) in clean theme:
> 
> ![Screenshot from 2022-10-18 11-03-55](https://user-images.githubusercontent.com/47217308/196400848-a1b9d06b-70a8-458b-84aa-1674790a4a92.png)

This is what Andy had mentioned about long links before:

> Do they have an example of a long URL linked in the text? We do in a few places.

And the reason why we need to `{word-break: beak-all}` for `<a>` tags

**Comment by joemull** [comment]
Using `word-wrap: break-word;` seems to be working for both cases using the custom styling plugin:

![Screenshot from 2022-10-18 11-35-34](https://user-images.githubusercontent.com/47217308/196408918-b7e73ad4-e527-47d5-b190-62eb0271aab0.png)

The way it is named, you would expect it to break only between words, but it also breaks inside very long words.

When we fix this across the board we should test it more carefully on all three themes and multiple browsers.

**Comment by joemull** [comment]
This was fixed by cd0fd21e173a7659f862eb4287277c9b75a9141a. Tested manually on all themes.
