### ISSUE TITLE
Option to publish content of field in review form

### ISSUE THREAD

**Issue by evelyn-gius** [BirkbeckCTP/janeway#2242]
We would like to enable open review in our journal. This means that we also will publish the reviews in cases where the reviewers agree to their publication. We will add a respective field to the review form, where reviewers can put the version of the review they would like to publish. 
The publishing option that we have in mind should:
- publish the content of the respective review from field as a **separate item** on the journal page
- together with the **corresponding metadata** of the reviewed article and the reviewer (extracted from the review form?)
- by also providing it with a **DOI**.

**Comment by ajrbyers** [comment]
@evelyn-gius we've added support for open peer review in Janeway. Editors can decide, in advance, which fields will be published and DOIs can be assigned. You can see examples of OPR in Janeway on UCL Open Environment (https://journals.uclpress.co.uk/ucloe/article/id/3042/#)
