### ISSUE TITLE
"Safe" filter on news list page continues to render &nbsp; codes

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#225]
For some reason, the |safe filter on the News list display page excerpts is allowing &nbsp; through.

A couple of thoughts:

1. This seems to happen when Word markup is pasted in. We could pre-sanitise this, because the markup is horrendous.
2. I wonder whether the order of the |safe filter makes a difference in the chain? (i.e. might be fixed by simply moving it to a different position?)

**Comment by ajrbyers** [comment]
Fix deployed to live via 1.1.1
