### ISSUE TITLE
Theme file templates/elements/submit/file.html does not appear to be used

### ISSUE THREAD

**Issue by hardyoyo** [BirkbeckCTP/janeway#2262]
**Describe the bug**
The theme file [templates/elements/submit/file.html](https://github.com/BirkbeckCTP/janeway/blob/master/src/themes/OLH/templates/elements/submit/file.html) does not appear to be used.

**Janeway version**
Discovered on the current version of the preprint-remodel branch, but it's believed to also affect themes in the master branch.

**To Reproduce**
1. Create a theme (copying the OLH theme is fine)
2. Modify the file.html element template for the theme.
3. Deploy and configure the theme
4. Attempt to submit a new manuscript, and notice that the change you made to the file.html template is not visible.

**Expected behavior**
Changes to the file.html template should be visible in the system, when the theme is deployed and configured.

**Comment by hardyoyo** [comment]
The theme file in question may be leftover from a previously working state, and the victim of a refactoring. However, you *can* override the file.html file that Janeway currently uses by copying the template from templates/admin/elements/submit/file.html to [theme_root]/templates/admin/elements/submit/file.html, like this example: https://github.com/eScholarship/GP/blob/master/templates/admin/elements/submit/file.html

This bug could probably be handled by removing the nonworking template, and possibly documenting how to override admin templates, or including an override in the template examples.

**Comment by ajrbyers** [comment]
> This bug could probably be handled by removing the nonworking template, and possibly documenting how to override admin templates, or including an override in the template examples.

We'll need to discuss whether this is something that should be documented or is itself a bug.

**Comment by ajrbyers** [comment]
Overriding admin files has been discussed elsewhere, this can be achived via altering the django settings.
