### ISSUE TITLE
[Preprints] Authors should be able to delete incomplete submissions

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2264]
**Is your feature request related to a problem? Please describe.**
As a submitting author, I expect to be able to delete incomplete submissions that are no longer relevant (eg I made mistakes and want a full redo, accidentally started 2 submissions for same article, no longer want to submit this item, etc). I should not see them in my dashboard.

**Version** 
Janeway Preprints 

**Describe the solution you'd like**
There should be a delete button in the dashboard (mockup below). When I click the delete button, there should be a confirmation Q&A box that I must select "Yes"  in order to proceed: "This will delete your unsubmitted item <Title>. You will not be able to restore it. Are you sure that you want to proceed? Yes/No"

**Describe alternatives you've considered**
Tick box to delete submissions (eg en masse). -- also seems a good option
Delete option somewhere within the submission workflow screens.  -- doesn't seem as good an option 
Moderator/Admin can impersonate user to delete unsubmitted item -- puts unnecessary burden on moderator/admin
Author can "archive" submissions so they no longer see them on their dashboard. 

**Additional context**
![Mockup](https://user-images.githubusercontent.com/15632391/122586530-cd823b00-d02a-11eb-814c-b6051f82ac82.png)

**Comment by ajrbyers** [comment]
PR in for this.
