### ISSUE TITLE
Preprints: Labels and logs for rejecting/declining a submission should be consistent

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2273]
**Describe the bug**

**Janeway version**
Janeway preprints

**To Reproduce**
1. As a manager, open a submission from the queue and click "**Decline** Preprint"
2. Add note if desired 
3. Edit message to author if desired
4. See notice that "This Preprint was **rejected** on <Date> <Time>". 
5. Click log and read most recent entry: "Preprint **Publication**"

**Expected behavior**
* **Expectation 1**: Reject/Decline button in manager view of pending submission (1) is consistent with notice on rejected/declined preprint (4)-- either "**Reject** Preprint"/"This Preprint was **rejected**" (preferred), or "**Decline** Preprint"/"This Preprint was **declined**"
* **Expectation 2**: Log entry reflects action: "Preprint **Rejected**" (preferred)/"Preprint **Declined**" 

**Screenshots**
![image](https://user-images.githubusercontent.com/15632391/123127147-026e0380-d418-11eb-9528-b7af2f78950f.png)

**Comment by ajrbyers** [comment]
PR in for this.
