### ISSUE TITLE
Preprints: Several bugs/issues with rejection notes, emails (or lack thereof), and the log

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2278]
**Describe the bug**
While testing the preprint rejection functionality, we found several issues: 

1. The "Decline preprint" "note to the author" is not displayed in a) the form email sent to the author, b) the item UI for the author or preprints manager, or c) in the item log 
2. If no email of the rejection is sent to the author, then the rejection is not recorded in the log 

**Janeway version**
Janeway preprints 

**To Reproduce**
Steps to reproduce the behavior when *no email is sent to the author*:
1. Go to existing submission or create new submission. 
2. Start the rejection process. 
3. Add a relevant note. 
4. Skip sending author a rejection notification email. 
5. After being redirected back to the item page, note that it has been successfully rejected. Note that the note about the rejection is not displayed anywhere on the page. 
6. Click on log. Note that there is no log entry for the rejection or rejection note. 
7. Return to item page and click on comments and discussion pages. Note that there is no record of the rejection note. 
8. If you the user were also the submitting author, check your version of the item page for any record of the rejection note.  Note that there is none. 

Steps to reproduce the behavior when *an email is sent to the author*:
1. Go to existing submission or create new submission. 
2. Start the rejection process. 
3. Add a relevant rejection note to the author, e.g. "Does this note get added to the message?"  
4. When you get to the "Notify the author" step, note that the rejection note added in step 3 appears nowhere in the message. 
5. After being redirected back to the item page, note that it has been successfully rejected. Note that the note about the rejection is not displayed anywhere on the page. 
6. Click on log. Note that the email from step 5 is displayed, but not the rejection note from step 3. 
7. Return to item page and click on comments and discussion pages. Note that there is no record of the rejection note. 
8. If you the user were also the submitting author, check your version of the item page for any record of the rejection note.  Note that there is none. 

**Expected behavior**

1. Any rejection (or acceptance, new version creation, etc.) activity would be recorded in the log, with the manager doing the rejection clearly labeled (see screenshot 1). 
2. Any reject note added during rejection process would also be recorded in the log (see screenshot 1). 
3. Any rejection note added during the rejection process would appear in the form email sent to the user (see screenshot 2). 
4. Any rejection note added during the rejection process would also be displayed to the user on their personal view page (see screenshot 3). 

**Screenshots**
![image](https://user-images.githubusercontent.com/15632391/123467481-911c8500-d5be-11eb-9d9c-c4b867d27f1c.png)
_1. Moderator view - rejection note added by moderator during rejection process_

![image](https://user-images.githubusercontent.com/15632391/123470991-2588e680-d5c3-11eb-9f88-a7aecddc2697.png)
_2. Moderator view - reject note added by moderator not added to reject email notice to author_

![image](https://user-images.githubusercontent.com/15632391/123469459-1012bd00-d5c1-11eb-9dbf-5452b8268978.png)
_3. Author view - no rejection note displayed_

**Comment by ajrbyers** [comment]
PR in for this.
