### ISSUE TITLE
Typesetters unable to access images via typesetting plugin

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/janeway#2279]
At present the typesetter (SC) has reported being unable to access article images in the typesetting plugin, and trying to add these in via the 'Review Typesetting' button isn't working (it's possible to tick the image files but the selection isn't saving and so the typesetters still can't get access).

The bug became apparent for the following article: https://traj.openlibhums.org/plugins/typesetting/article/4345/

Thanks for your help.

**Comment by ajrbyers** [comment]
This issue was resolved https://github.com/BirkbeckCTP/typesetting/pull/144
