### ISSUE TITLE
Banned Logging in error message and modifying "reply to" field"

### ISSUE THREAD

**Issue by StVicious** [BirkbeckCTP/janeway#228]
Hi, 

I got a "banned logging in" error as attached for the past few days. Usually failed logging in is banned for a certain period of time and I can regain access. 

Also, How can I modify the "reply to" field? The default is "janeway@voyager.com". We want to change to my own email address. 

Thanks for your help!

**Comment by StVicious** [comment]
![banned_logging_in](https://user-images.githubusercontent.com/4967666/32359598-685ee43a-c00c-11e7-8bf0-c5e7ddf64ef8.png)
adding screenshot:

**Comment by ajrbyers** [comment]
The login ban is due to failure to provide the correct details. Its not an error, its a security feature.

The default reply-to address can be changed under Manager > Email Templates > From Address

**Comment by StVicious** [comment]
Hi Andy,

Thank you very much!

Andrew
