### ISSUE TITLE
Text too faint: in Actions block in review system admin page

### ISSUE THREAD

**Issue by hardyoyo** [BirkbeckCTP/janeway#2283]
**Describe the bug**
The text in the Actions block in an admin review page is too faint. The color is set in [this stylesheet](https://github.com/BirkbeckCTP/janeway/blob/39aa95d941542a1d05534b4698da693ba3316ed9/src/static/admin/css/app.css#L5004-L5027). The color is used throughout Janeway, if you decide to darken it here, you might consider darkening it in every instance it is used for text.

**Janeway version**
Master and preprint-remodel both have this

**To Reproduce**
1. Review an article submission
2. Observe the faint text in the actions block (might vary from monitor to monitor)

**Expected behavior**
Legible text for actions that can be performed. A solid usability argument can be made that all links should be colored consistently (i.e. these links should probably be blue). However, I don't want to have that argument. The text *does* need to be legible.

**Screenshots**

faint text:
![image](https://user-images.githubusercontent.com/611569/124320800-2cbf6f80-db42-11eb-84bc-08c7abfd11ec.png)

default blue text (the color setting for these styles has been removed):
![image](https://user-images.githubusercontent.com/611569/124320857-495ba780-db42-11eb-993d-57313e772280.png)

**Comment by ajrbyers** [comment]
This text has been darkened in the interm. Closing.
