### ISSUE TITLE
ORCID field is not being validated

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2292]
**Describe the bug**
The `core.models.Account.orcid` field is not being validated. As such, users are entering sometimes in ID form and sometimes in URL form. This presents an issue under two scenarios:

 A) Users are not able to use the "login with orcid" feature when using URL based ORCID
 B) When exporting metadata, the ORCID field might be flagged as invalid by services such as Crossref and DOAJ, which leads to the entire article being not processed.

**Janeway version**
v1.3.10

**Expected behavior**
User input should be validated to ensure ORCID ids are always added in ID form

**Comment by ajrbyers** [comment]
We need to make this a read only field and have a “connect orcid” button to link the account with the orcid imo.

**Comment by alainna** [comment]
@ajrbyers concur. As a part of that feature, you could store the access token received after authenticating the iD and have users re-authenticate their ORCID iD if a valid access token isn't found -- so you can be sure that it's definitely their ORCID iD.

**Comment by ajrbyers** [comment]
> @ajrbyers concur. As a part of that feature, you could store the access token received after authenticating the iD and have users re-authenticate their ORCID iD if a valid access token isn't found -- so you can be sure that it's definitely their ORCID iD.

This is covered in https://github.com/BirkbeckCTP/janeway/issues/2610

Meanwhile manual input of ORCIDs is now validated so closing this.
