### ISSUE TITLE
article submission fails when there are multiple of the same keyword

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#2306]
**Describe the bug**
An editor submits an article on `/submit/477/info/ ` and it fails. the stacktrace says that it found multiple keywords when just looking up a single one. 
This is before any keywords had been submitted through the form.

**Janeway version**
7739efb00070221bdd6cb76d53c0d65724826dd4

**To Reproduce**
figured out that the keywords are not unique but should be. this likely happened after using the import plugin and there are multiple blank keywords so that would probably be the first step to reproduce.
but once those are in there try to submit an article.
the last version that we had up this did not appear to be a problem. that was 1.3.8

**Expected behavior**
you submit the article and everyone cheers.

**Comment by ajrbyers** [comment]
This issue was fixed by https://github.com/BirkbeckCTP/janeway/pull/2754
