### ISSUE TITLE
XSLT: A space is appearing before the year in biblio ref tags

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2308]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8321378/126546422-01e2a11f-8774-4fb5-989d-b90f807fcae9.png)

**Janeway version**
1.3.10

**To Reproduce**

**Expected behavior**
There should not be a space before the year.

**Comment by joemull** [comment]
Same as #2350 @ajrbyers
