### ISSUE TITLE
[Preprints] Email notifications using main system (journal) templates lack subject lines, do not always display proper URLs

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2310]
**Describe the bug**
If a preprint uses a notification that is not a part of the preprints/repository, the notification will lack the specified subject line (instead: e.g. "subject_user_email_change"); in some cases, a link embedded in the notification will lack the :// of the protocol (e.g. "http//eartharxiv.org" rather than "https://eartharxiv.org"). 

**Janeway version**
Preprints. 

**To Reproduce**
1. In a Janeway install with both a journal and repository/preprint server, log into the repository/preprints instance, then update your account email address
2. Check the resulting message's subject line and confirmation link URL's lack of protocol (hyperlink version, not the displayed version)
3. In the same Janeway install with both a journal and repository/preprint server, log into the journal instance, then update your account email address
4. Compare 

**Expected behavior**

1. The email subject for the preprints instance would be the same as the journal instance 
2. There would be no issue with the hyperlink URL's protocol

**Screenshot**

![image](https://user-images.githubusercontent.com/15632391/126582119-eef1d4bf-acfb-49ad-9868-604d65b843b8.png)

**Comment by ajrbyers** [comment]
PR in for this.
