### ISSUE TITLE
Upgrading to v1.4 wipes all settings/translatable attributes if USE_I18N is set to False

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2321]
**Describe the bug**
Journals with `USE_I18N` set to `False` will see all translated model attributes wiped after running the 1.4 migrations included in Master

**Janeway version**
`master` HEAD at 6bd1c3194a76bc2468d753e4a0ac34b2ae11c57d

**Expected behavior**
Either:
 - The migration process should stop and error when this setting is disabled.
 - The migrations will copy the data to the regular attributes/columns rather than the translated ones when USE_I18N is set to False. All in all, it is problematic that the value of this setting can completely alter the result of a database migration so drastically.

**Comment by ajrbyers** [comment]
So! USE_I18N must be enabled for the `update_translation_fields` to work so it doesn't lose the settings it just doesn't copy them to the _lang_code version.
