### ISSUE TITLE
Top-level navigation can be label rather than just clickable menu option

### ISSUE THREAD

**Issue by lstachew** [BirkbeckCTP/janeway#2327]
**Is your feature request related to a problem? Please describe.**
One of our journals has requested sub-navigation for the "About" section of their website, so the main "About" heading should open up to the pages for General About, Editorial Leadership, and DSA About. However, "About" is duplicated as the first option in the drop-down menu, but because this isn't actually a page on the website -- it's just a heading -- it leads to an error page, and there isn't any way to get rid of it.

**Describe the solution you'd like**
A top-level navigation label can just be a label and not a clickable menu option on the dropdown by default.

**Comment by pgoussy** [comment]
@lstachew I learned today from @ajrbyers that the secret to doing this is simply to remove the URL from the top-level navigation item. i.e., if you're setting up About in the Content Manager while checking Has Sub Navigation, you would simply _not_ enter anything in the Link field.

**Comment by ajrbyers** [comment]
I did do some dev work to make this work properly ;)
