### ISSUE TITLE
Blank Keywords

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2334]
**Describe the bug**
The Disciplines header shows when the keyword underlying is blank.

**Janeway version**
1.3.10 & 1.4

**Expected behavior**
We should not save blank keywords, and we should remove them with a migration.

**Comment by joemull** [comment]
This seems to be caused by empty strings being saved as keyword objects:
![Screenshot from 2022-01-04 09-09-39](https://user-images.githubusercontent.com/47217308/148073355-cac64165-dd77-40fe-8ee6-eb601cf9d67d.png)
