### ISSUE TITLE
Retain issue article order in issue download

### ISSUE THREAD

**Issue by lstachew** [BirkbeckCTP/janeway#2408]
**Is your feature request related to a problem? Please describe.**
We noticed that when downloading the full issue of Global Storytelling, the articles are ordered by article ID rather than the issue article order (eg. the first file is an article that starts on p. 87 and the third file in the list is the Letter from the Editor that starts on p.1).

**Describe the solution you'd like**
It would be great if we could either (1) retain the order of the issue's articles in the issue download or (2) if there was a way to just upload a single concatenated full-issue PDF, whichever option is easiest / most sensible.

**Comment by ajrbyers** [comment]
Hi Lauren,

the latter is already possible for this very reason. You can upload an issue galley file. :)

Andy
