### ISSUE TITLE
Apply Stylesheet to Sitemap

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2450]
**Is your feature request related to a problem? Please describe.**
Humans sometimes look at sitemaps and can't read XML.

**Describe the solution you'd like**
Apply an XSL stylesheet (eg. https://gist.github.com/vitobotta/889526) so that humans can read sitemaps.

**Describe alternatives you've considered**
Leaving as is.

**Additional context**
Request from ULBD

**Comment by hardyoyo** [comment]
Breadcrumbs:

the sitemap.xml file needs something like this:

`<?xml-stylesheet type="text/css" href="sitemap-style.css"?>`

and the CSS file (named sitemap-style.css in the example above) for urlset, url, loc, lasmod, changefreq needs to exist somewhere. Wherever it's parked, the href in the xml-stylesheet directive needs to reflect that path.
