### ISSUE TITLE
'hidden from press' titles should not be included in the KBART API

### ISSUE THREAD

**Issue by pbastijn** [BirkbeckCTP/janeway#2466]
**Is your feature request related to a problem? Please describe.**
We have several titles that are hidden from press; a test journal and also new journals that are in development. They are not public (yet) and should not be communicated through KBART

**Describe the solution you'd like**
exclude hidden from press titles from the kbart api

**Describe alternatives you've considered**

**Additional context**

**Comment by ajrbyers** [comment]
This is an interesting one. I don't think we can equate "hide from press" with "hide from everything". At OLH we have a couple of journals hosted on our install of Janeway that are hidden from the press because we don't publish them but that doesn't mean I want them hidden from KBART.

**Comment by pbastijn** [comment]
Thanks! I get it. It’s not a major problem. I can remove these titles from the file when I send the KBART list to third party indexing services like a link resolver
