### ISSUE TITLE
RSS support should be extended to preprints/repository

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2498]
**Is your feature request related to a problem? Please describe.**
As a preprints server administrator, I would like to have an RSS feed to conveniently share the latest published preprints. 

**Describe the solution you'd like**
Extend RSS support to preprints/repository.

**Comment by hardyoyo** [comment]
breadcrumbs: https://github.com/BirkbeckCTP/janeway/blob/master/src/rss/views.py#L56-L102 do that, but for preprints, and add a URL. Would have to be careful with author metadata.

**Comment by hardyoyo** [comment]
here are the [docs on the Syndication Framework for Django 1.11](https://docs.djangoproject.com/en/1.11/ref/contrib/syndication/), which is current for Janeway 1.4, here are the [docs for the newer version of the framework](https://docs.djangoproject.com/en/3.2/ref/contrib/syndication/), which will be included in Janeway 1.5.
