### ISSUE TITLE
Possibility to display acceptance dates on the article landing page

### ISSUE THREAD

**Issue by camuwl** [BirkbeckCTP/janeway#2522]
Hi there, :)

Would absolutely love the acceptance date information which we are recording using the Back Content plugin to also appear on the front end. Acceptance date information has of course been used in the past for REF policy compliance but would also give prospective authors and contributors an idea of the turn around time from acceptance to publication.

Thanks for all of your brilliant work!

**Comment by ajrbyers** [comment]
This is covered by https://github.com/BirkbeckCTP/janeway/pull/4062
