### ISSUE TITLE
Social meta URLs are broken for some installations

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2535]
**Describe the bug**
Some URLs created for social media meta tags are broken for some installations (e.g. Michigan)

**Janeway version**
1.4

**To Reproduce**
1. Go to https://journals.publishing.umich.edu/fc/article/id/977/
2. Inspect HTML and search for `og:image`
3. See problem URL: `<meta property="og:image" content="https://journals.publishing.umich.edu/fc/fc/article/id/977/file/3046/">`

**Expected behavior**
URL should be formed as `https://journals.publishing.umich.edu/fc/article/id/977/file/3046/`

**Additional context**
Has to do with domain mode vs what Michigan is using.

**Comment by ajrbyers** [comment]
Hi Lauren,

You're correct we missed a tag on the OLH theme. I've added a PR for this: https://github.com/BirkbeckCTP/janeway/pull/2594

A
