### ISSUE TITLE
Preprints: Moderators should be able to un-reject submissions

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2539]
**Is your feature request related to a problem? Please describe.**
As a preprints moderator, I want to be able to un-reject a preprint if an author has submitted (or wants to submit) a new version. 

**Describe the solution you'd like**

Grant moderators permission to see and use un-reject button, similar to admins 

**Additional context**

permissions on the Un-reject button ```./templates/admin/repository/article.html```: 

```
139                         {% if request.user.is_staff and preprint.date_declined and not preprint.date_published %}
140                             <li>
141                                 <button name="reset" class="control-button"><i class="fa fa-recycle">&nbsp;</i>Un-reject
142                                     this {{ request.repository.object_name }}
143                                 </button>
144                             </li>
145                         {% endif %}
```

**Comment by ajrbyers** [comment]
This was closed by @alainna with https://github.com/BirkbeckCTP/janeway/pull/3067
