### ISSUE TITLE
Option to display article number on issue TOC/Current Issue/article pages

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#2545]
**Is your feature request related to a problem? Please describe.**
In lieu of dividing each annual volume into issues, _Ergo_ assigns each individual article its own number. These numbers have been captured in the running footer of the PDFs, but the editors would like them to appear on Janeway as well: in the TOC that appears on the issue page and the Current Issue widget, as well as in the article info on the right-hand side of each individual article page.

**Describe the solution you'd like**
Currently, I have captured these article numbers using the Article Sequence field in Janeway. I know that this field is primarily intended to be used for article ordering rather than labeling; however, it seems like a relatively simple solution to this request might be to add a checkbox to Journal Settings that would allow us to set the article sequence number as either displayed or hidden. Note that these numbers will not always reset at the beginning of each new volume (as is the case with the [Ergo volume I just published](https://journals.publishing.umich.edu/ergo/issue/30/info/), which continues the numbering scheme from the last volume published on our old platform) so we wouldn't necessarily want Janeway to automatically assign article numbers just based on the order within an issue.

**Additional context**
I've attached a screenshot of how the volume TOCs are displayed on our old platform, where _Ergo_'s back content is still hosted:

![2021-10-22_16-10-58](https://user-images.githubusercontent.com/36245100/138516940-cbefa78a-3724-4099-bc71-52ac9759d0d0.png)

**Comment by ajrbyers** [comment]
@joemull Having discussed this with Mauro it would be good to extend the issue display settings to allow editors to select page numbers or article numbers and display them in the article blocks. We should have a new method on the article object called something like `issue_title` and it should return the issue display and then page_numbers or article_numbers.

**Comment by mauromsl** [comment]
Hi @pgoussy,

We added an Article Number field to the article metadata in the latest release (v1.4) that can be used for this purpose. It is rendered as part of the generated "how to cite" field, and in the metadata sidebar:
https://demo.janeway.systems/playtest/article/id/14023/

![image](https://user-images.githubusercontent.com/10760678/141280861-84993a7e-a3c1-4d5e-8666-41b3a2eb625b.png)

We will look into adding a new setting so you can add page numbers and/or article numbers to the issue title on the article cards (issue TOC) across the site.
