### ISSUE TITLE
JATS OAI Metadata Prefix

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2547]
**Is your feature request related to a problem? Please describe.**
We currently have an endpoint for OAI_DC, we will need to at a JATS endpoint for the NGLP project.

**Describe the solution you'd like**
- Add a new metadata prefix for JATS
- If an article has JATS we need to use the JATS file
- If an article does not have JATS we should create a stub file

**Describe alternatives you've considered**
N/a

**Additional context**
For a Galley should we store a copy of the content in a Text field to make this process a lot faster?

**Comment by joemull** [comment]
Might be a good idea to consider advanced SEO via Google Scholar and Google Search at the same time, to see if what we implement for NGLP is also meeting the structured data needs of those services
