### ISSUE TITLE
Submit Files Page

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2550]
**Is your feature request related to a problem? Please describe.**
Editors want to be able to customise this area to suit their journal.

**Describe the solution you'd like**
- Allow editors to edit all of the text on this screen
- Allow editors to customise the content of the pop up windows

**Describe alternatives you've considered**
N/a

**Additional context**
Requested by various, most recently Peer @ jcls.

**Comment by joemull** [comment]
The first bullet point should now be resolved by #2496.
