### ISSUE TITLE
Latest Posts News Summary Formatting

### ISSUE THREAD

**Issue by jscottbranson** [BirkbeckCTP/janeway#2568]
**Describe the bug**
If I add a news item that begins with a few words of text, then a bullet list, the "Latest Posts" feed on the main press or journal pages will replace newlines with spaces, so the text becomes hard to read. In other words, the summary text on the main page does not include spaces between items that should be bullets.

**Janeway version**
Master/head bac13f84

**To Reproduce**
1. Go to "News Manager"
2. Add a news item that is just a bullet list
3. View the summary of the news item in the "Latest News" feed - there aren't spaces between items in the bullet list, making the preview hard to read

**Expected behavior**
It seems reasonable to assume a newline should be translated to a space when rendering the summary output for the Latest News feed.

**Screenshots**
![jw_issue_add](https://user-images.githubusercontent.com/18340247/139450559-2331db24-cb34-451e-b2c5-2ce41458a9d6.png)

![post_feed_issue](https://user-images.githubusercontent.com/18340247/139450584-a97d105f-cfed-470a-993a-7cd528bfa6a2.png)

Note the lack of spaces between bullet items in the second screen shot.

**Additional context**
Please let me know if this issue is with a plugin that Janeway uses, so I can refile the issue in the appropriate place. I really appreciate all the work that has gone into making this incredible publishing platform!

**Comment by ajrbyers** [comment]
<img width="304" alt="Screenshot 2024-08-06 at 17 49 12" src="https://github.com/user-attachments/assets/93389a4c-ac6c-4253-af51-4b4a0f787396">

List items are now renedered with spaces using the new template tag.
