### ISSUE TITLE
Enable account merge to work with preprint authors

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2577]
**Is your feature request related to a problem? Please describe.**
Preprint author and ownership roles should be transferred when Merging Accounts. 

**Describe the solution you'd like**
Extend the Account Merge feature to work with Preprint authors/owners, i.e. when one account (Merged Account) is merged into another (Target Account), the Merged Account's author and owner roles should be inherited by the Target Account.

**Comment by ajrbyers** [comment]
I don't think the Merge Account feature has been updated to work with Preprints.

**Comment by alainna** [comment]
@ajrbyers oh! I'll reword the above then

**Comment by ajrbyers** [comment]
Hey @alainna I tested this out today and merge accounts does work for Repos :)

**Comment by ajrbyers** [comment]
> @ajrbyers Testing this against our preprint author merge script, I've identified some potential issues with the merge users feature for authors, particularly if the duplicate accounts are both listed as author on a single item. Would it be better to provide these as a separate feature improvement / bug report ?

Feel free to edit this one or close it and open a clean one.
