### ISSUE TITLE
OLH theme won't render more than 3 child nav items on mobile

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2581]
**Describe the bug**
When a navigation item has more than 3 child items, these won't be rendered when browsing on mobile (OLH theme only)

**Janeway version**
v1.4

**Expected behavior**
All subnavitems should be rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/10760678/140175182-f0edc9cf-5750-42eb-9db1-50223844e9bc.png)

**Comment by ajrbyers** [comment]
A bit of investigation, I found two solutions:

1. Set: .is-drilldown{overflow-y: scroll;} this will let users scroll the nav
2. Upgrade to foundation 6.3 where this issue is fixed.
https://github.com/foundation/foundation-sites/pull/8699
