### ISSUE TITLE
Extra empty p tags in references

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2585]
Reference lists are rendered with extra `<p>` tags not in the XML. Creates the unwanted effect of prompting CSS to add padding between references and is also bad for accessibility. Reported by @pgoussy.

Version 1.4.0

1. Go to https://journals.publishing.umich.edu/tia/plugins/typesetting/preview_galley/article/964/galley/264/#heading3
2. Inspect HTML
3. See extra tags

![Screenshot from 2021-11-04 12-23-19](https://user-images.githubusercontent.com/47217308/140378735-7e92d9be-812f-4510-b9a3-0c0d6cf86d81.png)
![Screenshot from 2021-11-04 12-25-10](https://user-images.githubusercontent.com/47217308/140378938-53ab79d8-a466-431d-8a48-3ec4d313c636.png)

**Comment by pgoussy** [comment]
Possibly related issue with XSLT introducing blank `<p>` tags:

If the JATS is tagged with a `<list>` _inside_ a `<p>`, then Janeway will render an empty `<p></p>` _after_ the list. (See screenshots of the HTML + element inspector and the way it's tagged in the JATS.) Moving the entire `<list>` to be outside of the `<p>` tag in the JATS will prevent the appearance of that blank `<p>` in the HTML. 

![2021-11-11_10-51-35](https://user-images.githubusercontent.com/36245100/141330188-5f615bda-25f3-4b1a-8160-d8ea41dab001.png)
![2021-11-11_10-51-05](https://user-images.githubusercontent.com/36245100/141330194-1d38f7ee-1f52-42be-9bae-4d70124a8ebd.png)
