### ISSUE TITLE
JATS error: <bio> not rendering as a distinct section w/ header

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#2595]
**Describe the bug**
Our JATS vendor has tagged author bibliographies (meant to be displayed as a backmatter section within the article, rather than as metadata) using `<bio>`. This text _is_ displaying on the Janeway article page, but it's not recognizing it as a discrete section: the `<title>` is rendering as bold para text, rather than `<h2>`, and it is not appearing on the floating TOC in the right-hand margin. As a workaround, I was able to fix this by changing the `<bio>` tags to `<sec>` tags, but it seems like it would be semantically preferable if it could remain tagged as `<bio>` and still display as expected.

**Expected behavior**
`<title>` within `<bio>` should be treated like `<title>` within `<sec>`: rendered as a section heading (presumably `<h2>`) and appearing on the TOC

**Screenshots**
![error-tagged_with_bio](https://user-images.githubusercontent.com/36245100/141195451-edcf33ff-73a9-441c-86c7-1540f7f48ca4.png)
![workaround-tagged_with_sec](https://user-images.githubusercontent.com/36245100/141195454-8c8bbe19-e13e-4dd3-abb0-0916a9f56159.png)

**Comment by ajrbyers** [comment]
Semantically these could be h3 but not h2. Not sure they need to be in the TOC either otherwise it starts to lose its usefulness. Thoughts?

**Comment by pgoussy** [comment]
My thought was that if other backmatter sections (Acknowledgements, References, etc.) are rendered as h2 and displayed on the TOC, then it stands to reason that Biographies would be treated similarly. The `<title>` seems to have become an `<h2>` as soon as I replaced the bio tags with sec tags.

**Comment by ajrbyers** [comment]
Sorry, my mistake I though you mean the names of the authors 🤦‍♂️

Yup we can make this change.
