### ISSUE TITLE
Copyediting 0008 fails for new installs

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2597]
**Describe the bug**
When we try to make a new install copyediting 0008 fails because it runs before the NL languange fields are added to settings.

**Janeway version**
1.4-RC-8

**Comment by ajrbyers** [comment]
Note: not spotted by jenkins.

**Comment by joemull** [comment]
This may have been fixed by a migration already. Adding to 1.5.1 so we can check that and close if fixed.

**Comment by mauromsl** [comment]
Confirmed as fixed
