### ISSUE TITLE
Journals can switch languages even if the language switcher is off

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2601]
**Describe the bug**
In path mode, when you change a journal's language, the language, the cookie will be shared amongst every journal under that domain. This leads to journals getting translated to other languages even when they shouldn't be.

This also happened on non path journals, perhaps by matching the browser locale

**Janeway version**
v1.4

1. In a path mode install, switch one journal to german
2. visit another journal with language switching off
3. Journal is in German without option to revert back to english

**Expected behavior**
When switching to another journal, consider if the language selection from the previous journal is compatible with the current one.

**Comment by ajrbyers** [comment]
- [ ] Add language selection per-journal
- [ ] Add a middleware to consider if the currently selected language is compatible with the current journal
- [ ] If not, set to the default
