### ISSUE TITLE
Add subject line to the “review_assignment” email log

### ISSUE THREAD

**Issue by rachelleeucop** [BirkbeckCTP/janeway#2622]
**Is your feature request related to a problem? Please describe.**
When editors view the email logs for a particular article, the subject line is missing from the display for all messages and each specific message. This makes it difficult to search for the correct message. 

**Describe the solution you'd like**
The subject line should display on the main email log page and on each individual message when you click 'view content'.

**Describe alternatives you've considered**
None

**Additional context**
![missing subject line](https://user-images.githubusercontent.com/93212619/142516344-69e58306-0e69-4506-aa0a-b8146b40ef9a.png)
![image](https://user-images.githubusercontent.com/93212619/142516424-31a210e3-9e60-4f70-a85f-2f47dc0ec643.png)

**Comment by ajrbyers** [comment]
I'm assuming a more generic process in adding this feature:

- [ ] Add a subject line to the LogEntry model
- [ ] When an email is sent capture the subject
- [ ] Display the subject on the Log page
