### ISSUE TITLE
Glossary title rendered as para text rather than h2

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#2651]
**Describe the bug**
If an article has a glossary, the text captured in `<title>` within the `<glossary>` is rendering as paragraph text, rather than as a section title.

**To Reproduce**
1. Go to https://journals.publishing.umich.edu/ergo/plugins/typesetting/preview_galley/article/1132/galley/431/
2. Click on Notes in the floating TOC
3. Scroll down to Abbreviations at the end of Notes
4. Notice that (a) "Abbreviations" is formatted as bold paragraph text, rather than as an h2, and (b) there is no space or line break between the glossary title and the first glossary term "BT"--they run together as a single line of text

```
<glossary>
<title>Abbreviations</title>
<def-list>
<def-item><term>BT:</term>
<def><p id="P75">Heidegger, Martin (1962). <italic>Being and Time</italic> (John Macquarrie and Edward Robinson, Trans.). Blackwell. Original work published 1927. References are to the pagination of the original German edition of the work (Max Niemeyer Verlag, 1953, 1986) given in the margins of this translation.</p></def>
</def-item>
```

**Expected behavior**
In a `<glossary>`, text tagged in `<title>` should be treated like any other backmatter section title: rendered as h2 and displayed on the floating TOC.

**Screenshots**
![2021-12-07_16-05-18](https://user-images.githubusercontent.com/36245100/145106059-31f6ea1b-cc8f-4744-94b0-64c03112cf35.png)

**Comment by pgoussy** [comment]
Bumping this up to note that this is a recurring issue (see screenshot). Glossary is not a content type we see super frequently, but it occurs often enough that it would be better to display it natively rather than needing to use workarounds.
![2022-01-27_13-52-28](https://user-images.githubusercontent.com/36245100/151427032-10d1d00a-303b-49e6-b245-583cd4624fee.png)

**Comment by joemull** [comment]
@pgoussy Thanks for bumping--added to 1.4.2 roadmap.
