### ISSUE TITLE
Dollar signs in para text improperly triggering MathJax

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#2658]
**Describe the bug**
If a single paragraph contains more than one dollar sign character ($), all of the text between those characters is treated like a string of LaTeX content and rendered with MathJax.

**To Reproduce**
1. Go to https://journals.publishing.umich.edu/jala/plugins/typesetting/preview_galley/article/1914/galley/440/
2. Click on Lincoln and the Cantralls: “Too Good a Whig” in the floating TOC
3. Scroll down to the paragraph beginning "Lincoln's professional relationship..."
4. Note that a significant chunk of text is rendering in MathJax (and because it's not _meant_ to be LaTeX content, it's rendering very poorly, with no spaces between characters and inconsistent italics). It also extends past the text margin because (I assume) MathJax doesn't know where to insert a line break.

Here's the original JATS tagging:
`<p>Lincoln&#x2019;s professional relationship with the extended Cantrall family is further revealed when Lincoln, as a money lender, extended a loan to Thomas Cantrall, Levi&#x2019;s oldest son, for $600 on November 28, 1851 for two years with interest at ten per cent, secured with 80 acres of farm land, near the Cantrall survey. On November 29, 1852, Thomas and his wife, Elizabeth, gave Lincoln a new note for $660, releasing the first note. The new note, written and signed by Lincoln, contained on the reverse side three interest payments between 1854 and 1855. Then a tragic accident took Thomas&#x2019;s life when on June 22, 1856, while working at a sawmill, his team of horses became frightened at the blowing of the whistle, ran off, and dragged a log over him. A younger brother, Charles S. Cantrall, administered the estate, paid off the note where Lincoln recorded on it: &#x201C;Received, June 22, 1858 of Charles S. Cantrall, adm. of Thomas Cantrall, eight hundred and twenty-four dollars and twenty-four cents, in full balance of principal and interest on the note.&#x201D;<sup><xref ref-type="fn" rid="fn021">21</xref></sup></p>`

I did attempt to replace the "$" characters with the encoded hex reference (`&#x0024;`) in the JATS, but the final rendering in Janeway was unchanged. I suspect that the hex is converted to a plain "$" during the JATS>HTML transformation, and then MathJax picks it up the same as it would have picked up an unencoded "$".

As a workaround (in the interest of getting this article published ASAP) I will probably replace the default dollar sign characters with a "fullwidth dollar sign" (`&#xFF04;`), so the above example may no longer be relevant. However, I have attached a screenshot below.

**Expected behavior**
Simply, a dollar sign in JATS should be a dollar sign in Janeway. Or, to put it another way, MathJax shouldn't be activated unless there's explicit math tagging in the JATS.

**Screenshots**
![2021-12-09_14-55-15](https://user-images.githubusercontent.com/36245100/145466878-511a7f13-e753-4ae6-8c41-e64f4bdabf2d.png)

**Comment by pgoussy** [comment]
Through trial and error, I've just realized that a way to (seemingly) avoid this error is to have JATS tagging _between_ the two dollar signs that share a paragraph. I noticed that [footnote 20](https://journals.publishing.umich.edu/jala/plugins/typesetting/preview_galley/article/1914/galley/440/#heading5) featured two dollar signs with a few italicized words between them. As an experiment, I tried putting italics tags around a single space character (which has no visible change for the reader) between two dollar signs in another paragraph--and lo and behold, the MathJax stopped rendering in that paragraph. So, that will be my new workaround instead of replacing the dollar sign character: italicizing a single space somewhere between the two dollar signs to "interrupt" the MathJax.

**Comment by ajrbyers** [comment]
I think all we need to do is change the delimiter for Mathjax and then update the jats to output the new delimiter. Some suggest \$ \$ is a good delimiter as it would rarely occur in natural text.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pgoussy** [comment]
That makes sense to me conceptually! Currently, when actual LaTeX content is present, the JATS is tagged with `<mml:math>` and wrapped in either `<inline-formula>` or `<disp-formula>` as appropriate. In other words, I don't actually see any dollar signs in the JATS--so I assume that somehow the XSLT is transforming these tags into the delimiters that are picked up by MathJax?

Either way, let me know once you've made some sort of fix, and I can test if it's worked by reverting my example article back to the version _without_ the italics workaround.

**Comment by pgoussy** [comment]
Bumping this up because we've encountered it in another journal. Is this on the docket for the next RC (or perhaps a test case for the editable XSLT)?

**Comment by joemull** [comment]
@pgoussy We added this to the list for 1.4.2 at least

**Comment by pgoussy** [comment]
![2022-02-18_13-35-55](https://user-images.githubusercontent.com/36245100/159039385-c1a892e4-72af-4381-baca-0f767ab0a2ab.png)
