### ISSUE TITLE
Add a setting for displaying the journal title in the navbar

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2661]
**Is your feature request related to a problem? Please describe.**
Some journals don't have a logo or have a logo that doesn't render the journal title. These journals would like to render the journal title in text form as part of the navbar.

**Describe the solution you'd like**
A setting that allows the journal to render the journal title in the navbar

**Additional context**
It is unlikely we will be able to render the journal title in the Material theme, given that there is already very little space between buttons and logo.

For mobile viewports, we could render the journal code rather than the whole title.

**Comment by ajrbyers** [comment]
@mauromsl clean already does this FYI.
