### ISSUE TITLE
Preprints: Item DOI link directs to relative location, not doi.org 

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2668]
**Describe the bug**
When viewing a preprint in the repository manager or author dashboard view, the Preprint DOI link directs to a relative location in Janeway and not to a location at https://doi.org/ 

**Janeway version**
Preprints (1.4.x)

**To Reproduce**
1. Go to a preprint in the repository manager view or author dashboard view, example: https://dev.eartharxiv.org/repository/manager/1787/
2. Click on Preprint DOI link, example: https://dev.eartharxiv.org/repository/manager/1787/10.31223/X5CK5K
3. See error
4. Go to live version of preprint and click on Preprint DOI link: https://dev.eartharxiv.org/repository/view/1787/ , goes to: https://doi.org/10.31223/X5CK5K

**Expected behavior**
Preprint DOI link in dashboard view would direct to https://doi.org/xxxxx

**Comment by ajrbyers** [comment]
This should have been closed automatically bu PRs. Closing now.
