### ISSUE TITLE
Custom submission fields allow rich-text values but don't render the HTML

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2670]
**Describe the bug**
When a custom submission field is value has HTML, `answer` field is not marked as safe and hence all markup is displayed on screen.

**Janeway version**
v1.4.0

**To Reproduce**
1. Add HTML to any rich text submission field
2. Publish the article
3. View article page

**Expected behavior**
The string should be marked as safe so that the HTML is rendered. 
**Screenshots**
![image](https://user-images.githubusercontent.com/10760678/146752806-26cb302d-35fe-4442-a0e9-d5f995d4874c.png)

**Additional context**
These fields allow input from any registered users. It is important we bleach the fields to prevent from XSS attacks

**Comment by ajrbyers** [comment]
On OLH, clean and material output of field answers is now marked as safe.
