### ISSUE TITLE
Preprints: user can upload arbitrary file types by renaming extension as .pdf

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#273]
A user can upload anything if they rename the file to have a .pdf extension to preprints. Unsure how internal MIME handling will cope with this when serving, so we may want to check.

- [x] Implement check with python-magic

**Comment by ajrbyers** [comment]
Files are currently mime-checked by Python, not sure what more we can do here.

```           
 if not files.guess_mime(uploaded_file.name) == 'application/pdf':
    form.add_error(None, 'You must upload a PDF for your manuscript')
```

**Comment by ajrbyers** [comment]
![screenshot from 2017-11-22 11 51 29](https://user-images.githubusercontent.com/8321378/33126180-801f078e-cf7b-11e7-810f-ce9f78846518.png)

Output from an HTML file renamed PDF.

**Comment by ajrbyers** [comment]
Implement magic checks, example:
```
>>> import magic
>>> magic.from_file('/tmp/img_3304.jpg', mime=True)
```
