### ISSUE TITLE
Can't delete duplicate FrozenAuthor object due to logic around AuthorOrder

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2736]
**Describe the bug**
A production editor merged a duplicate author's accounts, but there were still duplicate FrozenAuthor records on the Edit Metadata page for the article. So he tried to click Delete to remove the spare entries, but he get a Server Error screen.

This happened because `submission.models.remove_author_from_article` expects to find only one ArticleAuthorOrder object for a given unique pair author+article.

```python
    try:
        ArticleAuthorOrder.objects.get(
            author=instance.author,
            article=instance.article,
        ).delete()
    except ArticleAuthorOrder.DoesNotExist:
        pass
```

**Expected behavior**
The function would ideally only remove the ArticleAuthorOrder object corresponding to the duplicate FrozenAuthor.

**Janeway version**
1.4.0

**Comment by mauromsl** [comment]
For this to happen, it means the article already had both accounts listed as authors with the article prior to merging the acounts.

We need a unique constraint  ArticleAuthorOrder.article and ArticleAuthorOrder.author. When a constraint is present, the logic for merging will only preserve the relationship existing on the account that is being preserved and discard the child object of the account to be deleted. 
The same constraint would also be needed on the FrozenAuthor model.
