### ISSUE TITLE
Error page doesn't remember login state

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2738]
**Describe the bug**
When encountering an error, the error message page's navigation bar does not display indication of login status; instead, it always displays "Home | Login | Register", giving the impression that the user has also been logged out. 

**Janeway version**
Preprints

**To Reproduce**
1. After logging into Janeway, note that the navigation bar reflects the user's login status. 
2. Do something known to create an error, eg [accepting new version](https://github.com/BirkbeckCTP/janeway/issues/2730) 
3. See error page and note the current navigation bar: "Home | Login | Register|" 

**Expected behavior**
Navigation bar does not reflect the user's login status 

**Screenshots**
Actual: 
![image](https://user-images.githubusercontent.com/15632391/151890802-ecdd75dd-6518-4aad-ae6e-02ff961c81f7.png)

Expected: 
![image](https://user-images.githubusercontent.com/15632391/151890897-c310e9b0-646e-4ad6-a616-6fde0c9e8b49.png)

**Comment by ajrbyers** [comment]
Hi @alainna this has been changed already. The error page doesn’t have access to any of this context so we’ve made it plainer with no nav bar at all being displayed.
