### ISSUE TITLE
Preprints: AttributeError on submission of preprint

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#274]
Clicked final "Complete Submission" button on uploading a preprint and get:

Request Method: | POST
-- | --
http://****/repository/submit/5/review/
1.11.5
AttributeError
'NoneType' object has no attribute 'get'
/var/www/janeway/src/utils/notify_plugins/email_log.py in notify_hook, line 20
/usr/bin/python3
3.5.2
['/var/www/.virtualenvs/janeway/lib/python3.5/site-packages',  '/var/www/.virtualenvs/janeway/src/django-bootstrap4',  '/var/www/.virtualenvs/janeway/src/foundationform',  '/var/www/.virtualenvs/janeway/src/django-mailgun',  '/var/www/.virtualenvs/janeway/src/dynamicsites',  '/var/www/.virtualenvs/janeway/src/ebooklib',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages',  '/var/www/janeway/src/',  '/var/www/.virtualenv/janeway/lib/python3.5/site-packages/',  '/var/www/janeway/src/plugins']
Wed, 22 Nov 2017 11:14:44 +0000

Environment:

Request Method: POST
Request URL: http://****/repository/submit/5/review/

Django Version: 1.11.5
Python Version: 3.5.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.humanize',
 'cms',
 'core',
 'copyediting',
 'cron',
 'events',
 'identifiers',
 'journal',
 'metrics',
 'comms',
 'preprint',
 'press',
 'production',
 'proofing',
 'review',
 'reports',
 'security',
 'submission',
 'transform',
 'utils',
 'django_summernote',
 'dynamicsites',
 'markdown_deux',
 'foundationform',
 'hvad',
 'raven.contrib.django.raven_compat',
 'bootstrap4',
 'core.homepage_elements.about',
 'core.homepage_elements.issue',
 'core.homepage_elements.featured',
 'core.homepage_elements.carousel',
 'core.homepage_elements.journals',
 'core.homepage_elements.news',
 'snowpenguin.django.recaptcha2']
Installed Middleware:
('raven.contrib.django.middleware.SentryMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'core.middleware.SiteSettingsMiddleware',
 'utils.template_override_middleware.ThemeEngineMiddleware',
 'core.middleware.MaintenanceModeMiddleware',
 'cron.middleware.CronMiddleware',
 'core.middleware.CounterCookieMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'core.middleware.GlobalRequestMiddleware',
 'django.middleware.gzip.GZipMiddleware')

Traceback:

File "/var/www/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/var/www/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/var/www/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/var/www/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/.virtualenvs/janeway/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/var/www/janeway/src/preprint/views.py" in preprints_review
  458.         event_logic.Events.raise_event(event_logic.Events.ON_PREPRINT_SUBMISSION, **kwargs)

File "/var/www/janeway/src/events/logic.py" in raise_event
  233.             [func(**kwargs) for func in Events._hooks[event_name]]

File "/var/www/janeway/src/events/logic.py" in <listcomp>
  233.             [func(**kwargs) for func in Events._hooks[event_name]]

File "/var/www/janeway/src/utils/transactional_emails.py" in preprint_submission
  935.     notify_helpers.send_email_with_body_from_user(request, 'Preprint Submission', request.user.email, email_text)

File "/var/www/janeway/src/utils/notify_helpers.py" in send_email_with_body_from_user
  40.     notify.notification(**notify_contents)

File "/var/www/janeway/src/utils/notify.py" in notification
  21.     [func(**kwargs) for func in settings.NOTIFY_FUNCS]

File "/var/www/janeway/src/utils/notify.py" in <listcomp>
  21.     [func(**kwargs) for func in settings.NOTIFY_FUNCS]

File "/var/www/janeway/src/utils/notify_plugins/notify_email.py" in notify_hook
  84.     notify.notification(**notify_contents)

File "/var/www/janeway/src/utils/notify.py" in notification
  21.     [func(**kwargs) for func in settings.NOTIFY_FUNCS]

File "/var/www/janeway/src/utils/notify.py" in <listcomp>
  21.     [func(**kwargs) for func in settings.NOTIFY_FUNCS]

File "/var/www/janeway/src/utils/notify_plugins/email_log.py" in notify_hook
  20.     types = log_dict.get('types')

Exception Type: AttributeError at /repository/submit/5/review/
Exception Value: 'NoneType' object has no attribute 'get'

**Comment by ajrbyers** [comment]
This issue has already been resolved.
