### ISSUE TITLE
Some JATS list types not supported

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2744]
**Describe the bug**
Some list-type attributes are all still rendering with Arabic numerals (even with, for example, list-type="alpha-lower").

**Janeway version**
1.4.1

**Comment by pgoussy** [comment]
Just wanted to bump this up and mention a couple of related notes:

- JATS spec says that "If the [`<label>`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/label.html) element is used in a [`<list-item>`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/list-item.html), it overrides the [@list-type](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/list-type.html) and [@prefix-word](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/prefix-word.html) attributes." This does not appear to be the case in Janeway, which displays the "default" Arabic numeral for each `<list-item>` **plus** whatever `<label>` has been tagged.
- Janeway is still inserting a line break between the label(s) and the text of the `<list-item>`. When I mentioned this a few months ago, Andy said that `<p>` within `<list-item>` was unnecessary, but our vendor pointed out that it's technically in the JATS specs, so Andy said "We will probably need to tweak common.css to alter `<li><p></p></li>` to stop it rendering any margins."
![2022-04-28_17-16-35](https://user-images.githubusercontent.com/36245100/165848324-85d0587e-3b1d-4196-8030-21b43bb1b834.png)
![2022-04-28_17-15-56](https://user-images.githubusercontent.com/36245100/165848325-7acc7da3-28a7-4663-aa70-69fb01f3f86c.png)
