### ISSUE TITLE
Collections cover images

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2749]
**Describe the bug**
The page listing a journal's collections (example below) doesn't always show the right images, due to some inconsistency in the templates (`collection.html`) under each theme.

https://www.glossa-journal.org/collections/collection/ 

**Janeway version**
1.4.1

**Expected behavior**
There are a few possibilities:

1. The collections list should try to pull the cover image for each collection (an Issue object under the hood) and failing that, should load the default cover image.
2. Solution 1 would cause problems for some journals that currently use large image for collection / issue lists. So the template could try to load the cover image and then the large image, leaving out the default cover image.
3. We could do solution 1 and move data for affected journals.

**Comment by ajrbyers** [comment]
From what I can see is that all three use the here_image_url method but tow have a fallback image. I've removed that in #2807.

**Comment by mauromsl** [comment]
Closed by #2807
