### ISSUE TITLE
Article and Issue can disagree about being friends

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2750]
**Describe the bug**
It is possible for an Article to think that it's in an Issue (via Article.primary_issue or Article.projected_issue, both ForeignKey), but for the Issue to disagree (via Issue.articles, a ManyToManyField). See screenshots for an example.

![Screenshot from 2022-02-07 14-25-40](https://user-images.githubusercontent.com/47217308/152858545-b2b54a68-394a-46e8-aed1-b8c0eddae360.png)

![Screenshot from 2022-02-07 14-26-17](https://user-images.githubusercontent.com/47217308/152858551-c38682f6-bc41-44b5-8339-b44c3a8d9f4e.png)

**Janeway version**
1.4.0

**Expected behavior**
The model properties should be modified to make sure there's just one source of truth about this. Or, we should do lots of testing on the interfaces dealing with issue assignment to find the bug that lets users create this situation.

**Comment by ajrbyers** [comment]
The interface only lets you assign a primary issue to an issue an article is part of. Projected issue isn’t a factor here. Admin doesn’t restrict primary issue tho so perhaps that’s how this was done?
