### ISSUE TITLE
Manual stage change not logged as a WorkflowLog

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2774]
**Describe the bug**
When a staff user needs to move an article manually from one stage to the other, no `WorkflowLog` element is created. As a result, the stage does not appear in the jump navigation in `templates/admin/elements/article_jump.html`

**Janeway version**
1.4.1-ish

**Expected behavior**
The `Article.save()` custom function should call `workflow.log_stage_change()` in addition to creating an `ArticleStageLog` object.

**Comment by joemull** [comment]
After discussing this, new expected behavior: users should have a tool that allows them to move articles between stages, and should use this rather than the admin interface. See https://github.com/BirkbeckCTP/janeway/issues/493

Related but separate: We need to make sure all import methods create appropriate workflow logs.

**Comment by mauromsl** [comment]
Discussion: Add help text indicating that changing a stage won't create the required workflow elements and that shouldn't generally be used
