### ISSUE TITLE
Large tables overlapping with sidebar on OLH theme article page

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2800]
**Describe the bug**
Tables can now be expanded to be viewed in fullscreen across al themes. There is however a bug on OLH where the table is always expaneded, making it overlap with the sidebar

**Janeway version**
v1.4.1-RC-2

**To Reproduce**
 - Create a table in a JATS article with a fairly large amount of columns
 - 
**Expected behavior**
The table should be horizontally scrollable and not overflow the boundaries of the div it is cointained in

**Screenshots**
![image](https://user-images.githubusercontent.com/10760678/158988732-781a6c16-af8b-41bf-85f6-a31afca6795b.png)

**Comment by ajrbyers** [comment]
overflow is missing. Fun.
