### ISSUE TITLE
Skipping 'Accept Article' email from 'Unassigned' stage should still trigger Accept action

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#2814]
**Describe the bug**
For a new submission, just after an editor is assigned, you can choose from 3 actions: Move to Review, Accept Article, Decline Article. If you choose 'Accept Article' and send the subsequent Accept Article email, the article is properly accepted, the Editor is returned to the dashboard, and the article moves to the next workflow stg (typically Copyediting).

If, however, you choose to skip sending the Accept Article email, the editor ends up on the Peer Review stage with a message "This article is not yet in the review stage" and there is no apparent way to proceed. It seems that the Skip button is not properly recording the Accept decision.

**Janeway version**
1.4

**To Reproduce**
1. From the Unassigned page of a new article, assign an editor
2. Select Accept Article from the Actions block
3. If you send the email on the next page, everything works fine. If you skip the email, you get stuck as described above.

**Expected behavior**
Skip email button should result in the same behavior as if the email were sent. The user should be returned to the dashboard and the article should move past the review stage / have an Accept decision recorded.

**Additional context**
Potentially related closed issue? https://github.com/BirkbeckCTP/janeway/issues/440
I think the problem is somewhere around here? https://github.com/BirkbeckCTP/janeway/blob/1cfaa6ca911c55950c81530924353705744f7e9e/src/review/views.py#L1426

**Comment by ajrbyers** [comment]
What stage shows for the article? Is date_accepted null?

**Comment by ajrbyers** [comment]
@justingonder I've attempted to replicate this and cannot. Accepting the paper and skipping the notification still moves the article into the next stage.
