### ISSUE TITLE
Add suffix to account model and snapshot

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2820]
**Is your feature request related to a problem? Please describe.**
The salutation attribute of Account needs to be added to the FrozenAuthor model as frozen_salutation along with a salutation() function property, similar to other frozen author attributes.

**Comment by ajrbyers** [comment]
Additionally can we add suffix? From #2938 

>Is your feature request related to a problem? Please describe.
As an author who publishes using my title and name, including suffix, I want to be able to represent my name in full in Janeway. If I add my title to the Given Name field and suffix to the Family Name field, then there may be errors registering DOIs which my name in the metadata.

>Describe the solution you'd like
Add a prefix/title field and a suffix field to the account table
(?) Add support for prefix/suffix in output DOI metadata (?)

**Comment by alainna** [comment]
@ajrbyers Just confirming: This would make it possible to add Titles/prefixes/salutations and suffixes to the account table for authors, right? 
(Thinking of the notices we get from Crossref every time a "Jr" or "III" is in the Familyname field. 😅 )
Thanks!

**Comment by ajrbyers** [comment]
> @ajrbyers Just confirming: This would make it possible to add Titles/prefixes/salutations and suffixes to the account table for authors, right? (Thinking of the notices we get from Crossref every time a "Jr" or "III" is in the Familyname field. 😅 ) Thanks!

Yup!

**Comment by ajrbyers** [comment]
Update:

name_prefix already exists and we've decided not to snapshot this, after a discussion it was agreed that:

- [ ] We should add suffix to the Account model
- [ ] It should be snapshotted
- [ ] It should be passed to crossref
