### ISSUE TITLE
Render HTML galley but suppress HTML file download

### ISSUE THREAD

**Issue by edubinsky1116** [BirkbeckCTP/janeway#2840]
One of our journal editors requested that the HTML galley be displayed on the article page, but that the HTML file was not available to users for download. The reasoning was that since the HTML file did not include the images within the article, the PDF file was a better option for readers to download.

**Comment by edubinsky1116** [comment]
Thanks - this is awesome! I don’t see anything on the Article Settings page that would allow me to suppress the HTML file download, however. Will this roll out on a future version release or am I missing something obvious?

-Ellen


From: Andy Byers ***@***.***>
Sent: Monday, September 5, 2022 6:10 AM
To: BirkbeckCTP/janeway ***@***.***>
Cc: Dubinsky, Ellen - (edubinsky) ***@***.***>; Author ***@***.***>
Subject: [EXT]Re: [BirkbeckCTP/janeway] Render HTML galley but suppress HTML file download (Issue #2840)


External Email

Closed #2840<https://github.com/BirkbeckCTP/janeway/issues/2840> as completed via #3035<https://github.com/BirkbeckCTP/janeway/pull/3035>.

**Comment by ajrbyers** [comment]
Hey @edubinsky1116 this will roll out shortly!
