### ISSUE TITLE
Public profile page links to broken article URLs from other journals

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2841]
**Describe the bug**
On the user public profile page, publications from other journals are rendered using the `article_listing` component.
This component renders article urls using the `journal_url` template tag which uses the current journal (`request.journal`) to construct the URL. In situations where the journal is configured with a custom domain, this leads to a broken URL.

The same problem occurs with the thumbnail URL which won't load properly.

We should either use absolute URLs for the articles (`submission,models.Article.url`) in `article_listing.html` or drop articles from other journals being listed from the user's public profile.

**Janeway version**
v1.4.1-RC-6

**To Reproduce**
1. Create a user with publications on two or more journals
2. visit the user profile page from one of the journals
3. See error on article URLs from other journals

**Expected behavior**
Either the URLs resolve correctly to the other journals or this articles to be omitted

**Screenshots**
![image](https://user-images.githubusercontent.com/10760678/162163670-7dae3331-f17c-4109-a80f-67a95dabe4c8.png)

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**

**Comment by joemull** [comment]
@ajrbyers I don't believe this one has a PR yet. It's ready for one, right?
