### ISSUE TITLE
Wrong "next stage" in Complete Copyediting modal when Typesetting Plug-in installed

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#2847]
<img width="1407" alt="2022-04-15_15-22-58" src="https://user-images.githubusercontent.com/29953714/163629565-9717fad9-a668-4d30-8b9f-6c3e7740f477.png">

With the typesetting plug-in installed, complete the copyediting stage for any article. You'll get a modal that says "Complete copyediting and move this article to the next stage: **production**." 

In this case, the next stage is typesetting, not production.

**Comment by ajrbyers** [comment]
Likely this is simply hard coded from before flexible workflow existed.
