### ISSUE TITLE
Duplicate DOIs

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2848]
**Describe the bug**
It is currently possible to have two DOIs that are the same.

**Janeway version**
1.4.1

**To Reproduce**
1. Add a DOI
2. Add another the same

**Expected behavior**
We should check that the DOI is not a duplicate.

**Comment by joemull** [comment]
Will try solving this with a `unique_together` constraint that checks identifier string along with with `id_type`.
