### ISSUE TITLE
"Modified" date column in Typesetting Plugin no longer populating

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#2904]
**Describe the bug**
In the Typesetting Plugin, the Modified column no longer displays the date the typeset file was last modified, as it used to. This occurs in both the top-level Typesetting Plugin ("Current Typeset Files" box) _and_ in each individual galley's Edit Typeset File page. The latter  feels more problematic in practical use, since there's no longer an indication of whether or not I've already edited a typeset file that I clicked in to replace.

**Janeway version**
Currently 1.4.1; I don't recall when it started happening, but it's been a couple of months at least (I just kept forgetting to report it).

**To Reproduce**
1. Go to the archive page of any published article. (e.g. https://journals.publishing.umich.edu/ergo/manage/archive/article/1113/)
2. Click the "Typesetting Plugin" button in the top menu bar. (e.g. https://journals.publishing.umich.edu/ergo/plugins/typesetting/article/1113/)
3. Scroll down to the Current Typeset Files.

**Expected behavior**
"Modified" column should display the date (and time?) that the typeset file was last modified.

**Screenshots**
![2022-06-01_09-35-24](https://user-images.githubusercontent.com/36245100/171417375-b74f2837-2562-4046-aa18-c92b9fdd86bf.png)
![2022-06-01_09-34-57](https://user-images.githubusercontent.com/36245100/171417378-3d75c46f-d4b0-4216-b085-05363aa67f1f.png)

**Comment by mauromsl** [comment]
This a side-effect of the changes made in #2804  (removed the old `date_modified` column from `core_file`)

We should add a property to to the model with a deprecation notice, preserving the old interface.

I've also raised an issue to update typesetting plugin: https://github.com/BirkbeckCTP/typesetting/issues/158
