### ISSUE TITLE
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

### ISSUE THREAD

**Issue by lifengfan13** [BirkbeckCTP/janeway#2905]
**Describe the bug**

**Janeway version**
The version of Janeway under which the bug has been reproduced.
If running off of master, please, indicate the current HEAD of the Janeway installation

**To Reproduce**

**Expected behavior**

**Screenshots**

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ajrbyers** [comment]
@lifengfan13 can you please provide the steps to reproduce this?
