### ISSUE TITLE
Add support for title/salutation and suffix to author/account table

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#2938]
**Is your feature request related to a problem? Please describe.**
As an author who publishes using my title and name, including suffix, I want to be able to represent my name in full in Janeway. If I add my title to the Given Name field and suffix to the Family Name field, then there may be errors registering DOIs which my name in the metadata. 

**Describe the solution you'd like**
Add a prefix/title field and a suffix field to the account table 
(?) Add support for prefix/suffix in output DOI metadata (?)

**Additional context**
Ref: https://github.com/BirkbeckCTP/janeway/issues/2231

**Comment by ajrbyers** [comment]
@alainna I've added this to the existing issue #2820
