### ISSUE TITLE
"Article Jump" menu on preprints points to inappropriate locations

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#298]
At the moment, we have the "Article Jump" feature at the top right of the backend of preprints. This points to places like "copyediting" and "review" that aren't appropriate.

Suggest:

1. We hide this menu or items that aren't right.

2. Implement checks on those pages that the article isn't a preprint. Otherwise it will be possible to get weird state information around a preprint article.

**Comment by MartinPaulEve** [comment]
For clarification: this is on the log page

**Comment by ajrbyers** [comment]
Closed by ff4dbaf
