### ISSUE TITLE
Additional Submission Field answers cannot be edited.

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2986]
**Describe the bug**
As an editor, I can't update the answer given by an author to a custom submission field during the submission process

**Janeway version**
Janeway v1.4.2

**To Reproduce**
1. Create a custom field via "Additional Submission Fields"
2. Make a submission and populate the answer to the additional field
3. As an editor, visit the edit metadata page and try to edit the answer to the field
4. There is no form for editing the answer

**Expected behavior**
The edit metadata form should display for elements allowint to tweak all article metadata which is displayed under the "View Metadata" modal, including custom fields.

**Comment by justingonder** [comment]
@ajrbyers @mauromsl just noticed that, when editing metadata, if you leave a required additional field blank, hitting the Update Metadata button fails silently / user does not get prompted to complete the missing required field.

**Comment by ajrbyers** [comment]
@justingonder just to clarify: The form update completes but it doesn't force the editor to complete the required field, right? I think this is the correct behavior here as we don't want to force editors to complete additional fields that they may not have the answer to. Perhaps we should remove the required (*) though.

**Comment by justingonder** [comment]
@ajrbyers in my testing, no, the save does not complete. the button seems to have no action if you click it when you've missed a required field. for example, this journal has a "Suggested Reviewers" custom field that has no value. Clicking Update Metadata doesn't do anything.
<img width="660" alt="2022-09-27_12-28-47" src="https://user-images.githubusercontent.com/29953714/192595872-a5b55272-6609-4653-ae5c-de4d21ca3bcc.png">

Instead, I would expect leaving a required Additional Field blank to behave the same as if I left the title field blank:
<img width="398" alt="2022-09-27_12-31-28" src="https://user-images.githubusercontent.com/29953714/192595989-5569cf25-7c4f-45c8-947e-6a9c477df0a8.png">
