### ISSUE TITLE
Allow a base theme to be specified at the same time as specifying a theme

### ISSUE THREAD

**Issue by hardyoyo** [BirkbeckCTP/janeway#2992]
**Is your feature request related to a problem? Please describe.**
Maintaining a theme for Janeway is a lot of work, because many new features are facilitated by changes in the theme files. Custom themes usually only change a few templates, sometimes only one.

**Describe the solution you'd like**
Janeway themes are already based on the "clean" theme, it should be fairly simple to allow us to specify which base theme to use. This is, according to Andy, just a few lines of code.

**Describe alternatives you've considered**
Keep maintaining a full set of theme files, OR keep sending feature requests until we no longer need the customized theme.

**Additional context**
n/a

**Comment by hardyoyo** [comment]
breadcrumbs from @ajrbyers:
https://github.com/BirkbeckCTP/janeway/blob/473705e4c9e94cc19749fd08b337ba735b110436/src/utils/template_override_middleware.py#L71

> this is the line that needs changing. Need a setting and then tweak it so clean is no longer hard coded.

**Comment by ajrbyers** [comment]
Note from team discussion: OLH should be the base theme.
