### ISSUE TITLE
Email notification sent after revisions complete is not being logged

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#3011]
**Describe the bug**
When an author completes revisions during a peer review round, a notification is fired that sends an email to the editor who created the assignment. This email is never logged into a LogEntry

**Janeway version**
v1.4.2

**To Reproduce**
1. Create a revision assignment
2. Complete the revision assignment
3. Open the log entry
4. Email is missing from the logs despite being sent.

**Expected behavior**
This email should be logged against the article, same as any other article-related email.

**Additional context**
The reason behind it not being logged is due to the call to `send_email_with_body_from_user` not passing through a log_dict for constructing the LogEntry: https://github.com/BirkbeckCTP/janeway/blob/473705e4c9e94cc19749fd08b337ba735b110436/src/utils/transactional_emails.py#L483

**Comment by ajrbyers** [comment]
A log entry was added to this 7 months ago.

https://github.com/BirkbeckCTP/janeway/blob/5ff3d233223eb61328755ae99b9f45e81735bc13/src/utils/transactional_emails.py#L582-L599
