### ISSUE TITLE
"Replace preprint file" should go in for moderation

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#304]
OK, this is probably a painful thing to implement, but I think the replace file option, available to end users, needs to go into a moderation loop for both minor corrections and major versions. Otherwise there's nothing to stop someone putting in something legit, then modifying the file after it's been accepted to something obscene/illegal. So whether it's a minor revision or a new version, I think we need a way to hold this in the queue until it's confirmed.

This is also important since it might otherwise be possible for an author to make their preprint unavailable by uploading a blank PDF to the process as a minor correction replacement.

**Comment by ajrbyers** [comment]
94ef8d868147dcffdd945e4f5665ae51a26def92

**Comment by ajrbyers** [comment]
0af98e13c39c6f7f20d717c29b318028de469276

**Comment by ajrbyers** [comment]
530754446e2247ba94cfb164f225efbb5c7831c9

**Comment by ajrbyers** [comment]
ad8839bad217752b5a719075fdd0cabb52916772

**Comment by ajrbyers** [comment]
acbd01c318b8b7bd47c20c83a27723d8f56eefe3

**Comment by ajrbyers** [comment]
- [ ] Display a warning if there are multiple versioning requests for the same article
