### ISSUE TITLE
Email Subjects on Template

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#3043]
**Describe the bug**
Currently the email subject value displayed is hard coded on the template.

**Janeway version**
1.4.1

**Expected behavior**
The email subject for the template being sent should be displayed.

**Additional**
We should check that all email subjects conform to the pattern: `subject_name_of_related_template` this can be achieved by a test and will also identify any that do not conform.

**Comment by ajrbyers** [comment]
- [ ] In typesetting some emails (emails.py) do not pull a setting from the database.

**Comment by ajrbyers** [comment]
See PRs on Typesetting and APC:

- https://github.com/BirkbeckCTP/janeway/issues/3043
- https://github.com/BirkbeckCTP/typesetting/pull/167

**Comment by joemull** [comment]
@ajrbyers In addition to the PRs on apc and typesetting, does the fix for this involve https://github.com/BirkbeckCTP/janeway/compare/3043-email_subjects ? Ready for a PR?

**Comment by joemull** [comment]
> Mmm we agreed this wouldn’t go forward as @mauromsl was making changes to these templates.

OK, then is there anything that I can do on this issue @ajrbyers @mauromsl ? I set the status to in progress.

**Comment by ajrbyers** [comment]
See this PR: https://github.com/BirkbeckCTP/janeway/pull/3121
