### ISSUE TITLE
Plugins should be able to inject themselves into the main menu/dashboard

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#305]
It would be much neater if plugins could inject themselves into various areas of the backend menu.

For instance, consortial billing underneath "Staff" in the menu would be far neater than its current location under plugins.

**Comment by ajrbyers** [comment]
This feature already exists, see: https://github.com/BirkbeckCTP/janeway/blob/d6905dc93381fa8c589c2409ee34b2dc4fbe29a4/src/templates/admin/press/nav.html#L37
