### ISSUE TITLE
Home link in OLH theme hardcoded to server root

### ISSUE THREAD

**Issue by atiro** [BirkbeckCTP/janeway#313]
The Home link in the navbar in the OLH theme assumes it is always at the root of the server name, regardless of whether it is a path based setup or not. Need to change https://github.com/BirkbeckCTP/janeway/blob/d6905dc93381fa8c589c2409ee34b2dc4fbe29a4/src/themes/OLH/templates/core/nav.html#L7 to check if server is using paths and if so use the correct journal path.

**Comment by ajrbyers** [comment]
If we update the href to {{ request.journal_base_url }} the correct path/domain url should be output.
