### ISSUE TITLE
Author notification not logged

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#3160]
**Describe the bug**
When sending an author notification there is no log entry added.

**Janeway version**
1.4.2.1

**Expected behavior**
A log entry should be added as normal.

**Comment by alainna** [comment]
Confirming that we're seeing log entries for the text of the message sent to preprint Owners in the Repository. What's not seen is a record of the chosen subject and whether there was an attachment (n.b. not expecting that the attachment itself would appear). However that may be intentional?

**Comment by ajrbyers** [comment]
> Confirming that we're seeing log entries for the text of the message sent to preprint Owners in the Repository. What's not seen is a record of the chosen subject and whether there was an attachment (n.b. not expecting that the attachment itself would appear). However that may be intentional?

Not intentional, but we altered the Log system to store emails. I might close this one if you want to write up yours as a feature enhancement.
