### ISSUE TITLE
Unsubmitted articles visible in issue assignment interface

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3188]
**User Story**
As a staff member, when I am adding articles to an issue, I can see the titles of unsubmitted articles in the list. 

This is happening because they aren't excluded from the queryset:
https://github.com/BirkbeckCTP/janeway/blob/795bec0a7447a2d75e5d45274b6de9a9e1a63552/src/journal/views.py#L1436-L1440

**Proposed Solution**
Exclude unsubmitted articles from the queryset creation in the view.

Alternatively, use the `ActiveArticlesManager`, and redefine it to exclude unsubmitted articles.

Should active articles be defined to mean submitted articles?

**Comment by pgoussy** [comment]
Bumping this up as Media Industries has asked about it once again.

**Comment by ajrbyers** [comment]
> Bumping this up as Media Industries has asked about it once again.

Hey @pgoussy this has been assigned to 1.5.1. We’re finishing up 1.5 at the moment so it’s in the following version.

**Comment by pgoussy** [comment]
> 

Oh that's great news! Thanks!
