### ISSUE TITLE
the update script (.update.sh) does not fail on errors

### ISSUE THREAD

**Issue by hardyoyo** [BirkbeckCTP/janeway#3190]
**Describe the bug**
When running the update.sh script, even if the script encounters errors, it will still complete, and appear to succeed. This requires the operator to pay attention to the output and scan for errors, which is not expected behavior from a script. Errors should cause the update script to fail.

**Janeway version**
1.4.3-RC3, but the script has been this way since it was written

**To Reproduce**
1. Introduce an error in any migration (easy thing to do is delete an import at the top)
2. Invoke the update script: ./.update.sh
3. Observe that the script appears to complete, despite the failed migration.

**Expected behavior**
The migration error should cause the script to obviously fail.

**Screenshots**
n/a

## Front-end Issues
n/a

**Additional context**
Utilizing the [Unofficial Bash Strict Mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/) should help solve this problem.

**Comment by cederom** [comment]
`set -e` should fix?
