### ISSUE TITLE
Hardcoded language in funder metadata

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3195]
The word 'grant' is hardcoded on the article page, making it hard to control the overall funder statement:

https://github.com/BirkbeckCTP/janeway/blob/eacd5c858863a7400a03194faae125bf05709f27/src/themes/OLH/templates/journal/article.html#L217

https://github.com/BirkbeckCTP/janeway/blob/eacd5c858863a7400a03194faae125bf05709f27/src/themes/material/templates/journal/article.html#L142

![Screenshot from 2022-10-11 10-59-22](https://user-images.githubusercontent.com/47217308/195060247-19d7aaa1-bce5-4cbe-aa0a-7673f05ff94d.png)

**Comment by ajrbyers** [comment]
I think the issue here is someone put the word "Grant" in the grant id field which should only have the id of the grant.

**Comment by joemull** [comment]
Yes, true, but they weren't given instructions on how to form that field, so we should:

- [ ] add help text for the Funder attributes
```py
name = models.CharField(max_length=500, blank=False, null=False)
fundref_id = models.CharField(max_length=500, blank=True, null=True)
funding_id = models.CharField(max_length=500, blank=True, null=True)
```
- [ ] make sure the help text is visible for people entering funders
- [ ] add the Funder to the Django admin so that it can be edited by support staff
