### ISSUE TITLE
Draft Decisions: Updating template

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#3220]
**Is your feature request related to a problem? Please describe.**
When an Editor is writing a draft decision they may change some of the metadata after editing the email. This casues the text to reset.

**Describe the solution you'd like**
There are a few possible ways to resolve this.

1. Warn the user more on changing an element and force them to confirm
2. Move the feedback from the editor into its own form element and then insert it into the template email using a placeholder

**Comment by joemull** [comment]
This feels like a bug to me. Does it not to you?

**Comment by ajrbyers** [comment]
> This feels like a bug to me. Does it not to you?

This isn't a bug, no. Changing the date or decision type refreshes the text of the decision email so its working as expected.
