### ISSUE TITLE
Author sees broken button when uploading revised manuscript

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3230]
**Describe the bug**
As an author, when I go to upload a revised manuscript file, the **Save and Continue** button does not work.

**Janeway version**
1.4.3-RC-6

**To Reproduce**
1. Get a revision request assigned to you as author.
2. Open it.
3. Click the **Upload Revised File** cloud icon.
4. Don't click **Upload** but **Save and Continue**.
5. The file that was staged for uploaded is removed, and the screen stays the same. Nothing is saved.

**Expected behavior**
There should only be one button, and it should perform the upload as well as redirect back to the revision request. This is the current behavior of the upload button, so perhaps:
- [ ] Remove **Save and Continue**
- [ ] Rename **Upload** to **Upload and Continue**

**Screenshots**
![Peek 2022-10-19 12-32](https://user-images.githubusercontent.com/47217308/196679436-8de410c3-fbae-43ed-8f36-ab700de30d55.gif)

**Comment by ajrbyers** [comment]
This was closed by https://github.com/BirkbeckCTP/janeway/pull/3417
