### ISSUE TITLE
Cache on article.url causing problems

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#327]
The cache(600) directive on the article.url problem causes difficulties when we update an identifier and try to register it.

The upshot of this is that you end up with DOIs that resolve to non-existent local URLs.

**Comment by ajrbyers** [comment]
Should we: 1. remove the cache or 2. clear the cache when identifiers are changed?

**Comment by MartinPaulEve** [comment]
Could do #2, but the problem is that, with the other bug, I had to alter identifiers in the admin interface

**Comment by ajrbyers** [comment]
We can do a on save call so whenever the save happens (or wherever it is called from) it will execute when the identifier is changed.

**Comment by MartinPaulEve** [comment]
"Make it so"
