### ISSUE TITLE
[XSLT] Anchorlinks for chapter references do not work

### ISSUE THREAD

**Issue by MatthiasULB** [BirkbeckCTP/janeway#3282]
**Describe the bug**
The anchor links for chapter references in the HTML view do not work in the OLH and the clean theme.

**Janeway version**
1.4.3

**XML example**
The chapter is referenced correctly and the URL changes when you click on it, but the jump does not happen:

`<xref ref-type="sec" rid="S2">Section 2</xref>`
should lead to
`<sec id="S2">`
`<title>2. Section 2</title>`

**Desktop (please complete the following information):**
 - OS: Win10
 - Firefox, Chrome

**Comment by mattiker** [comment]
@ajrbyers looks like this is still an issue, see https://jcls.io/article/id/104/, section "Introduction":

> First, we discuss the impact model and explain our selection of new impact categories in [Section 2](https://jcls.io/article/id/104/#S2).

The jump still does not happen.
