### ISSUE TITLE
Editable footer at publisher level 

### ISSUE THREAD

**Issue by AmeliePlaysKath** [BirkbeckCTP/janeway#3295]
**problem**:

Certain policies are too prominent when they needn’t be included in the navigation bar for each journal, e.g. ‘Ethics and Malpractice Statement’, but should still really feature on journal sites somewhere; conversely, publisher level navigation items that are really needed on the main navigation bar are also at risk of being removed by journal editors editing the nav bar (e.g. Research Integrity).

**solution**:

The ability for the publisher to configure the footer, so that aPublisher Policies pages can be created. These policies would be accessible but no longer unnecessarily prominent. Nav bar links to these pages should still be possible to make and include as needed. 

If there is a means of making such nav bar items permanent (non-removable) at publisher level then this would be appreciated but less important than being able to create nav bar links to policy pages. 

**extra context**:

For an example, see: see https://www.igi-global.com/).

The pages we currently would like for this to happen to are the ‘Publication Ethics and Malpractice Statement’ and ‘Research Integrity’. It has been discussed that this might be possible to implement as soon as Janeway v.1.5.1. We would like to be able to roll this out to our journals alongside the announcement for Janeway 1.5.1.

**Comment by severett89** [comment]
Just to reiterate that this should include the ability to restrict editing to the publisher's staff at press level only. The point is to be able to gate the policies so that journal level editors cannot tamper with them.
