### ISSUE TITLE
Reader notifications bugs

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3304]
**Describe the bug**
There are 3 things I'd call bugs in the new reader notification system, though they have varying effects on the functionality: 

1. The self-enrolment form was only implemented on the material theme, not OLH or clean. As a result, the feature only works if you have a certain theme activated.
2. The template tag that is used to make the enrolment button operational breaks for staff, so staff can't see how the feature works in order to provide support around it.
3. The cron command calls the wrong setting group name and the wrong setting name, so even if the setting was turned on, it would not run.

https://github.com/BirkbeckCTP/janeway/blob/c1402a947829b076d2a4db87648941941f325fbc/src/cron/management/commands/send_publication_notifications.py#L45-L49

https://github.com/BirkbeckCTP/janeway/blob/c1402a947829b076d2a4db87648941941f325fbc/src/utils/install/journal_defaults.json#L3722-L3736

There are also two things that make it quite hard to use, even if they do not break it:

1. There is no documentation of how to set up reader notifications for a press or journal.
2. The reader index page showing enrolled readers and sent notifications does not include the setting for turning notifications on or off. The existence of this reader index page implies complete information about reader notifications, but users are not shown a crucial setting, or alerted to its existence, which is quite unfriendly.

**Janeway version**
1.4.3

**Comment by joemull** [comment]
One more thing that is unfriendly: I can sign up for reader notifications even if the journal has turned the feature off. I'd prefer not to have the option to sign up if it won't do anything.

**Comment by ajrbyers** [comment]
@joemull let me know how far you’ve managed with this on Monday, I can pitch in as this is my balls up.
