### ISSUE TITLE
Deleting a galley results in an error page

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#331]
The galley is deleted, but an error is displayed to the user.

**Comment by ajrbyers** [comment]
Where are you deleting the Galley from? There are multiple pages...

**Comment by MartinPaulEve** [comment]
Article archive page -> edit (on galley) -> delete

**Comment by ajrbyers** [comment]
- [ ] If no return URL attempt to make the best return URL possible based on user context and stage
