### ISSUE TITLE
generate_sitemaps management command needs work (is slow, doesn't work incrementally, doesn't build sitemaps for preprints)

### ISSUE THREAD

**Issue by hardyoyo** [BirkbeckCTP/janeway#3316]
**Describe the bug**
"is slow" = Running generate_sitemaps on a large press (50+ journals, 3 repositories) is very slow, 2 hours to complete.
"doesn't work incrementally" = The problem is compounded when attempting to re-run the command, as it simply rebuilds the sitemaps from scratch on each run.
"doesn't build sitemaps for preprints" = The repository sitemaps are created but the links to preprints are dead links. 

**Janeway version**
1.4.3

**To Reproduce**
1. run generate_sitemaps
2. wait for it to complete (our dev instance took about 2 hours)
3. re-run generate_sitemaps
4. wait...

**Expected behavior**
Subsequent runs of generate_sitemaps should avoid duplicative work. Generate_sitemaps should also have flags to only run for repositories, if an instance doesn't need sitemaps for journals (say if the instance is headless), or for general testing purposes.

**Screenshots**
n/a

## Front-end Issues
n/a

**Additional context**
One incremental solution would be to add a flag to limit sitemap building to just repositories. In fact, the headless flag for journals could be used for this purpose. For headless journals, you can safely skip building sitemaps, as they'd be unwanted and not helpful.

**Comment by ajrbyers** [comment]
The PR for this has been merged.
