### ISSUE TITLE
As a typesetter I'd like to see the date a file was uploaded

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3339]
**User story**
In my typesetter overview, I can't see the dates files were uploaded, making it tricky to select the latest file.

Editor's explanation: "Would it be possible to show the typesetters the dates when files are uploaded on Janeway? That would avoid a lot of confusion. In a recent case, I am sure that I ticked the right zip file for typesetting, and nevertheless the typesetter got confused because they saw 2 sets of zip files, one very old one, and the latest one."

**Describe the solution you'd like**
Add date uploaded to the file table.

**Screenshots**
![CRec9tPjEodHVUyJBnbBg6JPon4W0_NhlA](https://user-images.githubusercontent.com/47217308/211554298-114930e5-f217-46a2-b4ae-c2f4d4ac7d1a.png)

**Comment by ajrbyers** [comment]
@joemull has this been confirmed as an issue in Production or is it a https://github.com/birkbeckctp/typesetting issue?

**Comment by joemull** [comment]
Oh, good question. It is a Typesetting issue. I think subconsciously I have stopped thinking of them as different since we plan to make Typesetting core. Should I move it there?

**Comment by ajrbyers** [comment]
I think we will have a release of the TS plugin to align it with v1.5 of core so it might be worth adding it there this week if you can get to it so it can be included?

**Comment by joemull** [comment]
Moving to https://github.com/BirkbeckCTP/typesetting/issues/179.
