### ISSUE TITLE
Display current Janeway version in the Manager UI

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#3342]
**Is your feature request related to a problem? Please describe.**
As a Repository Manager Journal Manager, etc I find it beneficial to know which version of Janeway we are using. 

**Describe the solution you'd like**
In the Repository Manager and Journal Manager UI, there should be information about the current Janeway version (full version, e.g. 1.4.1-RC68) somewhere in the UI. For example, at the bottom or bottom of the page. (Similar to Press Manager -- but ideally in the left nav column)

**Screenshot examples**
Top
![image](https://user-images.githubusercontent.com/15632391/211632856-7b41745e-678d-4f6d-8eea-4ec189e4d91a.png)
Bottom 
![image](https://user-images.githubusercontent.com/15632391/211633091-776c1154-a32c-4e25-85dd-e9341241518e.png)

**Comment by hardyoyo** [comment]
It should be doable to link to the git commit that is checked out, assuming that the deployed code is deployed via git. Here's my quick research spike on that:

```
pip install gitpython
python src/manage.py shell
>>> import git
>>> repo = git.Repo(search_parent_directories=True)
>>> sha = repo.head.object.hexsha
>>> print(sha)
d738f7a1886e5b6b8afb69f0f8f6e9a24d8a398b
>>> short_sha = sha[:8]
>>> print(short_sha)
d738f7a1
```

**Comment by ajrbyers** [comment]
@hardyoyo we display the current version on the manager page of the press/journals and it can be pulled from the database.

**Comment by joemull** [comment]
Recently I was providing support to editors and realised this is still not visible to editors, because it is filtered to `is_staff` in the template:

https://github.com/BirkbeckCTP/janeway/blob/436de4d14a9be0b70df53a747ec17210650e62be/src/templates/admin/core/nav.html#L130-L140

What if we add editors to this visibility filter?

**Comment by ajrbyers** [comment]
> Recently I was providing support to editors and realised this is still not visible to editors, because it is filtered to `is_staff` in the template:
> 
> https://github.com/BirkbeckCTP/janeway/blob/436de4d14a9be0b70df53a747ec17210650e62be/src/templates/admin/core/nav.html#L130-L140
> 
> What if we add editors to this visibility filter?

I can’t think of a reason why we should just display this for everyone.
