### ISSUE TITLE
Preprints: OAI-PMH feed shouldn't display email addresses

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#3361]
**Is your feature request related to a problem? Please describe.**
As a Janeway preprints administrator, I want to ensure that systems reading preprints metadata are able to obtain all information that they see on the public item page. I also want information hidden from the public item page to be excluded. 

**Describe the solution you'd like**
Remove from the oai-pmh feed author email addresses. 

**Additional context**
This seems to only be an issue in the JATS feed. 

It may also be affecting the Janeway journals OAI-PMH JATS feed.

This is not an issue in the read API for preprints currently in development

**Comment by alainna** [comment]
Wondering whether the suggested change from @hardyoyo may help resolve this? https://github.com/BirkbeckCTP/janeway/pull/3166/commits/d755c0fe94fda6fdb8ae0d72c2bdeaebbff3d5fd

**Comment by mauromsl** [comment]
> Wondering whether the suggested change from @hardyoyo may help resolve this? [d755c0f](https://github.com/BirkbeckCTP/janeway/commit/d755c0fe94fda6fdb8ae0d72c2bdeaebbff3d5fd)

Sadly no, the serializer on that commit is used for the REST API, but not for the OAI-PMH interface
