### ISSUE TITLE
Cached Issue Display and Languages

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#3372]
**Describe the bug**
Sometimes an issue display title will get stuck displaying the wrong information. An example was reported by UGent on one of their Dutch language journals where a title was generated using the 'en' language code and so displayed "Issue" rather than the Dutch "Nummer".

**Janeway version**
v.1.4.4

**To Reproduce**
1. Create an issue with the wrong language set
2. There is no obvious way to force a change to the cached display
3. Switching languages may also not change wording due to the cached nature of the field

**Expected behavior**
This field should be translatable and be set for each active language.

**Comment by hardyoyo** [comment]
SO thread on this topic: https://stackoverflow.com/questions/11144245/django-i18n-and-caching-interference

**Comment by ajrbyers** [comment]
This is a special kind of caching where the value is written to the DB so we can easily resolve it by making the field translatable.
