### ISSUE TITLE
Reminders that seem correctly configured are not sent

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3427]
**Describe the bug**
Editors sometimes configure review assignment reminders with a combination of fields that does not result in a reminder being sent.

For example, setting a reminder for X days *before* an assignment is accepted won't work because there is no acceptance due date, but it's represented with this Info text:

"Sent 14 days before Review (Accepted) is due."

**Janeway version**
1.4.3

**Expected behavior**
A couple of options:
1) The help text should give instructions about which combination of fields works
2) Better yet, we make this a confirmable form and warn about combinations that don't work

**Comment by ajrbyers** [comment]
As discussed previously with Joe there currently is no way to create an non-sendable combo. I have updated the text to make how each reminder type is evaluated against due dates.

**Comment by joemull** [comment]
> As discussed previously with Joe there currently is no way to create an non-sendable combo. I have updated the text to make how each reminder type is evaluated against due dates.

Thanks Andy. I misunderstood the form in the same way as the original reporter. So I'm adding a bit of context here about what the problem is, in their words:

'The wording is very confusing! I'd like reviewers to get a reminder in 5 days if they haven't yet accepted the invitation. I changed the "Review (Invited)" to "Run type" = After and "Days" = 5. Will that setting do what I want?  It's very confusing because the Info in the reminder list displays "Send 5 days after Review (Invited) is **due**" rather than "Send 5 days after Review (Invited) is **sent**".'

I believe the word "invited" is tripping up the meaning of "after" and "before", even though we mention the review being due. We could change these to "after the due date" and "before the due date", and we could take away "is due", which would result in status messages like this:
- Send 5 days before the due date for Review (Invited)
- Send 5 days after the due date for Review (Invited)

With this wording, I believe it will be clearer that the invitation date is not the point of reference.
