### ISSUE TITLE
Add "jump" link for admins to "Edit issue" page

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#349]
If viewing an issue page, as an admin/staff, it would be cool to have a jump link to "edit issue data"

**Comment by ajrbyers** [comment]
Links appear in the Account drop down and in the Issues list page.

![screenshot from 2018-01-29 11 08 07](https://user-images.githubusercontent.com/8321378/35507652-6e75b3bc-04e5-11e8-9a44-b46ce6988518.png)
