### ISSUE TITLE
Update requirements for Python 3.10

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3524]
**Describe the bug**
We still get versions of 3 dependencies that are incompatible with Python 3.10.

**Janeway version**
911347c994a43b36eb295657ec9cbfe82245b0f3

**To Reproduce**
1. Git clone a new copy
2. Create a virtual environment with Python 3.10.7
3. run pip install
4. See:

```shell
Collecting jsmin==2.2.1
  Using cached jsmin-2.2.1.tar.gz (12 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in jsmin setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Expected behavior**
Pip install runs with no issues

**Comment by ajrbyers** [comment]
Note: any changes must also work for 3.6-3.9 unless you’re also suggesting changing the supported version of Python.

**Comment by joemull** [comment]
> Note: any changes must also work for 3.6-3.9 unless you’re also suggesting changing the supported version of Python.

These are pretty minor changes and none of them drop support for Python 3.6.

**Comment by ajrbyers** [comment]
> > Note: any changes must also work for 3.6-3.9 unless you’re also suggesting changing the supported version of Python.
> 
> These are pretty minor changes and none of them drop support for Python 3.6.

Great. It might be worth talking about though. 3.6 is EoL and 3.7 will be EoL very soon.
