### ISSUE TITLE
Add "Edit Metadata" to navbar/"Logs, Documents and More" drop-down

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#3533]
**Is your feature request related to a problem? Please describe.**
I frequently need to make an update to an article's metadata for one reason or another. As far as I can tell, the best way to do this at the moment is to navigate to the Copyediting or Typesetting Plugin tab, scroll down to the "View Metadata" link, then click "Edit Metadata" at the top of the pop-up. (Frankly, as a production person, I can't think of _any_ scenarios where I would prefer to View the metadata rather than Edit it, so the fact that I need to go through the pop-up first feels like an unnecessary extra step. Plus, the View Metadata pop-up doesn't list _all_ of the fields present on the Edit Metadata page.)

**Describe the solution you'd like**
There should be a link that goes directly to the Edit Metadata page, conveniently placed and available from _any_ page associated with an article. Therefore, in my mind, the obvious option would be to add it to the navigation bar--either as a stand-alone button on par with the workflow stages, or as a new list item under the "Logs, Documents and More" drop-down.

**Comment by ajrbyers** [comment]
Thanks Patrick. I think adding this to the drop-down is feasible. I wonder if there are any other useful utility links were missing.
