### ISSUE TITLE
[XSLT] <ack> automatically displays "Acknowledgements" section heading regardless of <title>

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#3542]
**Describe the bug**
Recently, _To Improve the Academy_ asked us to edit the JATS to use the American-style spelling "Acknowledgments", which would match their PDFs. However, it appears that Janeway ignores the `<title>` field within `<ack>` and automatically displays the British-style spelling "Acknowledgements" (with the extra "e") instead.

As a workaround, I changed `<ack>` to `<sec>`, but it would be nice to keep the tagging semantically accurate without compromising the journal's established style!

**Janeway version**
1.4.5

**To Reproduce**
1. Go to https://journals.publishing.umich.edu/tia/plugins/typesetting/preview_galley/article/2044/galley/2123/
2. Click on "Acknowledgements" in the right-hand section menu
3. Notice that the section heading says "Acknowledgements" despite `<title>` being tagged as "Acknowledgments"

**Expected behavior**
Janeway should render the `<title>` as tagged rather than automatically deciding the section heading based on the parent `<ack>` tags.

**Comment by ajrbyers** [comment]
> automatically displays the British-style spelling "Acknowledgements" (with the extra "e") instead

I think you’ll find @pgoussy that we call this the “correct” spelling, not the “British-style”. 😛

**Comment by ajrbyers** [comment]
@mauromsl could we include this in the batch of XSLT changes in 1.5.1? If no title is supplied fall back to the default so it doesn’t affect JATS articles with no title in this section?

**Comment by mauromsl** [comment]
> @mauromsl could we include this in the batch of XSLT changes in 1.5.1? If no title is supplied fall back to the default so it doesn’t affect JATS articles with no title in this section?

Yes, we've had a similar issue with the "References" block. We can extrapolate the logic to other content blocks that are injecting a static header. This is not only an issue because of the differences in spelling, but it is even worse for articles published in a language other than English
