### ISSUE TITLE
Footer issues and more tbh...

### ISSUE THREAD

**Issue by rossmounce** [BirkbeckCTP/janeway#356]
Google Chrome Version 64.0.3282.119 (Official Build) (64-bit), running on a shitty OS (Win 10 Enterprise build 14393.2007) https://orbit.openlibhums.org/article/doi/10.16995/orbit.219/ 

![capture](https://user-images.githubusercontent.com/824120/35671713-31404240-0734-11e8-9987-dbb450be28de.JPG)

**Comment by ajrbyers** [comment]
This is now fixed on live. Bad CSS rule for .card max-size which was supposed to only apply to Editorial Team cards had been applied to all of them... woops!

Thanks @rossmounce 

Commit: d87cf52a170c1c4e6b4a90adc89f300808e1ef14

**Comment by MartinPaulEve** [comment]
Thanks, @rossmounce ! If you could do a refresh, this should now be resolved (cheers, @ajrbyers )
