### ISSUE TITLE
Embedded PDF viewer on article and preprint views is not working with Janeway 1.5.0

### ISSUE THREAD

**Issue by hardyoyo** [BirkbeckCTP/janeway#3572]
**Describe the bug**
On a new installation of Janeway 1.5.0, the Embedded PDF viewer does not work for either the article or preprint views. This is due to the new [ClickJacking middleware](https://docs.djangoproject.com/en/4.2/ref/clickjacking/#setting-x-frame-options-for-all-responses) which comes with the newer version of Django upon which Janeway 1.5.0 is based. You can see this middleware is [enabled in the janeway_global_settings.py file](https://github.com/BirkbeckCTP/janeway/blob/master/src/core/janeway_global_settings.py#L114)

It's possible to [disable the X-Frame-Options for a single view](https://docs.djangoproject.com/en/4.2/ref/clickjacking/#setting-x-frame-options-per-view). We should do so for every view that needs to use the pdf-viewer (preprint and article views, maybe others?).

**Janeway version**
1.5.0-RC-4

**To Reproduce**
0. Ensure you're using a [web browser that honors X-Frame-Options](https://docs.djangoproject.com/en/4.2/ref/clickjacking/#browsers-that-support-x-frame-options)
1. Install Janeway 1.5.0-RC-4
2. Navigate to a journal article or preprint with a PDF file
3. Observe the non-functioning PDF viewer.

**Expected behavior**
A working PDF viewer for every preprint and journal article in Janeway.

**Screenshots**
n/a

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by ajrbyers** [comment]
It should be okay to use 

X_FRAME_OPTIONS = "SAMEORIGIN"

in global settings.

**Comment by mauromsl** [comment]
If we were to do this our settings would contradict the official docs default. Wouldn't it be simpler to leave the default as DENY?

https://docs.djangoproject.com/en/4.2/releases/3.0/#security

**Comment by ajrbyers** [comment]
Docs recommend changing it if you use frames rather than disabling it for a view. 

“If your site uses frames of itself, you will need to explicitly set X_FRAME_OPTIONS = 'SAMEORIGIN' for them to continue working.”

**Comment by mauromsl** [comment]
> If your site uses frames of itself, you will need to explicitly set

I suppose the flip-side of my argument is that Janeway has always had this setting set to `'SAMEORIGIN'` and this is now a breaking change for anyone upgrading to v1.5.0, in which case it is better to add the setting as you suggested.

**Comment by hardyoyo** [comment]
confirmed: adding `X_FRAME_OPTIONS = "SAMEORIGIN"` to janeway_global_settings.py does fix this issue. I will make a PR for that addition.

**Comment by ajrbyers** [comment]
Closed by https://github.com/BirkbeckCTP/janeway/pull/3573
