### ISSUE TITLE
IE-specific(?) Table of Contents box top-edge overhang

### ISSUE THREAD

**Issue by rossmounce** [BirkbeckCTP/janeway#358]
Not a problem in Chrome but with with IE11 version 11.2007.14393.0, running on Win 10 Enterprise build 14393.2007 

Table of Contents box slightly obscures box above.

![capture3](https://user-images.githubusercontent.com/824120/35672513-bf89116a-0736-11e8-85e4-5c5b8fe66f35.JPG)

**Comment by ajrbyers** [comment]
@rossmounce can you confirm the ToC box doesn't disappear (which is what it is supposed to do)?

**Comment by MartinPaulEve** [comment]
Yes, to confirm, I've seen this bug when scrolling back up in Chrome. Box doesn't disappear in time to not occlude other boxes.

**Comment by rossmounce** [comment]
When scrolled-up a notch higher, it _does_ dissappear 

But at one particular place it slightly occludes with the box _not_ disappeared (i.e. a minor issue but reproducible)

**Comment by ajrbyers** [comment]
I've made a change that may help with this (but currently dont have access to IE). This should now work ok on monitor resolutions above 1024x768 (94%) and with slight degradation for the others (6%).

Commit: 381d413d595f22b32726203d21c9cd545853c017

**Comment by rossmounce** [comment]
Confirmed, fixed for me.
