### ISSUE TITLE
Moving articles non-linearly through the workflow causes navigation dupes

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#3593]
**Describe the bug**
<img width="1267" alt="2023-05-31_15-14-09" src="https://github.com/BirkbeckCTP/janeway/assets/29953714/5e9f96bf-adf7-40fd-84e5-ba32f3c163e7">
Andy says this happens when "Moving articles back and forward thru the workflow.
We can update this so it’s distinct."

**Comment by ajrbyers** [comment]
@justingonder can you confirm how this article was moved around the workflow? Also can you confirm which version of Janeway is this from?
