### ISSUE TITLE
Installation Issue - Ubuntu 16.04.3 LTS - django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: foundationform

### ISSUE THREAD

**Issue by azharmateen** [BirkbeckCTP/janeway#360]
Hi,

I am trying to install janeway on Amazon EC2 and facing the following issue:

django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: foundationform

Following is my environment, steps and screen outputs:
```
WEB SERVICES: AWS EC2

OPERATING SYSTEM
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
```

INSTALLATION STEPS:
sudo apt-get install python3 python3-pip python-pip virtualenvwrapper -y
source /etc/bash_completion.d/virtualenvwrapper
sudo apt-get install libxml2-dev libxslt1-dev python3-dev zlib1g-dev lib32z1-dev libffi-dev libssl-dev libjpeg-dev mysql-client mysql-server git -y
mkvirtualenv janeway -p /usr/bin/python3
workon janeway
git clone https://github.com/BirkbeckCTP/janeway.git
cd janeway
pip3 install -r requirements.txt

sudo cp src/core/example_settings.py src/core/settings.py

CREATE DATABASE janeway CHARACTER SET = utf8 COLLATE = utf8_general_ci;

python3 manage.py install_janeway
```
```
ISSUE:
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: foundationform

```
```
INSTALLED PACKAGES:
beautifulsoup4==4.4.1
blinker==1.3
boto==2.46.1
bs4==0.0.1
chardet==2.3.0
cloud-init==17.1
command-not-found==0.3
configobj==5.0.6
contextlib2==0.5.5
cryptography==1.2.3
Django==1.11.5
-e git+https://github.com/GabrielUlici/django-bootstrap4@d230ec23d9f8f08c1505e0679ce0c6dba8090f0a#egg=django_bootstrap4
django-debug-toolbar==1.8
django-hvad==1.8.0
-e git+https://github.com/BirkbeckCTP/django-mailgun.git@dbf95eea4e55e9f16cf4689dba3ef88bee4f40ad#egg=django_mailgun
django-markdown-deux==1.0.5
django-recaptcha2==1.0.3
django-settings-export==1.2.1
django-simple-math-captcha==1.0.7
django-summernote==0.8.8.1
djangorestframework==3.6.3
-e git+https://github.com/BirkbeckCTP/django-dynamicsites@f439c524cf964d957a75fbec4b23ad03a9a5d159#egg=dynamicsites
-e git+https://github.com/BirkbeckCTP/ebooklib@b7005c57602eeea06358ac569a4cf52c630a32ef#egg=EbookLib
enum34==1.1.6
-e git+https://github.com/BirkbeckCTP/django-foundation-form.git@b5a4089d6c940bfe7bcba6565da05babb0936515#egg=foundationform
hibagent==1.0.1
html2text==2017.10.4
idna==2.1
ipaddress==1.0.16
Jinja2==2.8
jsmin==2.2.1
jsonpatch==1.10
jsonpointer==1.9
kitchen==1.2.4
language-selector==0.1
libsass==0.11.1
lxml==3.6.4
markdown2==2.3.0
MarkupSafe==0.23
mock==2.0.0
mysqlclient==1.3.12
oauthlib==1.0.3
pbr==3.1.1
pdfkit==0.6.1
Pillow==3.1.1
prettytable==0.7.2
pyasn1==0.1.9
pycparser==2.14
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
pyserial==3.0.1
python-apt==1.1.0b1
python-crontab==2.2.3
python-dateutil==2.6.0
python-debian==0.1.27
python-magic==0.4.13
python-systemd==231
pytz==2017.3
PyYAML==3.11
raven==6.0.0
requests==2.9.1
six==1.10.0
sqlparse==0.2.3
ssh-import-id==5.5
ua-parser==0.7.2
ufw==0.35
unattended-upgrades==0.1
urllib3==1.13.1
user-agents==1.0.1
virtualenv==15.0.1
```
```
SCREEN OUTPUTS:
Using username "ubuntu".
Authenticating with public key "imported-openssh-key"
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1041-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

34 packages can be updated.
0 updates are security updates.


*** System restart required ***
Last login: Sun Feb  4 16:18:21 2018 from IP ADDRESS
ubuntu@ip-IP-ADDRESS:~$ mkvirtualenv janeway -p /usr/bin/python3
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/ubuntu/.virtualenvs/janeway/bin/python3
Not overwriting existing python script /home/ubuntu/.virtualenvs/janeway/bin/python (you must use /home/ubuntu/.virtualenvs/janeway/bin/python3)
Installing setuptools, pkg_resources, pip, wheel...done.
(janeway) ubuntu@ip-IP-ADDRESS:~$ git clone https://github.com/BirkbeckCTP/janeway.git
Cloning into 'janeway'...
remote: Counting objects: 8598, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 8598 (delta 74), reused 89 (delta 34), pack-reused 8466
Receiving objects: 100% (8598/8598), 21.65 MiB | 25.21 MiB/s, done.
Resolving deltas: 100% (5539/5539), done.
Checking connectivity... done.
(janeway) ubuntu@ip-IP-ADDRESS:~$ cd janeway
(janeway) ubuntu@ip-IP-ADDRESS:~/janeway$ sudo pip3 install -r requirements.txt
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: beautifulsoup4==4.4.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: boto==2.46.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: bs4==0.0.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: chardet==2.3.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: Django==1.11.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5))
Obtaining django_bootstrap4 from git+https://github.com/GabrielUlici/django-bootstrap4@d230ec23d9f8f08c1505e0679ce0c6dba8090f0a#egg=django_bootstrap4 (from -r requirements.txt (line 6))
Cloning https://github.com/GabrielUlici/django-bootstrap4 (to d230ec23d9f8f08c1505e0679ce0c6dba8090f0a) to ./src/django-bootstrap4

  Could not find a tag or branch 'd230ec23d9f8f08c1505e0679ce0c6dba8090f0a', assuming commit.

Obtaining foundationform from git+https://github.com/BirkbeckCTP/django-foundation-form.git#egg=foundationform (from -r requirements.txt (line 7))
  Cloning https://github.com/BirkbeckCTP/django-foundation-form.git to ./src/foundationform
Requirement already satisfied: django-debug-toolbar==1.8 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: django-hvad==1.8.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 9))
Obtaining django-mailgun from git+https://github.com/BirkbeckCTP/django-mailgun.git#egg=django-mailgun (from -r requirements.txt (line 10))
  Cloning https://github.com/BirkbeckCTP/django-mailgun.git to ./src/django-mailgun
Requirement already satisfied: django-markdown-deux==1.0.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: django-settings-export==1.2.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: django-simple-math-captcha==1.0.7 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: django-recaptcha2==1.0.3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied: django-summernote==0.8.8.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied: djangorestframework==3.6.3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 16))
Obtaining dynamicsites from git+https://github.com/BirkbeckCTP/django-dynamicsites@#egg=dynamicsites (from -r requirements.txt (line 17))
  Cloning https://github.com/BirkbeckCTP/django-dynamicsites to ./src/dynamicsites
Obtaining ebooklib from git+https://github.com/BirkbeckCTP/ebooklib@b7005c57602eeea06358ac569a4cf52c630a32ef#egg=ebooklib (from -r requirements.txt (line 18))
  Cloning https://github.com/BirkbeckCTP/ebooklib (to b7005c57602eeea06358ac569a4cf52c630a32ef) to ./src/ebooklib

  Could not find a tag or branch 'b7005c57602eeea06358ac569a4cf52c630a32ef', assuming commit.

Requirement already satisfied: enum34==1.1.6 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied: html2text==2017.10.4 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 20))
Requirement already satisfied: idna==2.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 21))
Requirement already satisfied: ipaddress==1.0.16 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 22))
Requirement already satisfied: jsmin==2.2.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 23))
Requirement already satisfied: kitchen==1.2.4 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 24))
Requirement already satisfied: libsass==0.11.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 25))
Requirement already satisfied: lxml==3.6.4 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 26))
Requirement already satisfied: markdown2==2.3.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 27))
Requirement already satisfied: mock in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 28))
Requirement already satisfied: mysqlclient in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 29))
Requirement already satisfied: pdfkit in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 30))
Requirement already satisfied: Pillow==3.1.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 31))
Requirement already satisfied: pyasn1==0.1.9 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 32))
Requirement already satisfied: pycparser==2.14 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 33))
Requirement already satisfied: python-crontab==2.2.3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 34))
Requirement already satisfied: python-dateutil==2.6.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 35))
Requirement already satisfied: python-magic==0.4.13 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 36))
Requirement already satisfied: raven==6.0.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 37))
Requirement already satisfied: requests==2.9.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 38))
Requirement already satisfied: six==1.10.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 39))
Requirement already satisfied: sqlparse==0.2.3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 40))
Requirement already satisfied: ua-parser==0.7.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 41))
Requirement already satisfied: ua-parser==0.7.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 41))
Requirement already satisfied: user-agents==1.0.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 42))
Requirement already satisfied: pytz in /usr/local/lib/python3.5/dist-packages (from Django==1.11.5->-r requirements.txt (line 5))
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python3.5/dist-packages (from mock->-r requirements.txt (line 28))
Requirement already satisfied: contextlib2 in /usr/local/lib/python3.5/dist-packages (from raven==6.0.0->-r requirements.txt (line 37))
Installing collected packages: django-bootstrap4, foundationform, django-mailgun, dynamicsites, ebooklib
  Found existing installation: django-bootstrap4 0.0.2
    Can't uninstall 'django-bootstrap4'. No files were found to uninstall.
  Running setup.py develop for django-bootstrap4
  Found existing installation: foundationform 0.3
    Can't uninstall 'foundationform'. No files were found to uninstall.
  Running setup.py develop for foundationform
  Found existing installation: django-mailgun 0.9.1
    Can't uninstall 'django-mailgun'. No files were found to uninstall.
  Running setup.py develop for django-mailgun
  Found existing installation: dynamicsites 0.1
    Can't uninstall 'dynamicsites'. No files were found to uninstall.
  Running setup.py develop for dynamicsites
  Found existing installation: EbookLib 0.15
    Can't uninstall 'EbookLib'. No files were found to uninstall.
  Running setup.py develop for ebooklib
Successfully installed django-bootstrap4 django-mailgun dynamicsites ebooklib foundationform
(janeway) ubuntu@ip-IP-ADDRESS:~/janeway$ sudo cp src/core/example_settings.py src/core/settings.py
(janeway) ubuntu@ip-IP-ADDRESS:~/janeway$ cd src/sore
-bash: cd: src/sore: No such file or directory
(janeway) ubuntu@ip-IP-ADDRESS:~/janeway$ cd src/core
(janeway) ubuntu@ip-IP-ADDRESS:~/janeway/src/core$ sudo pico settings.py
(janeway) ubuntu@ip-IP-ADDRESS:~/janeway/src/core$ cd ..
(janeway) ubuntu@ip-IP-ADDRESS:~/janeway/src$ python3 manage.py install_janeway
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/janeway/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/janeway/lib/python3.5/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: foundationform
(janeway) ubuntu@ip-IP-ADDRESS:~/janeway/src$

```

**Comment by ajrbyers** [comment]
Thanks for this - it would appear that example_settings.py has fallen behind a little from our development_settings module. I’ll update the example and get back to you.

**Comment by ajrbyers** [comment]
Hi @azharmateen can you confirm you were using the Master branch?

**Comment by azharmateen** [comment]
Hi @ajrbyers, I have downloaded the application from:

1. https://github.com/BirkbeckCTP/janeway.git
and
2. https://github.com/BirkbeckCTP/janeway/archive/master.zip

The first download output I mentioned in my issue request. While the 2nd download from https://github.com/BirkbeckCTP/janeway/archive/master.zip give the following errors:

1. dynamicsites missing
2. foundationform missing
3. bootstrap4 missing

and after that the following issue:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: foundationform

For both installations, I update the environment by using requirements.txt

**Comment by azharmateen** [comment]
I have tried again to install the Janeway on same environment by downloading the fresh release and this time the message issue is different:

Code downloaded by using:

sudo git clone https://github.com/BirkbeckCTP/janeway.git

And tried to install the script by using:
sudo python3 manage.py install_janeway

SCREEN OUTPUT:
No changes detected in app 'sites'
Operations to perform:
  Apply all migrations: admin, auth, carousel, cms, comms, contenttypes, copyediting, core, cron, django_summernote, featured, identifiers, journal, metrics, preprint, press, production, proofing, review, sessions, sites, submission, utils
Running migrations:
  Applying core.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying journal.0001_initial... OK
  Applying submission.0001_initial... OK
  Applying carousel.0001_initial... OK
  Applying carousel.0002_auto_20170711_1203... OK
  Applying cms.0001_initial... OK
  Applying comms.0001_initial... OK
  Applying comms.0002_auto_20170816_1050... OK
  Applying copyediting.0001_initial... OK
  Applying copyediting.0002_auto_20170711_1203... OK
  Applying copyediting.0003_auto_20180122_2211... OK
  Applying submission.0002_auto_20170813_1302... OK
 Applying submission.0003_field... OK
  Applying submission.0004_fieldanswer... OK
  Applying submission.0005_field_width... OK
  Applying journal.0002_auto_20170711_1203... OK
  Applying journal.0003_pinnedarticle... OK
  Applying journal.0004_auto_20170813_1302... OK
  Applying submission.0006_field_journal... OK
  Applying submission.0007_auto_20170822_1256... OK
  Applying submission.0008_auto_20170907_1652... OK
  Applying submission.0008_auto_20170907_1159... OK
  Applying submission.0009_merge_20170907_1721... OK
  Applying submission.0010_auto_20170915_1146... OK
  Applying submission.0011_auto_20170921_0937... OK
  Applying submission.0012_auto_20170929_0835... OK
  Applying submission.0013_auto_20171004_1002... OK
  Applying submission.0014_auto_20171009_1028... OK
  Applying submission.0015_auto_20171013_1104... OK
  Applying press.0001_initial... OK
  Applying press.0002_auto_20170813_1302... OK
  Applying press.0003_auto_20170829_1501... OK
  Applying press.0002_auto_20170727_1504... OK
  Applying press.0004_merge_20170908_1215... OK
  Applying press.0005_auto_20170929_0834... OK
  Applying press.0006_press_preprints_about... OK
  Applying press.0007_auto_20171004_1605... OK
  Applying press.0008_auto_20171005_1158... OK
  Applying press.0009_press_preprint_editors... OK
  Applying press.0010_presssetting... OK
  Applying press.0011_remove_press_preprint_editors... OK
  Applying press.0012_presssetting_is_boolean... OK
  Applying submission.0016_auto_20171106_0909... OK
  Applying submission.0017_auto_20171114_1502... OK
  Applying submission.0018_article_preprint_journal_article... OK
  Applying submission.0019_auto_20171130_1115... OK
  Applying core.0002_auto_20170711_1203... OK
  Applying core.0003_load_countries... OK
  Applying core.0004_auto_20170813_1302... OK
  Applying core.0005_auto_20170816_0851... OK
  Applying core.0006_auto_20170816_0900... OK
  Applying core.0007_auto_20170829_1501... OK
  Applying core.0008_auto_20170925_1129... OK
  Applying core.0009_auto_20170925_1133... OK
  Applying core.0010_account_enable_public_profile... OK
  Applying core.0011_auto_20171010_1535... OK
  Applying core.0012_workflowlog... OK
  Applying core.0013_auto_20180207_1525... OK
  Applying cron.0001_initial... OK
  Applying cron.0002_auto_20170711_1203... OK
  Applying cron.0003_auto_20171121_1115... OK
  Applying django_summernote.0001_initial... OK
  Applying featured.0001_initial... OK
  Applying featured.0002_auto_20170711_1203... OK
  Applying identifiers.0001_initial... OK
  Applying identifiers.0002_auto_20170711_1203... OK
  Applying identifiers.0003_brokendoi_journal... OK
  Applying identifiers.0004_auto_20170921_1113... OK
  Applying journal.0005_auto_20171002_1503... OK
  Applying journal.0006_auto_20171115_1216... OK
  Applying journal.0007_auto_20180129_2342...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/options.py", line 617, in get_field
    return self.fields_map[field_name]
KeyError: 'issue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/janeway/src/utils/management/commands/install_janeway.py", line 26, in handle
    call_command('migrate')
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/operations/models.py", line 536, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 349, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/schema.py", line 88, in _delete_composed_index
    return super(DatabaseSchemaEditor, self)._delete_composed_index(model, fields, *args)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 372, in _delete_composed_index
    columns = [model._meta.get_field(field).column for field in fields]
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 372, in <listcomp>
    columns = [model._meta.get_field(field).column for field in fields]
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: ArticleOrdering has no field named 'issue'

**Comment by azharmateen** [comment]
I have applied the manual migrations to individual apps: 

_**sudo python3 manage.py migrate journal**_ 
sudo python3 manage.py migrate metrics
sudo python3 manage.py migrate preprint
sudo python3 manage.py migrate press
sudo python3 manage.py migrate production
sudo python3 manage.py migrate proofing
sudo python3 manage.py migrate review
sudo python3 manage.py migrate sessions
sudo python3 manage.py migrate sites
sudo python3 manage.py migrate submission
sudo python3 manage.py migrate utils

The above reduced the pending migrations from 40 to 5. Following app is showing some issues:
sudo python3 manage.py migrate journal

ISSUE:
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: journal
Running migrations:
  Applying journal.0007_auto_20180129_2342...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1060, "Duplicate column name 'section_id'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/operations/fields.py", line 87, in database_forwards
    field,
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/schema.py", line 48, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 429, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1060, "Duplicate column name 'section_id'")

**Comment by ajrbyers** [comment]
Hey @azharmateen thanks for this - I've just run an install and fixed a few issues. I'll make a commit onto Master shortly that should fix the installation process.

**Comment by ajrbyers** [comment]
See above commit (b6f63d0) which should fix the issues you're seeing. Two steps to take:

1. Drop and recreate your database
2. Run install_janeway again

If you'd like an invite into our Slack group let me know as its usually quicker to get answers there for little issues during install.
