### ISSUE TITLE
Preprint version title should be allowed to be null

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#3624]
**Describe the bug**
Preprint version titles may be null if the author wishes to submit a new version but not change its title. The preprint version titles are now exposed in the admin view of a preprint. Attempting to edit a preprint which has a version will a null title (such as a newly submitted preprint) will result in an error. 

**Janeway version**
1.5.0 

**To Reproduce**
1. Submit a new preprint and publish it. 
2. View the preprint in Janeway admin (``/admin/repository/preprint/xxxx``)
3. Note that the preprint version title is blank/null.
4. Make an update in the preprint such as adding a Published article DOI, then click Save
5. Note error

**Expected behavior**
Null preprint version titles should be permitted; if there is a null preprint version title, the preprint should still be able to be saved.

**Comment by mauromsl** [comment]
closed by #3759
