### ISSUE TITLE
'support_email' setting should also allow URLs

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#3629]
**Is your feature request related to a problem? Please describe.**
Currently you can set a support_email so users know how to get help. We do not publish our support email address because we want to guide users to our help center website first, in the hopes that they'll find the answer to their problem without having to contact us

**Describe the solution you'd like**
I would like to be able to provide a "support_url" instead of a support_email. I imagine others might appreciate the option to provide either or both.

**Describe alternatives you've considered**
Tried just putting a URL in the existing support_email field, but Janeway prepends 'mailto:' to my entry, making the URL invalid.

**Additional context**
Nobody likes email ;P

**Comment by ajrbyers** [comment]
@justingonder can you set this as a task for one of your team?

**Comment by justingonder** [comment]
@ajrbyers welcome back! yes, i'd already put it on our Trello board. i'll mark these from now on whenever we're happy to take a crack.

**Comment by joemull** [comment]
Hi @justingonder, when we made that setting we also made one where you can customize the text that wraps the support email: 

https://github.com/BirkbeckCTP/janeway/blob/fd0464d838ce5e95b68d483a28f64ecc6ec08fc9/src/utils/install/journal_defaults.json#L4408-L4426

Would it suit your needs to edit this setting at the press level? This HTML should let any URL put in `support_email` work as a normal link:

```html
<p>For help with Janeway, please <a href="{{ support_email }}">check out our guide</a>.</p>
```

**Comment by justingonder** [comment]
Sorry to come back to this so much later, but @joemull 's suggested fix above worked out perfectly to accomplish what I was trying to do. Closing.
