### ISSUE TITLE
Text tagged in <bio> displays as part of the article body

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#3632]
**Describe the bug**
If `<p>` text is tagged in `<bio>`, it is displayed in the HTML identically to `<p>` text in the `<body>`, both in text style _and_ paragraph/line spacing, despite being contained within the `<back>` section of the XML. This leads to the `<bio>` text appearing, for all intents and purposes, to be a continuation of the last portion of the `<body>` text. See screenshot for an illustration of this.

**Janeway version**
1.4.3

**To Reproduce**
1. Go to https://journals.publishing.umich.edu/mij/plugins/typesetting/preview_galley/article/3149/galley/2475/
2. Click on "Conclusion" in the TOC
3. Scroll down to final 2 paragraphs of text
4. Note that these 2 paragraphs, which are technically within `<back><bio>` are indistinguishable from `<body>` paragraphs, and there's no visible separation between `<body>` and `<back>`

**Expected behavior**
I know that author bios are meant to be captured in Janeway's metadata rather than tagged in the XML, but `<bio>` would be a convenient place to put text that's hard to place elsewhere. For instance, I've mentioned the recurring issue where an article may have an unnumbered footnote on the first page of the PDF (either without a callout, or perhaps with an asterisk or other symbol) and standard numbered footnotes for the rest of the article. This causes problems in Janeway because the first footnote in `<fn-group>` is automatically treated as part of the numbered sequence. It wouldn't necessarily be inappropriate to put these unnumbered notes in `<bio>`, since they're typically notes about/from the authors, special thanks, etc. 

So, if `<bio>` could be styled in such a way that it's clearly part of the back-matter--either by including it at the beginning of the rendered "Notes" section, or by adding a horizontal rule to mark the end of the `<body>` or something--this would be an ideal use-case.

**Screenshots**
![image](https://github.com/BirkbeckCTP/janeway/assets/36245100/50dda5af-526f-44df-8251-4e32ff69101d)

**Desktop (please complete the following information):**
Windows 11, Chrome v. 114.0.5735.199 (64-bit)

**Comment by ajrbyers** [comment]
Hey @pgoussy,

We've had a quick discussion internally. The `<bio>` section supports `<title>` and Janeway's XSLT will output this, could this be used to provide the breakup in the text you want?


![Image](https://github.com/BirkbeckCTP/janeway/assets/8321378/4157a498-c81c-4f08-9202-c4708235614e)

![Image](https://github.com/BirkbeckCTP/janeway/assets/8321378/e9666938-7426-402b-b4e2-cacecc3a0a1d)
