### ISSUE TITLE
Checkbox toggles in All Settings cannot be updated as of 1.5

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#3643]
**Describe the bug**
Demo'd for Mauro on 7/26/23: Some settings cannot be updated as of 1.5. This appears to be limited to checkbox toggles. For example, try to override the default value of use_crossref. After saving your change, it will revert back to the default. This also only seems to occur when accessing settings from the All Settings interface.

As a workaround, you can achieve your desired setting by changing in in the Django admin.

**Janeway version**
1.5

**Comment by mauromsl** [comment]
@ajrbyers this is specific to the all settings interface, the bool settings never save. It works fine on grouped settings pages and of course on the admin

**Comment by ajrbyers** [comment]
> @ajrbyers this is specific to the all settings interface, the bool settings never save. It works fine on grouped settings pages and of course on the admin

Thanks!
