### ISSUE TITLE
As an editor I'd like to see which sections are closed for submission

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3652]
**Is your feature request related to a problem? Please describe.**
As an editor, if I turn off submissions for a section (submission.models.Section.public_submission), I'd like for the dropdown in the submission form (submission.forms.ArticleInfoSubmit) to reflect that.

For authors, it will be invisible, but for me, it's still visible, which provides me flexibility but doesn't give me confidence that the feature is working and that authors won't see it.

**Describe the solution you'd like**
Add a parenthetical "public submission closed" or something similar in the dropdown option label.

**Comment by philippagrand** [comment]
I agree that this is needed.  I have a journal I inherited which has many sections no longer in use.  I cannot remove them as historic articles are assigned to these sections but I want to make sure new articles cannot be assigned to them in future.  Could there be a function to make some sections 'live' and others 'historic' perhaps and these can be changed as necessary?
