### ISSUE TITLE
Provide choice of who is cc'd into author emails at prepublication stage

### ISSUE THREAD

**Issue by philippagrand** [BirkbeckCTP/janeway#3685]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I cannot simply cc in relevant editors/section editors/marketing people inhouse into the author email at prepublication stage alerting the relevant people when an article is due to publish.  At the moment I can choose peer reviewers or section editors but I don't want to alert either of those groups - I want to alert the journal editors and my marketing intern. 

**Describe the solution you'd like**
Give options to choose who to cc in to emails to authors regarding the publication of the article via a drop down list of everyone involved in the journal.  Or allow customisation somewhere on the site of who receives emails re publication of articles.

**Describe alternatives you've considered**
No alternatives tried.

**Additional context**
At present there seems to be no way to alert journal editors or others in the publisher team that an article is about to publish.  This function needs to be customisable to allow better choice about who receives emails when an article is due to publish (alongside the author).  It might also be useful to include ALL the authors of an article, not just one.

**Comment by ajrbyers** [comment]
Hi @philippagrand we've got a similar feature with a ticket opened here: https://github.com/BirkbeckCTP/janeway/issues/3409

**Comment by ajrbyers** [comment]
Marking this one as closed in favour of #3409
