### ISSUE TITLE
Meta tag improvements

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3692]
As a developer I'd like a few improvements relate to writing meta tags:

- [x] Django provides `request.build_absolute_uri()` for getting an absolute URI for any location. This is useful in templates when creating precise meta tags. So I'd like a template tag for this method, because so far as I know, we don't have another way to build these URLs in some cases. Example usage:

    ```django
    <meta property="og:image" content="{% build_absolute_uri request.press.default_carousel_image.url %}">
    ```

- [x] Use Django's built-in `truncatewords` rather than our custom `truncatesmart` in `templates/common/elements/social_meta.html`

**Comment by joemull** [comment]
> We have a template tag for building urls with the sites framework:
> 
> `{% site_url 'core_reset_password' reset_token.token %}` is an example.
> 
> Is this not working as expected?

If memory serves I tried to use this but we didn't have a `url_name` that would work as an argument to `site_url` for the URL I put in the example. In other words our custom `site_url` is not as flexible as Django's `build_absolute_uri`.

**Comment by ajrbyers** [comment]
Cool - its worth double checking if using `build_absolute_uri` will work correctly with the sites middleware. I wonder if there is a reason we haven't used it in the past. (@mauromsl ?)
