### ISSUE TITLE
Refer a library discount scheme

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#370]
We ideally need a way for institutions to refer other institutions, with both then receiving a discount; the referrer getting a one-time yearly reduction, the referee getting the same.

- [x] Configuration system allowing us to specify percentages for both referrers and referees.
- [x] Page where institutions can visit to get their referral code. Since they don't have accounts, this needs to be a "pick/search for your institution from the list of supporters" page. This should give them a URL that they can share.
- [x] A version of the signup page at that URL that has the percentage discounts applied. On completion of the signup the multiplier of the referring institution should be decreased by 10%.
- [x] Some kind of logging and "undo" function should be built in, in the case of false/spam signups.
- [x] Potential for a REFERRAL LEADERBOARD - add setting to control display of this!

**Comment by ajrbyers** [comment]
This issue is now closed, see https://github.com/BirkbeckCTP/consortial_billing
