### ISSUE TITLE
Readme says Django version is 1.11 and Python is 3.6

### ISSUE THREAD

**Issue by eshellman** [BirkbeckCTP/janeway#3727]
requirements.txt says django=3.2. Not sure if there is compatibility for earlier versions, but given that these versions are no longer supported, it's not a good look.

**Comment by ajrbyers** [comment]
Thanks, I've updated that! :)

**Comment by eshellman** [comment]
that was fast! Is there a description of the architecture for developers anywhere?

**Comment by ajrbyers** [comment]
> that was fast! Is there a description of the architecture for developers anywhere?

Generally speaking Janeway follows standard Django architecture, we have one or two deviations but nothing massive. This is an area where we should probably expand our docs though.

**Comment by eshellman** [comment]
yes, I see that, I was hoping for a little more module documentation than "review" or "production". Not that my docs are any better, but having taken over someone else's book production code, I'm sensitive to the importance of that sort of documentation for sustainability. Anyway, mostly looks pretty clear.
