### ISSUE TITLE
notify_email.py error due to invalid characters being passed as the display-name part of a sender/recipient

### ISSUE THREAD

**Issue by hardyoyo** [BirkbeckCTP/janeway#3731]
**Describe the bug**
We have observed that an account name containing special characters such as "Goodwin, DO", if run through this bit of Janeway code https://github.com/BirkbeckCTP/janeway/blob/master/src/utils/notify_plugins/notify_email.py#L61  causes Django's message.py (django/core/mail/message.py) to throw this error: ValueError: not enough values to unpack (expected 2, got 1).

**Janeway version**
1.5.0

**To Reproduce**
1. unclear, notify_email does not appear to have any tests

**Expected behavior**
Bad e-mail information is common in most webapps. This util should ideally be more resilient.

**Screenshots**
n/a

## Front-end Issues
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by everreau** [comment]
The problem is not an incomplete email address but rather a comma in the last_name. such as "Goodwin, DO".

**Comment by ajrbyers** [comment]
> The problem is not an incomplete email address but rather a comma in the last_name. such as "Goodwin, DO".

Yeah this is the same reason we had a problem. We will need to clean these.

**Comment by hardyoyo** [comment]
Feel free to close this and write a better issue for the actual issue :-)
