### ISSUE TITLE
File attachment in Editor Decision email does not get delivered

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#3732]
**Describe the bug**
Editors are able to attach a file to the email that is sent upon Accepting an article in the review page, but the attachment does not arrive in the recipient's inbox.

**Janeway version**
1.5

**To Reproduce**
1. For an article in the Review stage, select 'Make a Decision'
2. Select 'Accept'
3. In the email screen that pops up, add an attachment and send the message.
4. The recipient will receive the email, but the attachment will be missing.

**Expected behavior**
Expect attached file to be delivered to recipient. This is working as expected for other emails, such as the Editor Assignment notification.

**Comment by mauromsl** [comment]
This is now resolved in #3121
