### ISSUE TITLE
Problem adding articles to issues

### ISSUE THREAD

**Issue by philippagrand** [BirkbeckCTP/janeway#3733]
**Describe the bug**
Assigning an issue on the Editor Assignment page doesn't feed through to other parts of the site - i.e. the Archive page or add the article to an issue under Issues.  

**Janeway version**
1.5.0

**To Reproduce**
If details of which issue the article is to appear in aren't registered on the Archive page, go to Editor Assignment to add the article to the issue.  This doesn't feed through to the Archive page so you need to also then go into Issues and add the article to the Issue.  This seems to solve the problem, but solving the problem should be a one-stop shop and not require going via multiple pages.  Adding to an Issue should also be a mandatory field to complete before the article comes through to production.

**Expected behavior**
If you add an article to an issue in one place on the site that should feed through to all relevant places where this information is needed.  It should be a one-stop action, not needing repeated in different places across the site.

**Screenshots**

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ajrbyers** [comment]
Hi @philippagrand,

The projected issue assignment is for tracking the issue an article is expected to join, not for assigning an article directly to an issue. Generally you would assign a projected issue at the start of the workflow (Editor Assignment) and then when you get to the end (Prepublication) the projected issue is recommnded for assignment.

Other than Prepub the only other place to assign an issue is through the Issue Management page.

I don't think a change in how Projected Issues works is required, but I am open to suggestions about how we can word this to make it clearer if you have any.

**Comment by philippagrand** [comment]
ok - makes sense! thanks for explaining! Why do I get so many articles come through unassigned - is this not something Editors are prompted to do ahead of passing the articles over to copyediting?

**Comment by ajrbyers** [comment]
It may be that they are ignoring it, it may be worth sending an email around asking them to ensure it gets set.
