### ISSUE TITLE
Chasing up overdue copyediting/typesetting

### ISSUE THREAD

**Issue by philippagrand** [BirkbeckCTP/janeway#3735]
**Is your feature request related to a problem? Please describe.**
There is no way in the system to chase up coypeditors/typesetters who have not submitted work within the timeframe requested. This needs to be done outside the system via email. 

**Describe the solution you'd like**
Functionality to send an email to the copyeditor/typesetter if the deadline for delivery of work has passed and the Journal Manager wants to give them a nudge and find out when edits/proofs will be submitted/make sure the article hasn't been overlooked at some point in the process/generally send a reminder.  I think this functionality is available at review stage? 

**Describe alternatives you've considered**
At present this requires an email to be sent outside of Janeway. 

**Additional context**

**Comment by ajrbyers** [comment]
Hi @philippagrand,

On both copyediting and typesetting you can see a mail icon (see below) which will open a popup that lets you send an email to that user from within Janeway, this gets logged against the article.

<img width="315" alt="image" src="https://github.com/BirkbeckCTP/janeway/assets/8321378/91c38ee3-450b-4a4d-a7dd-cf19d8fb8858">
