### ISSUE TITLE
Switch to conceal editors' names so authors cannot see who has been assigned to look after their submission

### ISSUE THREAD

**Issue by philippagrand** [BirkbeckCTP/janeway#3738]
**Is your feature request related to a problem? Please describe.**
As things stand, authors are able to find out which member of the editorial team has been assigned to “look after” their submission (i.e. give it a preliminary assessment and, if it is deemed good enough to go out for review, administer this process).  This is undesirable because our research community is small and we need to protect the identity of the individual to avoid potential bad blood and to ensure that our editors can do as they see fit (e.g. reject an article) without fear of repercussions.
 
**Describe the solution you'd like**
We’d like there to be a switch at the journal level that enables us to conceal the editors’ names that authors can currently see.  It would also be good to be able to switch this on or off at the level of an individual paper, in case we decide to change our policy in future but find it necessary to conceal editors’ identities from time to time.
 
**Describe alternatives you've considered**
N/A
 
**Additional context**

**Comment by ajrbyers** [comment]
@StephDriver this will be a good one for investigating how the settings system works. Happy to look at this one with you when I’m back if you don’t get to it though.

**Comment by ajrbyers** [comment]
@philippagrand I've added a PR for this request (https://github.com/BirkbeckCTP/janeway/pull/4014) but there is some discussion to be had around how far we go with anonymising the editors information.
