### ISSUE TITLE
Server Error encountered when previewing a review form

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#3744]
**Describe the bug**
Users encounter a Server Error when they click 'Preview' on any review form via the settings.

From Sentry:
[ReviewAssignment.article.RelatedObjectDoesNotExist]
ReviewAssignment has no article.

**Janeway version**
1.5

**To Reproduce**
Go to Manager > Review Forms. Click the pencil icon next to any review form, then click Preview. Server Error will result.

**Comment by ajrbyers** [comment]
@justingonder this has been fixed and will be in the 1.5.1 release!

**Comment by justingonder** [comment]
that's what i get for not searching issues first - sorry!
