### ISSUE TITLE
Hyper-author preprints cause server errors in some situations 

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#3770]
**Describe the bug**
1. Submitting author cannot load Author Dashboard due to preprint with 300+ authors causing a Server Error. 

2. Admin cannot update preprint owner via user interface due to Server Error. 

**Janeway version**
1.5.0

**To Reproduce**

1. Submitting author cannot load Author Dashboard due to preprint with 300+ authors causing a Server Error: 

   a. Submit a preprint with 300+ authors 
   b. Attempt to view the author dashboard 
   c. Encounter Server Error. 

2. Admin cannot update preprint owner via user interface due to Server Error 

   a. In the admin UI, open a preprint with 300+ authors: ``/admin/repository/preprint/xxxx``
   b. Attempt to update owner to an account you control
   c. Encounter Server Error

**Comment by hardyoyo** [comment]
We tracked this one down (with the help of @ajrbyers) to the memcached backend we were using. Here's the TLDR of what we did to resolve the error:

```
pip3 install python-memcached

tail -n 6 settings.py
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'SERVER_MAX_VALUE_LENGTH': 1024 * 1024 * 50
    }
}
```

**Comment by mauromsl** [comment]
> We tracked this one down (with the help of [@ajrbyers](https://github.com/ajrbyers)) to the memcached backend we were using. Here's the TLDR of what we did to resolve the error:
> 
> ```
> pip3 install python-memcached
> 
> tail -n 5 settings.py
> CACHES = {
>     'default': {
>         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
>         'LOCATION': '127.0.0.1:11211'
>     }
> }
> ```
> 
> Our assumption is that the python-memcached backend is ignoring the "too big" error that was causing this failure with our previously-used backend (pyLibMCCache).

Thanks @hardyoyo , glad it has been resolved, I'm closing the issue but it will come up if anyone searchs for a similar issue
