### ISSUE TITLE
"None" appears in HTML when press footer description left empty

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3788]
**Describe the bug**

"None" appears in the footer when press.footer_description is not filled in:

![image](https://github.com/BirkbeckCTP/janeway/assets/47217308/3791c685-5e72-45a7-803b-b6d78ba61822)

This is caused with the combination of these two things:
1. Empty values for a CharField or TextField are stored as null rather than an empty string (Django's default and the recommendation for such fields)
2. There is no template default set

**Janeway version**
[1a5baed](https://github.com/BirkbeckCTP/janeway/commit/1a5baed50512a3f8e8399049ca54d3035b6ad92d)

**Comment by mauromsl** [comment]
fixed by #3789
