### ISSUE TITLE
Journal-level statistics for editors

### ISSUE THREAD

**Issue by cpence** [BirkbeckCTP/janeway#3790]
It's often important for editors and staff to be able to track things like acceptance rate, average time from submission to final decision, etc. As far as I can tell from searching through the docs and the code here, that kind of info isn't currently collected by Janeway, and there's no place to put it. It would be fantastic if a list of such statistics was available from the Manager page, updated automatically by a cron job.

I'm sure people could think of further ideas for statistics that would be useful, but at the moment I can imagine at least:

- Acceptance rate
- Average time from submission to final decision
- Average number of reviewers solicited per article
- Average time from reviewer invite to submitted review

**Comment by ajrbyers** [comment]
Hi @cpence

I think for the most part these stats are available via the reporting plugin. Though I don't think we have the number of reviews per article yet.

https://github.com/BirkbeckCTP/reporting

**Comment by cpence** [comment]
Aha, thanks so much! Wasn't aware of that plugin. I'll go ahead and close, and reopen perhaps in the other repo if I see things that are missing.
