### ISSUE TITLE
Prevent reviewers from overlooking the "Reviewer Recommendation" field on review forms

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#3792]
**Is your feature request related to a problem? Please describe.**
We've had a number of reports that reviewers have hit the 'Complete Review' button on review forms and afterward discovered that their Recommendation selection is not what they intended.

I believe this is because the Recommendation field, though marked as required, already has a default selection of 'Accept Without Revisions." Some reviewers are skimming over that part of the form, not considering their intended answer for the field, and then hitting the Complete Review button, after which they receive a summary of their review, notice the unintentional Recommendation selection, and have no recourse for modifying the selection. At this point they write to the editor about the mistake, but the Editor similarly has no ability to modify the Recommendation field value on the reviewer's behalf, unless they happen to have access to the Django admin interface.

**Describe the solution you'd like**
I think the simplest solution here would be to leave the field as required, but not load a default value. That way if the reviewer misses the question and hits Complete Review, they'll get an error that they've missed a required field.
(Importantly, note that this solution introduces the potential for data loss, as described in #3766 because some reviewers are missing the field validation error and closing their browser windows, which results in the complete loss of their review form inputs.)

**Describe alternatives you've considered**
I suppose there could instead be a confirmation step of some sort, so that when the reviewer hits Complete Review they get a chance to review their inputs before actually submitting, but this seems potentially cumbersome and reviewers might not realize that they have one additional button to press on the confirmation screen before finalizing their review.

**Additional context**
<img width="596" alt="2023-11-21_19-19-47" src="https://github.com/BirkbeckCTP/janeway/assets/29953714/82db51ba-bb67-4e08-91a1-5c270696ab55">

**Comment by ajrbyers** [comment]
PR for this has been merged.
