### ISSUE TITLE
peer review audit improvements

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/janeway#3796]
**Is your feature request related to a problem? Please describe.**
At present, a user with admin access, e.g. an editor, is not prevented from changing a peer review through the admin side.  Any such changes would be logged, so are detectable on the system, but are not currently flagged up as changes on the front end.  In a scenario with multiple editors, this would make it theoretically possible for one to change a peer-reviewer's decision and the others not to be aware this had occurred.  I have no reason to suspect this has happened, but that it could is not ideal.

**Describe the solution you'd like**
Lock the peer review data once submitted, such that it cannot be changed after this in the admin side (it is already locked in the front end).  There is already an option for editors to put in an edited review response for sending to the author, which is displayed as a second field, so this allows any necessary edits to be made (e.g. removing identifying information from anonymous reviewers) while still showing the original.  

**Describe alternatives you've considered**
I considered displaying a history of any edits to these fields such that what can currently be seen in the log would appear on the front end, but that could encourage editing.  The more elegant solution is to restrict it.  Nobody should be changing a peer review after it has been submitted, so far better to make it impossible to do so.

**Additional context**
The peer review data is submitted via user-templates, so the fields are user-defined.  All of these fields will need to become immutable after submission by the peer reviewer.  This could pose a problem if a reviewer realises they made a mistake (e.g. clicked the wrong part of a drop down) after submitting the form.  It is not possible to reassign the review without creating a new round of reviews, which automatically closes out the old round.  Therefore as this is likely to rare, any resetting of the review could be done via technical support staff rather than the front end, which would mean there was an audit trail of it happening.

**Comment by ajrbyers** [comment]
In discussion we decided collectively that no change is required here. Admin already logs actions so there is an audit trail if someone were to edit a peer review.
