### ISSUE TITLE
Email log has wrong property name

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3810]
I think the property on this line is wrong:

https://github.com/BirkbeckCTP/janeway/blob/e8176e51c8847744ca80be19c642bdfd2402c5d2/src/core/email.py#L29

It should be `action_text` as picked up here:

https://github.com/BirkbeckCTP/janeway/blob/e8176e51c8847744ca80be19c642bdfd2402c5d2/src/utils/notify_plugins/email_log.py#L22

**Comment by ajrbyers** [comment]
- [ ] @joemull  open new issue to convert log_dict text to constants
