### ISSUE TITLE
NotSupportedError in decision helper -> share on mysql

### ISSUE THREAD

**Issue by everreau** [BirkbeckCTP/janeway#3849]
**Describe the bug**
When a users select "Share" from the decision helper page we get  "NotSupportedError - DISTINCT ON fields is not supported by this database backend".  We are running mysql.

https://github.com/eScholarship/janeway/blob/master/src/review/views.py#L2847

**Janeway version**
1.5.1-RC3

**To Reproduce**
1. Go to an article in review
2. Click on "Make a decision"
3. Click on "Share reviews"
4. See error (if you're using mysql)

**Expected behavior**
No error.

**Comment by mauromsl** [comment]
Closed by #3876 on b_1_5_1
