### ISSUE TITLE
EmailForm is duplicated

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3865]
**Describe the bug**
There are two definitions of EmailForm in core forms.

It looks like this one needs to go:

https://github.com/BirkbeckCTP/janeway/blob/63d32009f60bf815edb629815b26f3156f31d0e2/src/core/forms/forms.py#L676-L697

**Janeway version**
63d32009f60bf815edb629815b26f3156f31d0e2

**Comment by ajrbyers** [comment]
PR for this has been merged.
