### ISSUE TITLE
Email context passed as message content

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3866]
Something is wrong here:

https://github.com/BirkbeckCTP/janeway/blob/195da20fa7c4990fb73b0ac809ac56c6493ef874/src/review/logic.py#L704

We also got an email from a user saying they'd received this as the body of an email:

> {'article': , 'editor': , 'assignment': , 'review_in_review_url':
> 'https://olh.openlibhums.org/review/article/15098/'}
> Open Library of Humanities

I think the two are related.

Janeway version: 63d32009f60bf815edb629815b26f3156f31d0e2

**Comment by joemull** [comment]
I've put up some work in progress on this, but it is extremely thorny in this function chain, so a more comprehensive refactor may be called for. Importing forms into logic is also causing problems.

**Comment by mauromsl** [comment]
closed by #3882
