### ISSUE TITLE
File attachment does not get delivered when emailing an author directly, entire message missing from logs

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#3873]
**Describe the bug**
When you click the letter icon next to an author on one of the metadata screens, you can send an email with an attachment, but the attachment does not get delivered. The message is also not recorded in the logs.

**Janeway version**
1.5.1 RC3

**To Reproduce**
1. From the Review stage of an article, click 'View Metadata'
2. In the Authors section, click the envelope icon next to an author to send a message
3. Compose a message and include a file attachment, send.
4. Email will be received by the author, but the attached file will be missing and the message will not appear in the logs.

**Expected behavior**
Email attachment gets delivered as expected.

**Additional context**
Similar issue that has been resolved #3732

**Comment by mauromsl** [comment]
Closed by #3873
