### ISSUE TITLE
Repository search exposes results from other Press Repositories 

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#3877]
**Describe the bug**
When a Janeway Press hosts more than one Repository, search in Repository A exposes results from Repository B. If a user clicks on a result from Repository B, they will encounter an error. 

**Janeway version**
1.5.1 RC1

**To Reproduce**
Steps to reproduce: 
1. Go to ``https://eartharxiv.org``
2. Search for an author of an EcoEvoRxiv preprint, eg ``https://eartharxiv.org/repository/search/Julia%20Stewart%20Lowndes/`` 
3. Scroll to the result and click the link ``https://eartharxiv.org/repository/view/5449/``
![image](https://github.com/BirkbeckCTP/janeway/assets/15632391/a3f4950e-6f2d-424f-9eec-649b2cb1d683)
5. See error: 
![image](https://github.com/BirkbeckCTP/janeway/assets/15632391/91cce0ee-38ef-492d-a8b2-194ab2b4aed5)

**Expected behavior**
1. Results from Repository B would not be exposed in Repository A 
2. If a user for some reason accesses a preprint ID for Repository B while in Repository A, they should be shown a page with a relevant message, such as "Preprint ``[ID]`` does not belong to ``[Repository A name]``. To access, go to: ``[Repository B URL]/repository/view/[ID]``. You will be automatically directed there in 10 seconds, or you can click the link to be taken there immediately". 

**Additional context**
This seems to only occur when searching by author name. Searches of preprint titles (eg title of EER preprint ``https://doi.org/10.32942/osf.io/d5rqh``: ``https://eartharxiv.org/repository/search/Online%20conferences%20for%20better%20learning/``) do not expose.

**Comment by mauromsl** [comment]
closed by #3879
