### ISSUE TITLE
Default sorting of journal articles is incorrect

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#3883]
**Describe the bug**
In 1.5.1 we introduced a new class based view for the article page. When viewing the page without any set filters/sorting the articles are not in newest order, as they should be in this view.

**Janeway version**
1.5.1

**To Reproduce**
1. Open any journal
2. Go to the Articles page
3. Sort will show Newest, articles are not in newest order

**Expected behavior**
The articles page should always, by default, show the newest articles.

**Comment by mauromsl** [comment]
closed by #3884
