### ISSUE TITLE
Review form preview shows some incorrect elements

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#3888]
**Describe the bug**
There is a section at the very bottom about comments to the editor, a box that can be checked to make the comments public, and a statement "This journal has a policy of sharing reviews openly alongside the published article to aid transparency. If you give permisson here and the article is published, your name and review will be visible

**Janeway version**
1.5.1-RC-4

**Expected behavior**
This section should only display when the OPR settings are enabled.

**Comment by mauromsl** [comment]
Closed by #3889
