### ISSUE TITLE
Titles with quote marks have quoted section removed

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#3896]
**Janeway version**
1.5.1

**To Reproduce**
1. Add a quoted section to a title eg This is "my" title
2. "my" will be deleted

**Expected behavior**
This should not be deleted

**Screenshots**

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mauromsl** [comment]
closed by #3983
