### ISSUE TITLE
Searches starting with a blank space result in practically everything published

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#3897]
**Describe the bug**
When a search of Janeway begins with a blank space, the resulting hit count is unexpectedly high, seemingly almost everything published.

**Janeway version**
1.5.1 RC1 (Repository confirmed, possibly journals also)

**To Reproduce**
1. Search Janeway for a published article title, starting the search with a space. Note the hit count. For example, this search of EarthArXiv for "High-resolution methane mapping with the EnMAP" begins with a space and results in 3933 hits: ``https://eartharxiv.org/repository/search/%20High-resolution%20methane%20mapping%20with%20the%20EnMAP/``(at the time, there were 4335 items published)
2. Compare remove the starting space and compare. For example,  this search results in 3933 hits: ``https://eartharxiv.org/repository/search/High-resolution%20methane%20mapping%20with%20the%20EnMAP/`` (note: adding a trailing space at the end does not change the result count.)

**Expected behavior**
The initial space would be ignored. 

**Screenshot**
![attachment](https://github.com/BirkbeckCTP/janeway/assets/15632391/e8263669-7a34-47d3-8cfa-774e5649f136)

**Comment by ajrbyers** [comment]
To be fair… most titles and abstracts contain spaces… but yes we should strip white space 🤣
