### ISSUE TITLE
Spontaneous bilingualism (wrong language showing)

### ISSUE THREAD

**Issue by S-Haime** [BirkbeckCTP/janeway#3898]
Reported through Freshdesk:

"There’s just a (small but) really weird thing going on: wherever the issue information about appears on the DES site, we’re currently seeing what we think is the French wording (Volume 1 - Numéro 1) regardless of which language we’ve selected. Yesterday, however, the English version was correctly showing up as ‘Volume 1 - Issue 1’. This bug seems to come and go: I was definitely seeing this particular French wording in the English interface previously, before it corrected itself, and now it’s back."

1.5.0

**To Reproduce**
Go to: https://digitalenlightenmentstudies.org/issues/ (language: English)
 It may show:

![image](https://github.com/BirkbeckCTP/janeway/assets/148049561/dbe54e61-4713-4e95-9376-8b7744a2238a)

**Comment by ajrbyers** [comment]
There is a fix in 1.5.1 for this so it will be fixed shortly.
