### ISSUE TITLE
Installation fails on CentOS

### ISSUE THREAD

**Issue by LukeGaudreau** [BirkbeckCTP/janeway#391]
I managed to install the requirements for janeway on CentOS, but I'm getting an error during installation:

```
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/luke/janeway/src/core/models.py", line 34, in <module>
    from submission import models as submission_models
  File "/home/luke/janeway/src/submission/models.py", line 25, in <module>
    from core import models as core_models
  ImportError: cannot import name 'models'
```
Is it possible there's a dependency missing from requirements.txt?

**Comment by ajrbyers** [comment]
This doesn't look like a missing dependency, its trying to import the models module from inside core (ie. src/core/models.py) which seems very odd. I've never used CentOS, can you fire over the steps you used to install the requirements and the version of CentOS so I can take a look?

**Comment by ajrbyers** [comment]
@LukeGaudreau which version of Python are you using here?

**Comment by LukeGaudreau** [comment]
```
python --version
Python 3.4.5
```

**Installation Steps**
1. Install python, pip3, and virtualenvwrapper:
`yum install python34-virtualenv python34-pip python34-devel virtualenvwrapper`
2. Create a project
```
source /usr/bin/virtualenvwrapper.sh
mkvirtualenv janeway -p /usr/bin/python3 --no-site-packages
```
without `--no-site-packages`, pip tries to install packages to system site packages directory
3. Install system dependencies:
`yum install libxml2-devel libxslt-devel python-devel libffi-devel libssl-devel libjpeg-devel libmysqlclient-devel mariadb-devel git gcc-c++ mariadb-server`
clone the git repository and
`pip install -r requirements.txt`

**Comment by ajrbyers** [comment]
Yeah - this is a circular import that is supported by 3.5 but is breaking in 3.4.

I'm checking this out now.

**Comment by ajrbyers** [comment]
I've fixed the circular import on master, see commit above so if you do a pull on the master branch install should run. That said, I'd recommend using python 3.5!

**Comment by LukeGaudreau** [comment]
Thanks! That did allow me to complete the installation. However, it looks like there's at least one additional occurrence of this problem:
```
File "/home/luke/janeway/src/press/models.py", line 16, in <module>
    from core import models as core_models
ImportError: cannot import name 'models'
```

At the moment, we're evaluating janeway alongside several other platforms (currently using OJS 2). I should be able to use 3.5 in production, but it's not part of the standard CentOS/RHEL repos unfortunately.

**Comment by ajrbyers** [comment]
Hi @LukeGaudreau,

I can't replicate the error you're reporting there. If I use python 3.4.5 I can import press.models without any errors:
```
(jwp34) ajrbyers@Arnor:~/Code/janeway/src$ python3 manage.py shell
Python 3.4.5 (default, Jul 15 2016, 16:39:07) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from press import models
```
Can I invite you to our slack channel so we can chat about it?

**Comment by LukeGaudreau** [comment]
sure thing. Please use gaudreal at bc [dot] edu.

**Comment by ajrbyers** [comment]
Invite sent!

**Comment by ajrbyers** [comment]
I've updated the readme to show that 3.5+ is required and will open an issue to restore support for 3.4 in the future.
