### ISSUE TITLE
container element is empty

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/janeway#3911]
Some lists where there are no list elements are being put out as empty containers, rather than being skipped when there are no list elements to include.

example at https://www.iastatedigitalpress.com/iscore/article/id/12400/
with empty download and jump to lists. 

More generally, we need to review how our lists are populated such that if there are no list items we don't insert an empty list.  While this may not be visible, it will be picked up by screen-readers.

**Comment by ajrbyers** [comment]
AB and SD: Likely caused by a forloop without a {% if %} check.

**Comment by StephDriver** [comment]
was closed by #4293
