### ISSUE TITLE
New email template - article into review

### ISSUE THREAD

**Issue by S-Haime** [BirkbeckCTP/janeway#3920]
[Requested through FD #7752 - UGent]

A new email + template has been requested. This email would inform editors when their manuscript moves into the review stage.
Currently, authors are only informed about rejection-status, but not if their paper will enter review. This leads to requests for status updates. An automated email that is send upon this movement between workflow stages would be beneficial.

**Comment by ajrbyers** [comment]
Thanks @S-Haime, there is an issue for this already: https://github.com/BirkbeckCTP/janeway/issues/3409
