### ISSUE TITLE
Ordering unassigned articles

### ISSUE THREAD

**Issue by S-Haime** [BirkbeckCTP/janeway#3926]
Suggestion: Could the way in which unassigned articles are ordered be customisable? A user indicated this would be a quality of life improvement with how they process articles.

(Based on FD ticket 7774:P
"At present, the Unassigned Articles are ordered alphabetically for article title. I'd prefer an ordering on the basis of submission date (since I typically look to work on submissions in the order that they arrived). Is it possible to change this (or to add multiple ways to sort)?" )

**Comment by justingonder** [comment]
We would also like the ability to sort items on the Unassigned page, similar to how they can be sorted on all of the other pages that list articles.
