### ISSUE TITLE
Not possible to skip e-mail for editor assignment

### ISSUE THREAD

**Issue by S-Haime** [BirkbeckCTP/janeway#3927]
(Reported through FD 7773):

"When I assign an editor (e.g., myself) and select "Skip & continue" for the associated e-mail, the e-mail still gets sent... Is there a way to prevent the sending of the e-mail?"

**Janeway version**
1.5.1.

**Comment by ajrbyers** [comment]
THere is a PR for this already. Will be in the RC-5 deployment.
