### ISSUE TITLE
Changing default citation

### ISSUE THREAD

**Issue by Sebkrau** [BirkbeckCTP/janeway#3951]
**Is your feature request related to a problem? Please describe.**
A journal forwarded a feature request to us, that we found could be quite helpful.

**Describe the solution you'd like**
Can there be an option of changing the default citation janeway gives or generates per journal? That would make less copy pasting and therefore less man made mistakes possible. 

**Describe alternatives you've considered**
This could be either various options to chose from, which you can enable/disable in the backend or one standard citation that can be changed at any time.

**Comment by ajrbyers** [comment]
There is already an issue open that covers this: https://github.com/BirkbeckCTP/janeway/issues/1666

Closing this one.
