### ISSUE TITLE
"Skip" button on various notification emails not working

### ISSUE THREAD

**Issue by everreau** [BirkbeckCTP/janeway#3975]
**Describe the bug**
When users choose to "skip" a notification they are sent an email anyway.  We have observed it with both cancelling review requests and assigning editors.  It may apply to others as well. It appears that the "skip" value is not passed properly into the event.

**Janeway version**
1.5.1RC3

**To Reproduce**
1. Navigate to an "Unassigned" article
2. Click on "Add" next to one of the editors
3. Click "Skip & continue"
4. Email is sent anyway

**Expected behavior**
Emails not sent if notification is skipped.

**Comment by ajrbyers** [comment]
Thanks for this @everreau, this PR includes a fix for this: https://github.com/BirkbeckCTP/janeway/pull/3882/files

**Comment by ajrbyers** [comment]
(It’s in RC5)
