### ISSUE TITLE
Error Check on ORCID Entry for User Profile

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#3989]
**Is your feature request related to a problem? Please describe.**
orcid field accepts non-orcid ids when creating users or editing users.

**Describe the solution you'd like**
something in the form that checks that the orcid id is valid and then requires the user to enter a proper ID.
i know you have the help text in the model that states
`"format (e.g: 0000-0000-0000-000X)"`
but we still have editors adding people as "https://orcid.org/0000..."

**Describe alternatives you've considered**
sitting the users down and giving them a stern talking to about the importance of reading instructions and help text.

**Additional context**
this is nto high-priority

**Comment by ajrbyers** [comment]
Thanks @hachacha, can you let me know which version this occurs on? We added some ORCID validation recently.

**Comment by hachacha** [comment]
currently on 
v1.5.0-RC-6, 70e0ebd11ce05173d5b36639f77cd60849af32c4
it may be the case that these authors were added before the upgrade if the validation has been added in this version.

**Comment by ajrbyers** [comment]
> currently on v1.5.0-RC-6, [70e0ebd](https://github.com/BirkbeckCTP/janeway/commit/70e0ebd11ce05173d5b36639f77cd60849af32c4) it may be the case that these authors were added before the upgrade if the validation has been added in this version.

I'm going to mark this one as closed - do let me know if you think someone worked a way around this!

**Comment by hachacha** [comment]
@ajrbyers 
We tried pushing some articles to the DOAJ using the transporter and ran into an issue of malformed ORCIDs.
Looking at the accounts we found that they had "http://" in the string instead of just the ID string

I went and tested on our dev to be certain and found that you can enter in just whatever if you are on the /JOURNAL/profile/ page. Please reference the screenshot.
This test was done on a different version than when this issue was opened:
1cbf646f0d3fafce301e6401cf68f0628dc11308

<img width="433" height="115" alt="Image" src="https://github.com/user-attachments/assets/e8060c4a-13f1-461e-b683-d88026610767" />
