### ISSUE TITLE
Clean theme template issues

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#4004]
**Describe the bug**
The clean theme presents a couple of issues that are affecting live services:

1. The press nav has various links that are not closed properly
2. The journal submissions page has a series of if/else/endif sections that are not closed properly

**Janeway version**
1.5.1-RC-5

**To Reproduce**
1. Go to a press with the clean theme enabled, ensure you're logged out
2. Go to a journal submission page with the clean theme enabled

**Expected behavior**
These pages should render as normal

**Comment by mauromsl** [comment]
closed by #4003
