### ISSUE TITLE
name '_' is not defined in submission.logic

### ISSUE THREAD

**Issue by everreau** [BirkbeckCTP/janeway#4016]
**Describe the bug**
`_` is referenced in `check_file` method of submission.logic but not imported. An error is triggered on manuscript file submission when `limit_manuscript_types` is enabled.

**Janeway version**
1.5.1RC5 (also tested on master)

**To Reproduce**
1. Enable `limit_manuscript_types` setting for the given journal
2. Start a submission up to manuscript file submission step
3. Upload a PDF to manuscript files

**Expected behavior**
This should produce a form error instead of a server/name error.

I think `from django.utils.translation import gettext, gettext_lazy as _` should be imported here. I can submit a PR if you want.

**Comment by mauromsl** [comment]
closed by 854aaa9f3e52c962b505db8cb278cd7bc29e8fa4
