### ISSUE TITLE
Meta image not displaying for repositories on Bluesky

### ISSUE THREAD

**Issue by S-Haime** [BirkbeckCTP/janeway#4041]
**Describe the bug**
There is a bug in Bluesky where the phrase "Janeway-Logo-Final" is shown in the snippet from the article title: https://bsky.app/profile/inggrid.bsky.social/post/3knkxvnk4mk2w:

![image](https://github.com/BirkbeckCTP/janeway/assets/148049561/cbdc0ba6-4cf0-40bc-a73d-9ee4539d9f90)

Reported through FD (ULBD) 8035.

**Comment by mauromsl** [comment]
I believe this is actually a bug with the preview on bluesky, it is picking up the title inside the Janeway SVG logo from the footer and appending it to the `<title>` inside the `<head>`.

An HTML document should only have a a single `<title>` element, however for accessibility purposes, it is also recommended that the `<svg>` elements also include a `<title>`. In any case, the W3C validator is accepting our title on the `<svg>`

I tested the preview on other platforms and it wasn't picking up the title, so I'm inclined to say it is a bug on bluesky and going to close this. Perhaps worth raising an issue on https://github.com/bluesky-social/social-app @S-Haime ?

**Comment by S-Haime** [comment]
@mauromsl I'll raise an issue there. Interesting :)!
