### ISSUE TITLE
Revision Request Notes Not Saving as of 1.5.1

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#4088]
**Describe the bug**
When editors enter text into the Editor Note field on the Request Revisions page:
<img width="567" alt="2024-04-10_13-19-40" src="https://github.com/BirkbeckCTP/janeway/assets/29953714/85d05673-b1a5-4bd7-b534-37ed026eb7cf">

The text of the note is not present in the email sent to the author:
<img width="752" alt="2024-04-10_13-19-51" src="https://github.com/BirkbeckCTP/janeway/assets/29953714/491b7dbf-dd68-49c1-92aa-2ad42b366ba3">

Nor on the Revision Request Details page:
<img width="1370" alt="2024-04-10_13-23-30" src="https://github.com/BirkbeckCTP/janeway/assets/29953714/3f952a1d-c9fc-4910-94ee-0677cb74a473">

**Janeway version**
Our users began noticing this data loss when we rolled out 1.5.1 RC6
Have confirmed the behavior is the same in 1.5.1 final as well.

**Comment by joemull** [comment]
Thanks @justingonder. I'm looking into this now.

**Comment by joemull** [comment]
One more update: I've reviewed all the templates that could theoretically be affected by this and narrowed it down to just one additional problem template:

```
src/templates/admin/review/draft_decision.html
```

You don't use the Draft Decisions feature at CDL, do you? If not, this shouldn't affect you.

So, what you can do for the time being in production is switch the branch `4088-jqte-hotfix`, which is one commit ahead of the pinned v1.5.1. All it does is drop the offending line that breaks the Request Revisions form.

In terms of Janeway versions and pins, we have already pinned the final version of 1.5.1, and haven't yet sped up our semantic versioning to make better use of the small numbers, we will need to figure out how to solve the pinning/versioning question next week. Once Mauro is back online we will follow up.
