### ISSUE TITLE
migrated login warning wording typo

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/janeway#4105]
**Describe the bug**
grammar / typo on log in page for recently migrated journals.
https://olh.openlibhums.org/login/?next=/submit/start/

**Actual**
> ... required to use set a new password ....

**Expected**
>  ... required to set a new password ....

**Screenshots**
<img width="976" alt="image" src="https://github.com/BirkbeckCTP/janeway/assets/5330770/1dccd2e4-5a63-4516-a9ac-b1c604f85616">

**Additional Context**
Found on OLJH having followed the "Submit a Manuscript" button from Science Open as in screenshot below:
https://www.scienceopen.com/collection/a53f0add-5934-4b04-bff1-ca5e7295510b
<img width="707" alt="image" src="https://github.com/BirkbeckCTP/janeway/assets/5330770/0bd2ddd4-f658-44cf-a498-44cf0c73eec2">

**Comment by StephDriver** [comment]
This is a typo in the user-defined content - i.e. in the journal settings.  As it is OLHJ assigning this to @severett89 .

**Comment by StephDriver** [comment]
further, As OLHJ migrated some time ago, please consider whether this warning is needed at all.

**Comment by severett89** [comment]
I've changed it to: 
If you have already signed up to the journal with an account but are experiencing problems logging in, you may need to reset your password via the [Password Reset](https://olh.openlibhums.org/reset/step/1/) page. Please follow the steps to do this and check your nominated email account for verification. This should solve any login issues, however if issues persist please contact support at [support@janeway.freshdesk.com](mailto:support@janeway.freshdesk.com).
