### ISSUE TITLE
Exporting all articles - metadata field issue

### ISSUE THREAD

**Issue by S-Haime** [BirkbeckCTP/janeway#4109]
**Describe the bug**
There is an issue with the metadata fields, where a field has been deleted but the answer is still stored. This causes an error when trying to do an export, making it impossible to export metadata. If the answer was stored so that it contains the question itself, rather than the linked object this might resolve the issue. Additionally, this shouldn't be killing the export even if an answer is not found.

**Janeway version**
The version of Janeway under which the bug has been reproduced.
If running off of master, please, indicate the current HEAD of the Janeway installation

**To Reproduce**
1. https://jcls.io/plugins/imports/articles/all/
2. Export all or Export CSV.

**Additional context**
Reported by jcls (ULB) FD 8101

**Comment by joemull** [comment]
Backlog refinement: We can do a quick-fix by adding a try / except check around the code that gets custom fields.

Longer term we might want to make sure answers are deleted when the question is deleted. Maybe, maybe not. What does it mean to delete a submission field? Need to discuss further.

**Comment by joemull** [comment]
@S-Haime could we copy and paste this over to BirkbeckCTP/imports?

**Comment by S-Haime** [comment]
@joemull Done. Also added to 'need investigation', can I close this issue?
