### ISSUE TITLE
Failover server setup

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#414]
Recent Digital Ocean block storage outage has shown vulnerability in key OLH systems. 

Suggested mitigation plan:

1. Register second Reclaim account in different European region (must be in EU to comply with GDPR).
2. Register VPS as transparent SSL proxy.
3. Setup MySQL master-slave replication between Reclaim accounts.
4. Setup unison bidirectional replication between Reclaim accounts. (Will need to place unison binary on servers. MPE can advise on configuration. Cron job or similar to run this: one direction on the hour, the other direction on the half hour.)
5. Setup rsync unidirectional transfer of "ssl" folder in home directory from master -> slave to replicate on daily basis.
6. Implement interface on VPS that allows easy switch of server for passthrough.
7. Implement automatic downtime check on VPS that implements automatic switch on failure.
8. Implement way of testing system on a monthly basis.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
