### ISSUE TITLE
Non-staff able to assign Journal Manager role

### ISSUE THREAD

**Issue by justingonder** [BirkbeckCTP/janeway#4141]
**Describe the bug**
[Only users with Is Staff permission](https://github.com/BirkbeckCTP/janeway/pull/3464) are supposed to be able to assign the Journal Manager role to other users, but in a recent test with a non-staff Editor role account I was able to assign the Journal Manager role to other users. We've also seen other users of our system mass-enrolling Journal Managers when they do not have the Is Staff flag set.

**Janeway version**
1.5.1

**To Reproduce**
1. Log in to a journal with an account that is not staff, admin or superuser, but has the Editor role
2. Navigate to Staff > Manager > Enrol Users
3. Assign Journal Manager role to any other account. You will be able to do so successfully even though you should not be able to.

**Comment by mauromsl** [comment]
Thanks for the report @justingonder , we've discussed this in the team and we've decided to add a patch for v.1.5 (v.1.5.3) to include a short term hotfix, where only staff users can grant the journal manager role.

We have also raised an issue for implementing a role hierarchy system that can be used for the account management area but also for any other areas with competing responsibilities between editors and journal managers.

**Comment by mauromsl** [comment]
bug closed by hotfix in #4143 which is part of https://github.com/BirkbeckCTP/janeway/releases/tag/v1.5.3
Longer term solution recorded in #4142
