### ISSUE TITLE
Review assignments should be closed if an article is rejected

### ISSUE THREAD

**Issue by everreau** [BirkbeckCTP/janeway#4251]
**Describe the bug**
When an article is published any unresolved review assignments are marked as closed. However, the same is not done when an article is rejected.  This ultimately throws off reviewer stats so it looks like reviewers have many additional open reviews.

**Janeway version**
1.5.3

**To Reproduce**
1. Open a review assignment on an in process article
2. Reject the article
3. Note status of review assignment doesn't change

**Expected behavior**
We talked to Andy about this issue a few weeks ago he said that the review assignments should be marked as withdrawn and there should be a callout on the send email page saying so.

**Comment by everreau** [comment]
I plan to submit a PR for this issue as soon as I get to it just making an issue to attach it to.

**Comment by ajrbyers** [comment]
> I plan to submit a PR for this issue as soon as I get to it just making an issue to attach it to.

Awesome, thanks.
