### ISSUE TITLE
HTML entities in bleached settings are not all rendered properly

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#4258]
## User story
I might use an ampersand in the title of my journal:
![Screenshot from 2024-06-06 14-34-49](https://github.com/BirkbeckCTP/janeway/assets/47217308/093d9521-299a-47a4-9dec-02c27107072e)

But it is converted to an entity and not displayed properly on save:

![Screenshot from 2024-06-06 14-35-09](https://github.com/BirkbeckCTP/janeway/assets/47217308/5adc1231-ab58-4f46-815c-03b79544669a)

![Screenshot from 2024-06-06 14-37-40](https://github.com/BirkbeckCTP/janeway/assets/47217308/0cddd29a-2f55-4bd2-8375-d327c1fee2fe)
![Screenshot from 2024-06-06 14-36-29](https://github.com/BirkbeckCTP/janeway/assets/47217308/97ef6096-227a-48f4-aed1-e04730827d67)

Angle brackets are also transformed:
![Screenshot from 2024-06-06 14-46-09](https://github.com/BirkbeckCTP/janeway/assets/47217308/4669f0b9-3f27-4f06-acdc-061be0f40387)

![image](https://github.com/BirkbeckCTP/janeway/assets/47217308/55cdd4fc-69c9-4800-92f9-56b94436102f)

But other [commonly escaped characters](https://developer.mozilla.org/en-US/docs/Glossary/Entity) are left alone:

![Screenshot from 2024-06-06 14-48-32](https://github.com/BirkbeckCTP/janeway/assets/47217308/a58b5b2e-54f3-4a8f-8c90-170079abaa90)
![Screenshot from 2024-06-06 14-48-49](https://github.com/BirkbeckCTP/janeway/assets/47217308/d7a76252-b220-4bbe-8391-cada3f3922ab)

Downstream, ampersands may also be an issue, but many systems could probably handle them:
https://community.crossref.org/t/html-entities-in-journal-titles/3061/2

## Janeway version
1.5.5

**Comment by mauromsl** [comment]
closed by merging #4267 and https://github.com/BirkbeckCTP/typesetting/pull/211
