### ISSUE TITLE
Issue.manage_issue_list returns not valid data

### ISSUE THREAD

**Issue by yakky** [BirkbeckCTP/janeway#4277]
**Describe the bug**

`Issue.manage_issue_list` returns a mix of `Article` and `ArticleOrdering` objects

**Janeway version**

1.5.5 (but code is unchanged on 1.6 / HEAD)

**To Reproduce**

- Create an `Issue`
- Create sections for such issue
- Assign `Article` to `Issue` and customize the order using http://localhost:8000/manage/issues/<issue.pk>/
- Call `Issue.objects.get(pk=<issue.pk>).manage_issue_list()`
- Returned dictionary values has a mix of `Article` and `ArticleOrdering` objects

**Expected behavior**

The returned dictionary values contains `Article` instances only

**Comment by ajrbyers** [comment]
I wonder if we should consider deprecating this method. We don't use it on the manage issues interface other than to count articles and this could be done by counting Issue's article set.

**Comment by yakky** [comment]
I can add a deprecation warning to the method, maybe? it's worth fixing it as long as it exists

Does something equivalent exists if one wants the list of articles divided by section?
