### ISSUE TITLE
C21 list of articles ordered by newest first not working

### ISSUE THREAD

**Issue by the-blochian** [BirkbeckCTP/janeway#4333]
Hi,

The OLH journal C21's Articles page doesn't list articles in order of most recent / newest at the top. [https://c21.openlibhums.org/articles/]. 

Even if you try different sort by newest, sort by oldest, sort by A-Z etc. nothing happens. To the best of my knowledge it hasn't in the past 2-3 years I've been involved with the journal. It's frustrating that people can't find our recently published articles, without digging into the specific issues pages.

Can this be fixed? Thank you :)

**Comment by ajrbyers** [comment]
@the-blochian is is possible the first two articles are pinned? The rest of the list sorts properly.

**Comment by the-blochian** [comment]
Oh possibly - how would I go about unpinning them, in that case?

**Comment by ajrbyers** [comment]
> Oh possibly - how would I go about unpinning them, in that case?

https://c21.openlibhums.org/manager/articles/pinned/
