### ISSUE TITLE
Repository: custom fields help box WYSIWYG input not formatted in output, displays HTML tags

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#4375]
**Describe the bug**
Since the WYSIWYG editor was introduced, new added or edit custom fields have exposed HTML. In addition, any HTML formatting used to create the custom fields' help text is not applied as expected. 

**Janeway version**
1.5.6

**To Reproduce**
1. In Repository manager, add a new custom field and input help text. Do not use any formatting, but also do not use the "clear formatting" option. Save. 
2. Add a second custom field and input help text. Add some light formatting, such as bold and some line breaks. Save.
4. Add a third custom field and input help text. Before saving, select 
5. Start a new submission, scroll to new custom fields. 
6. Note the exposed HTML in all custom fields.

**Expected behavior**
Custom field help box reflects the formatted (or non-formatted) text as generated by WYSIWYG editor. 

**Screenshots**
In the below screenshot, the first custom field has not yet been edited since upgrading to the latest Janeway release (1.5.6).
![image](https://github.com/user-attachments/assets/39d22a35-7b16-46e7-9e29-208423dec104)

Comparing third custom field with the settings in Repository Manager view: 
![image](https://github.com/user-attachments/assets/8d2c8027-8da8-4444-a711-d2d0993fbbcc)

**Comment by ajrbyers** [comment]
This has been reverted in the next release. It shouldn’t be an HTML element.
