### ISSUE TITLE
Reverse Match Problems with 1.3-alpha

### ISSUE THREAD

**Issue by hackman104** [BirkbeckCTP/janeway#455]
We're seeing similar errors with several sites. Here is an example of the type of error we get:

NoReverseMatch at /cmsh/manager/settings/group/general/setting/publication_fees/
Reverse for ‘django_summernote-upload_attachment’ with keyword arguments ’{’journal_code’: ‘cmsh’}' not found. 1 pattern(s) tried: [‘summernote/upload_attachment/$’]
Request Method:    GET
Request URL:    http://dc-vm2-rhel.andrew.cmu.edu/cmsh/manager/settings/group/general/setting/publication_fees/
Django Version:    1.11.5
Exception Type:    NoReverseMatch
Exception Value:    
Reverse for ‘django_summernote-upload_attachment’ with keyword arguments ’{’journal_code’: ‘cmsh’}' not found. 1 pattern(s) tried: [‘summernote/upload_attachment/$‘]
Exception Location:    /usr/src/cmesh_env/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497

**Comment by ajrbyers** [comment]
hey @hackman104 this should fix the bug you saw!
