### ISSUE TITLE
Strange Link Redirect from Submission Pages

### ISSUE THREAD

**Issue by hackman104** [BirkbeckCTP/janeway#463]
When a journal user is working on the submission process, the name of the journal appears at the top of the page as a link. When the user clicks this link, though, it jumps them all the way back to the overall press homepage, not the journal homepage. (Our instance is configured to use "path"). I was able to fix this issue by going to templates/admin/core/nav.html and changing to <a href="{% url 'website_index' %}">.

**Comment by ajrbyers** [comment]
1.3 and Master have been cross merged.
