### ISSUE TITLE
Links in Email Templates Broken

### ISSUE THREAD

**Issue by hackman104** [BirkbeckCTP/janeway#465]
When using janeway with URL_CONFIG = "path", the links in many of the email templates (such as those generated for new user registration or password reset) don't work. They produce something along the lines of http://dc-vm2-rhel.andrew.cmu.edu/cmsh:80/cmsh/register/step/2/token (where token is the token string). Both {{ request.journal_base_url }} and {% url 'core_confirm_account' user.confirmation_code %} seem to include the journal code cmsh, so it ends up duplicated (with request.journal_base_url including the port as well). When I change {{ request.journal_base_url }} to {{ request.press.domain }} it fixes the problem for us.

**Comment by ajrbyers** [comment]
I have update the full_url function (650c6139370bc6f40099156b437611136c3ecf30) on master, will look to get these onto 1.3-alpha shortly.
