### ISSUE TITLE
Privacy Policy link is broken in path based urls

### ISSUE THREAD

**Issue by danieljohnevans** [BirkbeckCTP/janeway#466]
Created new privacy policy page but get 404 error : http://dc-vm2-rhel.andrew.cmu.edu/site/privacy/

Actual correct link is : http://dc-vm2-rhel.andrew.cmu.edu/CMSH/site/privacy/ 

Could point to larger problem with page creation?

**Comment by ajrbyers** [comment]
Don't think this is page creation, probably a hard coded link in footer.html

**Comment by hackman104** [comment]
In core/base.html there is a footer tag, and the privacy policy is linked as <a href="/site/privacy">. I changed it to <a href="{% url 'cms_page' "privacy" %}"> and it finds the page.
