### ISSUE TITLE
HTML Galleys

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#473]
We should strip any CSS links or <style> tags from HTML galleys.

**Comment by MartinPaulEve** [comment]
Though this is one the few useful things we can do with an HTML document. Perhaps add the capacity to inject custom stylesheets?

**Comment by ajrbyers** [comment]
@MartinPaulEve this feature is already available :)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
