### ISSUE TITLE
Article moved into copyediting and back into review closes active reviews

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#486]

**Comment by ajrbyers** [comment]
@MartinPaulEve its the process of moving an article into copyediting the closes the reviews... which would be expected behaviour, we dont want open reviews for an article thats moved onto a new stage?

**Comment by MartinPaulEve** [comment]
Yes, I guess. The problem here was that an article was accidentally put into copyediting instead of review on import, I think. Reviewers still thought they were supposed to do the work but then had nowhere to put it...
