### ISSUE TITLE
Skip Core Workflow

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#493]
- Allow an Editor to skip a Core workflow element like Copy editing already has.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by joemull** [comment]
@ajrbyers can you point me to the thing you're referring to when you say "like Copy editing already has"?

**Comment by ajrbyers** [comment]
I think its just that you can click Complete right away without doing anything.

**Comment by joemull** [comment]
After discussing this we narrowed it down to an old issue with Production and Proofing, which we also ruled out by putting an article through those elements.

There are some similar issues in Review, but we are handling those in #3051.
