### ISSUE TITLE
Need a cron cleanup job for dashboard tasks

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#496]
If migrating from a previous version of Janeway, it is possible for tasks to be in an inconsistent state (i.e. proofreading tasks open for articles that are published).

We should probably have a periodic task that checks this and clears things up. Or as part of the migration process or a management command. To discuss on slack.

**Comment by MartinPaulEve** [comment]
To be tested and cleaned up as part of upgrade and fixed if there's a recurrence

**Comment by ajrbyers** [comment]
Cant see that this has reoccurred...
