### ISSUE TITLE
‘foundation’ is not a registered tag library bug

### ISSUE THREAD

**Issue by jeffpooley** [BirkbeckCTP/janeway#502]
[Apologies in advance - I am new to issuing tickets]

The following error appears on much of the Janeway backend (1.2.4 installed on ubuntu 16 server):

~~~~
TemplateSyntaxError at /manager/settings/journal/
'foundation' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
article
bool_fa
bootstrap4
cache
dict
field
files
fqdn
hooks
humanize
i18n
l10n
log
markdown_deux_tags
materialize
pathurl
press_url
raven
recaptcha2
rest_framework
roles
securitytags
settings
static
staticfiles
text
truncate
tz
utils_forms
~~~~

Here is a list of pages that cannot be accessed:

* Journal Home Settings
* Journal Settings
* Review Settings
* Review Forms
* Submission Settings
* Additional Submission Fields
* News Manager
* Journal Contacts
* Editorial Team
* Articles Image Manger
* Issue Manager
* Article Sections
* License Manager
* CrossRef Settings
* CrossCheck Settings
* Publication Schedule
* Articles
* Issues

**Comment by ajrbyers** [comment]
Hi Jeff,

I can see foundationform in requirements.py and I can see it in example_settings.py also, can you check your settings.py INSTALLED_APPS list is the same as example_settings.py?

**Comment by ajrbyers** [comment]
FYI it should be:

`'foundationform',`

**Comment by jeffpooley** [comment]
The INSTALLED APPS are identical in example_settings.py and settings.py, and do not include ‘foudnationform’

~~~~
INSTALLED_APPS = [
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.sites',
'django.contrib.humanize',

# Installed Apps
'cms',
'core',
'copyediting',
'cron',
'events',
'identifiers',
'journal',
'metrics',
'comms',
'preprint',
'press',
'production',
'proofing',
'review',
'reports',
'security',
'submission',
'transform',
'utils',
'install',

# 3rd Party
'django_summernote',
'dynamicsites',
'markdown_deux',
'hvad',
'raven.contrib.django.raven_compat',
'bootstrap4',
'rest_framework',
'materialize',
]
~~~~

**Comment by ajrbyers** [comment]
Jeff, your local copy of the repo must be out of date because these are definitely already fixed. See for example this line in the latest 1.2.4 commit:

https://github.com/BirkbeckCTP/janeway/blob/7181db1012b6b4b4bd2f7a38ef5f6d4ede719764/src/core/example_settings.py#L87

**Comment by jeffpooley** [comment]
Updated and fixed. Thanks.
