### ISSUE TITLE
Can't Display Galleys with Unicode

### ISSUE THREAD

**Issue by hackman104** [BirkbeckCTP/janeway#508]
When we upload a galley with unicode letters, we get an error that says ascii couldn’t decode it ([here](https://dc-vm2-rhel.andrew.cmu.edu/cmsh/article/id/54)). Error message is: `'ascii' codec can't decode byte 0xce in position 1069: ordinal not in range(128)`. Is there a setting to turn on rendering via unicode?

**Comment by ajrbyers** [comment]
Tested this @hackman104 and it works okay for me. I wonder if the encoding on your file is wrong?
