### ISSUE TITLE
Fix file path errors in the ‘Apache and mod_wsgi’ installation instructions

### ISSUE THREAD

**Issue by jeffpooley** [BirkbeckCTP/janeway#513]
#170  ‘Janeway, Apache and WSGI’ [live installation documention](https://github.com/BirkbeckCTP/janeway/wiki/Janeway%2C-Apache-and-WSGI) has two file path errors. 

The current static path is:

```
Alias /static/ /path/to/janeway/src/collected-static/
    <Directory /path/to/janeway/src/collected-static>
            Require all granted
    </Directory>
```

Should be fixed to:

```
Alias /static/ /path/to/janeway/src/static/
    <Directory /path/to/janeway/src/static>
            Require all granted
    </Directory>
```

The current path to wsgi.py is

```
WSGIScriptAlias / /path/to/janeway/src/wsgi.py
    WSGIDaemonProcess janeway python-path=/path/to/.virtualenvs/janeway/lib/python3.5/site-packages
    <Location />
    WSGIProcessGroup janeway
    </Location>
    <Directory /path/to/janeway/src/>
            <Files wsgi.py>
                    Require all granted
            </Files>
    </Directory>
```

Should be fixed to:

```
WSGIScriptAlias / /path/to/janeway/src/core/wsgi.py
    WSGIDaemonProcess janeway python-path=/path/to/.virtualenvs/janeway/lib/python3.5/site-packages
    <Location />
    WSGIProcessGroup janeway
    </Location>
    <Directory /path/to/janeway/src/core/>
            <Files wsgi.py>
                    Require all granted
            </Files>
    </Directory>
```

**Comment by ajrbyers** [comment]
Hi Jeff,

The first issue is not a bug, you're supposed to run the build_assets command which will collect all static files into the collected-static folder assuming you haven't changed that setting in settings.py.

The second has been updated in the wiki.

Andy

**Comment by jeffpooley** [comment]
Thanks for the heads-up in terms of build_assets. Maybe it makes sense to explicitly include that step in the instructions?

**Comment by ajrbyers** [comment]
It is part of the install process (see utils/management/commands/install_janeway.py so if you've completed the install process this folder will already exist.

**Comment by amardesi** [comment]
Is line 21 of janeway.conf supposed to be 
```
    <Directory /path/to/janeway/src/>
            <Files wsgi.py>
```

or

```
    <Directory /path/to/janeway/src/core/>
            <Files wsgi.py>
```

**Comment by jeffpooley** [comment]
It did not create the folder in my case, though I followed the manual install instructions (ubuntu).

**Comment by ajrbyers** [comment]
Ok @jeffpooley, hope thats resolved for you.

@amardesi I've updated this also, I'm going to run through an apache install to ensure the setting are working as expected.

I've created an issue for testing this: https://github.com/BirkbeckCTP/janeway/issues/515
