### ISSUE TITLE
Couple other issues in ‘Apache and mod_wsgi’ installation instructions

### ISSUE THREAD

**Issue by amardesi** [BirkbeckCTP/janeway#514]
• Missing <\/VirtualHost> closing tag
• Not sure this is supposed to be wrapped with a location tag:
```
<Location />
    WSGIProcessGroup janeway
</Location>
```

**Comment by ajrbyers** [comment]
The close tag is present in the markdown but for some reason Github isn't rendering it properly.

Re the second, can you confirm a setup works without having the process group wrapped?

Thanks,

**Comment by amardesi** [comment]
@ajrbyers Yes, our setup is working without the Location tag around the process group, although I am not sure what the test would be to confirm this.

**Comment by ajrbyers** [comment]
Ah! An open without a close seems to be the culprit, fixed now.

As I'm sure you can tell we don't actually use Apache and WSGI to run out live instance of Janeway (we use Passenger), I think the location tags were used in previous applications I *did* run with Apache and WSGI, but are evidently not required.
