### ISSUE TITLE
Reader Group and Article Notifications

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#518]
- [x] When a user registers or edits their account give them the option to enroll as a reader
- [x] Add new setting that will allow an editor to enable emails to be sent when either a new article is published
    - [x] Add a new email setting
    - [x] Add a new email subject setting
    - [x] Add a new boolean to flag this feature on or off
    - [x] Add a new management command to send these emails
    - [x] Update CRON installation to add this new command 
- [x] Alow users to cancel their subscription
- [x] Add page where Editors can see readers and see notifications sent

**Comment by ajrbyers** [comment]
This issue is a duplicate of #507. #507 has been closed and this is the version of record for this issue.

**Comment by mauromsl** [comment]
Proposed workflow from Alex at DCU: An interested reader would like to receive a notification email every time new content is published in a given Janeway journal. 
> As part of the registration process, they need to explicitly provide consent for this particular purpose and tick a "I give consent" box. Once that box is ticked, the user role "Reader" is allocated to the registrant and the journal manager can see those "Readers" in the management module in the enrolled users section (i.e. https://cujournal.ie/manager/user/). The journal manager can remove user roles. So a reader could be removed if and when they want to be removed. Would that work?
