### ISSUE TITLE
Urgent/blocking: Security decorator causing site-wide crash on typeset edits

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#535]
This line in the security decorator crashes:

article_id = kwargs['article_id']

security/decorators.py in wrapper at line 400

Editing or notifying a typeset causes this to crash because the URL does not contain article_id. It only passes 'typeset_id': '9'. (for instance)

I've found this bug on the notify typesetter page and the delete typesetter page.

See: https://sentry.io/open-library-of-humanities/olh-acta/issues/681113822/?query=is:unresolved

**Comment by ajrbyers** [comment]
I've added a handler for typeset_id without article_id into the decorator:

6bd078a04002418396670fa25434139c23ae4dbd
