### ISSUE TITLE
backup command writes non-json content into janeway.json

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#546]
When running `python manage.py backup` on v1.3, the resulting `janeway.json` starts with messages from the app about loading plugin urls, before the valid JSON content begins:

```
Loaded URLs for back_content
Loaded URLs for pandoc_plugin
[
{
    "model": "contenttypes.contenttype",
    "pk": 1,
    "fields": {
        "app_label": "admin",
        "model": "logentry"
    }
...
```

**Comment by ajrbyers** [comment]
Cheers @mdlincoln. TBH, this backup procedure is full of holes as re-importing the JSON into a freshly migrated DB wont work straight off anyway.

Working on a fix for this though, will let you know.
