### ISSUE TITLE
Error When Configuring Featured Articles

### ISSUE THREAD

**Issue by hackman104** [BirkbeckCTP/janeway#549]
Within a journal, when going to manager -> journal home settings and trying to click configure next to featured articles, we receive the attached error.
![screen shot 2018-09-27 at 10 06 06 am](https://user-images.githubusercontent.com/31514656/46151564-0d7eaf80-c23d-11e8-991a-83f5932bf27f.png)

**Comment by ajrbyers** [comment]
I've patched his but this feature only works for Presses at the moment. I've added an issue to convert this to a generic controller for presses and journals:

https://github.com/BirkbeckCTP/janeway/issues/550
