### ISSUE TITLE
add links to existing examples in README

### ISSUE THREAD

**Issue by evanwill** [BirkbeckCTP/janeway#55]
It would be helpful to have links to examples and contextual info, I came across it from the GitHub repo and it took a bit of digging around to find out more. thank you.

<https://ijwwe.uwp.co.uk/>

<https://dandelionjournal.org/>

<http://www.ctp.bbk.ac.uk/2017/08/04/birkbeck-centre-for-technology-and-publishing-releases-scholarly-communications-platform-janeway/>

**Comment by ajrbyers** [comment]
Hi,

Im not sure that the readme is the appropriate place for this so I have added them to the home page of the wiki.

https://github.com/BirkbeckCTP/janeway/wiki
