### ISSUE TITLE
Setup Questions

### ISSUE THREAD

**Issue by atiro** [BirkbeckCTP/janeway#56]
Do you require two domains for setting Janeway up (press & first journal), I think I've confused the URL routing by trying them both under the same domain.

Is the gallery stage entirely manual ? Am trying to work out how the submission goes from Word/ODF to JATS, is this process left for the implementer to deal with  (presumably using a converter tool, then some manual XML cleanup?)

**Comment by ajrbyers** [comment]
Currently you do require two domains (though you can use sub domains i use localhost for press and journal.localhost for journal. 

Currently, the flow relies on an external typesetting process though we may investigate automated processes. Janeway can automatically generate PDF and EPUB from a JATS xml document

**Comment by atiro** [comment]
Thanks @ajrbyers is domain per journal hardcoded in or is there potential for path per journal on one domain ? (although obviously could manage this with proxying)

**Comment by ajrbyers** [comment]
To be frank, I'm not sure if a path would work. I'll add a new issue to try and add support for this. If you need assistance getting a setup running, let me know, I can invite you to our slack channel.

**Comment by ajrbyers** [comment]
New issue opened for this issue: https://github.com/BirkbeckCTP/janeway/issues/57
