### ISSUE TITLE
Unable to change status of declined article

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#566]
I declined an article on purpose to see what happens if this is done by mistake.
It appears the only way to retrieve the article is to use Admin tools to change its stage status.
However, when I tried to do the only option I got was:
Can only delete item(?)  'NoneType' object has no attribute 'code' 
From a functionality point of view perhaps Declined Articles should be deposited in 'Folder' in the same way as those in other states such as Copy Editing, Production etc?

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
The Editor Article Manager will allow Editors to resurrect these.
