### ISSUE TITLE
Unable to produce final article,which gives an error, and article 'disappears' from work stream

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#569]
This happened twice at the Metadata Confirmation etc stage:
https://demojournal.janeway.systems/plugins/back_content/article/578/ gave:
"Error in rendering: NoReverseMatch at /plugins/back_content/article/578/
Reverse for '' not found. '' is not a valid view function or pattern name. Error during template rendering
In template /home/martindev/demo/janeway/src/templates/admin/elements/article_jump.html, error at line 11"

https://demojournal.janeway.systems/plugins/back_content/article/579/# gave:
"Error: NoReverseMatch at /plugins/back_content/article/579/
Reverse for '' not found. '' is not a valid view function or pattern name. n template /home/martindev/demo/janeway/src/templates/admin/elements/article_jump.html, error at line 11"

**Comment by ccaadeh** [comment]
Replicated again (or I am doing something very wrong):

Request Method: | GET
-- | --
https://demojournal.janeway.systems/plugins/back_content/article/580/
1.11.16
NoReverseMatch
Reverse for '' not found. '' is not a valid view function or pattern name.
/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
/home/martindev/virtualenv/demo_janeway_src/3.5/bin/python3.5
3.5.6
['/home/martindev/demo/janeway/src',  '/home/martindev/demo/janeway/src',  '/opt/passenger-5.1.12-1.el7.cloudlinux/src/helper-scripts',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python35.zip',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/plat-linux',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/lib-dynload',  '/opt/alt/python35/lib64/python3.5',  '/opt/alt/python35/lib/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-bootstrap4',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/foundationform',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-mailgun',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/dynamicsites',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/ebooklib',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-materialize',  '/path/to/installation/',  '/path/to/your/virtualenv/name/lib/python3.5/site-packages/',  '/home/martindev/demo/janeway/src/plugins']
Thu, 25 Oct 2018 09:01:32 +0000

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
