### ISSUE TITLE
File Similarity Check Gives Error

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#570]
https://demojournal.janeway.systems/review/unassigned/article/579/:

"AssertionError at /review/unassigned/article/579/
No exception message supplied"

**Comment by ajrbyers** [comment]
When disabled, similarity check should be hidden an not run.

**Comment by ajrbyers** [comment]
Closed by c000ea6cb85c31655cfa77ed474bbd2747e60815
