### ISSUE TITLE
Wrong Password Yields Incorrect Error Message/No Warning of Lockout/Lockout Does Not Work?

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#571]
https://demojournal.janeway.systems/login/
Using valid and activated account (david.hurrell@open.ac.uk), when entering the wrong password I get 
"Account not found or account not active" rather than incorrect password.
Also, no warning given of the number of attempts allowed, and subsequently account was said to be locked out. "You have been banned from logging in due to failed attempts"
Refreshed the page, and using the same account I could login successfully.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
