### ISSUE TITLE
Permission denied to view articles even by privileged account – linked to issue #569

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#574]
E.g. https://demojournal.janeway.systems/article/doi/10.16995/orbit.580/ logged in as 
david.hurrell@open.ac.uk
Yields:
"Permission Denied You do not have permission to view this page"
Same for all the articles I submitted and which failed to be 'produced' as per issue #569.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
