### ISSUE TITLE
The 'Request Revisions' button does work unless somethings is entered into the editor note box

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#576]
https://demojournal.janeway.systems/review/article/582/revisions/request/
When you make request a revision:
The 'Request Revisions' button does not do anything unless some text is entered into the editor note box, although this does not appear to be a mandatory requirement like the setting of a date(?), which tells you that must enter some input.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
