### ISSUE TITLE
Cosmetic: Interface Function/Dialogue (?) Box Partially Masks Other Options

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#577]
https://demojournal.janeway.systems/review/unassigned/article/583/
When looking at my own article I have recently submitted at Dashboard: Unassigned
The Function Box(?) 'Action' to the lower right, partial masks the 'Files' box to the lower left with a message of 'Before you can perform actions on an article you must assign an Editor.', even if I am wishing to say, replace the files etc.

**Comment by ajrbyers** [comment]
@ccaadeh can you supply a screenshot of this in effect?

**Comment by ccaadeh** [comment]
Andy, the quick answer is no as I can't presently reproduce it. I will have
to try different browsers and submissions etc. David

**Comment by ccaadeh** [comment]
![screenshot 2](https://user-images.githubusercontent.com/44443205/48335644-44c2e780-e656-11e8-87b2-760fa6d22b0a.png)
I could not quite reproduce what I saw originally, but this gives you an idea . . . .

**Comment by ajrbyers** [comment]
Hi @ccaadeh keep this open, I'll look into this.

**Comment by ccaadeh** [comment]
![screenshot 4](https://user-images.githubusercontent.com/44443205/48335773-9cf9e980-e656-11e8-85ab-0370a2651679.png)
A similar problem at the following stage:
http://demojournal.janeway.systems/review/unassigned/article/590/

**Comment by ccaadeh** [comment]
Andy, screenshots now on GitHub (not quite the same as I originally saw).
It is a very minor issue anyway . . .

David

**Comment by ccaadeh** [comment]
Perhaps a better example is below, which seriously masks the buttons underneath the overlay. 
Therefore, I have reopened this. Of course, close it if you feel it is not an issue.
![screenshot 13](https://user-images.githubusercontent.com/44443205/48473145-c69a4880-e7ef-11e8-81e5-9e24c7a46684.png)

**Comment by ccaadeh** [comment]
This seems to happen if one zooms in or out a little, but the page does not redraw correctly.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
