### ISSUE TITLE
Confusing Error Message When Activating New Account

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#578]
I create a new account, check using Admin rights that it has been created and is NOT active.
As the new user I click on the link in the registration email and get the following error message:
Error
There was no inactive account with this activation code found. It is possible that your account is already active, you can check by attempting to login.

https://demojournal.janeway.systems/register/step/2/fb66a174-65a4-41b7-b1e7-24e9ace8a773/

However, Admin rights confirm that the account is active, and as the user I can login successfully. This has happened on a number of occasions when registering a new account, although not every time. I assume that clicking on the link does actually activate the account but gives a confusing message to the end user,

**Comment by ccaadeh** [comment]
Andy says: This is an odd one probably caused by a browser pre-loading the URL. We need to make the activation process require a POST.

I would add: I completely closed the browser i.e. no windows open, opened the browser again, and registered a new account. I got the same error when clicking on activation email.

**Comment by ccaadeh** [comment]
Andy,

I completely closed the browser i.e. no windows open, opened the browser
again, and registered a new account. I got the same error when clicking on
the activation email.

David

**Comment by ajrbyers** [comment]
Hi David,

Where are you opening the email from? A web based system like Gmail preloads links before you even click them. Either way a POST action (ie. requiring them to press a ACTIVATE button) will fix it.

Andy

**Comment by ccaadeh** [comment]
OK, I see now what you what you meant exactly. Yes, it was an outlook
account accessed via IE.
