### ISSUE TITLE
Upgrade to Django 2

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#579]
This might be quite a big one but something we should consider doing sooner rather than later. Some tips we should look out for:

https://eldarion.com/blog/2017/12/26/10-tips-upgrading-django-20/

And Django's official upgrade pages

https://docs.djangoproject.com/en/2.1/howto/upgrade-version/

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by mauromsl** [comment]
Sounds like we will need to press on:
https://github.com/django/django/commit/931c60c5216bd71bc11f489e00e063331cf21f40#commitcomment-31010149

**Comment by ajrbyers** [comment]
Yeah for sure, its going to be a biggie. Maybe we should make this the first card of 1.4?
