### ISSUE TITLE
Improve settings handling

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#582]
When new a new feature requires a setting to be added to the django settings.py, there should be a way to include a default case so that users are not required to immediately change their own settings files.

Janeway needs a way of supporting default settings, similar to how django's django.conf.global_settings behave. https://docs.djangoproject.com/en/1.11/topics/settings/#using-settings-without-setting-django-settings-module

**Comment by ajrbyers** [comment]
Moved up to 1.3.2.
