### ISSUE TITLE
ImageFields across multiple models refer to an absolute path location

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#587]
This leads annoying migrations being generated everytime `makemigrations` is called, as the absolute path is different between installations.

Should probably store a relative path instead and add a model property for resolving the absolute path when needed.

Example of a dull migration:
`class Migration(migrations.Migration):                                          
 11                                                                                 
 12     dependencies = [                                                            
 13         ('submission', '0027_auto_20180806_1005'),                              
 14     ]                                                                           
 15                                                                                 
 16     operations = [                                                              
 17         migrations.AlterField(                                                  
 18             model_name='article',                                               
 19             name='meta_image',                                                  
 20             field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/vol/janeway/src/media'), upload_to=submission.models.article_media    _upload),
`

**Comment by ajrbyers** [comment]
Interestingly in submission.models the upload_to is relative but the FS is settings.MEDIA_ROOT which may cause it to create an absolute path...

```

fs = FileSystemStorage(location=settings.MEDIA_ROOT)


def article_media_upload(instance, filename):
    try:
        filename = str(uuid.uuid4()) + '.' + str(filename.split('.')[1])
    except IndexError:
        filename = str(uuid.uuid4())

    path = "articles/{0}/".format(instance.pk)
    return os.path.join(path, filename)
```

**Comment by mauromsl** [comment]
According to `django.db.models.fields.files` seems to automatically construct the full path for the `upload_to` field, as well as the FileSystemStorage from the absolute path

Then the `makemigrations` management command will call `MigrationAutodetector.generate_altered_fields`, which will call the "deconstruct()" method from every field to workout what has changed.

As an example, our `core.models.Account.profile_image.deconstruct` returns:
`In [1]: from core.models import Account

In [2]: field = Account.profile_image

In [3]: type(field)
Out[3]: django.db.models.fields.files.ImageFileDescriptor

In [4]: type(field.field)
Out[4]: django.db.models.fields.files.ImageField

In [5]: field.field.deconstruct()
Out[5]: 
('profile_image',
 'django.db.models.ImageField',
 [],
 {'blank': True,
  'null': True,
  'storage': <django.core.files.storage.FileSystemStorage at 0x7f59c8819e48>,
  'upload_to': <function core.models.profile_images_upload_path(instance, filename)>})
`
Leading to a Migration like:

```
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180417_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/vol/janeway/src/media'), upload_to=core.models.profile_images_upload_path),
        ),
    ]
```
Which doesn't seem to have any impact on the database itself:

```
mysql> select `profile_image` from core_account where `profile_image` is not NULL AND `profile_image` != '';
+----------------------------------------------------------+
| profile_image                                            |
+----------------------------------------------------------+
| profile_images/743d6819-3b21-4bc3-8aa0-e1e6d8bd7b0f.jpeg |
+----------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by mauromsl** [comment]
The SQL from running the actual migration is even more useless:
```
$ manage sqlmigrations core 0018
BEGIN;
--
-- Alter field profile_image on account
--
COMMIT;
```

**Comment by ajrbyers** [comment]
https://code.djangoproject.com/ticket/22337

This seems to have been closed 5 years ago... related?

**Comment by mauromsl** [comment]
Seems like they decided not to remove those fields from `deconstruct` so that the `RunPython` instruction in the migrations can geniune changes up
