### ISSUE TITLE
Cosmetic: On Submission 'Section' Drop Down Box Shows 'Article' Three Times

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#589]
http://demojournal.janeway.systems/submit/588/info/
On submission: SubmissionStart>Article Info>Section
Amongst the options presented by the drop down box  'Article' appears three times, and I assume there is no difference between them.

**Comment by ccaadeh** [comment]
Hi Martin,

It is on the test system, hence the path/URL of
http://demojournal.janeway.systems/submit/588/info/

Regards,

David

**Comment by ajrbyers** [comment]
There are three "Article" sections with various settings so this isn't a bug.

**Comment by ccaadeh** [comment]
Hi Andy,

What are the differences between the three then? I can't say I have noticed
any.
Surely there is a need to label them differently to guide the user E.g.
Plain Article, Article with X, Article with X and Y etc

Regards,

David

**Comment by ajrbyers** [comment]
Hi David,

There is not difference. Its just a bug with this journal caused by my merging a bunch of journals together. It can safely be ignored in this context.

Cheers,

Andy
