### ISSUE TITLE
Strange Functionality On Author Information Stage of New Submission

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#590]
http://demojournal.janeway.systems/submit/581/authors/
Author Information>Current Authors: 
The up/down arrow icon to the left of any listed author does not appear to do anything
The wastebasket to the right of any listed author's email address does not remove the author listed as a current author.
However, clicking on the button does remove the author from 'Select Main Author' drop down list, making it possible to empty the list and have no option to choose from. However, if you search for email address still visible under the 'Current Authors' list, a successful match will repopulate the Select Main Author' drop down list, and can be selected so the submission can proceed.

**Comment by ajrbyers** [comment]
The up and down icons should be changed to “handles” as you can drag and drop to reorder. 

The issue with deleting appears to be related to author order models not also being deleted.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
These have been fixed in other commits to do with authors.
