### ISSUE TITLE
Cosmetic (& Possibly undesirable way to proceed): Typesetters  

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#595]
http://demojournal.janeway.systems/production/590/ (screenshot attached).
Probably a typo: 'Status . . . 2. At lease one Galley' which I assume should be 'at LEAST one Galley (file)'.
If I understand this correctly: if it is the case that there should be at least one galley file, it is nonetheless possible to proceed by assigning a typesetter without a galley file:
http://demojournal.janeway.systems/production/590/assignment/25/typeset/assign/
At this stage you just need to select ANY file:
![screenshot 5](https://user-images.githubusercontent.com/44443205/48338269-1bf22080-e65d-11e8-8885-049582cd8fdf.png)

Also, if you select a file without having selected a typesetter, the page ungracefully bombs out:
http://demojournal.janeway.systems/production/590/assignment/25/typeset/assign/

Request Method: | POST
-- | --
http://demojournal.janeway.systems/production/590/assignment/25/typeset/assign/
1.11.16
DoesNotExist
Account matching query does not exist.
/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages/django/db/models/query.py in get, line 380
/home/martindev/virtualenv/demo_janeway_src/3.5/bin/python3.5
3.5.6
['/home/martindev/demo/janeway/src',  '/home/martindev/demo/janeway/src',  '/opt/passenger-5.1.12-1.el7.cloudlinux/src/helper-scripts',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python35.zip',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/plat-linux',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/lib-dynload',  '/opt/alt/python35/lib64/python3.5',  '/opt/alt/python35/lib/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-bootstrap4',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/foundationform',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-mailgun',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/dynamicsites',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/ebooklib',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-materialize',  '/path/to/installation/',  '/path/to/your/virtualenv/name/lib/python3.5/site-packages/',  '/home/martindev/demo/janeway/src/plugins']
Mon, 12 Nov 2018 09:31:47 +0000

**Comment by ccaadeh** [comment]
If 'At lease' is a mistake, it also appears here:
http://demojournal.janeway.systems/production/590/
![screenshot 6](https://user-images.githubusercontent.com/44443205/48362766-48795d00-e69c-11e8-8a77-ad891a028f98.png)

**Comment by ccaadeh** [comment]
I obviously hit the wrong button by mistake . . .

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
