### ISSUE TITLE
Set Upload Mask

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#598]
We currently do not set an upload mask, it should be `0x664` but randomly is sometimes `0x600`.

https://docs.djangoproject.com/en/1.11/ref/settings/#file-upload-permissions

**Comment by mauromsl** [comment]
Apparently it was part of the django 1.11 Release Notes:
https://docs.djangoproject.com/en/2.1/releases/1.11/

> FileField now moves rather than copies the file it receives. With the default file upload settings, files larger than FILE_UPLOAD_MAX_MEMORY_SIZE now have the same permissions as temporary files (often 0o600) rather than the system’s standard umask (often 0o6644). Set the FILE_UPLOAD_PERMISSIONS if you need the same permission regardless of file size.

Some systems default to 0o600 so good to have our default in the settings.py in any case
