### ISSUE TITLE
Dashboard Production  Overview Not Functioning Correctly (or Is Confusing)?

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#599]
Logged in with a privileged account, and open dashboard:
http://demojournal.janeway.systems/dashboard/

Production shows:  Production Request [1], Accepted Request [1], Completed Requests [1]
If I click on 'View Requests' it goes to 'Typesetting Requests' and there are NO requests i.e.
Awaiting Decision [0], In Progress [0], Completed [0]

Perhaps the typesetting and Production distinction is confusing?

![screenshot 7](https://user-images.githubusercontent.com/44443205/48405996-575b2080-e72b-11e8-90e3-11ba3115e281.png)
![screenshot 8](https://user-images.githubusercontent.com/44443205/48406011-5fb35b80-e72b-11e8-965c-f8f0d736115a.png)
![screenshot 9](https://user-images.githubusercontent.com/44443205/48406026-65a93c80-e72b-11e8-96b1-256259f58e3e.png)
![screenshot 10](https://user-images.githubusercontent.com/44443205/48406041-6b9f1d80-e72b-11e8-8a66-1fb44717a96a.png)

**Comment by ccaadeh** [comment]
In a similar way, with a non-privileged account, I open the dashboard:
http://demojournal.janeway.systems/dashboard/
Reviewer: [0] Review Requests, [0] Accepted Reviewer, [0] Completed Reviews [0]
If I click on 'View Requests@ I see two completed requests:
http://demojournal.janeway.systems/review/requests/
![screenshot 14](https://user-images.githubusercontent.com/44443205/48474928-889f2380-e7f3-11e8-9a6d-16ae8895d527.png)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
This has been fixed.
