### ISSUE TITLE
Very Minor Cosmetic Issue - Adding Web Link to text is far from easy to see

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#606]
Within any text box if one chooses 'Add Link', a web link address can be added, but it renders as an underscore _ that is very difficult to see, rather than say, a hyperlink like http://news.sky.com
(I would add a screenshot but the underscore will not show up)
If one clicks the source button, the link is correctly displayed as markup. e.g:
<a href="http://news.sky.com">&nbsp;</a>

All the other buttons in the text box appear to work correctly.

**Comment by ajrbyers** [comment]
Hi David,

When you are adding a link are you selecting the text you want to *be* the link? Thats how this button works.

Andy

**Comment by ccaadeh** [comment]
Andy,
No, I was not highlighting the text, Maybe I was being a little dense. I
thought it was a way of inserting a hyperlink.
Anyway, yes if you highlight the text and put a URL in etc it works.
David
