### ISSUE TITLE
Checking of Submission List Gives Errors

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#615]
http://demojournal.janeway.systems/dashboard/active/
As privileged account, when I check the list of submitted articles I see the following errors:

1) Again, a minor problem that the screen overlay is out as the varying amount of text for each article is not necessarily visible as best shown by the top article  (I reset the screen size but no improvement)

![screenshot 15](https://user-images.githubusercontent.com/44443205/48543748-0d547500-e8ba-11e8-942b-b20d1e7fb3b2.png)

2) If I use the filter mechanism to choose article 578 'More Decadence', which works, and then choose 'View Article' the article is not found. 

Request Method: | GET
-- | --
http://demojournal.janeway.systems/dashboard/active/None
Using the URLconf defined in core.urls, Django tried these URL patterns, in this order:

^$ [name='website_index']
^admin/
^summernote/
^submit/
^ ^article/(?P<article_id>\d+)/galley/(?P<galley_id>\d+)/figure/(?P<file_name>.*)/$ [name='article_figure']
^ ^article/(?P<identifier_type>.+?)/(?P<identifier>.+)/file/(?P<file_id>\d+)/replace$ [name='article_file_replace']
^ ^article/(?P<identifier_type>.+?)/(?P<identifier>.+)/file/(?P<file_id>\d+|None)/$ [name='article_file_download']
^ ^article/(?P<article_id>\d+)/galley/(?P<galley_id>\d+)/download/ [name='article_download_galley']
^ ^article/(?P<identifier_type>.+?)/(?P<identifier>.+?/.+?)/table/(?P<table_name>.+)$ [name='article_figure']
^ ^article/(?P<identifier_type>.+?)/(?P<identifier>.+?/.+?)/(?P<file_name>.+)$ [name='article_figure']
^ ^articles/$ [name='journal_articles']
^ ^issues/$ [name='journal_issues']
^ ^issue/current/$ [name='current_issue']
^ ^issue/(?P<issue_id>\d+)/info/$ [name='journal_issue']
^ ^issue/(?P<issue_id>\d+)/download/$ [name='journal_issue_download']
^ ^collections/$ [name='journal_collections']
^ ^collections/(?P<collection_id>\d+)/$ [name='journal_collection']
^ ^cover/$ [name='journal_cover_download']
^ ^article/(?P<identifier_type>.+?)/(?P<identifier>.+)/edit/$ [name='article_edit']
^ ^article/(?P<identifier_type>.+?)/(?P<identifier>.+)/print/$ [name='article_print_article']
^ ^article/(?P<identifier_type>.+?)/(?P<identifier>.+)/$ [name='article_view']
^ ^(?P<article_id>\d+)/files/management/$ [name='document_management']
^ ^(?P<article_id>\d+)/files/(?P<file_id>\d+)/info/$ [name='submit_replacement_files_info']
^ ^(?P<article_id>\d+)/files/(?P<file_id>\d+)/history/$ [name='file_history']
^ ^(?P<article_id>\d+)/files/(?P<file_id>\d+)/delete/$ [name='file_delete']
^ ^(?P<article_id>\d+)/files/(?P<file_id>\d+)/old/(?P<file_history_id>\d+)/reinstate/$ [name='file_reinstate']
^ ^(?P<article_id>\d+)/file/(?P<file_id>\d+)/makegalley/$ [name='article_file_make_galley']
^ ^note/(?P<article_id>\d+)/new/$ [name='article_new_note']
^ ^publish/$ [name='publish']
^ ^publish/article/(?P<article_id>\d+)/$ [name='publish_article']
^ ^publish/article/(?P<article_id>\d+)/check/$ [name='publish_article_check']
^ ^manage/issues/$ [name='manage_issues']
^ ^manage/issues/order/$ [name='issue_order']
^ ^manage/issues/(?P<issue_id>\d+)/$ [name='manage_issues_id']
^ ^manage/issues/(?P<issue_id>\d+)/add/article/$ [name='issue_add_article']
^ ^manage/issues/(?P<issue_id>\d+)/order/$ [name='issue_article_order']
^ ^manage/issues/(?P<issue_id>\d+)/guest/$ [name='manage_add_guest_editor']
^ ^manage/issues/(?P<issue_id>\d+)/(?P<event>[-\w.]+)/$ [name='manage_issues_event']
^ ^manage/issues/(?P<issue_id>\d+)/sort/sections/$ [name='manage_sort_issue_sections']
^ ^manage/archive/$ [name='manage_archive']
^ ^manage/archive/article/(?P<article_id>\d+)/$ [name='manage_archive_article']
^ ^manage/article/(?P<article_id>\d+)/log/$ [name='manage_article_log']
^ ^manage/article/(?P<article_id>\d+)/log/(?P<log_id>\d+)/resend/$ [name='manage_resend_logged_email']
^ ^manage/articles/schedule/$ [name='publication_schedule']
^ ^reviewer/$ [name='become_reviewer']
^ ^contact/$ [name='contact']
^ ^editorialteam/$ [name='editorial_team']
^ ^editorialteam/(?P<group_id>\d+)/$ [name='editorial_team_group']
^ ^search/$ [name='search']
^ ^submissions/$ [name='journal_submissions']
^ ^texture/(?P<file_id>\d+)/edit/$ [name='texture_edit']
^ ^download/article/(?P<article_id>\d+)/supp_file/(?P<supp_file_id>\d+)/ [name='article_download_supp_file']
^review/
^metrics/
^identifiers/
^production/
^proofing/
^cms/
^transform/
^copyediting/
^rss/
^feed/
^cron/
^install/
^i18n/
^api/
^api-auth/
^news/
^reports/
^preprints/
^repository/
^utils/
^$ [name='website_index']
^journals/$ [name='press_journals']
^kanban/$ [name='kanban']
^login/$ [name='core_login']
^login/orcid/$ [name='core_login_orcid']
^register/step/1/$ [name='core_register']
^register/step/2/(?P<token>[\w-]+)/$ [name='core_confirm_account']
^register/step/orcid/(?P<token>[\w-]+)/$ [name='core_orcid_registration']
^reset/step/1/$ [name='core_get_reset_token']
^reset/step/2/(?P<token>[\w-]+)/$ [name='core_reset_password']
^profile/$ [name='core_edit_profile']
^logout/$ [name='core_logout']
^dashboard/$ [name='core_dashboard']
^dashboard/active/$ [name='core_active_submissions']
^dashboard/active/filters/$ [name='core_submission_filter']
^dashboard/article/(?P<article_id>\d+)/$ [name='core_dashboard_article']
^press/cover/$ [name='press_cover_download']
^article/(?P<article_id>\d+)/note/(?P<note_id>\d+)/delete/$ [name='kanban_delete_note']
^manager/$ [name='core_manager_index']
^manager/settings/$ [name='core_settings_index']
^manager/settings/group/(?P<setting_group>[-\w.]+)/setting/(?P<setting_name>[-\w.]+)/$ [name='core_edit_setting']
^manager/settings/(?P<group>[-\w.]+)/$ [name='core_edit_settings_group']
^manager/settings/(?P<plugin>[-\w.]+)/(?P<setting_group_name>[-\w.]+)/(?P<journal>\d+)/$ [name='core_edit_plugin_settings_groups']
^manager/home/settings/$ [name='home_settings_index']
^manager/home/settings/order/$ [name='journal_home_order']
^manager/roles/$ [name='core_manager_roles']
^manager/roles/(?P<slug>[-\w.]+)/$ [name='core_manager_role']
^manager/roles/(?P<slug>[-\w.]+)/user/(?P<user_id>\d+)/(?P<action>[-\w.]+)/$ [name='core_manager_role_action']
^manager/user/$ [name='core_manager_users']
^manager/user/inactive/$ [name='core_manager_inactive_users']
^manager/user/authenticated/$ [name='core_logged_in_users']
^manager/user/add/$ [name='core_add_user']
^manager/user/(?P<user_id>\d+)/edit/$ [name='core_user_edit']
^manager/user/(?P<user_id>\d+)/history/$ [name='core_user_history']
^manager/templates/$ [name='core_email_templates']
^manager/templates/(?P<template_code>[-\w.]+)/$ [name='core_edit_email_template']
^manager/templates/(?P<template_code>[-\w.]+)/(?P<subject>[-\w.]+)/$ [name='core_edit_email_template_subject']
^manager/article/images/$ [name='core_article_images']
^manager/article/images/edit/(?P<article_pk>\d+)/$ [name='core_article_image_edit']
^manager/contacts/$ [name='core_journal_contacts']
^manager/contacts/(?P<contact_id>\d+)/$ [name='core_journal_contact']
^manager/contacts/order/$ [name='core_journal_contacts_order']
^manager/editorial/$ [name='core_editorial_team']
^manager/editorial/(?P<group_id>\d+)/$ [name='core_edit_editorial_team']
^manager/editorial/(?P<group_id>\d+)/add/$ [name='core_editorial_member_to_group']
^manager/editorial/(?P<group_id>\d+)/add/(?P<user_id>\d+)/$ [name='core_editorial_member_to_group_user']
^manager/editorial/order/(?P<type_to_order>[-\w.]+)/$ [name='core_editorial_ordering']
^manager/editorial/order/(?P<type_to_order>[-\w.]+)/group/(?P<group_id>\d+)/$ [name='core_editorial_ordering_group']
^manager/notifications/$ [name='core_manager_notifications']
^manager/notifications/(?P<notification_id>\d+)/$ [name='core_manager_edit_notifications']
^manager/plugins/$ [name='core_plugin_list']
^manager/sections/$ [name='core_manager_sections']
^manager/sections/(?P<section_id>\d+)/$ [name='core_manager_section']
^manager/articles/pinned/$ [name='core_pinned_articles']
^manager/press/$ [name='press_edit_press']
^manager/press/journal_order/$ [name='press_journal_order']
^manager/press/journal/(?P<journal_id>\d+)/domain/$ [name='press_journal_domain']
^workflow/$ [name='core_journal_workflow']
^workflow/order/$ [name='core_order_workflow_elements']
^manager/cache/flush/$ [name='core_flush_cache']
^edit/article/(?P<article_id>\d+)/metadata/$ [name='edit_metadata']
^edit/article/(?P<article_id>\d+)/authors/order/$ [name='order_authors']
^edit/article/(?P<article_id>\d+)/ident/$ [name='edit_identifiers']
^edit/article/(?P<article_id>\d+)/ident/(?P<identifier_id>\d+)/$ [name='edit_identifiers_with_ident']
^edit/article/(?P<article_id>\d+)/ident/(?P<identifier_id>\d+)/(?P<event>[-\w.]+)/$ [name='edit_identifiers_with_event']
profile/(?P<uuid>[0-9a-f-]+)/$ [name='core_public_profile']
^sitemap/$ [name='journal_sitemap']
^download/file/(?P<file_id>\d+)/$ [name='journal_file']
^homepage/elements/news/
^homepage/elements/issue/
^homepage/elements/featured/
^homepage/elements/carousel/
^homepage/elements/html/
^homepage/elements/preprints/
^homepage/elements/about/
^homepage/elements/journals/
^plugins/back_content/
^site/(?P<page_name>.*)/$ [name='cms_page']
^media/(?P<path>.*)$
^404/$
^500/$
^__debug__/
The current path, dashboard/active/None, didn't match any of these.

'

**Comment by ccaadeh** [comment]
Perhaps related to #569 when an article 'fails' to be published and 'disappears' from the work stream?

**Comment by ccaadeh** [comment]
3) https://demojournal.janeway.systems/dashboard/active/
Under 'Section' to the left, the 'Three Article' Problem is also repeated, and each one of the three has different numbers of articles in them, which would probably correspond to which one of the three options was used. See the above screenshot.

**Comment by ajrbyers** [comment]
Yes. Again. Ignore the articles thing, it’s because multiple journals were merged together.

**Comment by ccaadeh** [comment]
Related to 1) There is something not right with the way the text is displayed:
https://demojournal.janeway.systems/dashboard/active/
![screenshot 20](https://user-images.githubusercontent.com/44443205/48549231-1b5cc280-e8c7-11e8-9035-6671a67b667f.png)

**Comment by ccaadeh** [comment]
![screenshot 21](https://user-images.githubusercontent.com/44443205/48608179-245a9c00-e97a-11e8-99c2-a8d6c0095fa0.png)
Similar problem, I can't get to the 'View Article' link for the Review 'Proper Submission' without using the search facility to redraw the screen.
