### ISSUE TITLE
Assign Typesetter Gives Error Unless You Choose A Typesetter AND Files / Status shows more than ONE typesetter

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#635]
Possibly linked to #595 but some behaviour different.
Logged in with privileged account.
https://demojournal.janeway.systems/production/588/assignment/26/typeset/assign/
Dashboard>Article In Production>(Article) 'Yet Another One>Typesetter
Click on 'Add Typesetter' with:
NO Typesetter choosen & also
NO files choosen (see issue #596) I get an error:
![screenshot 26](https://user-images.githubusercontent.com/44443205/48761122-c8f11c80-ec9f-11e8-9f31-b5298a359386.png)

Request Method: | POST
-- | --
https://demojournal.janeway.systems/production/588/assignment/26/typeset/assign/
1.11.16
DoesNotExist
Account matching query does not exist.
/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages/django/db/models/query.py in get, line 380
/home/martindev/virtualenv/demo_janeway_src/3.5/bin/python3.5
3.5.6
['/home/martindev/demo/janeway/src',  '/home/martindev/demo/janeway/src',  '/opt/passenger-5.1.12-1.el7.cloudlinux/src/helper-scripts',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python35.zip',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/plat-linux',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/lib-dynload',  '/opt/alt/python35/lib64/python3.5',  '/opt/alt/python35/lib/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-bootstrap4',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/foundationform',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-mailgun',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/dynamicsites',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/ebooklib',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-materialize',  '/path/to/installation/',  '/path/to/your/virtualenv/name/lib/python3.5/site-packages/',  '/home/martindev/demo/janeway/src/plugins']
Tue, 20 Nov 2018 08:37:32 +0000

If NO Typesetter choosen & also I now choose the files I get the same error:

Request Method: | POST
-- | --
https://demojournal.janeway.systems/production/588/assignment/26/typeset/assign/
1.11.16
DoesNotExist
Account matching query does not exist.
/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages/django/db/models/query.py in get, line 380
/home/martindev/virtualenv/demo_janeway_src/3.5/bin/python3.5
3.5.6
['/home/martindev/demo/janeway/src',  '/home/martindev/demo/janeway/src',  '/opt/passenger-5.1.12-1.el7.cloudlinux/src/helper-scripts',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python35.zip',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/plat-linux',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/lib-dynload',  '/opt/alt/python35/lib64/python3.5',  '/opt/alt/python35/lib/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-bootstrap4',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/foundationform',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-mailgun',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/dynamicsites',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/ebooklib',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-materialize',  '/path/to/installation/',  '/path/to/your/virtualenv/name/lib/python3.5/site-packages/',  '/home/martindev/demo/janeway/src/plugins']
Tue, 20 Nov 2018 08:40:07 +0000

Only appears to work if you choose a typesetter together with (some) files (which obviously makes sense but it should give constructive error if one or both are not choosen)
If you enrol a new typesetter and choose no files a warning is given
However, it also appears to be able to assign TWO typesetters (undesirable?) by moving backwards/forwards between pages:
![screenshot 27](https://user-images.githubusercontent.com/44443205/48761884-a7913000-eca1-11e8-9557-4906dc407852.png)
Or simply enrol more users as typesetters:
![screenshot 28](https://user-images.githubusercontent.com/44443205/48762315-ad3b4580-eca2-11e8-96f9-3e5ba8aeb320.png)
And another, so I now have 4 tasks:
![screenshot 29](https://user-images.githubusercontent.com/44443205/48762515-191dae00-eca3-11e8-9995-cb22ceef744c.png)

I would appear that more than two people can be assigned (undesirable?) , yet really only one can get their first (?) i.e. there is no 'lock' on adding typesetters or the task.

**Comment by ajrbyers** [comment]
Assigning multiple typesetters is okay, but the form should be converted into a `django.forms.form` so we can provide better error handling.
