### ISSUE TITLE
Material theme renders "None" as the article_content for articles with no HTML content

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#662]
Looks like the other themes check for truthiness of article_content before rendering, just need to bring the material theme in-line with the other two themes.

**Comment by ajrbyers** [comment]
@mauromsl can you close up these issues when the are merged?

**Comment by mauromsl** [comment]
They should close themselves when we merge back into master

**Comment by mauromsl** [comment]
Okay, that doesn't seem to have worked ... maybe it only works when you merge the branch via PR with master as a base... :(
