### ISSUE TITLE
User Not Aware They Have Typesetter Task Proofreading Corrections from the Dashboard

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#670]
Logged in with a privileged account, and wish to assign proofreading correction task to another account.
This is successfully done.
However, if I login to the other account, no request is shown on the dashboard at:
https://demojournal.janeway.systems/dashboard/
![screenshot 50](https://user-images.githubusercontent.com/44443205/49077523-5ea62200-f233-11e8-91ef-e39ebf3b18d0.png)
However, if I click on 'View Requests' I find it:
![screenshot 50](https://user-images.githubusercontent.com/44443205/49077586-8d23fd00-f233-11e8-8285-4404da846ff5.png)
If I accept the task it still does not show up on the top level of the dashboard:
https://demojournal.janeway.systems/dashboard/
![screenshot 50](https://user-images.githubusercontent.com/44443205/49077707-e5f39580-f233-11e8-88c5-4f0dfba06756.png)
But does show up one level further down:
https://demojournal.janeway.systems/dashboard/requests
![screenshot 53](https://user-images.githubusercontent.com/44443205/49077729-f3108480-f233-11e8-9694-675fbe745075.png)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
The new corrections listing fixes this issue.
