### ISSUE TITLE
Allow PDF galleys to be opened in browser

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#672]
At the moment, we server the galleys via request, we could also offer them statically so that they can be opened in the browser without the user needing to download it and then open it.

This was proposed by Megan:

> I have the following query from a journal editor: when the ‘download’ button is clicked – can the pdf be viewed in browser in a new window instead of asking for a download location? This helps with reading materials over smart devices and computers where someone is not intending to download a copy but just view it only?

**Comment by ajrbyers** [comment]
In chrome this is the default functionality. Same in iOS Safari. Suspect someone is using IE....

**Comment by mauromsl** [comment]
I'm pretty sure this is Janeway, not the browset. Our headers are telling the browser to download the file:
`* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< date: Tue, 27 Nov 2018 16:27:14 GMT
< server: Apache
< content-disposition: attachment; filename="jcms-525-collins.pdf"
< cache-control: max-age=600
< vary: Accept-Encoding,Accept-Language,Cookie
< x-frame-options: SAMEORIGIN
< content-language: en
< x-powered-by: Phusion Passenger 5.1.12
< set-cookie: ACTASESSID=4tvnwz6ah0kwly275wlvs3mp9talwfde; expires=Tue, 11-Dec-2018 16:27:14 GMT; HttpOnly; Max-Age=1209600; Path=/
< content-length: 788584
< status: 200 OK
< content-type: application/pdf
`

**Comment by ajrbyers** [comment]
Yup. When someone clicks a “download” button I want it to download. Maybe we should have a “View” button but not overwrite the behaviour of the download button.

**Comment by mauromsl** [comment]
Agree, I haven't proposed otherwise.

**Comment by ajrbyers** [comment]
👍
