### ISSUE TITLE
Delete Assaignment Button Missing for Proofing

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#673]

**Comment by ccaadeh** [comment]
Having successfully assigned a proofreader, the chosen proofreader declines the task.
This shows up with my privileged account:
![screenshot 42](https://user-images.githubusercontent.com/44443205/49142441-b48ccf80-f2f0-11e8-8840-79740870fc4f.png)

I choose 'Actions button':
But I try to remove the task and get told I delete it using the button below - which does not exist (?)
I can't see the relevant button on either the screen below.

![screenshot 41](https://user-images.githubusercontent.com/44443205/49142447-bbb3dd80-f2f0-11e8-864b-da0301fc1568.png)

The Button I am referring to is present is this screenshot from a different scenario:
![screenshot 43](https://user-images.githubusercontent.com/44443205/49142504-d71ee880-f2f0-11e8-8dc7-1c05e1aa2e7f.png)

**Comment by ajrbyers** [comment]
The reason you can't delete this is because it has been accepted or declined, but we should update the text to be clearer.
