### ISSUE TITLE
Janeway Installation Procedure

### ISSUE THREAD

**Issue by CroZg** [BirkbeckCTP/janeway#690]
Hi,
I'm trying to follow guidelines for installation, as found in documents "Installation" and "Janeway, Apache and WSGI" but I have difficulties.
For example, starting automatic install script does not install everything needed (can't start installer), but following manual script after the command python3 manage.py install_janeway following error occured:
(janeway) joe@joe:/var/www/janeway/src$ python3 manage.py install_janeway
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

Also, it is not clear enough how to edit settings.py file.

I could provide a number of problems now, but is it possible to provide detailed guideline how to install Janeway on Debian or some other standard Linux+Apache or nGnix server environment up to point the web server operates Janeway application without errors?

Currently documentation is unfortunately not detailed enough neither the installer script operates without error.

On one side, I am not satisfied with OJS, but with Janeway I even have problems with install. With these errors I am afraid how it works from the inside.

Thanks for any useful help!

**Comment by ajrbyers** [comment]
Hi @CroZg,

Thanks for getting in touch. We understand the install process isn't as easy as with the likes of OJS. As you can imagine its quick difficult for us to debug this issue for you but I'll try. Can you tell me the version of Debian you are using?

Andy

**Comment by CroZg** [comment]
Hi,
thanks for a quick reply.
I'm using Deb 9 stretch (9.6).

I'll try to be as specific as possible, as this could be also useful for creating some kind of instructions as well.

0. Clean Debian 9 was installed.
1. A username (for example joe) was created, and placed in sudoers. 
Also MariaDB and Apache were installed with apt-get install commands.
System was updated with apt-get update and apt-get upgrade.

2. Following command was run in /home/[user]/:
wget -O - https://raw.githubusercontent.com/BirkbeckCTP/janeway/master/setup_scripts/debian.sh | bash
Two directories were created under /home/joe/ and those are: /.virtualenvs and /janeway

3. A MariaDB 10 database was created with:
CREATE DATABASE janeway CHARACTER SET = utf8 COLLATE = utf8_general_ci;

4. Copy the example settings file: cp src/core/example_settings.py src/core/settings.py
A first problem-what should be modified here?
I've edited parameters under the mysql part (DB_NAME, DB_USER, ... DB_PORT), but it is not clear to me where the DB_VENDOR is set-up at all?

5. From inside the src directory following command was given:
workon janeway

6. python3 manage.py install_janeway

The installer crashes.
I need to edit /janeway/src/utils/notify_plugins/notify_email.py to include "import re" line (before sanitize part) to resolve the issue.

Then I observe the installer writes everything not in mariadb database, but in sqlite file db (obviously because django environment is not properly set-up).
After that, there are issues with setting up Apache I need to have some help with.

Of course, I have some experience with Debian administration, but I am not a professional Python programmer, so I would really appreciate some help and advice here.

**Comment by mauromsl** [comment]
Hi @CroZg,

First of all, thank you for trying out Janeway. We understand that the installation process is not as simple as it should be, so your feedback as an external user is very valuable to us.

It seems you are trying to run Janeway in a live-like environment, from the master branch.
I would suggest you checkout the latest stable release (v1.3 https://github.com/BirkbeckCTP/janeway/releases). You can do so by running `git checkout v1.3`. The wiki page is maintained according to the features available on the latest stable release.

Once that is done, you can repeat step 4 above (copying `src/core/example_settings.py` as `src/core/settings.py`) and ignore the environment variables such as `DB_VENDOR` (these changes part of the upcoming release 1.3.2).

The `DATABASES` under your `src/core/settings.py` should be updated again by filling-in the missing entries regarding your MariaDB server:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}
```

Finally, regarding the traceback you received when running `(janeway) joe@joe:/var/www/janeway/src$ python3 manage.py install_janeway` - It seems like django is not installed on your janeway virtual environment. This can be verified by running `pip3 freeze`. Django should be on that list.

If it isn't, you will need to install the dependancies with `pip3 install -r requirements.txt` from the root of the janeway project (as explained on the manual install guide: https://github.com/BirkbeckCTP/janeway/wiki/Installation#manual-install)

As a final note, we are adding some commands to run Janeway within a docker container, which should require less knowledge about python and django in general (but it assumes familiarity with docker instead). If that sounds like an interesting idea, keep an eye to our progress on the next release v1.3.2 (https://github.com/BirkbeckCTP/janeway/projects/7)

**Comment by CroZg** [comment]
Hi @mauromsl,
thanks!

So, currently these are the steps I've went through:

#sudo apt-get install python3 python3-pip python-pip virtualenvwrapper
#source /etc/bash_completion.d/virtualenvwrapper
#mkvirtualenv janeway -p /usr/bin/python3
#sudo apt-get install libxml2-dev libxslt1-dev python3-dev zlib1g-dev lib32z1-dev libffi-dev libssl-dev libjpeg-dev
#git clone https://github.com/BirkbeckCTP/janeway.git
#cd janeway
#git checkout v1.3
#cp src/core/example_settings.py src/core/settings.py (edited DATABASES, DEFAULT_HOST,... accordingly to local settings)
mariadb>CREATE DATABASE janeway CHARACTER SET = utf8 COLLATE = utf8_general_ci;
#pip3 install -r requirements.txt (generated a number of warnings)

Setup script ended without problems. I hope everything will work ok.

Now I need to finish to Apache setup.

My first question was - what is /path/to/janeway/? Is it GIT-cloned directory (/home/joe/janeway/) or a ./virtualenvs/janeway?

Anyway, I've continued with following commands:

	sudo chown -R joe:www-data /home/joe/janeway/ && sudo adduser www-data joe

	sudo apt-get install apache2 libapache2-mod-wsgi-py3

	cd /etc/apache2/sites-available/

	sudo nano 000-janeway.conf
****************000-janeway.conf contents**********************

<VirtualHost *:80>
        RewriteEngine on
        RewriteOptions Inherit

        Alias /media/ /home/joe/janeway/src/media/
        <Directory /home/joe/janeway/src/media>
                Require all granted
        </Directory>

        Alias /static/ /home/joe/janeway/src/collected-static/
        <Directory /home/joe/janeway/src/collected-static>
                Require all granted
        </Directory>

        WSGIApplicationGroup %{GLOBAL}
        WSGIScriptAlias / /home/joe/janeway/src/core/wsgi.py
        WSGIDaemonProcess janeway python-path=/home/joe/.virtualenvs/janeway/lib/python3.5/site-packages
        WSGIProcessGroup janeway

        <Directory /home/joe/janeway/src/core/>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

        # http://wiki.apache.org/httpd/InternalDummyConnection
        # disable logging of the "(internal dummy connection)" requests.
        # may be skewing traffic reported by logwatch.
        SetEnvIf Remote_Addr "127\.0\.0\.1" loopback
        ErrorLog ${APACHE_LOG_DIR}/janeway_error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/janeway.log vhost_combined env=!loopback
</VirtualHost>

**************************************

	#sudo a2enmod rewrite

	#sudo a2dissite 000-default && sudo a2ensite 000-janeway.conf

	#sudo systemctl reload apache2

Apache2 reloads without errors/warnings.

And finally, Janeway does not work - obviously something went wrong. 
/var/log/apache2/janeway error.log is full of error messages (exceptions, no module warnings, etc).

I really appreciate your time and effort while helping me with these install problems, but as you can see, a lot of Janeway system information is actually expected from end-user to know.

**Comment by mauromsl** [comment]
Hi @CroZg,

I'm glad you've managed to install Janeway succesfully.

The problems you are having setting up apache have more to do with the complexity of setting up apache with mod_wsgi than the complexity of installing Janeway itself. In particular, I found an error on the example given on the wiki. Please replace the following line on your `/etc/apache2/sites-available/000-janeway.conf` vhost config:
```WSGIDaemonProcess janeway python-path=/home/joe/.virtualenvs/janeway/lib/python3.5/site-packages```
with this:
```WSGIDaemonProcess janeway python-home=/home/joe/.virtualenvs/janeway python-path=/home/joe/janeway/src```

Afterwards restart apache (`sudo systemctl reload apache2`) and you should be able complete your journal setup when you visit `http://localhost/install`.

Let me know how you get on and I will then ammend the instructions on the wiki

Finally, if apache keeps giving you problems and all you want to do is try the system you can try the Janeway's development server instead:
```
cd /home/$USER/janeway
source /etc/bash_completion.d/virtualenvwrapper && workon janeway
python3 src/manage.py runserver
```
Once that is done just point your browser to `http://localhost:8000/install to complete the setup of your first journal.

**Comment by CroZg** [comment]
Hi, thanks for the advice, but now i got endless loop 302 - The page isn’t redirecting properly. Also in the access log is a number of "302 /" lines. Obviously something went wrong.

Now this time I reset VM and tried manual install, and again, it went wrong.
For debugging purposes I provide you with exact list of commands:

# sudo apt-get install python3 python3-pip python-pip virtualenvwrapper
# source /etc/bash_completion.d/virtualenvwrapper
# mkvirtualenv janeway -p /usr/bin/python3
# sudo apt-get install libxml2-dev libxslt1-dev python3-dev zlib1g-dev lib32z1-dev libffi-dev libssl-dev libjpeg-dev
# git clone https://github.com/BirkbeckCTP/janeway.git
# cd janeway
# git checkout v1.3
From the /janeway I run 
# pip3 install -r requirements.txt

While running pip3 I receive several of this warnings
Could not find a tag or branch 'b7005c57602eeea06358ac569a4cf52c630a32ef', assuming commit.
and at last I receive fatal error:
 Downloading https://files.pythonhosted.org/packages/f7/a2/1230ebbb4b91f42ad6b646e59eb8855559817ad5505d81c1ca2b5a216040/mysqlclient-1.3.14.tar.gz (91kB)
    100% |████████████████████████████████| 92kB 12.4MB/s
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zv924vsk/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-zv924vsk/mysqlclient/setup_posix.py", line 53, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-zv924vsk/mysqlclient/setup_posix.py", line 28, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zv924vsk/mysqlclient/


So again, I tried automatic script debian.sh run from /home/joe/ *** after manually *** git to v1.3.
This time it finished without problems.
Also I did manage to configure Apache to work without problems, so currently everything seems to operate ok.


I have another question regarding write permissions for each directory. 
Can you specify what directories in janeway/src/files should have write permission?

Thanks for your help and I hope this thread will help others with similar problems.

**Comment by CroZg** [comment]
Well...it did not last long.
After trying to setup Journal in administration, system crashed.
Now I have
DoesNotExist at /
PluginSetting matching query does not exist.

Request Method: | GET
-- | --
http://161.53.17.73/
1.11.5
DoesNotExist
PluginSetting matching query does not exist.
/home/joe/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/query.py in get, line 380
/usr/bin/python3
3.5.3
['/home/joe/janeway/src',  '/home/joe/.virtualenvs/janeway/lib/python35.zip',  '/home/joe/.virtualenvs/janeway/lib/python3.5',  '/home/joe/.virtualenvs/janeway/lib/python3.5/plat-x86_64-linux-gnu',  '/home/joe/.virtualenvs/janeway/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/joe/.virtualenvs/janeway/lib/python3.5/site-packages',  '/home/joe/.virtualenvs/janeway/src/django-bootstrap4',  '/home/joe/.virtualenvs/janeway/src/foundationform',  '/home/joe/.virtualenvs/janeway/src/django-mailgun',  '/home/joe/.virtualenvs/janeway/src/dynamicsites',  '/home/joe/.virtualenvs/janeway/src/ebooklib',  '/home/joe/.virtualenvs/janeway/src/django-materialize',  '/path/to/installation/',  '/path/to/your/virtualenv/name/lib/python3.5/site-packages/',  '/home/joe/janeway/src/plugins']

Any advice????

**Comment by mauromsl** [comment]
> Hi, thanks for the advice, but now i got endless loop 302 - The page isn’t redirecting properly. Also in the access log is a number of "302 /" lines. Obviously something went wrong.
> 
> Now this time I reset VM and tried manual install, and again, it went wrong.
> For debugging purposes I provide you with exact list of commands:
> # sudo apt-get install python3 python3-pip python-pip virtualenvwrapper
> # source /etc/bash_completion.d/virtualenvwrapper
> # mkvirtualenv janeway -p /usr/bin/python3
> # sudo apt-get install libxml2-dev libxslt1-dev python3-dev zlib1g-dev lib32z1-dev libffi-dev libssl-dev libjpeg-dev
> # git clone https://github.com/BirkbeckCTP/janeway.git
> # cd janeway
> # git checkout v1.3
> 
> From the /janeway I run
> # pip3 install -r requirements.txt
> 
> While running pip3 I receive several of this warnings
> Could not find a tag or branch 'b7005c57602eeea06358ac569a4cf52c630a32ef', assuming commit.
> and at last I receive fatal error:
> Downloading https://files.pythonhosted.org/packages/f7/a2/1230ebbb4b91f42ad6b646e59eb8855559817ad5505d81c1ca2b5a216040/mysqlclient-1.3.14.tar.gz (91kB)
> 100% |████████████████████████████████| 92kB 12.4MB/s
> Complete output from command python setup.py egg_info:
> /bin/sh: 1: mysql_config: not found
> Traceback (most recent call last):
> File "", line 1, in
> File "/tmp/pip-build-zv924vsk/mysqlclient/setup.py", line 16, in
> metadata, options = get_config()
> File "/tmp/pip-build-zv924vsk/mysqlclient/setup_posix.py", line 53, in get_config
> libs = mysql_config("libs_r")
> File "/tmp/pip-build-zv924vsk/mysqlclient/setup_posix.py", line 28, in mysql_config
> raise EnvironmentError("%s not found" % (mysql_config.path,))
> OSError: mysql_config not found
> 
> ```
> ----------------------------------------
> ```
> 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zv924vsk/mysqlclient/
> 
> So again, I tried automatic script debian.sh run from /home/joe/ *** after manually *** git to v1.3.
> This time it finished without problems.
> Also I did manage to configure Apache to work without problems, so currently everything seems to operate ok.
> 
> I have another question regarding write permissions for each directory.
> Can you specify what directories in janeway/src/files should have write permission?
> 
> Thanks for your help and I hope this thread will help others with similar problems.

Hi  @CroZg,

I have spotted a problem on your manual installation, you've ran `pip3 install -r requirements.txt` outside the virtual environment. Remember to activate the virtual environment first to ensure that the requirements are installed in `~/.virtualenvs/janeway` , otherwise they might conflict with the libraries installed on your host. So, before installing requirements, remember to run `workon janeway`.

Can you confirm if running the script `debian.sh` and following instructions to setup apache + `mod_wsgi` resulted on a working installation? (i've just seen your other run-time problem and will address that one separately)

**Comment by CroZg** [comment]
> > So again, I tried automatic script debian.sh run from /home/joe/ *** after manually *** git to v1.3.
> > This time it finished without problems.
> > Also I did manage to configure Apache to work without problems, so currently everything seems to operate ok.
> > I have another question regarding write permissions for each directory.
> > Can you specify what directories in janeway/src/files should have write permission?
> > Thanks for your help and I hope this thread will help others with similar problems.
> 
> Hi @CroZg,
> 
> I have spotted a problem on your manual installation, you've ran `pip3 install -r requirements.txt` outside the virtual environment. Remember to activate the virtual environment first to ensure that the requirements are installed in `~/.virtualenvs/janeway` , otherwise they might conflict with the libraries installed on your host. So, before installing requirements, remember to run `workon janeway`.
> 
> Can you confirm if running the script `debian.sh` and following instructions to setup apache + `mod_wsgi` resulted on a working installation? (i've just seen your other run-time problem and will address that one separately)

I will try to install everything again on clear machine and follow all the steps again, but it seems now it works ok. I really appreciate your help.!

**Comment by mauromsl** [comment]
Happy to be of help!
I've amended the apache vhost template on the wiki and added a couple of hints about the paths.
Feel free to join our discord channel if you want to chat with me or the rest of the community about Janeway: https://discord.gg/gpakC8

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
