### ISSUE TITLE
Multiple emails for single authors

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#692]
It would be cool to be able to associate multiple emails with a single account and to let the user login using any of these.

**Comment by ajrbyers** [comment]
It would be cool...

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
This issue has been marked for possible future development but is now closed.

For more information see: https://github.com/BirkbeckCTP/roadmap/issues/13
