### ISSUE TITLE
inconsistent icons in content settings

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#695]
"Editorial Team" has a different, non-button sigil...? It's also not quite clear that these are toggle buttons?

![screenshot_2018-12-10 carnegie mellon encyclopedia of science history](https://user-images.githubusercontent.com/4392604/49760801-5ae2b880-fc93-11e8-8d62-cf5f18e1720a.png)

**Comment by ajrbyers** [comment]
Hi @mdlincoln, we have a issue in place for 1.4 that will replace this whole system with one simpler. 

As it stands editorial team display is under journal settings.

**Comment by ajrbyers** [comment]
https://github.com/BirkbeckCTP/janeway/issues/509

**Comment by ajrbyers** [comment]
I'm going to close this as #509 will rectify this in 1.4.
