### ISSUE TITLE
invalid variable: collection.title!!

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#697]
OLH theme throws a template error `invalid variable: collection.title!!` on collections. It looks like all the templates for OLH, (plus material, and default too, though I haven't actually tested them) try to call `collection.title` when the the underlying object is actually an `Issue` which only has the attribute `issue_title`

Is this the kind of thing you'd generally like to see addressed by changing the templates? Or would you create a new class method for Issue to alias `issue_title` for backwards compatibility with these existing themes?

**Comment by ajrbyers** [comment]
@mdlincoln a fix to the themes would be great (and would love a PR!)
