### ISSUE TITLE
License manager allows deleting licenses already applied to published articles

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#698]
After publishing an article with a given license, I'm then able to remove that license from the journal using the license manager without throwing any integrity errors. Among other things, this causes a template error to display on the article page because its license is now null.

Can the `Article` `license` field's `on_delete` behavior here be switched to `PROTECT`? Or some other mechanism for warning you that you're about to delete a license already applied to published lessons?

(sorry for the wave of new issues... clearly I'm looking closely at Janeway this week 😆)

**Comment by ajrbyers** [comment]
The error you are seeing is only seen when debug is set to true. I don’t think we should use PROTECT but perhaps could warn that there are x articles using the license before allowing it to be deleted.
