### ISSUE TITLE
journal has no submissionconfiguration

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#700]
navigating to `/submit/manager/configurator/` throws an error that the journal has no `submissionconfiguration`

**Comment by ajrbyers** [comment]
@mdlincoln can you confirm you have no outstanding migrations? There is a migration that creates these.

**Comment by mdlincoln** [comment]
Just ran `makemigrations` and nothing came up?

**Comment by ajrbyers** [comment]
Try running migrate, here is the migration:

https://github.com/BirkbeckCTP/janeway/pull/677/commits/b63c9134a99353286bf45ff07ef9d0ce30f123cd

**Comment by mdlincoln** [comment]
hm, that's definitely been applied days ago when I set up this DB originally - it shows up in the `django_migrations` table

**Comment by ajrbyers** [comment]
Great. I'm suspecting then that the Signal to create this model isn't being fired when a Journal is created. Will test this out.

**Comment by ajrbyers** [comment]
Workaround is to jump to `/admin/submission/submissionconfiguration/` and add one.

**Comment by mdlincoln** [comment]
The workaround worked for the time being at least - thanks!
