### ISSUE TITLE
Links don't work on submission checklist - minor issue

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#710]

**Comment by ccaadeh** [comment]
https://demojournal.janeway.systems/submit/start/
When starting to submit an article, on the opening page with the heading of 'Author Agreement', under the section that says 'submission checklist' there are two links under the following lines of text:
5) 'Author Guidelines', clicking on this (-> https://orbit.openlibhums.org/site/authorguidelines/)
gives 'Page not found'
6) 'Blind Review', clicking on this does nothing (and does not actually appear to  be linked to another page)

**Comment by ajrbyers** [comment]
Hi @ccaadeh, this isn’t a real bug. Just that this test journal doesn’t have these pages configured properly. Closing with #wontfix.
