### ISSUE TITLE
Typos/Character Mismatch in Review Request Guidelines - Minor Issue

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#712]

**Comment by ccaadeh** [comment]
https://demojournal.janeway.systems/review/requests/128/
1) There are a number of instances where a question mark is used instead of an apostrophe. E.g.
"Please consider the originality, relevance and rigour of the submission and the author?s depth of understanding of the issues being researched. Please comment on the adequacy of the author?s referencing and whether or not the existing knowledge base has been explored and built upon." 
2) Full stop missing at the end of the line 5) Language that ends with 'improvement'.
![screenshot 54](https://user-images.githubusercontent.com/44443205/50077475-675b9980-01dc-11e9-9eb1-776edcc7067d.png)

**Comment by ccaadeh** [comment]
Accidently closed.

**Comment by ccaadeh** [comment]
This issue does not appear to show up in the list - maybe this will help . . .

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
