### ISSUE TITLE
Skipped Proofing Acknowledgement Presented As Sent

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#715]
https://demojournal.janeway.systems/proofing/609/

Logged in with a privileged account, if I acknowledge that Proofing Task is completed BUT then skip sending the email, it stills shows up as acknowledged.
![screenshot 56](https://user-images.githubusercontent.com/44443205/50140482-bf59d500-029c-11e9-8600-c1b7755fa673.png)

**Comment by ajrbyers** [comment]
Hey David, this isn’t a bug, this is the expected result of skipping emails throughout he system.
