### ISSUE TITLE
User checking proof reading requests presented with two summaries with inconsistent info

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#718]
https://demojournal.janeway.systems/proofing/requests/
As a normal user, the dashboard for proofing requests presents a summary of the tasks twice, with each one of the two giving a different status of awaiting/in progress/completed tasks. This is difficult to capture in a single screenshot, so the following two  screenshots combined shows what the user sees on a single screen:
![screenshot 58](https://user-images.githubusercontent.com/44443205/50213409-775ab100-0375-11e9-9f3c-3ea87ca2a389.png)
![screenshot 59](https://user-images.githubusercontent.com/44443205/50213412-7a55a180-0375-11e9-9666-5fc04facd96b.png)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
