### ISSUE TITLE
Annoyance and incomplete error messages when making mistakes assigning a copyeditor - minor issue

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#731]
https://demojournal.janeway.systems/copyediting/article/612/assignment/add/

When assigning a copy-editing task with a privileged account, I choose the person to perform the task with the corresponding radio-button, but mistakenly forget to choose a file and click on 'Add Copyeditor'. An error message is given of 'You must select at least one file.' But in the process the chosen copy editor has been deselected. If you don't notice this, the only error message given pertains to not choosing a file:

![screenshot 64](https://user-images.githubusercontent.com/44443205/50683027-9bbabc80-1008-11e9-9e19-d391828dea0b.png)

So you choose the file and then get told (correctly) that you have not (now) chosen a user:

![screenshot 65](https://user-images.githubusercontent.com/44443205/50683009-85acfc00-1008-11e9-944b-8aff8b51f77d.png)

An annoyance that might throw a novice user?

**Comment by ccaadeh** [comment]
This is NOT an issue with the similar process of choosing a typesetter and then forgetting to choose the files.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
