### ISSUE TITLE
Possible Functionality Issue Depending on Requirements

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#732]

**Comment by ccaadeh** [comment]
https://demojournal.janeway.systems/edit/article/612/metadata/?return=/production/requests/21/

Logged in with a non-privileged account and assigned typesetting task which I accept.
under actions, I can view Metadata, which I open. I am presented with the data and an edit button at top-right. If I choose get 'Permission Denied'.
If I write a note under the notes field, and choose 'Save', nothing is saved.
 Is this desirable/intentional? I would have thought the type-setter may well have good reason to change the information of the metadata and/or write notes.
![screenshot 67](https://user-images.githubusercontent.com/44443205/50763319-5cd67200-1267-11e9-98e9-c621f0bde1d5.png)
![screenshot 66](https://user-images.githubusercontent.com/44443205/50763334-6cee5180-1267-11e9-90f5-90d97fc7c244.png)

**Comment by ajrbyers** [comment]
Thanks @ccaadeh we need to have a new version of this pop up for non-editor accounts.

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
