### ISSUE TITLE
Analytics Reports

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#733]
Reporting at Press and Journal level to allow us to see the below info for all articles, filterable by journal, and publication year:

- [x] Downloads
- [ ] Views
- [ ] Citations
- [ ] Altmetric scores
- [ ] Geographical spread

**Comment by MeganTaylorHud** [comment]
Reporting at Press and Journal level to allow us to see the below info for all articles, filterable by journal, and publication year:

Downloads
Views
Citations
Altmetric scores
Geographical spread

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
