### ISSUE TITLE
Forbidden Error on trying to delete file on submission

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#739]
Logged in as a regular user. I start the submission process. At the end of this I select a file to upload which I do.
![screenshot 70](https://user-images.githubusercontent.com/44443205/50891664-b15b2800-13f4-11e9-82e0-771e5a4847f5.png)

I then test to see if I can delete that file, as if by accident I had chosen the wrong file, by clicking on the trash icon. Immediately the session 'crashes' out to a forbidden error (because of debug mode?), although I see no reason for this as the session has been continuous, and I believe the browser (IE) is using default settings:

"CSRF verification failed. Request aborted.
You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.
If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests."

I wonder if this is necessary?

![screenshot 69](https://user-images.githubusercontent.com/44443205/50891408-195d3e80-13f4-11e9-9186-31295de5f561.png)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
This is not a problem we can address but an issue with he EDGE broswer. 

According to this ticket it has been fixed in a future release of EDGE: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12457205/
