### ISSUE TITLE
Editor Dashboard

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#74]
We should include useful information for Editors like number of submissions per stage. 

@MartinPaulEve please add any suggestions you might have. 
@maur likewise, any ideas for this page!?

**Comment by MartinPaulEve** [comment]
Number of submissions requiring action/overdue?

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
Duplicate of #1472
