### ISSUE TITLE
Update Roles Template Tag

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#743]
- [ ] Add a tag for each of the roles

**Comment by mauromsl** [comment]
Or make it a property on the model so that it can be used like the django auth model properties (`user.is_editor`, `user.is_staff`)

**Comment by ajrbyers** [comment]
> Or make it a property on the model so that it can be used like the django auth model properties (`user.is_editor`, `user.is_staff`)

Looking this up needs the request object available so don't think it can be a property. Unless we access the global request object?

**Comment by mauromsl** [comment]
Yeah, we don't really need to pass in the request

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
Each role now has a is_x property.
