### ISSUE TITLE
Presented with the option a 'Blank Form' when assigning Reviewer Gives an Error - Minor issue

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#749]
https://demojournal.janeway.systems/review/article/613/review/add/
As an editor I am in the process of selecting a reviewer Under set options I am presented with two choices for the form field, one of which is 'blank' as indicated by - - - - - - - - -  I can choose this option and complete the process, but when I choose the final button of 'Add Reviewer' I get the error 'You must select an item from the list':

![screenshot 71](https://user-images.githubusercontent.com/44443205/51026463-7983ea00-1586-11e9-96eb-44ae12102c31.png)
![screenshot 72](https://user-images.githubusercontent.com/44443205/51026471-7be64400-1586-11e9-98b7-7b5327805dfc.png)
![screenshot 73](https://user-images.githubusercontent.com/44443205/51026474-7e489e00-1586-11e9-9fb5-6e9776747060.png)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
This is the expected behaviour for a journal that does not have a default review form which would constitute a pre-selection. "------" is an empty selection for a required field so this is the correct error message.
