### ISSUE TITLE
Inconsistent Instructions vs Behaviour When Submitting A Review, Plus Erronous Outcome?

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#751]
https://demojournal.janeway.systems/review/requests/131/
As a normal user I attempt to submit my review. The interface suggests that rather than filling in the review text box,  that "Alternatively, you may upload a file in lieu of completing the review form." If I attach a review file, and try to submit, I am told that the filling in the review text box is still a required field, and I can't submit:

![screenshot 74](https://user-images.githubusercontent.com/44443205/51104795-0e812000-17df-11e9-8714-ba00add9eea6.png)

Moreover, if I do add some text, and choose the blank decision option, it is accepted:
![screenshot 75](https://user-images.githubusercontent.com/44443205/51104995-9f57fb80-17df-11e9-85d6-8616de0dae31.png)
So my recommendation for the article is 'None' which I assume is not very useful (?)

![screenshot 76](https://user-images.githubusercontent.com/44443205/51105024-c282ab00-17df-11e9-937d-23ce9f2bb91e.png)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
