### ISSUE TITLE
makefile issue: illegal tr sequence

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#757]
On OS X running GNU Make 3.81 (and the BSD version of tr I suppose?) I'm getting the error

```
tr: Illegal byte sequence
```

which happens even when I try to run this bit independently

https://github.com/BirkbeckCTP/janeway/blob/bbd426f2b5b8da40d2674a51c25b3aa8ad8d3f7b/Makefile#L41

I think relying on shell scripts to create a random string sequence just to append to backup filenames is a bit fragile one you need it to work across different platforms. At the very least, it should be taken out of the makefile so you can run the other commands without throwing errors.

**Comment by mdlincoln** [comment]
re: #745

**Comment by mauromsl** [comment]
Agreed, will opt for a POSIX compliant option instead #745

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
