### ISSUE TITLE
On Declining Review, it is possible to send blank recommendations. Also a typo - Minor Issues

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#760]
https://demojournal.janeway.systems/review/requests/132/decline/suggest/
Upon declining a review, an email dialogue box is presented asking for recommendations suggesting another reviewer. It is possible to enter no text and send the email i.e. there is no check for content. Although I appreciate this a general function of the email module, this is perhaps an undesirable way of trying to handle this functionality?
 
Also, there is an error in the text: "Thanks for suggesting reviewers, please add the suggested reviewer's name, institution and email address below.." I.e. two full stops.

![screenshot 77](https://user-images.githubusercontent.com/44443205/51244332-bed85b00-197c-11e9-8ef5-4b0e5672652d.png)
![screenshot 78](https://user-images.githubusercontent.com/44443205/51244336-c566d280-197c-11e9-8435-16f697c80c72.png)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.
