### ISSUE TITLE
Declining Copy editing Task Produces a Typo in Displayed Log - Minor Issue

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#763]
https://demojournal.janeway.systems/copyediting/article/613/assignment/39/review/

Having declined a copy editing task, the screen and the log displayed to the editor yields a typo:
"Copyeditor declineed the request"
![screenshot 79](https://user-images.githubusercontent.com/44443205/51304565-6cf10d00-1a30-11e9-99a1-e4f270231edb.png)

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ccaadeh** [comment]
The same typo as appears here:
![screenshot 131](https://user-images.githubusercontent.com/44443205/52771289-779dc280-302d-11e9-99cc-89dade89d524.png)

**Comment by ccaadeh** [comment]
I meant here: 
![screenshot 130](https://user-images.githubusercontent.com/44443205/52771350-a025bc80-302d-11e9-8b4b-e4ec8b82bad9.png)
