### ISSUE TITLE
Production Preview

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#781]
Allow Production staff to preview Galley files.

**Comment by mdlincoln** [comment]
Can you remind me - how far out does this feel like it will be? 1.4? 1.5?

**Comment by ajrbyers** [comment]
1.3.3 probably.

**Comment by mdlincoln** [comment]
Awesome - this would be fantastic for us to have for CMESH. Let us know if we can coordinate on development & testing in any way.
