### ISSUE TITLE
Missing Functionality? As an Editor I Can't Trace A Rejected Article/Review?

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#783]
https://demojournal.janeway.systems/dashboard/
Logged in with privileged account - as an Editor

The article December's Test #3 was rejected by the reviewer, and as an Editor, an email has been sent to the Author to say it has been rejected. As the Author I can see the rejected review etc.
However, I cannot see a way for the Editor to trace the rejected article on the system - even by searching by name. I would have thought there is good reason why an editor would want to do this i.e. answering a query by an author of 'What has happened to my article?' (if they has missed the email)

I would suggest:
1) A' Rejected Article's' or 'Non-active submissions' button on the dashboard
2) A 'Find status of an article' search field somewhere obvious on the dashboard

**Comment by ajrbyers** [comment]
All published and rejected articles are listed on the Article Archive page:

From Dashboard, select "Articles" from the sidebar, however, I do like a 'Find status of an article' page so will keep this open.

**Comment by ccaadeh** [comment]
OK, I missed that (perhaps not obvious?), but is there I way for the Editor
to easily retrieve the (rejected) review in order to check it again?
I.e. Under the article archive, there is no link to the rejected article,
but there is one to a published one .

Regards,

David
