### ISSUE TITLE
Remove DEBUG options from janeway_global_settings.py

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#787]
#582 added support for having 2 layers of settings (global and local) but some DEBUG specific settings were left in the `src/core/janeway_global_settings.py`. Whilst this is not a problem for current installations, new installations would need to explicitly override this debug options on their custom local `settings.py`

Any debug specific settings should be moved to a dev_settings.py file that the docker container can then choose as the default.

**Comment by ajrbyers** [comment]
I believe based on https://github.com/BirkbeckCTP/janeway/blob/master/src/core/janeway_global_settings.py that this has been done. @mauromsl can you confirm and close?

**Comment by mauromsl** [comment]
It is!
