### ISSUE TITLE
Error Handling Required When Fail to Choose Typesetter Options

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#794]
https://demojournal.janeway.systems/production/620/assignment/33/typeset/assign/
Logged in with a privileged account of an Editor and at the stage of 'Assign Typesetter'
If I ignore all 3 requirements: i.e. Select a typesetter, Select files, Set options, on purpose
and then click on 'Add Typesetter', the program bombs out with the following error:
"DoesNotExist at /production/620/assignment/33/typeset/assign/
Account matching query does not exist."
This was repeated with another article and appears to happen with both Chrome and MS Edge browsers.
![screenshot 98](https://user-images.githubusercontent.com/44443205/51739997-c7224b80-208a-11e9-8cbc-fdf36120a023.png)

I appear to get the same error if I do choose only option two, but I get a sensible error message if I have chosen option one only i.e. 'You must select at least one file.'

**Comment by ajrbyers** [comment]
This has also been previously fixed in 1.3.3.
