### ISSUE TITLE
Adding new user in submission set to active

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#801]
When adding a new user during the submission process as an author, the [AuthorForm](https://github.com/BirkbeckCTP/janeway/blob/master/src/submission/forms.py#L185) is used 
However, the user is not automatically set to active so they don't appear immediately and must be set on the dashboard. 
Not sure if this is a feature or a bug but I think it would be more clear if they are automatically set to active so they will appear on the article (like in #446 ) or an event should send them a registration link.

**Comment by ajrbyers** [comment]
I think this will tie in with https://github.com/BirkbeckCTP/janeway/issues/145, we don't want to set the account to active unless they've "confirmed" the address like the normal process. This is in for 1.5.
