### ISSUE TITLE
Remove Article from Issue Still Returns Article

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#807]
To recreate:
- create issue id=2
- add article id=8, id=4
- remove 4 using /manage/issues/2/remove/?article=4
- on /manage/issues/2/  the number of articles = 1

- on the manage page `table_of_contents.html` TOC shows both 8 and 4
- on the front end `/issue/2/info/` shows both 8 and 4

- only 8 is showing as selected in url `/admin/journal/issue/2/change/`

the journal view's `def issue` uses 
	[Issue.structure](https://github.com/BirkbeckCTP/janeway/blob/master/src/journal/models.py#L487) which returns: `<QuerySet [<ArticleOrdering: 0: Article, #4>, <ArticleOrdering: 1: Article, #8>]>`
as does the table of contents template  {% for section, articles in issue.structure.items %}

4 is still showing in /admin/journal/articleordering/
so the articles are being found and displayed through the `ArticleOrdering` model and not really through `Issue` 

deleting 4 from ArticleOrdering.article.pk=4 removes it from all the places it should not be.

the remove function should probably also delete the article ordering entry as well as it relates to Issue and/or views could gather the ordering integer and not the article from articleordering with `issue_articles` and `get_article_order`?
I don't fully understand what sections are or do but there seems to be a portion in that structure function that loops through and adds articles to the final returned list based on ArticleOrdering [here](https://github.com/BirkbeckCTP/janeway/blob/master/src/journal/models.py#L493):
``` 
    for section in sections:
            article_with_order = ArticleOrdering.objects.filter(issue=self, section=section)

            article_list = list()
            for order in article_with_order:
                article_list.append(order.article)

            for article in articles.filter(section=section):
                if not article in article_list:
                    article_list.append(article)
            structure[section] = article_list
```

**Comment by ajrbyers** [comment]
Cheers for this. I guess no one has used the remove button in anger before!

Sections are just arbitrary groups of papers so “Reaearch Article” or “Reviews” or “Editorial” might be section names. 

I’m adding this to 1.3.3.
