### ISSUE TITLE
Manage Galleys in Proofing Stage deny_access

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#819]
Manage galleys button is available in the proofing stage and directs to `url/production/article_id/`

![image](https://user-images.githubusercontent.com/1020384/52002596-7185de80-2490-11e9-9b3d-60fae867e704.png)

that page has a decorator: `@article_stage_production_required` which requires that the article is on typesetting stage resulting in `deny_access`

**Comment by ajrbyers** [comment]
Yup I think we can drop this decorator we only care that the user is a pm or editor.
