### ISSUE TITLE
Similarity Check Error (Related to #570 now closed)

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#833]
https://demojournal.janeway.systems/review/unassigned/article/621/

As an Editor, I am looking at an unassigned submission.
There are a number of different version of the file, and I click on 'Similarity Check' and get a rather unhelpful error message (different to the one logged on #570):
![screenshot 109](https://user-images.githubusercontent.com/44443205/52203468-348f6280-2869-11e9-8251-f5b94c442084.png)
Andy's addition to #570 seems to suggest that this button should be hidden anyway . . . ? 
I thought it best to log this anway . . . Obviously close this one if it is effectively a duplicate.

**Comment by ajrbyers** [comment]
HI @ccaadeh, this error message asks that you check your iThenticate login details. For the demo journal ithenticate is enabled but there is no password so this error message seems to be okay for me.
