### ISSUE TITLE
Press site not accessible on URL_CONFIG= 'domain'

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#836]
(This issue is not huge for us because we are going to be using the 'path' but noticed it and bringing this to your attention.)

when accessing our press url we get
```
AttributeError at /
'Press' object has no attribute 'press'
```
Coming from [this line in middleware.py](https://github.com/BirkbeckCTP/janeway/blob/master/src/core/middleware.py#L39)
press = journal.press 

Is journal actually a press object?
Unclear what's going on here but in my shell where we only have 1 journal:
```
>>> from journal.models import Journal
>>> j = Journal.objects.get(pk=1)
>>> j.press
CMU Libraries
```

alter_domains shows the proper urls. 
When switching to path based urls it renders just fine.

**Comment by ajrbyers** [comment]
Can you rebase to the tip of 1.3.2? I think this fixes the issue you are seeing; 
https://github.com/BirkbeckCTP/janeway/commit/d0bd334dd2d142f88dbe8eee4126751c12d0e848

**Comment by ajrbyers** [comment]
@hachacha Can you confirm this is okay to close?

**Comment by hachacha** [comment]
just tested. it's a-okay.
