### ISSUE TITLE
Editor review unassigned article - link in notification email

### ISSUE THREAD

**Issue by amardesi** [BirkbeckCTP/janeway#866]
The email sent editor when something is submitted (editor_new_submission)
includes a broken URL (with two paths combined)
myjournal/submit/10/review//myjournal/review/unassigned/article/10/

...When running 1.3.2

**Comment by mauromsl** [comment]
Solved by https://github.com/BirkbeckCTP/janeway/pull/850

**Comment by amardesi** [comment]
Thanks @mauromsl
