### ISSUE TITLE
Possible Access Flaw: Editor can decline the requested review

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#867]
Logged in with privileged account as an Editor. I assign a review to another person:
![screenshot 115](https://user-images.githubusercontent.com/44443205/52554774-c35b2c80-2ddf-11e9-9c4d-88ceb2196e35.png)
When I log in as that reviewer I see the request to review:
![screenshot 116](https://user-images.githubusercontent.com/44443205/52554800-dec63780-2ddf-11e9-96ba-8e6d4a54a167.png)
Switching back to Editor, if I click on the 'view' button of the request:
![screenshot 117](https://user-images.githubusercontent.com/44443205/52554888-1fbe4c00-2de0-11e9-9a60-13b2813f84fc.png)

and then on the 'access code' button in the following screen . . .

![screenshot 118](https://user-images.githubusercontent.com/44443205/52554942-48dedc80-2de0-11e9-8f2f-29c57244d620.png)

I can click on the 'decline review' button and decline the review as if I was the actually reviewer . . 
which I assume I should not be able to do . . . 
![screenshot 120](https://user-images.githubusercontent.com/44443205/52555048-8a6f8780-2de0-11e9-8724-95192022c0da.png)

Switching back to the Reviewer session, if I try to decline the review I get 'permission declined' presumably because there now is no request . . . 
![screenshot 121](https://user-images.githubusercontent.com/44443205/52555126-bdb21680-2de0-11e9-9003-701dee78301f.png)

**Comment by ajrbyers** [comment]
Thanks for this report, its not a bug though, We allow Editors to see and make actions on this page on purpose.

**Comment by ccaadeh** [comment]
I would just point out that as far as I can see, if the person X, the
Editor, can decline the review requested of person Y, then the record
states that person Y declined and not person X i.e. the 'audit trail' is
false.

**Comment by ajrbyers** [comment]
Noted, but the editor is granted access only so that they can take actions on behalf of the reviewer. Anyway our Log system records the user who made the action.
