### ISSUE TITLE
Non-Crossref DOI Settings are available in manager to edit but seem to do nothing

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#876]
Under all settings where you are able to change DOI-related things: DOI display prefix, suffix, DOI Pattern, Use Crossref DOIs all seem to do nothing other than retain the value that is entered and saved. In `identifiers/logic.py` all the settings that are being referenced are specific to crossref and these are being ignored or not used.

Confusing at this point but perhaps you want to reintroduce them when #871 is completed?

**Comment by ajrbyers** [comment]
I’m not sure I follow you. identifiers/logic.py clearly uses settings from the Crossref page to determine the registration of Crossref settings. 

For example under create_crossref_doi_identifier I can see:

doi_prefix = setting_handler.get_setting('Identifiers', 'crossref_prefix', article.journal)

Which is fetching the Crossref prefix for the journal....

**Comment by ajrbyers** [comment]
Right, I see what you're saying.

`doi_pattern` is used in `identifiers.logic` and the other two are not used as you say but we probably will use them when we re-write the Identifiers app to support other DOI registrars.
