### ISSUE TITLE
Confusing boolean form for settings

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#877]
your-journal-name/manager/settings/group/Identifiers/setting/use_crossref/

![image](https://user-images.githubusercontent.com/1020384/52600720-93854680-2e2a-11e9-89dc-65860bca152b.png)

Confusing design/ux
The checkbox must be checked and then you have an option of submit or delete. Unchecking the checkbox and clicking submit is what one would expect would undo the value and turn this to False. However, you must check the box (with no description) and then press delete to set to false.

**Comment by ajrbyers** [comment]
Yep this is a bug with the individual settings form. Will add to 1.3.3.
