### ISSUE TITLE
Unable to disable slack logging

### ISSUE THREAD

**Issue by amardesi** [BirkbeckCTP/janeway#886]
/manager/settings/group/general/setting/slack_logging/

I am unable to disable slack logging (I've added a webhook but would now like to turn it off). I uncheck the box and click submit, but a popup says I must check it to proceed?

**Comment by ajrbyers** [comment]
Go to Manager > Journal Settings and disable it there. Weve had a report for the individual settings page (we don’t really use it so haven’t spotted it) a fix has been merged into master already.

**Comment by amardesi** [comment]
It seems that to turn off logging the checkbox should be checked when clicking the delete button? It's not totally clear. I thought unclicking the checkbox and clicking submit would turn it off.
