### ISSUE TITLE
Minor Costmetic Issues with the Status of an Article when it is in the Review Stage

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#887]
https://demojournal.janeway.systems/review/article/623/
When a new article has been assigned an editor, and then is moved on to the next stage of assigning a reviewer the status is given as 'This article is currently Assigned. ', which presumably means assigned an editor? Personally I don't think this is very clear.
![screenshot 124](https://user-images.githubusercontent.com/44443205/52696919-28da2500-2f68-11e9-9947-80fd22e5cfaf.png)

When the a reviewer is assigned the status change to 'This article is currently Under Review':
![screenshot 125](https://user-images.githubusercontent.com/44443205/52697181-d2b9b180-2f68-11e9-8f6a-6529997410e9.png)
But even if the review assignment is declined, and no other review is pending, the status remains This article is currently Under Review':
![screenshot 126](https://user-images.githubusercontent.com/44443205/52697405-4c519f80-2f69-11e9-8243-33f298166e5e.png)
Even when the review is completed and the article is accepted the status remains 'This article is currently Under Review': I.e. I think this is misleading and perhaps  should be 'This Article is currently in [the] Peer Review [stage]' , and therefore make it consistent with say, the next stage which says 'This article is currently in Editor Copyediting.' 

![screenshot 127](https://user-images.githubusercontent.com/44443205/52698024-98511400-2f6a-11e9-8219-2724f395e4d9.png)

**Comment by ajrbyers** [comment]
Thanks David, we’ll add this to 1.3.3.

**Comment by rhb123** [comment]
Just in case this hasn't yet been done - this would be helpful for 1.4, thanks
