### ISSUE TITLE
Unclear function of table header on galley image upload page

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#893]
**Describe the bug**
What's the relationship of the highlighted header-looking words on the `/production/###/galley/###/` to the image file upload slots?

**Janeway version**
e345fa2747362c4f841049f99a1b37df6ba60df8

**To Reproduce**

**Expected behavior**

**Screenshots**
![screenshot_2019-02-13 edit galley - 20 1](https://user-images.githubusercontent.com/4392604/52719894-8d02e600-2f74-11e9-84b3-96f7f8c27044.png)

**Comment by ajrbyers** [comment]
When you upload an image, the images will appear under these headers in the table.
