### ISSUE TITLE
Pandoc-generated HTML galleys have broken src links to image files

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#895]
**Describe the bug**
Pandoc prefixes all image `src` attributes with `media/`, and so the images in generated HTML galleys don't properly point to the uploaded image files.

(@ajrbyers wasn't sure if this belongs as a Janeway issue or as a Pandoc plugin issue!)

**Janeway version**
e345fa2747362c4f841049f99a1b37df6ba60df8

**To Reproduce**
1. Upload a docx manuscript that contains inline images
2. Use the pandoc plugin to generate HTML galley
3. Upload image files via the "Edit Galley" page
4. Preview the HTML galley

**Screenshots**

![screenshot_2019-02-13 proofing preview](https://user-images.githubusercontent.com/4392604/52721822-7fe7f600-2f78-11e9-91dd-1dc050ba57c3.png)

**Comment by ajrbyers** [comment]
@mdlincoln shouldn't this be a bug for the Pandoc plugin repo?

**Comment by mdlincoln** [comment]
>(@ajrbyers wasn't sure if this belongs as a Janeway issue or as a Pandoc plugin issue!)

hah, well I wasn't sure if it was something you'd want to handle in your general rewriting of `<img>` tags as discussed on Discord, so you should transfer it if you think it belongs there

**Comment by ajrbyers** [comment]
Yeah it may be a good idea to handle this for XML and HTML galleys when a file is uploaded.
