### ISSUE TITLE
Author list view should be paginated

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#897]
The new `journal.views.author_list` loads all the authors at once and renders them all at once

These should probably be paginated with some search functionality similar to the articles page.

![image](https://user-images.githubusercontent.com/10760678/52725065-6363b200-2fa8-11e9-9955-c2c259b589f5.png)

**Comment by mauromsl** [comment]
@hachacha this might be of interest to you

**Comment by ajrbyers** [comment]
https://github.com/BirkbeckCTP/janeway/pull/912

**Comment by ajrbyers** [comment]
Has this been fixed?

**Comment by hachacha** [comment]
I believe so. This issue was made on the 13th. I did work for this and made the PR on the 15th to have those changes. 
https://github.com/BirkbeckCTP/janeway/pull/912
