### ISSUE TITLE
Very Minor Cosmetic Issues

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#903]
These two are very minor indeed, and I just thought I would point them out in case you want to address them:
The records per page option, which appears at a number of different stages does not ascend/descend in the right numerical order e.g. All/50/25/10 or the reverse:
![screenshot 129](https://user-images.githubusercontent.com/44443205/52771843-e891aa00-302e-11e9-9155-077497efbbb1.png)
Again, at a number of stages you get the 'Previous' & 'Next' buttons which you can select, but nothing happens as there is no previous or next page. Perhaps hide them?

**Comment by rhb123** [comment]
This would be helpful for 1.4 - thanks
