### ISSUE TITLE
TemplateSyntaxError on /admin when using suit theme

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#910]
**Describe the bug**
Some admin pages can't be loaded under the suit theme due to use of an unregistered template tag

**Janeway version**
1.3.1

**To Reproduce**
With `"suit"` enabled under `settings.INSTALLED_APPS`
1. Go to '/admin/'
2. Click on 'Pages'
3. See error `TemplateSyntaxError 'cms_admin' is not a registered tag library. Must be one of: [...]`

**Comment by ajrbyers** [comment]
This looks like a nice alternative:
https://github.com/fabiocaccamo/django-admin-interface

**Comment by ajrbyers** [comment]
Suit theme has been removed.
