### ISSUE TITLE
Old methods still available in settings. Method for updating those?

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#911]
**Describe the bug**
```
NoReverseMatch at /review/unassigned/article/15/notify/15/
Reverse for '{{ journal.site_url }}' not found. '{{ journal.site_url }}' is not a valid view function or pattern name.
```
When navigating through submissions I receive errors in several places regarding the journal url path when rendering an email template. 
On the `review/unassigned/article/x/` page it tries to render the `editor_assignment` email and I receive the above error message.
I believe this is happening because I have email template defaults in the settings that are using an older method for linking to the journal.

new method:
` <a href=\"{{ request.journal.site_url }}{% url 'review_in_review' article.pk %}\">`
old method
`<a href="{% journal_url '{{ journal.site_url }}' review_in_review%}">`

These email templates are in my database as defaults and I am not aware of a method of updating these when pulling the new commits...
Is there currently a method for updating the way urls or other things are referenced in these templates? 

**Janeway version**
master/e345fa2747362c4f841049f99a1b37df6ba60df8

**To Reproduce**
1. Have your database install set up with the journal_defaults.json from some older version before 86bab6c3f379d06499f0f4f1da80be3cd26ff267
2. Begin submission process and try to add an editor
3. Click submit
**Expected behavior**
Show the email that will be sent

**Screenshots**
![image](https://user-images.githubusercontent.com/1020384/52804065-4a630b80-3051-11e9-9a67-3c828b9fe8fc.png)

**Comment by ajrbyers** [comment]
I think I had this too and it was caused by a bad migration on master. I’ll confirm and let you know.

**Comment by ajrbyers** [comment]
Is it possible you ran core.0025_fix_bad_journal_urls_in_template on the 5th of Feb?

**Comment by hachacha** [comment]
I've only recently realized why this is happening to me. On my local I use sqlite and these migrations that fix old settings via regex don't seem to be applied for some reason. The migrations **do** work on psql. 
my solution is to switch to an actual database.
