### ISSUE TITLE
Janeway and Plan S

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#913]
For Plan S we should ensure the following:

- [x] references appear in an open format
- [X] OA status is machine readable via license tag (addressed by PR #1454)
- [X] Fundref stuff (addressed by PR #1451)

**Comment by MartinPaulEve** [comment]
Research funder details

**Comment by ajrbyers** [comment]
Cheers @MartinPaulEve

**Comment by ajrbyers** [comment]
Closed with https://github.com/BirkbeckCTP/janeway/pull/1451
