### ISSUE TITLE
MULIT typos

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#914]
**Describe the bug**
There are various typos for mulit/multi across the system

**Janeway version**
All

**To Reproduce**
 https://github.com/BirkbeckCTP/janeway/search?q=mulit&unscoped_q=mulit

**Expected behavior**
Should be spelled correctly

**Comment by justingonder** [comment]
Found another under press > Admin > "Presss" has an extra 's'

**Comment by ajrbyers** [comment]
Yeah this is caused by Django Admin attempting to pluralise the model "Press", we can add a plural string for the model though.
