### ISSUE TITLE
unexpected behavior of "missing images" text on production page

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#917]
When an html galley is uploaded/produced by Pandoc with img tags, a text warning reads "Missing Images" with a tooltip showing the missing filenames. The text looks like it ought to be a clickable link, but it isn't, and it's not clear to the user that they need to click "edit" to upload images.

<img width="926" alt="screen shot 2019-02-20 at 4 14 44 pm" src="https://user-images.githubusercontent.com/4392604/53125022-e2b63000-352a-11e9-9b76-d0e4fc56e98f.png">

**Comment by ajrbyers** [comment]
We can add information about where to upload the images but the styling clearly differs from links (which are blue and not underlined) so not sure we will xhange the tooltop styling
