### ISSUE TITLE
Cosmetic Issue: Unnecessary Tick Box present when asked which files to choose?

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#929]
When assigning a Typesetter, I notice that there is an additional(?) Tick box left of the row of headings, pertaining to which files to choose:

![screenshot 133](https://user-images.githubusercontent.com/44443205/53480081-5c41a700-3a72-11e9-8683-85a81647756a.png)

This is not present in other similar situations: For example:
![screenshot 134](https://user-images.githubusercontent.com/44443205/53480214-a32f9c80-3a72-11e9-848a-9a20ff9d62f2.png)

**Comment by ajrbyers** [comment]
This is a check all box. We should consider adding this to other places.
