### ISSUE TITLE
files not sent with copyeditor assignment 

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#938]
**Describe the bug**

**Janeway version**
269ce64f0cf4e1de13d225dbd5fcedad32bd3ee7

**To Reproduce**
1. Get article to copyediting stage
2. Assign a copyeditor and attach files
3. sign in as copyeditor to view the request
4. accept and then view request

**Expected behavior**
you should see the files that were assigned to you when you accepted the request.

**Screenshots**
During the assignment from the editor (you can see the files checked as well as the copyeditor)
![image](https://user-images.githubusercontent.com/1020384/53525833-afd2e580-3ab0-11e9-92d7-f91ba88f1ff4.png)

when the copyeditor goes to view:
![image](https://user-images.githubusercontent.com/1020384/53525722-6aaeb380-3ab0-11e9-9c47-b075e438a22d.png)

in the admin backend no files are assigned:
![image](https://user-images.githubusercontent.com/1020384/53525748-7b5f2980-3ab0-11e9-9e0f-94117ced0601.png)

**Desktop (please complete the following information):**
 - OS: linux
 - chromium

**Comment by ajrbyers** [comment]
Cheers - bug was introduced when moving copyedting to proper django forms. PR in for this to be added to 1.3.3.
