### ISSUE TITLE
Journal Manager Role

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#945]
**Is your feature request related to a problem? Please describe.**
Current permission levels are not as clear as they should be, and utilising is_staff isn't the best solution as its a Django permission that gives site-wide access.

**Describe the solution you'd like**
The introduction of a new role "Journal Manager" or similar so that we can limit access to certain areas/settings only to those with higher security clearance without granting site wide Django permission is_staff. JM role could be set only by staff/admin/superusers.

**Describe alternatives you've considered**
None come to mind in particular.

**Stuff to do**
A few things to do for 1.5:
- [x] Update the group settings getter to filter settings a user cannot edit
- [x] Tests
- [x] Documentation on how this whole things work
- [x] All Settings edit_key form should validate JSON input
- [x] Test all JSON fields on a clean DB

**Comment by ajrbyers** [comment]
Settings for Journal Managers:

- Uses HTTPS
- Crosscheck

**Comment by hardyoyo** [comment]
related to #3232 which will make use of this new role

**Comment by hardyoyo** [comment]
PR #3332 adds this role, as well as some decorators that use this role. I believe that is sufficient to close this issue, but, if that's not the case, please add more detail to this issue?

**Comment by ajrbyers** [comment]
- [ ] Update the group settings getter to filter settings a user cannot edit
- [ ] Tests
