### ISSUE TITLE
missing migrations

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#947]
**Describe the bug**
After downloading 1.3.3, there are changes in the models with no corresponding migrations committed to the repository. I get the following from `makemigrations`

```
Migrations for 'django_summernote':
  /usr/local/lib/python3.5/site-packages/django_summernote/migrations/0002_auto_20190228_2339.py
    - Alter field name on attachment
Migrations for 'journal':
  journal/migrations/0024_auto_20190228_2339.py
    - Alter field issue on issuegalley
Migrations for 'submission':
  submission/migrations/0032_auto_20190228_2339.py
    - Alter field stage on article
```

**Janeway version**
1.3.3

**Comment by ajrbyers** [comment]
I don't see the summernote one (its a package, hasn't been changed as far as I can tell) the other two aren't _real_ migrations but django tracks them anyway for some reason. Can you add a PR for the two core ones?

**Comment by mdlincoln** [comment]
I don't get an error for summernote alone, but if I run `makemigrations` off of fresh Janeway code it always wants to produce one.

**Comment by mauromsl** [comment]
Yes, the summernote migration is a harmless artifact of running Janeway in docker and can be ignored (As it is a third party package, the migration is deleted everytime the container is recreated)

**Comment by amardesi** [comment]
I'm getting this

```CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0030_auto_20190225_1449, 0031_field_display in submission).
To fix them run 'python manage.py makemigrations --merge'
$ python3 manage.py makemigrations --merge
Merging submission
  Branch 0030_auto_20190225_1449
    - Alter field keywords on submissionconfiguration
  Branch 0031_field_display
    - Alter field stage on article
    - Add field display to field

$ more src/submission/migrations/0032_merge_20190301_1650.py
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 00:50
from __future__ import unicode_literals
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [
        ('submission', '0030_auto_20190225_1449'),
        ('submission', '0031_field_display'),
    ]
    operations = [
    ]
```

**Comment by ajrbyers** [comment]
@amardesi have you created a migration on your branch? I can't see `0030_auto_20190225_1449` we only have `0030_rename_readable_stages.py`

**Comment by amardesi** [comment]
@ajrbyers Ah yes, that's mine. Apologies.
