### ISSUE TITLE
incorrect link served in registration email for new user

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#957]
**Describe the bug**
When registering a user the link that is emailed with the token returned from {% url 'core_confirm_account' user.confirmation_code %} is displayed as:

https://sitename/journal/register/step/1//journal/register/step/2/token/

two forward slashes and both steps. I _think_ it should just be https://sitename/journal/register/step/2/token . refreshing this gives login access to the user.

**Janeway version**
master @ 3dd176d60437f294ad5aeba9079dbe7f80831bd9

**To Reproduce**
1. register through /register/step/1/
2. go to your email 
3. follow the link

**Expected behavior**
following the link will bring you to a success page and tell you you may now log in.

**Screenshots**
![image](https://user-images.githubusercontent.com/1020384/53756618-8d154800-3e87-11e9-8097-411f496bd973.png)

**Comment by ajrbyers** [comment]
I’ll confirm this one, there is a migration that’s supposed to have fixed this in 1.3.3 for the new url pattern.

**Comment by ajrbyers** [comment]
Interestingly, tested on domain and path and don't get this:

```
Content-Type: multipart/alternative;
 boundary="===============1277400417574973409=="
MIME-Version: 1.0
Subject: Registration Confirmation
From: Open Library of Humanities <tech@openlibhums.org>
To: tech+testing@openlibhums.org
Date: Mon, 04 Mar 2019 19:23:57 -0000
Message-ID: <20190304192357.602.43209@a13de4605eb3>

--===============1277400417574973409==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Dear Andy Test ByersThank you for registering for . You can confirm your account at the following link:https://localhost/register/step/2/d3cd5970-5ca6-4141-97f4-2724f4f178fd/
--===============1277400417574973409==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

<p>Dear Andy Test Byers<br><br>Thank you for registering for . You can confirm your account at the following link:</p><p><br><a href="https://localhost/register/step/2/d3cd5970-5ca6-4141-97f4-2724f4f178fd/">https://localhost/register/step/2/d3cd5970-5ca6-4141-97f4-2724f4f178fd/</a><br></p>
--===============1277400417574973409==--

```

**Comment by ajrbyers** [comment]
Can you paste in the content of your registration template?

**Comment by hachacha** [comment]
This is the current value of the new_user_registration:
```
<p>Dear {{ user.full_name }}<br><br>Thank you for registering for {{ request.journal.name }}. You can confirm your account at the following link:</p><p><br><a href="{{ request.journal.site_url }}{% url 'core_confirm_account' user.confirmation_code %}">{{ request.journal.site_url }}{% url 'core_confirm_account' user.confirmation_code %}</a><br></p>
```

**Comment by amardesi** [comment]
I also am having this specific issue reported by @hachacha .
(And related issue https://github.com/BirkbeckCTP/janeway/issues/866 is also still occurring for me)
One issue with this migration fix https://github.com/BirkbeckCTP/janeway/pull/850 is that, upon installation, it is applied before the journal_defaults are loaded into the DB, when the SettingValueTranslation table is empty.

That issue aside, the regex is still not working. But this fixes that issue:
`re.compile("({{\ ?request\.journal\.site_url\ ?}})?{% url '(\w+)' ([\w\ \.]*)%}")`
I can't find any instances of `journal.site_url` in journal_defaults.json, so this seems like the appropriate regex fix.

**Comment by ajrbyers** [comment]
@mauromsl can you check this out?

**Comment by ajrbyers** [comment]
@amardesi on a new install it wouldn’t matter if the migration is applied as the defaults should load the correct values (and if they aren’t we need to fix that).

**Comment by mauromsl** [comment]
#850 + #835 solved the problem for most settings as they were currently installed, but did not amend `journal_defaults.json` I'll correct that now and add another migration for installations with the wrong settings.
