### ISSUE TITLE
Issue Page  Order

### ISSUE THREAD

**Issue by hinefuku** [BirkbeckCTP/janeway#964]
**Describe the bug**
Issues page displays issues in reverse order from the listing is Issue Manager.

**Janeway version**
1.3.2

**To Reproduce**
1. Go to Issue Manager and arrange issues
2. Go to Issues page

**Expected behavior**
Issues on the issues page should be displayed in the same order as listing in Issue Manager.

**Screenshots**
![issuemanagement](https://user-images.githubusercontent.com/45498398/53817582-66105200-3f2b-11e9-96cb-b17ebe1e30f9.png)
![issuespage](https://user-images.githubusercontent.com/45498398/53817631-7fb19980-3f2b-11e9-9155-2c04ef51d83b.png)

**Additional context**
A "sort by" feature would be useful as well.

**Comment by ajrbyers** [comment]
Fixed in 1.3.4.
