### ISSUE TITLE
After Submission

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#972]
**Describe the bug**
Its not at all clear what to do from here. There's just a bunch of text summarizing my submission with no indication of what to do next / where to go from here.

**Janeway version**
1.3.3

**To Reproduce**
1. Complete a submission

**Expected behavior**
I'm not sure what should happen here.

**Comment by justingonder** [comment]
I would suggest simply returning the user to /dashboard/ after the submission is completed. From there they could choose to start another submission, or they can 'View Status' on the item they just submitted. In any case, I think dropping them onto the Dashboard once the submission is complete reinforces the idea that this is where the user should go to monitor their submission's status.

**Comment by ajrbyers** [comment]
1.3.4 fixes this with a redirect to the dashboard.
