### ISSUE TITLE
Odd error message when adding a reviewer as a copyeditor (via API).

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#976]
**Describe the bug**
When attempting to add a reviewer as a copyeditor (without the right permissions), the error message renders:
"detail: Checks that the user is an editor for the current journal"
Which seems to be the docstring of the security decorator on the view. Probably a bug with the API

**Janeway version**
1.3.3

**Comment by ajrbyers** [comment]
This has been updated (2021) closing.
