### ISSUE TITLE
Author can't access a review assignment for a copyedit task

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#978]
**Describe the bug**
When an author is assigned a review for a copyedit task, they are unable to access it with the link sent on the email (Permission Denied) copyediting/article/<article_id>/assignment/<assignment_id>/review/
**Janeway version**
1.3.3

**Comment by ajrbyers** [comment]
Should this have been closed by the merge?

**Comment by mauromsl** [comment]
This is another issue

**Comment by ajrbyers** [comment]
D'oh!
