### ISSUE TITLE
Redirect to /dashboard after upload file from document manager

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#980]
**Describe the bug**
{% return_url %}  is lost after file upload in document management

**Janeway version**
master @ a25fd6373eacd227679a3fd71213ff9bdf05a657

**To Reproduce**
URL_CONFIG=path:
1. Get article to proofing stage (but this happens wherever document manager is available. I found the bug on proofing)
2. Navigate to the  Document Management page. At this point the return button should have the href="/journal_name/proofing/article_id/" 
3. upload a new file -- I did manuscript.
4. When page loads again the return button has a link to "/dashboard". clicking return will bring you to http://yoursiteurl/dashboard 

**Expected behavior**
return path to `/journal_name/review_step/article_id` would be retained and set as return_url or at least get bounced back to `/journal_name/dashboard`

**Additional context**
So maybe retain return_url in the upload form as input type="hidden" on document_management and add to the redirect on POST? I can do this PR if this is an approved method.

**Comment by ajrbyers** [comment]
@hachacha we usually put return URLS in as GET params so they are transparent to the user.

`/?return=/manager/`

**Comment by ajrbyers** [comment]
closed by #981
