### ISSUE TITLE
Cannot delete custom journal nav items

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#986]
**Describe the bug**
If you create a custom navigation link and add it to the nav bar, there's no button or link that allows you to delete or hide it afterwards.

**Janeway version**
1.3.3

**Expected behavior**
In addition to the edit button that appears there already, it should have a toggle switch similar to the built-in nav item options.

**Screenshots**
![screenshot_2019-03-07 carnegie mellon encyclopedia of science history 1](https://user-images.githubusercontent.com/4392604/53958981-66862580-40b0-11e9-9c72-b02db9249309.png)

**Comment by ajrbyers** [comment]
Why would you want to do this!? Just kidding, well add this to 1.3.3.1, in the mean time you can probably delete it in admin.
