### ISSUE TITLE
Images not rendering in article when using upload option in proofing/typesetting

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#988]
**Describe the bug**
Images are not rendering in the article after publication when they were uploaded during production.

**Janeway version**
39acd7a83eefa4b23076b3f36deb0600aea3c88c

**To Reproduce**
1. submit article and get to the proofing page
2. convert docx to html
3. add images to the converted html via upload
4. continue and publish the article
5. go to the article view page
6. be very sad that there is no image.

**Expected behavior**
You would see an image in the published article just as you saw in the proofing stage.

**Screenshots**
In proofing preview and with attached file (note URL):
![image](https://user-images.githubusercontent.com/1020384/54057123-02eb1d80-41c0-11e9-8826-7c28701412a0.png)
that image src is pointing @ http://localhost:8000/cmesh/production/18/preview/30/image1.jpeg

after publication:
![image](https://user-images.githubusercontent.com/1020384/54057166-29a95400-41c0-11e9-98f6-0e9796b61c05.png)
src is pointing @ http://localhost:8000/cmesh/article/id/18/image1.jpeg

**Additional context**
I'm assuming this is some url that was not set up to serve this?

**Comment by ajrbyers** [comment]
I have a PR coming for this shortly. If you add a DOI images will magically work again. But when using the ID they don’t... url regexes 😔
