### ISSUE TITLE
'Server Error' Encountered on Pressing Icons Associated with Due Date of Peer Review 

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#989]
**Describe the bug**
Logged in with a privileged account editor. Having sent a request for peer review, the invited reviewer is displayed along with the date of the review is due, next to which there are two icons - an envelope and a timer. If I click on either icon I get "Server ErrorSorry, there was a server error. Our team has been notified."

**Janeway version**
https://demojournal.janeway.systems/review/article/625/

**To Reproduce**
As above.
**Expected behavior**
The fact that these icons are present means I assume I can either email the reviewer (again) or change the due date. Either way an error is produced and no error handling (as such) is present.

**Screenshots**
![Screenshot (142)](https://user-images.githubusercontent.com/44443205/54114049-73bd5000-43e1-11e9-9aac-5422d737cb81.png)
![Screenshot (141)](https://user-images.githubusercontent.com/44443205/54114051-76b84080-43e1-11e9-8d4d-ff1b8460a3df.png)

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**
 Chrome and alslo MS Edge / Windows 10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ajrbyers** [comment]
Hi @ccaadeh this bug has already been fixed. I've updated the demo journal.
